/**
 * Localization-ready copy for `/christmas/photo-generator` and portrait verticals.
 * Wave 1 UI packs: en, ro, de, fr, es, it, pt (European Portuguese), nl, pl.
 * Style keys stay stable (e.g. cozy_fireplace); only visible names/descriptions localize.
 */

export const PHOTO_GEN_LOCALES = ["en", "ro", "de", "fr", "es", "it", "pt", "nl", "pl"] as const;
export type PhotoGenLocale = (typeof PHOTO_GEN_LOCALES)[number];
export const PHOTO_GEN_DEFAULT_LOCALE: PhotoGenLocale = "en";

export const PHOTO_GEN_LOCALE_DIR: Record<string, "ltr" | "rtl"> = {
  en: "ltr", ro: "ltr", de: "ltr", fr: "ltr", es: "ltr", it: "ltr", pt: "ltr", nl: "ltr", pl: "ltr",
  ar: "rtl", he: "rtl", fa: "rtl", ur: "rtl",
};

type CopyBag = Record<string, string>;

const EN: CopyBag = {
  "seo.title": "AI Christmas Photo Generator | Family, Couples & Pets",
  "seo.description": "Turn your favorite photo into a magical Christmas portrait. Create festive photos for family, couples, and pets in minutes.",
  "seo.h1": "Turn Your Photo Into Christmas Magic",
  "seo.ogAlt": "Before and after Christmas portrait transformation",
  "hero.kicker": "Christmas portraits",
  "hero.h1": "Turn Your Photo Into Christmas Magic",
  "hero.lede": "Upload a favorite photo and create a magical Christmas portrait for your family, partner or pet.",
  "hero.cta": "Create My Christmas Photo",
  "hero.secondary": "See Examples",
  "hero.beforeLabel": "Original",
  "hero.afterLabel": "Christmas",
  "hero.sliderAria": "Drag to compare original and Christmas portrait",
  "category.family": "Family",
  "category.couples": "Couples",
  "category.pets": "Pets",
  "category.aria": "Choose an example category",
  "upload.kicker": "Start here",
  "upload.h2": "Upload your photo",
  "upload.lede": "Choose a clear photo and we’ll turn it into a magical Christmas portrait.",
  "upload.choose": "Choose Photo",
  "upload.drop": "Or drop a photo here",
  "upload.hint": "JPEG, PNG, or WebP · under 15 MB",
  "upload.guidanceTitle": "For the best result:",
  "upload.g1": "use a clear photo",
  "upload.g2": "faces should be visible",
  "upload.g3": "avoid extremely blurry images",
  "upload.g4": "include everyone you want in the final portrait",
  "upload.privacy": "Your upload stays private by default. Finished portraits are available through your order link.",
  "subject.h2": "Who’s in the photo?",
  "subject.lede": "We’ll guide the Christmas look for your subjects.",
  "subject.family": "Family",
  "subject.couple": "Couple",
  "subject.person": "One person",
  "subject.pet": "Pet",
  "subject.person_pet": "Person + pet",
  "subject.continue": "Continue",
  "style.h2": "Christmas Photo Styles",
  "style.lede": "Pick the Christmas look you want.",
  "style.back": "Back",
  "preview.h2": "Ready to create",
  "preview.lede": "This preview is your original photo, softly veiled — the finished Christmas portrait unlocks after checkout.",
  "preview.continue": "Continue",
  "offer.h2": "Unlock your Christmas portrait",
  "offer.ready": "Usually ready a few minutes after payment",
  "offer.private": "Private by default · download via your order link",
  "offer.email": "Email for receipt / recovery (optional)",
  "offer.pay": "Continue to payment",
  "offer.disabled": "Checkout is preparing for launch. You can still upload, choose a style, and preview — payment unlocks when pricing goes live.",
  "offer.busy": "Preparing checkout…",
  "checkout.h2": "Secure payment",
  "gen.h2": "Creating your Christmas portrait",
  "gen.step1": "Preparing your Christmas scene…",
  "gen.step2": "Adding the lights…",
  "gen.step3": "Creating a little Christmas magic…",
  "gen.step4": "Your portrait is almost ready…",
  "gen.note": "You can leave this page — reopen your order link anytime.",
  "result.h2": "Your Christmas portrait",
  "result.download": "Download",
  "result.share": "Share",
  "result.another": "Create Another",
  "result.retryStyle": "Try Another Style",
  "result.card": "Turn It Into a Christmas Card",
  "result.tree": "Add It to Your Christmas Tree",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Christmas",
  "examples.h2": "Christmas Photo Examples",
  "examples.lede": "Demo examples for inspiration — not customer photos. Each pair shows an everyday photo beside a Christmas portrait direction.",
  "examples.demoNote": "Demo examples for inspiration — not customer photos.",
  "examples.family": "Family Christmas Photo",
  "examples.couple": "Couple Christmas Portrait",
  "examples.dog": "Dog Christmas Portrait",
  "examples.cat": "Cat Christmas Portrait",
  "examples.familyPet": "Family + Pet Christmas Portrait",
  "examples.before": "Original photo",
  "examples.after": "Christmas portrait result",
  "ecosystem.h2": "Christmas Photos for Families, Couples and Pets",
  "ecosystem.lede": "Start here for any Christmas portrait — or go straight to a specialized experience.",
  "family.kicker": "Christmas family photos",
  "family.h2": "Create the Christmas Family Photo You Wish You’d Taken",
  "family.lede": "No studio. No matching schedules. No trying to get everyone looking at the camera.",
  "family.cta": "Create a Family Portrait",
  "couples.kicker": "Christmas couple photos",
  "couples.h2": "Your Christmas Story, in One Magical Photo",
  "couples.lede": "First Christmas together, engaged, married, long-distance, or the card you’ll send this year.",
  "couples.cta": "Create a Couple Portrait",
  "pets.kicker": "Christmas pet photos",
  "pets.h2": "Make Your Pet the Star of Christmas",
  "pets.lede": "Turn a favorite dog or cat photo into a warm, realistic Christmas portrait.",
  "pets.cta": "Create a Pet Christmas Portrait",
  "how.h2": "How the Christmas Photo Generator Works",
  "how.1.title": "Upload a photo",
  "how.1.body": "Choose a favorite photo of the people or pets you love.",
  "how.2.title": "Pick your Christmas style",
  "how.2.body": "Choose the Christmas look you want.",
  "how.3.title": "Create your portrait",
  "how.3.body": "We transform the photo into your Christmas image.",
  "portraitExplain.h2": "Turn Your Photo Into a Christmas Portrait",
  "portraitExplain.body": "Upload a favorite photo, choose the subject type, pick a Christmas look, and create a festive portrait you can download. The goal is a holiday image that still feels like the people or pets you love.",
  "best.h2": "What Photos Work Best?",
  "best.body": "Use a clear photo with visible faces (or a clear pet), decent lighting, and enough sharpness that everyone you want in the portrait is recognizable. Avoid extreme blur, heavy crop-outs, or photos where key people are hidden.",
  "geo.h2": "What is an AI Christmas photo generator?",
  "geo.body": "An AI Christmas photo generator turns a real photo you upload into a festive Christmas portrait. On TheDigitalGifter, you choose who is in the photo, pick a Christmas style, and create a downloadable portrait for family, couples, people, or pets — private by default.",
  "geo.best": "What photos work best?",
  "geo.bestBody": "Clear photos where faces (or pet faces) are visible work best. Include everyone you want in the final portrait.",
  "geo.support": "Who can be in the photo?",
  "geo.supportBody": "Families, couples, one person, pets, and person-plus-pet photos are supported. Multi-person results depend on how clearly each person appears in the upload.",
  "geo.privacy": "What happens to my photo?",
  "geo.privacyBody": "Uploads and results are private by default. There is no public gallery. Access is through your order/result flow.",
  "faq.h2": "Frequently Asked Questions",
  "faq.1.q": "How does the Christmas photo generator work?",
  "faq.1.a": "Upload a photo, choose who is in it, pick a Christmas style, then create your portrait after checkout when required by the product flow.",
  "faq.2.q": "What photo should I upload?",
  "faq.2.a": "A clear photo with visible faces or a clear pet works best. Good lighting helps. Avoid extreme blur.",
  "faq.3.q": "Can I create a family Christmas photo?",
  "faq.3.a": "Yes. Choose family as the subject, or start from the Family Christmas route.",
  "faq.4.q": "Can I create a Christmas portrait of my dog or cat?",
  "faq.4.a": "Yes. Pet subjects are supported, with dedicated dog and cat routes for a clearer start.",
  "faq.5.q": "Can multiple people be included?",
  "faq.5.a": "Yes for family and couple flows. Upload a photo that includes everyone who should appear.",
  "faq.6.q": "Can I try different styles?",
  "faq.6.a": "Yes. Pick from the enabled Christmas styles listed on the page before you create.",
  "faq.7.q": "Can I download the result?",
  "faq.7.a": "Yes. When your portrait is ready, download it from the result screen.",
  "faq.8.q": "Can I turn my portrait into a Christmas card?",
  "faq.8.a": "Yes. After you create a portrait, you can continue to the Christmas card experience.",
  "faq.9.q": "What happens to my uploaded photo?",
  "faq.9.a": "Uploads and results are private by default. There is no public gallery. Access is through your order/result flow.",
  "error.unsupported": "We couldn’t use this photo. Try a clearer image with visible faces.",
  "error.generation": "The Christmas magic didn’t work that time. Let’s try again.",
  "error.network": "Connection hiccup. Your selection is saved — please try again.",
  "error.generic": "Something went wrong. Please try again.",
  "error.paidKeepLink": "If you already paid, keep your order link — support can retry fulfillment without charging again.",
  "nav.hub": "Christmas hub",
  "nav.family": "Family",
  "nav.couples": "Couples",
  "nav.pets": "Pets",
  "nav.dogs": "Dogs",
  "nav.cats": "Cats",
  "nav.cards": "Christmas cards",
  "nav.tree": "Christmas tree",
  "trust.fact1": "Realistic Christmas portraits from your own photo",
  "trust.fact2": "Built for families, couples, and pets",
  "trust.fact3": "Private by default — no public gallery",
  "busy.working": "Working…",
  "busy.uploading": "Uploading your photo…",
  "upload.replace": "Replace photo",
  "styleName.cozy_fireplace": "Cozy Christmas",
  "styleDesc.cozy_fireplace": "Fireplace, warm lights, Christmas tree.",
  "styleName.winter_wonderland": "Winter Wonderland",
  "styleDesc.winter_wonderland": "Snow, elegant winter atmosphere.",
  "styleName.vintage_christmas": "Luxury Christmas",
  "styleDesc.vintage_christmas": "Premium room, sophisticated gold details.",
  "styleName.christmas_movie": "Christmas Morning",
  "styleDesc.christmas_movie": "Warm home, presents, joyful atmosphere.",
  "styleName.north_pole": "Snowy Cabin",
  "styleDesc.north_pole": "Mountain cabin, snow, fireplace glow.",
  "styleName.classic_christmas": "Classic Christmas",
  "styleDesc.classic_christmas": "Traditional red, green and gold.",
  "styleName.elegant_christmas": "Elegant White Christmas",
  "styleDesc.elegant_christmas": "Bright, sophisticated winter style.",
  "styleName.santas_workshop": "Christmas Market",
  "styleDesc.santas_workshop": "European festive lights and atmosphere.",
  "styleName.classic_family_christmas": "Classic Family Christmas",
  "styleDesc.classic_family_christmas": "Warm traditional family portrait by the tree.",
  "styleName.family_cozy_fireplace": "Cozy Fireplace",
  "styleDesc.family_cozy_fireplace": "Family gathered in firelight.",
  "styleName.family_winter_wonderland": "Winter Wonderland",
  "styleDesc.family_winter_wonderland": "Snowy outdoor family Christmas magic.",
  "styleName.family_elegant_christmas": "Elegant Christmas",
  "styleDesc.family_elegant_christmas": "Refined holiday evening family portrait.",
  "styleName.family_christmas_morning": "Christmas Morning",
  "styleDesc.family_christmas_morning": "Soft morning light and festive calm.",
  "styleName.family_luxury_christmas": "Luxury Christmas",
  "styleDesc.family_luxury_christmas": "Polished boutique-holiday family portrait.",
  "styleName.family_christmas_movie": "Christmas Movie",
  "styleDesc.family_christmas_movie": "Cinematic holiday still of the family.",
  "styleName.family_vintage_christmas": "Vintage Family Christmas",
  "styleDesc.family_vintage_christmas": "Nostalgic film-era family warmth.",
  "styleName.romantic_snowfall": "Romantic Snowfall",
  "styleDesc.romantic_snowfall": "Soft snow and intimate winter light.",
  "styleName.couple_cozy_fireplace": "Cozy Fireplace",
  "styleDesc.couple_cozy_fireplace": "Firelight couple portrait.",
  "styleName.couple_christmas_movie": "Christmas Movie",
  "styleDesc.couple_christmas_movie": "Cinematic holiday couple still.",
  "styleName.couple_elegant_christmas": "Elegant Christmas",
  "styleDesc.couple_elegant_christmas": "Evening formal couple portrait.",
  "styleName.couple_winter_city": "Winter City",
  "styleDesc.couple_winter_city": "City lights and winter coats.",
  "styleName.couple_christmas_market": "Christmas Market",
  "styleDesc.couple_christmas_market": "Festive market glow behind you.",
  "styleName.couple_classic_portrait": "Classic Portrait",
  "styleDesc.couple_classic_portrait": "Timeless studio-style couple Christmas look.",
  "styleName.couple_vintage_christmas": "Vintage Christmas",
  "styleDesc.couple_vintage_christmas": "Nostalgic film-era couple warmth.",
  "styleName.santa_pet": "Santa Pet",
  "styleDesc.santa_pet": "Festive Santa-inspired pet portrait.",
  "styleName.pet_cozy_christmas": "Cozy Christmas",
  "styleDesc.pet_cozy_christmas": "Firelight and soft blankets.",
  "styleName.pet_north_pole": "North Pole",
  "styleDesc.pet_north_pole": "Snowy magical pet portrait.",
  "styleName.pet_christmas_sweater": "Christmas Sweater",
  "styleDesc.pet_christmas_sweater": "Festive knit without hiding identity.",
  "styleName.pet_snow_portrait": "Snow Portrait",
  "styleDesc.pet_snow_portrait": "Clean outdoor snow portrait.",
  "styleName.pet_christmas_card": "Christmas Card",
  "styleDesc.pet_christmas_card": "Greeting-card ready pet portrait.",
  "styleName.pet_royal_christmas": "Royal Christmas",
  "styleDesc.pet_royal_christmas": "Regal holiday pet portrait.",
  "styleName.pet_vintage_christmas": "Vintage Christmas",
  "styleDesc.pet_vintage_christmas": "Nostalgic film-era pet portrait.",
  "funnel.upload": "Upload your photo",
  "funnel.style": "Choose a Christmas style",
  "funnel.continueOffer": "Continue to offer",
  "funnel.unlock": "Unlock your Christmas portrait",
  "funnel.readyMinutes": "Usually ready a few minutes after payment",
  "funnel.privateDownload": "Private by default · download via your order link",
  "funnel.email": "Email for receipt / recovery (optional)",
  "funnel.preparing": "Preparing checkout…",
  "funnel.checkoutDisabled": "Checkout is preparing for launch. You can still upload, choose a style, and preview — payment unlocks when pricing goes live.",
  "funnel.securePayment": "Secure payment",
  "funnel.creating": "Creating your portrait",
  "funnel.magic": "Creating a little Christmas magic…",
  "funnel.leaveNote": "You can close this page — reopen your order link anytime.",
  "funnel.download": "Download",
  "funnel.share": "Share",
  "funnel.card": "Turn This Into a Christmas Card",
  "funnel.another": "Create another",
  "funnel.tryAnother": "Try another:",
  "funnel.errorTitle": "Something went wrong",
  "funnel.errorPaid": "If you already paid, keep your order link — support can retry fulfillment without charging again.",
  "funnel.working": "Working…",
  "funnel.yourUpload": "Your upload",
  "funnel.blurredPreview": "Blurred preview of your photo",
  "funnel.previewLede": "Your Christmas transformation is ready to create. This preview is your original photo, heavily blurred — the finished AI portrait unlocks after payment.",
  "funnel.styleLabel": "Style",
  "funnel.dogs": "Dogs",
  "funnel.cats": "Cats",
  "funnel.hub": "Christmas hub",
  "funnel.photoGen": "AI Christmas Photo Generator",
  "funnel.fileHint": "JPEG, PNG, or WebP · under 15 MB",
  "funnel.portraitAlt": "Your Christmas portrait",
};

const RO: CopyBag = {
  "upload.kicker": "Începe aici",
  "upload.h2": "Încarcă fotografia",
  "upload.lede": "Alege o fotografie clară și o transformăm într-un portret magic de Crăciun.",
  "upload.choose": "Alege fotografia",
  "upload.drop": "Sau lasă o fotografie aici",
  "upload.hint": "JPEG, PNG sau WebP · sub 15 MB",
  "upload.guidanceTitle": "Pentru cel mai bun rezultat:",
  "upload.g1": "folosește o fotografie clară",
  "upload.g2": "fețele trebuie să fie vizibile",
  "upload.g3": "evită imaginile foarte neclare",
  "upload.g4": "include pe toți cei pe care îi vrei în portret",
  "upload.privacy": "Încărcarea rămâne privată implicit. Portretele gata sunt disponibile prin linkul comenzii.",
  "subject.h2": "Cine e în fotografie?",
  "subject.lede": "Vom ghida look-ul de Crăciun pentru subiecții tăi.",
  "subject.family": "Familie",
  "subject.couple": "Cuplu",
  "subject.person": "O persoană",
  "subject.pet": "Animal de companie",
  "subject.person_pet": "Persoană + animal",
  "subject.continue": "Continuă",
  "style.h2": "Stiluri foto de Crăciun",
  "style.lede": "Alege look-ul de Crăciun dorit.",
  "style.back": "Înapoi",
  "preview.h2": "Gata de creat",
  "preview.lede": "Această previzualizare e fotografia originală, ușor voalată — portretul final se deblochează după checkout.",
  "preview.continue": "Continuă",
  "offer.h2": "Deblochează portretul de Crăciun",
  "offer.ready": "De obicei gata în câteva minute după plată",
  "offer.private": "Privat implicit · descarcă din linkul comenzii",
  "offer.email": "Email pentru chitanță / recuperare (opțional)",
  "offer.pay": "Continuă la plată",
  "offer.disabled": "Checkout-ul se pregătește pentru lansare. Poți încărca, alege stil și previzualiza — plata se activează când prețurile sunt live.",
  "offer.busy": "Pregătim plata…",
  "checkout.h2": "Plată securizată",
  "gen.h2": "Cream portretul de Crăciun",
  "gen.step1": "Pregătim scena de Crăciun…",
  "gen.step2": "Adăugăm luminile…",
  "gen.step3": "Cream puțină magie de Crăciun…",
  "gen.step4": "Portretul e aproape gata…",
  "gen.note": "Poți părăsi pagina — redeschide oricând linkul comenzii.",
  "result.h2": "Portretul tău de Crăciun",
  "result.download": "Descarcă",
  "result.share": "Distribuie",
  "result.another": "Creează altul",
  "result.retryStyle": "Încearcă alt stil",
  "result.card": "Transformă într-un card de Crăciun",
  "result.tree": "Adaugă pe bradul de Crăciun",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Crăciun",
  "error.unsupported": "Nu am putut folosi această fotografie. Încearcă o imagine mai clară cu fețe vizibile.",
  "error.generation": "Magia de Crăciun nu a mers de data asta. Hai să încercăm din nou.",
  "error.network": "Problemă de conexiune. Selecția e salvată — te rugăm încearcă din nou.",
  "error.generic": "Ceva nu a mers. Te rugăm încearcă din nou.",
  "error.paidKeepLink": "Dacă ai plătit deja, păstrează linkul comenzii — suportul poate reîncerca fără o nouă taxare.",
  "busy.working": "Se lucrează…",
  "busy.uploading": "Se încarcă fotografia…",
  "hero.cta": "Creează fotografia mea de Crăciun",
  "nav.hub": "Hub de Crăciun",
  "nav.family": "Familie",
  "nav.couples": "Cupluri",
  "nav.pets": "Animale",
  "nav.dogs": "Câini",
  "nav.cats": "Pisici",
  "nav.cards": "Carduri de Crăciun",
  "nav.tree": "Brad de Crăciun",
  "category.family": "Familie",
  "category.couples": "Cupluri",
  "category.pets": "Animale",
  "category.aria": "Alege o categorie de exemple",
  "upload.replace": "Înlocuiește fotografia",
  "funnel.upload": "Încarcă fotografia",
  "funnel.style": "Alege un stil de Crăciun",
  "funnel.continueOffer": "Continuă la ofertă",
  "funnel.unlock": "Deblochează portretul de Crăciun",
  "funnel.readyMinutes": "De obicei gata în câteva minute după plată",
  "funnel.privateDownload": "Privat implicit · descarcă din linkul comenzii",
  "funnel.email": "Email pentru chitanță / recuperare (opțional)",
  "funnel.preparing": "Pregătim plata…",
  "funnel.checkoutDisabled": "Plata se pregătește pentru lansare. Poți încărca, alege un stil și previzualiza — plata se activează când prețurile sunt live.",
  "funnel.securePayment": "Plată securizată",
  "funnel.creating": "Cream portretul tău",
  "funnel.magic": "Adăugăm puțină magie de Crăciun…",
  "funnel.leaveNote": "Poți închide pagina — redeschide oricând linkul comenzii.",
  "funnel.download": "Descarcă",
  "funnel.share": "Distribuie",
  "funnel.card": "Transformă într-un card de Crăciun",
  "funnel.another": "Creează altul",
  "funnel.tryAnother": "Încearcă altceva:",
  "funnel.errorTitle": "Ceva nu a mers",
  "funnel.errorPaid": "Dacă ai plătit deja, păstrează linkul comenzii — suportul poate reîncerca fără o nouă taxare.",
  "funnel.working": "Se lucrează…",
  "funnel.yourUpload": "Fotografia ta",
  "funnel.blurredPreview": "Previzualizare estompată a fotografiei",
  "funnel.previewLede": "Transformarea de Crăciun e gata de creat. Această previzualizare e fotografia originală, puternic estompată — portretul final se deblochează după plată.",
  "funnel.styleLabel": "Stil",
  "funnel.dogs": "Câini",
  "funnel.cats": "Pisici",
  "funnel.hub": "Hub de Crăciun",
  "funnel.photoGen": "Generator foto de Crăciun AI",
  "funnel.fileHint": "JPEG, PNG sau WebP · sub 15 MB",
  "funnel.portraitAlt": "Portretul tău de Crăciun",
  "styleName.cozy_fireplace": "Crăciun confortabil",
  "styleDesc.cozy_fireplace": "Șemineu, lumini calde, brad.",
  "styleName.winter_wonderland": "Țară a minunilor de iarnă",
  "styleDesc.winter_wonderland": "Zăpadă, atmosferă elegantă de iarnă.",
  "styleName.vintage_christmas": "Crăciun de lux",
  "styleDesc.vintage_christmas": "Cameră premium, detalii aurii sofisticate.",
  "styleName.christmas_movie": "Dimineața de Crăciun",
  "styleDesc.christmas_movie": "Casă caldă, cadouri, atmosferă veselă.",
  "styleName.north_pole": "Cabană înzăpezită",
  "styleDesc.north_pole": "Cabană de munte, zăpadă, lumină de șemineu.",
  "styleName.classic_christmas": "Crăciun clasic",
  "styleDesc.classic_christmas": "Roșu, verde și aur tradițional.",
  "styleName.elegant_christmas": "Crăciun alb elegant",
  "styleDesc.elegant_christmas": "Stil de iarnă luminos și sofisticat.",
  "styleName.santas_workshop": "Târg de Crăciun",
  "styleDesc.santas_workshop": "Lumini festive europene.",
  "styleName.classic_family_christmas": "Crăciun de familie clasic",
  "styleDesc.classic_family_christmas": "Portret tradițional de familie lângă brad.",
  "styleName.family_cozy_fireplace": "Șemineu confortabil",
  "styleDesc.family_cozy_fireplace": "Familie adunată la lumina focului.",
  "styleName.family_winter_wonderland": "Țară a minunilor de iarnă",
  "styleDesc.family_winter_wonderland": "Magie de Crăciun în zăpadă.",
  "styleName.family_elegant_christmas": "Crăciun elegant",
  "styleDesc.family_elegant_christmas": "Portret de seară rafinat.",
  "styleName.family_christmas_morning": "Dimineața de Crăciun",
  "styleDesc.family_christmas_morning": "Lumină blândă de dimineață.",
  "styleName.family_luxury_christmas": "Crăciun de lux",
  "styleDesc.family_luxury_christmas": "Portret de familie boutique.",
  "styleName.family_christmas_movie": "Film de Crăciun",
  "styleDesc.family_christmas_movie": "Cadru cinematografic de familie.",
  "styleName.family_vintage_christmas": "Crăciun vintage de familie",
  "styleDesc.family_vintage_christmas": "Căldură nostalgică de film.",
  "styleName.romantic_snowfall": "Ninsoare romantică",
  "styleDesc.romantic_snowfall": "Zăpadă blândă și lumină intimă.",
  "styleName.couple_cozy_fireplace": "Șemineu confortabil",
  "styleDesc.couple_cozy_fireplace": "Portret de cuplu la foc.",
  "styleName.couple_christmas_movie": "Film de Crăciun",
  "styleDesc.couple_christmas_movie": "Cadru cinematografic de cuplu.",
  "styleName.couple_elegant_christmas": "Crăciun elegant",
  "styleDesc.couple_elegant_christmas": "Portret formal de seară.",
  "styleName.couple_winter_city": "Oraș de iarnă",
  "styleDesc.couple_winter_city": "Lumini de oraș și paltoane.",
  "styleName.couple_christmas_market": "Târg de Crăciun",
  "styleDesc.couple_christmas_market": "Strălucirea târgului festiv.",
  "styleName.couple_classic_portrait": "Portret clasic",
  "styleDesc.couple_classic_portrait": "Look de studio atemporal.",
  "styleName.couple_vintage_christmas": "Crăciun vintage",
  "styleDesc.couple_vintage_christmas": "Căldură nostalgică de film.",
  "styleName.santa_pet": "Animalul lui Moș Crăciun",
  "styleDesc.santa_pet": "Portret festiv inspirat de Moș.",
  "styleName.pet_cozy_christmas": "Crăciun confortabil",
  "styleDesc.pet_cozy_christmas": "Lumina focului și pături moi.",
  "styleName.pet_north_pole": "Polul Nord",
  "styleDesc.pet_north_pole": "Portret magic înzăpezit.",
  "styleName.pet_christmas_sweater": "Pulover de Crăciun",
  "styleDesc.pet_christmas_sweater": "Tricot festiv fără a ascunde identitatea.",
  "styleName.pet_snow_portrait": "Portret în zăpadă",
  "styleDesc.pet_snow_portrait": "Portret curat în aer liber.",
  "styleName.pet_christmas_card": "Card de Crăciun",
  "styleDesc.pet_christmas_card": "Portret gata de felicitare.",
  "styleName.pet_royal_christmas": "Crăciun regal",
  "styleDesc.pet_royal_christmas": "Portret regal de sărbătoare.",
  "styleName.pet_vintage_christmas": "Crăciun vintage",
  "styleDesc.pet_vintage_christmas": "Portret nostalgic de film.",
};

const DE: CopyBag = {
  "upload.kicker": "Hier starten",
  "upload.h2": "Foto hochladen",
  "upload.lede": "Wähle ein klares Foto — wir machen daraus ein magisches Weihnachtsporträt.",
  "upload.choose": "Foto wählen",
  "upload.drop": "Oder Foto hier ablegen",
  "upload.hint": "JPEG, PNG oder WebP · unter 15 MB",
  "upload.guidanceTitle": "Für das beste Ergebnis:",
  "upload.g1": "ein klares Foto verwenden",
  "upload.g2": "Gesichter sollten sichtbar sein",
  "upload.g3": "extrem unscharfe Bilder vermeiden",
  "upload.g4": "alle Personen einbeziehen, die im Porträt sein sollen",
  "upload.privacy": "Dein Upload bleibt standardmäßig privat. Fertige Porträts erreichst du über den Bestelllink.",
  "subject.h2": "Wer ist auf dem Foto?",
  "subject.lede": "Wir passen den Weihnachtslook an deine Motive an.",
  "subject.family": "Familie",
  "subject.couple": "Paar",
  "subject.person": "Eine Person",
  "subject.pet": "Haustier",
  "subject.person_pet": "Person + Haustier",
  "subject.continue": "Weiter",
  "style.h2": "Weihnachtsfoto-Stile",
  "style.lede": "Wähle den gewünschten Weihnachtslook.",
  "style.back": "Zurück",
  "preview.h2": "Bereit zum Erstellen",
  "preview.lede": "Diese Vorschau ist dein Originalfoto, sanft verschleiert — das fertige Weihnachtsporträt wird nach dem Checkout freigeschaltet.",
  "preview.continue": "Weiter",
  "offer.h2": "Weihnachtsporträt freischalten",
  "offer.ready": "Meist wenige Minuten nach der Zahlung fertig",
  "offer.private": "Standardmäßig privat · Download über den Bestelllink",
  "offer.email": "E-Mail für Beleg / Wiederherstellung (optional)",
  "offer.pay": "Weiter zur Zahlung",
  "offer.disabled": "Checkout wird für den Launch vorbereitet. Du kannst hochladen, Stil wählen und Vorschau sehen — Zahlung startet, wenn die Preise live sind.",
  "offer.busy": "Checkout wird vorbereitet…",
  "checkout.h2": "Sichere Zahlung",
  "gen.h2": "Dein Weihnachtsporträt entsteht",
  "gen.step1": "Weihnachtszene wird vorbereitet…",
  "gen.step2": "Lichter werden gesetzt…",
  "gen.step3": "Ein bisschen Weihnachtsmagie…",
  "gen.step4": "Dein Porträt ist fast fertig…",
  "gen.note": "Du kannst die Seite verlassen — öffne den Bestelllink jederzeit erneut.",
  "result.h2": "Dein Weihnachtsporträt",
  "result.download": "Herunterladen",
  "result.share": "Teilen",
  "result.another": "Neues erstellen",
  "result.retryStyle": "Anderen Stil versuchen",
  "result.card": "In eine Weihnachtskarte verwandeln",
  "result.tree": "Zum Weihnachtsbaum hinzufügen",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Weihnachten",
  "error.unsupported": "Dieses Foto konnten wir nicht verwenden. Versuche ein klareres Bild mit sichtbaren Gesichtern.",
  "error.generation": "Die Weihnachtsmagie hat diesmal nicht geklappt. Lass es uns nochmal versuchen.",
  "error.network": "Verbindungsproblem. Deine Auswahl ist gespeichert — bitte erneut versuchen.",
  "error.generic": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
  "error.paidKeepLink": "Falls du schon bezahlt hast, behalte den Bestelllink — Support kann ohne erneute Zahlung erneut versuchen.",
  "busy.working": "Wird bearbeitet…",
  "busy.uploading": "Foto wird hochgeladen…",
  "hero.cta": "Mein Weihnachtsfoto erstellen",
  "nav.hub": "Weihnachts-Hub",
  "nav.family": "Familie",
  "nav.couples": "Paare",
  "nav.pets": "Haustiere",
  "nav.dogs": "Hunde",
  "nav.cats": "Katzen",
  "nav.cards": "Weihnachtskarten",
  "nav.tree": "Weihnachtsbaum",
  "category.family": "Familie",
  "category.couples": "Paare",
  "category.pets": "Haustiere",
  "category.aria": "Beispielkategorie wählen",
  "upload.replace": "Foto ersetzen",
  "funnel.upload": "Foto hochladen",
  "funnel.style": "Weihnachtsstil wählen",
  "funnel.continueOffer": "Weiter zum Angebot",
  "funnel.unlock": "Weihnachtsporträt freischalten",
  "funnel.readyMinutes": "Meist wenige Minuten nach der Zahlung fertig",
  "funnel.privateDownload": "Standardmäßig privat · Download über den Bestelllink",
  "funnel.email": "E-Mail für Beleg / Wiederherstellung (optional)",
  "funnel.preparing": "Checkout wird vorbereitet…",
  "funnel.checkoutDisabled": "Checkout wird für den Launch vorbereitet. Du kannst hochladen, Stil wählen und Vorschau sehen — Zahlung startet, wenn die Preise live sind.",
  "funnel.securePayment": "Sichere Zahlung",
  "funnel.creating": "Dein Porträt entsteht",
  "funnel.magic": "Ein bisschen Weihnachtsmagie…",
  "funnel.leaveNote": "Du kannst die Seite schließen — öffne den Bestelllink jederzeit erneut.",
  "funnel.download": "Herunterladen",
  "funnel.share": "Teilen",
  "funnel.card": "In eine Weihnachtskarte verwandeln",
  "funnel.another": "Neues erstellen",
  "funnel.tryAnother": "Andere Option:",
  "funnel.errorTitle": "Etwas ist schiefgelaufen",
  "funnel.errorPaid": "Falls du schon bezahlt hast, behalte den Bestelllink — Support kann ohne erneute Zahlung erneut versuchen.",
  "funnel.working": "Wird bearbeitet…",
  "funnel.yourUpload": "Dein Upload",
  "funnel.blurredPreview": "Unscharfe Vorschau deines Fotos",
  "funnel.previewLede": "Deine Weihnachtstransformation ist bereit. Diese Vorschau ist dein Originalfoto, stark unscharf — das fertige KI-Porträt wird nach der Zahlung freigeschaltet.",
  "funnel.styleLabel": "Stil",
  "funnel.dogs": "Hunde",
  "funnel.cats": "Katzen",
  "funnel.hub": "Weihnachts-Hub",
  "funnel.photoGen": "KI-Weihnachtsfoto-Generator",
  "funnel.fileHint": "JPEG, PNG oder WebP · unter 15 MB",
  "funnel.portraitAlt": "Dein Weihnachtsporträt",
  "styleName.cozy_fireplace": "Gemütliche Weihnachten",
  "styleDesc.cozy_fireplace": "Kamin, warmes Licht, Weihnachtsbaum.",
  "styleName.winter_wonderland": "Winterwunderland",
  "styleDesc.winter_wonderland": "Schnee, elegante Winterstimmung.",
  "styleName.vintage_christmas": "Luxuriöse Weihnachten",
  "styleDesc.vintage_christmas": "Premium-Raum, goldene Details.",
  "styleName.christmas_movie": "Weihnachtsmorgen",
  "styleDesc.christmas_movie": "Warmes Zuhause, Geschenke, Freude.",
  "styleName.north_pole": "Verschneite Hütte",
  "styleDesc.north_pole": "Berghütte, Schnee, Kaminschein.",
  "styleName.classic_christmas": "Klassische Weihnachten",
  "styleDesc.classic_christmas": "Traditionelles Rot, Grün und Gold.",
  "styleName.elegant_christmas": "Elegantes weißes Weihnachten",
  "styleDesc.elegant_christmas": "Heller, eleganter Winterstil.",
  "styleName.santas_workshop": "Weihnachtsmarkt",
  "styleDesc.santas_workshop": "Europäische Festbeleuchtung.",
  "styleName.classic_family_christmas": "Klassische Familienweihnachten",
  "styleDesc.classic_family_christmas": "Traditionelles Familienporträt am Baum.",
  "styleName.family_cozy_fireplace": "Gemütlicher Kamin",
  "styleDesc.family_cozy_fireplace": "Familie im Feuerschein.",
  "styleName.family_winter_wonderland": "Winterwunderland",
  "styleDesc.family_winter_wonderland": "Verschneite Weihnachtsmagie draußen.",
  "styleName.family_elegant_christmas": "Elegante Weihnachten",
  "styleDesc.family_elegant_christmas": "Raffiniertes Abendporträt.",
  "styleName.family_christmas_morning": "Weihnachtsmorgen",
  "styleDesc.family_christmas_morning": "Sanftes Morgenlicht.",
  "styleName.family_luxury_christmas": "Luxuriöse Weihnachten",
  "styleDesc.family_luxury_christmas": "Poliertes Boutique-Familienporträt.",
  "styleName.family_christmas_movie": "Weihnachtsfilm",
  "styleDesc.family_christmas_movie": "Filmisches Familienbild.",
  "styleName.family_vintage_christmas": "Vintage-Familienweihnachten",
  "styleDesc.family_vintage_christmas": "Nostalgische Filmwärme.",
  "styleName.romantic_snowfall": "Romantischer Schneefall",
  "styleDesc.romantic_snowfall": "Sanfter Schnee und intimes Licht.",
  "styleName.couple_cozy_fireplace": "Gemütlicher Kamin",
  "styleDesc.couple_cozy_fireplace": "Paarporträt im Feuerschein.",
  "styleName.couple_christmas_movie": "Weihnachtsfilm",
  "styleDesc.couple_christmas_movie": "Filmisches Paarbild.",
  "styleName.couple_elegant_christmas": "Elegante Weihnachten",
  "styleDesc.couple_elegant_christmas": "Formelles Abendporträt.",
  "styleName.couple_winter_city": "Winterstadt",
  "styleDesc.couple_winter_city": "Stadtlichter und Wintermäntel.",
  "styleName.couple_christmas_market": "Weihnachtsmarkt",
  "styleDesc.couple_christmas_market": "Festlicher Marktglanz.",
  "styleName.couple_classic_portrait": "Klassisches Porträt",
  "styleDesc.couple_classic_portrait": "Zeitloser Studio-Look.",
  "styleName.couple_vintage_christmas": "Vintage-Weihnachten",
  "styleDesc.couple_vintage_christmas": "Nostalgische Filmwärme.",
  "styleName.santa_pet": "Weihnachtsmann-Haustier",
  "styleDesc.santa_pet": "Festliches Weihnachtsmann-Porträt.",
  "styleName.pet_cozy_christmas": "Gemütliche Weihnachten",
  "styleDesc.pet_cozy_christmas": "Feuerschein und weiche Decken.",
  "styleName.pet_north_pole": "Nordpol",
  "styleDesc.pet_north_pole": "Verschneites magisches Porträt.",
  "styleName.pet_christmas_sweater": "Weihnachts-Pullover",
  "styleDesc.pet_christmas_sweater": "Festlicher Strick ohne Identitätsverlust.",
  "styleName.pet_snow_portrait": "Schnee-Porträt",
  "styleDesc.pet_snow_portrait": "Klares Outdoor-Schnee-Porträt.",
  "styleName.pet_christmas_card": "Weihnachtskarte",
  "styleDesc.pet_christmas_card": "Kartenfertiges Haustierporträt.",
  "styleName.pet_royal_christmas": "Königliche Weihnachten",
  "styleDesc.pet_royal_christmas": "Majestätisches Festporträt.",
  "styleName.pet_vintage_christmas": "Vintage-Weihnachten",
  "styleDesc.pet_vintage_christmas": "Nostalgisches Filmporträt.",
};

const FR: CopyBag = {
  "upload.kicker": "Commencer ici",
  "upload.h2": "Téléversez votre photo",
  "upload.lede": "Choisissez une photo nette — nous en ferons un portrait de Noël magique.",
  "upload.choose": "Choisir une photo",
  "upload.drop": "Ou déposez une photo ici",
  "upload.hint": "JPEG, PNG ou WebP · moins de 15 Mo",
  "upload.guidanceTitle": "Pour le meilleur résultat :",
  "upload.g1": "utilisez une photo nette",
  "upload.g2": "les visages doivent être visibles",
  "upload.g3": "évitez les images très floues",
  "upload.g4": "incluez toutes les personnes souhaitées dans le portrait",
  "upload.privacy": "Votre téléversement reste privé par défaut. Les portraits terminés sont disponibles via le lien de commande.",
  "subject.h2": "Qui est sur la photo ?",
  "subject.lede": "Nous adaptons le look de Noël à vos sujets.",
  "subject.family": "Famille",
  "subject.couple": "Couple",
  "subject.person": "Une personne",
  "subject.pet": "Animal",
  "subject.person_pet": "Personne + animal",
  "subject.continue": "Continuer",
  "style.h2": "Styles de photo de Noël",
  "style.lede": "Choisissez le look de Noël souhaité.",
  "style.back": "Retour",
  "preview.h2": "Prêt à créer",
  "preview.lede": "Cet aperçu est votre photo originale, légèrement voilée — le portrait final se débloque après le paiement.",
  "preview.continue": "Continuer",
  "offer.h2": "Débloquez votre portrait de Noël",
  "offer.ready": "Généralement prêt quelques minutes après le paiement",
  "offer.private": "Privé par défaut · téléchargement via le lien de commande",
  "offer.email": "E-mail pour reçu / récupération (optionnel)",
  "offer.pay": "Continuer vers le paiement",
  "offer.disabled": "Le paiement se prépare pour le lancement. Vous pouvez téléverser, choisir un style et prévisualiser — le paiement s’active quand les prix sont en ligne.",
  "offer.busy": "Préparation du paiement…",
  "checkout.h2": "Paiement sécurisé",
  "gen.h2": "Création de votre portrait de Noël",
  "gen.step1": "Préparation de la scène de Noël…",
  "gen.step2": "Ajout des lumières…",
  "gen.step3": "Un peu de magie de Noël…",
  "gen.step4": "Votre portrait est presque prêt…",
  "gen.note": "Vous pouvez quitter cette page — rouvrez le lien de commande à tout moment.",
  "result.h2": "Votre portrait de Noël",
  "result.download": "Télécharger",
  "result.share": "Partager",
  "result.another": "Créer un autre",
  "result.retryStyle": "Essayer un autre style",
  "result.card": "En faire une carte de Noël",
  "result.tree": "L’ajouter à votre sapin de Noël",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Noël",
  "error.unsupported": "Nous n’avons pas pu utiliser cette photo. Essayez une image plus nette avec des visages visibles.",
  "error.generation": "La magie de Noël n’a pas fonctionné cette fois. Réessayons.",
  "error.network": "Problème de connexion. Votre sélection est enregistrée — veuillez réessayer.",
  "error.generic": "Une erreur s’est produite. Veuillez réessayer.",
  "error.paidKeepLink": "Si vous avez déjà payé, gardez votre lien de commande — le support peut réessayer sans vous facturer à nouveau.",
  "busy.working": "Traitement…",
  "busy.uploading": "Téléversement de votre photo…",
  "hero.cta": "Créer ma photo de Noël",
  "nav.hub": "Hub de Noël",
  "nav.family": "Famille",
  "nav.couples": "Couples",
  "nav.pets": "Animaux",
  "nav.dogs": "Chiens",
  "nav.cats": "Chats",
  "nav.cards": "Cartes de Noël",
  "nav.tree": "Sapin de Noël",
  "category.family": "Famille",
  "category.couples": "Couples",
  "category.pets": "Animaux",
  "category.aria": "Choisir une catégorie d’exemples",
  "upload.replace": "Remplacer la photo",
  "funnel.upload": "Téléverser votre photo",
  "funnel.style": "Choisissez un style de Noël",
  "funnel.continueOffer": "Continuer vers l’offre",
  "funnel.unlock": "Débloquez votre portrait de Noël",
  "funnel.readyMinutes": "Généralement prêt quelques minutes après le paiement",
  "funnel.privateDownload": "Privé par défaut · téléchargement via le lien de commande",
  "funnel.email": "E-mail pour reçu / récupération (optionnel)",
  "funnel.preparing": "Préparation du paiement…",
  "funnel.checkoutDisabled": "Le paiement se prépare pour le lancement. Vous pouvez téléverser, choisir un style et prévisualiser — le paiement s’active quand les prix sont en ligne.",
  "funnel.securePayment": "Paiement sécurisé",
  "funnel.creating": "Création de votre portrait",
  "funnel.magic": "Un peu de magie de Noël…",
  "funnel.leaveNote": "Vous pouvez fermer cette page — rouvrez le lien de commande à tout moment.",
  "funnel.download": "Télécharger",
  "funnel.share": "Partager",
  "funnel.card": "En faire une carte de Noël",
  "funnel.another": "Créer un autre",
  "funnel.tryAnother": "Essayer autre chose :",
  "funnel.errorTitle": "Une erreur s’est produite",
  "funnel.errorPaid": "Si vous avez déjà payé, gardez votre lien de commande — le support peut réessayer sans vous facturer à nouveau.",
  "funnel.working": "Traitement…",
  "funnel.yourUpload": "Votre téléversement",
  "funnel.blurredPreview": "Aperçu flouté de votre photo",
  "funnel.previewLede": "Votre transformation de Noël est prête à créer. Cet aperçu est votre photo originale, fortement floutée — le portrait IA final se débloque après paiement.",
  "funnel.styleLabel": "Style",
  "funnel.dogs": "Chiens",
  "funnel.cats": "Chats",
  "funnel.hub": "Hub de Noël",
  "funnel.photoGen": "Générateur de photos de Noël IA",
  "funnel.fileHint": "JPEG, PNG ou WebP · moins de 15 Mo",
  "funnel.portraitAlt": "Votre portrait de Noël",
  "styleName.cozy_fireplace": "Noël cosy",
  "styleDesc.cozy_fireplace": "Cheminée, lumières chaudes, sapin.",
  "styleName.winter_wonderland": "Pays des merveilles d’hiver",
  "styleDesc.winter_wonderland": "Neige, atmosphère hivernale élégante.",
  "styleName.vintage_christmas": "Noël de luxe",
  "styleDesc.vintage_christmas": "Pièce premium, détails dorés.",
  "styleName.christmas_movie": "Matin de Noël",
  "styleDesc.christmas_movie": "Maison chaleureuse, cadeaux, joie.",
  "styleName.north_pole": "Chalet enneigé",
  "styleDesc.north_pole": "Chalet de montagne, neige, feu.",
  "styleName.classic_christmas": "Noël classique",
  "styleDesc.classic_christmas": "Rouge, vert et or traditionnels.",
  "styleName.elegant_christmas": "Noël blanc élégant",
  "styleDesc.elegant_christmas": "Style d’hiver lumineux et raffiné.",
  "styleName.santas_workshop": "Marché de Noël",
  "styleDesc.santas_workshop": "Lumières festives européennes.",
  "styleName.classic_family_christmas": "Noël de famille classique",
  "styleDesc.classic_family_christmas": "Portrait de famille traditionnel près du sapin.",
  "styleName.family_cozy_fireplace": "Cheminée cosy",
  "styleDesc.family_cozy_fireplace": "Famille réunie à la lueur du feu.",
  "styleName.family_winter_wonderland": "Pays des merveilles d’hiver",
  "styleDesc.family_winter_wonderland": "Magie de Noël sous la neige.",
  "styleName.family_elegant_christmas": "Noël élégant",
  "styleDesc.family_elegant_christmas": "Portrait du soir raffiné.",
  "styleName.family_christmas_morning": "Matin de Noël",
  "styleDesc.family_christmas_morning": "Douce lumière du matin.",
  "styleName.family_luxury_christmas": "Noël de luxe",
  "styleDesc.family_luxury_christmas": "Portrait familial boutique.",
  "styleName.family_christmas_movie": "Film de Noël",
  "styleDesc.family_christmas_movie": "Image cinématographique de famille.",
  "styleName.family_vintage_christmas": "Noël vintage familial",
  "styleDesc.family_vintage_christmas": "Chaleur nostalgique de film.",
  "styleName.romantic_snowfall": "Neige romantique",
  "styleDesc.romantic_snowfall": "Neige douce et lumière intime.",
  "styleName.couple_cozy_fireplace": "Cheminée cosy",
  "styleDesc.couple_cozy_fireplace": "Portrait de couple au feu.",
  "styleName.couple_christmas_movie": "Film de Noël",
  "styleDesc.couple_christmas_movie": "Image cinématographique de couple.",
  "styleName.couple_elegant_christmas": "Noël élégant",
  "styleDesc.couple_elegant_christmas": "Portrait formel du soir.",
  "styleName.couple_winter_city": "Ville d’hiver",
  "styleDesc.couple_winter_city": "Lumières de la ville et manteaux.",
  "styleName.couple_christmas_market": "Marché de Noël",
  "styleDesc.couple_christmas_market": "Éclat festif du marché.",
  "styleName.couple_classic_portrait": "Portrait classique",
  "styleDesc.couple_classic_portrait": "Look studio intemporel.",
  "styleName.couple_vintage_christmas": "Noël vintage",
  "styleDesc.couple_vintage_christmas": "Chaleur nostalgique de film.",
  "styleName.santa_pet": "Animal du Père Noël",
  "styleDesc.santa_pet": "Portrait festif inspiré du Père Noël.",
  "styleName.pet_cozy_christmas": "Noël cosy",
  "styleDesc.pet_cozy_christmas": "Lueur du feu et couvertures douces.",
  "styleName.pet_north_pole": "Pôle Nord",
  "styleDesc.pet_north_pole": "Portrait magique enneigé.",
  "styleName.pet_christmas_sweater": "Pull de Noël",
  "styleDesc.pet_christmas_sweater": "Tricot festif sans masquer l’identité.",
  "styleName.pet_snow_portrait": "Portrait dans la neige",
  "styleDesc.pet_snow_portrait": "Portrait net en extérieur.",
  "styleName.pet_christmas_card": "Carte de Noël",
  "styleDesc.pet_christmas_card": "Portrait prêt pour une carte.",
  "styleName.pet_royal_christmas": "Noël royal",
  "styleDesc.pet_royal_christmas": "Portrait de fête majestueux.",
  "styleName.pet_vintage_christmas": "Noël vintage",
  "styleDesc.pet_vintage_christmas": "Portrait nostalgique de film.",
};

const ES: CopyBag = {
  "upload.kicker": "Empieza aquí",
  "upload.h2": "Sube tu foto",
  "upload.lede": "Elige una foto nítida y la convertiremos en un retrato mágico de Navidad.",
  "upload.choose": "Elegir foto",
  "upload.drop": "O suelta una foto aquí",
  "upload.hint": "JPEG, PNG o WebP · menos de 15 MB",
  "upload.guidanceTitle": "Para el mejor resultado:",
  "upload.g1": "usa una foto nítida",
  "upload.g2": "los rostros deben verse",
  "upload.g3": "evita imágenes muy borrosas",
  "upload.g4": "incluye a todos los que quieras en el retrato",
  "upload.privacy": "Tu subida permanece privada por defecto. Los retratos listos están disponibles con el enlace del pedido.",
  "subject.h2": "¿Quién está en la foto?",
  "subject.lede": "Adaptaremos el look navideño a tus sujetos.",
  "subject.family": "Familia",
  "subject.couple": "Pareja",
  "subject.person": "Una persona",
  "subject.pet": "Mascota",
  "subject.person_pet": "Persona + mascota",
  "subject.continue": "Continuar",
  "style.h2": "Estilos de foto de Navidad",
  "style.lede": "Elige el look navideño que quieras.",
  "style.back": "Atrás",
  "preview.h2": "Listo para crear",
  "preview.lede": "Esta vista previa es tu foto original, suavemente velada — el retrato final se desbloquea tras el pago.",
  "preview.continue": "Continuar",
  "offer.h2": "Desbloquea tu retrato de Navidad",
  "offer.ready": "Suele estar listo unos minutos después del pago",
  "offer.private": "Privado por defecto · descarga con el enlace del pedido",
  "offer.email": "Email para recibo / recuperación (opcional)",
  "offer.pay": "Continuar al pago",
  "offer.disabled": "El pago se prepara para el lanzamiento. Puedes subir, elegir estilo y previsualizar — el pago se activa cuando los precios estén en vivo.",
  "offer.busy": "Preparando el pago…",
  "checkout.h2": "Pago seguro",
  "gen.h2": "Creando tu retrato de Navidad",
  "gen.step1": "Preparando la escena navideña…",
  "gen.step2": "Añadiendo las luces…",
  "gen.step3": "Creando un poco de magia navideña…",
  "gen.step4": "Tu retrato casi está listo…",
  "gen.note": "Puedes salir de esta página — reabre el enlace del pedido cuando quieras.",
  "result.h2": "Tu retrato de Navidad",
  "result.download": "Descargar",
  "result.share": "Compartir",
  "result.another": "Crear otro",
  "result.retryStyle": "Probar otro estilo",
  "result.card": "Convertir en tarjeta de Navidad",
  "result.tree": "Añadir a tu árbol de Navidad",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Navidad",
  "error.unsupported": "No pudimos usar esta foto. Prueba una imagen más nítida con rostros visibles.",
  "error.generation": "La magia navideña no funcionó esta vez. Intentémoslo de nuevo.",
  "error.network": "Problema de conexión. Tu selección está guardada — inténtalo de nuevo.",
  "error.generic": "Algo salió mal. Inténtalo de nuevo.",
  "error.paidKeepLink": "Si ya pagaste, guarda el enlace del pedido — el soporte puede reintentar sin cobrarte de nuevo.",
  "busy.working": "Trabajando…",
  "busy.uploading": "Subiendo tu foto…",
  "hero.cta": "Crear mi foto de Navidad",
  "nav.hub": "Hub de Navidad",
  "nav.family": "Familia",
  "nav.couples": "Parejas",
  "nav.pets": "Mascotas",
  "nav.dogs": "Perros",
  "nav.cats": "Gatos",
  "nav.cards": "Tarjetas de Navidad",
  "nav.tree": "Árbol de Navidad",
  "category.family": "Familia",
  "category.couples": "Parejas",
  "category.pets": "Mascotas",
  "category.aria": "Elegir una categoría de ejemplos",
  "upload.replace": "Reemplazar foto",
  "funnel.upload": "Sube tu foto",
  "funnel.style": "Elige un estilo navideño",
  "funnel.continueOffer": "Continuar a la oferta",
  "funnel.unlock": "Desbloquea tu retrato de Navidad",
  "funnel.readyMinutes": "Suele estar listo unos minutos después del pago",
  "funnel.privateDownload": "Privado por defecto · descarga con el enlace del pedido",
  "funnel.email": "Email para recibo / recuperación (opcional)",
  "funnel.preparing": "Preparando el pago…",
  "funnel.checkoutDisabled": "El pago se prepara para el lanzamiento. Puedes subir, elegir estilo y previsualizar — el pago se activa cuando los precios estén en vivo.",
  "funnel.securePayment": "Pago seguro",
  "funnel.creating": "Creando tu retrato",
  "funnel.magic": "Un poco de magia navideña…",
  "funnel.leaveNote": "Puedes cerrar esta página — reabre el enlace del pedido cuando quieras.",
  "funnel.download": "Descargar",
  "funnel.share": "Compartir",
  "funnel.card": "Convertir en tarjeta de Navidad",
  "funnel.another": "Crear otro",
  "funnel.tryAnother": "Probar otro:",
  "funnel.errorTitle": "Algo salió mal",
  "funnel.errorPaid": "Si ya pagaste, guarda el enlace del pedido — el soporte puede reintentar sin cobrarte de nuevo.",
  "funnel.working": "Trabajando…",
  "funnel.yourUpload": "Tu subida",
  "funnel.blurredPreview": "Vista previa difuminada de tu foto",
  "funnel.previewLede": "Tu transformación navideña está lista para crear. Esta vista previa es tu foto original, muy difuminada — el retrato IA final se desbloquea tras el pago.",
  "funnel.styleLabel": "Estilo",
  "funnel.dogs": "Perros",
  "funnel.cats": "Gatos",
  "funnel.hub": "Hub de Navidad",
  "funnel.photoGen": "Generador de fotos de Navidad con IA",
  "funnel.fileHint": "JPEG, PNG o WebP · menos de 15 MB",
  "funnel.portraitAlt": "Tu retrato de Navidad",
  "styleName.cozy_fireplace": "Navidad acogedora",
  "styleDesc.cozy_fireplace": "Chimenea, luces cálidas, árbol.",
  "styleName.winter_wonderland": "País de las maravillas invernal",
  "styleDesc.winter_wonderland": "Nieve, atmósfera invernal elegante.",
  "styleName.vintage_christmas": "Navidad de lujo",
  "styleDesc.vintage_christmas": "Habitación premium, detalles dorados.",
  "styleName.christmas_movie": "Mañana de Navidad",
  "styleDesc.christmas_movie": "Hogar cálido, regalos, alegría.",
  "styleName.north_pole": "Cabaña nevada",
  "styleDesc.north_pole": "Cabaña de montaña, nieve, fuego.",
  "styleName.classic_christmas": "Navidad clásica",
  "styleDesc.classic_christmas": "Rojo, verde y oro tradicionales.",
  "styleName.elegant_christmas": "Navidad blanca elegante",
  "styleDesc.elegant_christmas": "Estilo invernal luminoso y sofisticado.",
  "styleName.santas_workshop": "Mercadillo navideño",
  "styleDesc.santas_workshop": "Luces festivas europeas.",
  "styleName.classic_family_christmas": "Navidad familiar clásica",
  "styleDesc.classic_family_christmas": "Retrato familiar tradicional junto al árbol.",
  "styleName.family_cozy_fireplace": "Chimenea acogedora",
  "styleDesc.family_cozy_fireplace": "Familia reunida a la luz del fuego.",
  "styleName.family_winter_wonderland": "País de las maravillas invernal",
  "styleDesc.family_winter_wonderland": "Magia navideña bajo la nieve.",
  "styleName.family_elegant_christmas": "Navidad elegante",
  "styleDesc.family_elegant_christmas": "Retrato nocturno refinado.",
  "styleName.family_christmas_morning": "Mañana de Navidad",
  "styleDesc.family_christmas_morning": "Luz suave de la mañana.",
  "styleName.family_luxury_christmas": "Navidad de lujo",
  "styleDesc.family_luxury_christmas": "Retrato familiar boutique.",
  "styleName.family_christmas_movie": "Película de Navidad",
  "styleDesc.family_christmas_movie": "Fotograma cinematográfico familiar.",
  "styleName.family_vintage_christmas": "Navidad familiar vintage",
  "styleDesc.family_vintage_christmas": "Calidez nostálgica de cine.",
  "styleName.romantic_snowfall": "Nevada romántica",
  "styleDesc.romantic_snowfall": "Nieve suave y luz íntima.",
  "styleName.couple_cozy_fireplace": "Chimenea acogedora",
  "styleDesc.couple_cozy_fireplace": "Retrato de pareja al fuego.",
  "styleName.couple_christmas_movie": "Película de Navidad",
  "styleDesc.couple_christmas_movie": "Fotograma cinematográfico de pareja.",
  "styleName.couple_elegant_christmas": "Navidad elegante",
  "styleDesc.couple_elegant_christmas": "Retrato formal nocturno.",
  "styleName.couple_winter_city": "Ciudad de invierno",
  "styleDesc.couple_winter_city": "Luces de ciudad y abrigos.",
  "styleName.couple_christmas_market": "Mercadillo navideño",
  "styleDesc.couple_christmas_market": "Brillo festivo del mercado.",
  "styleName.couple_classic_portrait": "Retrato clásico",
  "styleDesc.couple_classic_portrait": "Look de estudio atemporal.",
  "styleName.couple_vintage_christmas": "Navidad vintage",
  "styleDesc.couple_vintage_christmas": "Calidez nostálgica de cine.",
  "styleName.santa_pet": "Mascota de Papá Noel",
  "styleDesc.santa_pet": "Retrato festivo inspirado en Papá Noel.",
  "styleName.pet_cozy_christmas": "Navidad acogedora",
  "styleDesc.pet_cozy_christmas": "Luz del fuego y mantas suaves.",
  "styleName.pet_north_pole": "Polo Norte",
  "styleDesc.pet_north_pole": "Retrato mágico nevado.",
  "styleName.pet_christmas_sweater": "Jersey de Navidad",
  "styleDesc.pet_christmas_sweater": "Punto festivo sin ocultar la identidad.",
  "styleName.pet_snow_portrait": "Retrato en la nieve",
  "styleDesc.pet_snow_portrait": "Retrato limpio al aire libre.",
  "styleName.pet_christmas_card": "Tarjeta de Navidad",
  "styleDesc.pet_christmas_card": "Retrato listo para tarjeta.",
  "styleName.pet_royal_christmas": "Navidad real",
  "styleDesc.pet_royal_christmas": "Retrato festivo majestuoso.",
  "styleName.pet_vintage_christmas": "Navidad vintage",
  "styleDesc.pet_vintage_christmas": "Retrato nostálgico de cine.",
};

const IT: CopyBag = {
  "upload.kicker": "Inizia qui",
  "upload.h2": "Carica la tua foto",
  "upload.lede": "Scegli una foto nitida e la trasformiamo in un ritratto magico di Natale.",
  "upload.choose": "Scegli foto",
  "upload.drop": "Oppure trascina una foto qui",
  "upload.hint": "JPEG, PNG o WebP · sotto i 15 MB",
  "upload.guidanceTitle": "Per il risultato migliore:",
  "upload.g1": "usa una foto nitida",
  "upload.g2": "i volti devono essere visibili",
  "upload.g3": "evita immagini molto sfocate",
  "upload.g4": "includi tutti quelli che vuoi nel ritratto",
  "upload.privacy": "Il caricamento resta privato di default. I ritratti finiti sono disponibili tramite il link dell’ordine.",
  "subject.h2": "Chi c’è nella foto?",
  "subject.lede": "Guidiamo il look natalizio per i tuoi soggetti.",
  "subject.family": "Famiglia",
  "subject.couple": "Coppia",
  "subject.person": "Una persona",
  "subject.pet": "Animale",
  "subject.person_pet": "Persona + animale",
  "subject.continue": "Continua",
  "style.h2": "Stili foto di Natale",
  "style.lede": "Scegli il look natalizio che vuoi.",
  "style.back": "Indietro",
  "preview.h2": "Pronto a creare",
  "preview.lede": "Questa anteprima è la tua foto originale, leggermente velata — il ritratto finito si sblocca dopo il checkout.",
  "preview.continue": "Continua",
  "offer.h2": "Sblocca il tuo ritratto di Natale",
  "offer.ready": "Di solito pronto pochi minuti dopo il pagamento",
  "offer.private": "Privato di default · download dal link dell’ordine",
  "offer.email": "Email per ricevuta / recupero (opzionale)",
  "offer.pay": "Continua al pagamento",
  "offer.disabled": "Il checkout si prepara al lancio. Puoi caricare, scegliere uno stile e vedere l’anteprima — il pagamento si attiva quando i prezzi sono live.",
  "offer.busy": "Preparazione del pagamento…",
  "checkout.h2": "Pagamento sicuro",
  "gen.h2": "Creazione del ritratto di Natale",
  "gen.step1": "Preparazione della scena natalizia…",
  "gen.step2": "Aggiunta delle luci…",
  "gen.step3": "Un po’ di magia di Natale…",
  "gen.step4": "Il tuo ritratto è quasi pronto…",
  "gen.note": "Puoi lasciare questa pagina — riapri il link dell’ordine in qualsiasi momento.",
  "result.h2": "Il tuo ritratto di Natale",
  "result.download": "Scarica",
  "result.share": "Condividi",
  "result.another": "Creane un altro",
  "result.retryStyle": "Prova un altro stile",
  "result.card": "Trasforma in un biglietto di Natale",
  "result.tree": "Aggiungilo al tuo albero di Natale",
  "result.toggleOriginal": "Originale",
  "result.toggleChristmas": "Natale",
  "error.unsupported": "Non abbiamo potuto usare questa foto. Prova un’immagine più nitida con volti visibili.",
  "error.generation": "La magia di Natale non ha funzionato questa volta. Riproviamo.",
  "error.network": "Problema di connessione. La selezione è salvata — riprova.",
  "error.generic": "Qualcosa è andato storto. Riprova.",
  "error.paidKeepLink": "Se hai già pagato, conserva il link dell’ordine — il supporto può riprovare senza addebitarti di nuovo.",
  "busy.working": "Elaborazione…",
  "busy.uploading": "Caricamento della foto…",
  "hero.cta": "Crea la mia foto di Natale",
  "nav.hub": "Hub di Natale",
  "nav.family": "Famiglia",
  "nav.couples": "Coppie",
  "nav.pets": "Animali",
  "nav.dogs": "Cani",
  "nav.cats": "Gatti",
  "nav.cards": "Biglietti di Natale",
  "nav.tree": "Albero di Natale",
  "category.family": "Famiglia",
  "category.couples": "Coppie",
  "category.pets": "Animali",
  "category.aria": "Scegli una categoria di esempi",
  "upload.replace": "Sostituisci foto",
  "funnel.upload": "Carica la tua foto",
  "funnel.style": "Scegli uno stile natalizio",
  "funnel.continueOffer": "Continua all’offerta",
  "funnel.unlock": "Sblocca il tuo ritratto di Natale",
  "funnel.readyMinutes": "Di solito pronto pochi minuti dopo il pagamento",
  "funnel.privateDownload": "Privato di default · download dal link dell’ordine",
  "funnel.email": "Email per ricevuta / recupero (opzionale)",
  "funnel.preparing": "Preparazione del pagamento…",
  "funnel.checkoutDisabled": "Il pagamento si sta preparando al lancio. Puoi caricare, scegliere uno stile e vedere l’anteprima — il pagamento si attiva quando i prezzi sono live.",
  "funnel.securePayment": "Pagamento sicuro",
  "funnel.creating": "Creazione del ritratto",
  "funnel.magic": "Un po’ di magia di Natale…",
  "funnel.leaveNote": "Puoi chiudere questa pagina — riapri il link dell’ordine quando vuoi.",
  "funnel.download": "Scarica",
  "funnel.share": "Condividi",
  "funnel.card": "Trasforma in un biglietto di Natale",
  "funnel.another": "Creane un altro",
  "funnel.tryAnother": "Prova altro:",
  "funnel.errorTitle": "Qualcosa è andato storto",
  "funnel.errorPaid": "Se hai già pagato, conserva il link dell’ordine — il supporto può riprovare senza addebitarti di nuovo.",
  "funnel.working": "Elaborazione…",
  "funnel.yourUpload": "Il tuo caricamento",
  "funnel.blurredPreview": "Anteprima sfocata della tua foto",
  "funnel.previewLede": "La trasformazione natalizia è pronta. Questa anteprima è la tua foto originale, molto sfocata — il ritratto IA finale si sblocca dopo il pagamento.",
  "funnel.styleLabel": "Stile",
  "funnel.dogs": "Cani",
  "funnel.cats": "Gatti",
  "funnel.hub": "Hub di Natale",
  "funnel.photoGen": "Generatore di foto di Natale IA",
  "funnel.fileHint": "JPEG, PNG o WebP · sotto i 15 MB",
  "funnel.portraitAlt": "Il tuo ritratto di Natale",
  "styleName.cozy_fireplace": "Natale accogliente",
  "styleDesc.cozy_fireplace": "Camino, luci calde, albero.",
  "styleName.winter_wonderland": "Paese delle meraviglie invernale",
  "styleDesc.winter_wonderland": "Neve, atmosfera elegante.",
  "styleName.vintage_christmas": "Natale di lusso",
  "styleDesc.vintage_christmas": "Stanza premium, dettagli dorati.",
  "styleName.christmas_movie": "Mattina di Natale",
  "styleDesc.christmas_movie": "Casa calda, regali, gioia.",
  "styleName.north_pole": "Baita innevata",
  "styleDesc.north_pole": "Baita di montagna, neve, fuoco.",
  "styleName.classic_christmas": "Natale classico",
  "styleDesc.classic_christmas": "Rosso, verde e oro tradizionali.",
  "styleName.elegant_christmas": "Natale bianco elegante",
  "styleDesc.elegant_christmas": "Stile invernale luminoso e raffinato.",
  "styleName.santas_workshop": "Mercatino di Natale",
  "styleDesc.santas_workshop": "Luci festive europee.",
  "styleName.classic_family_christmas": "Natale di famiglia classico",
  "styleDesc.classic_family_christmas": "Ritratto di famiglia tradizionale vicino all’albero.",
  "styleName.family_cozy_fireplace": "Camino accogliente",
  "styleDesc.family_cozy_fireplace": "Famiglia raccolta al fuoco.",
  "styleName.family_winter_wonderland": "Paese delle meraviglie invernale",
  "styleDesc.family_winter_wonderland": "Magia natalizia sotto la neve.",
  "styleName.family_elegant_christmas": "Natale elegante",
  "styleDesc.family_elegant_christmas": "Ritratto serale raffinato.",
  "styleName.family_christmas_morning": "Mattina di Natale",
  "styleDesc.family_christmas_morning": "Luce morbida del mattino.",
  "styleName.family_luxury_christmas": "Natale di lusso",
  "styleDesc.family_luxury_christmas": "Ritratto di famiglia boutique.",
  "styleName.family_christmas_movie": "Film di Natale",
  "styleDesc.family_christmas_movie": "Fotogramma cinematografico di famiglia.",
  "styleName.family_vintage_christmas": "Natale vintage di famiglia",
  "styleDesc.family_vintage_christmas": "Calore nostalgico da film.",
  "styleName.romantic_snowfall": "Neve romantica",
  "styleDesc.romantic_snowfall": "Neve soffice e luce intima.",
  "styleName.couple_cozy_fireplace": "Camino accogliente",
  "styleDesc.couple_cozy_fireplace": "Ritratto di coppia al fuoco.",
  "styleName.couple_christmas_movie": "Film di Natale",
  "styleDesc.couple_christmas_movie": "Fotogramma cinematografico di coppia.",
  "styleName.couple_elegant_christmas": "Natale elegante",
  "styleDesc.couple_elegant_christmas": "Ritratto formale serale.",
  "styleName.couple_winter_city": "Città d’inverno",
  "styleDesc.couple_winter_city": "Luci cittadine e cappotti.",
  "styleName.couple_christmas_market": "Mercatino di Natale",
  "styleDesc.couple_christmas_market": "Bagore festivo del mercato.",
  "styleName.couple_classic_portrait": "Ritratto classico",
  "styleDesc.couple_classic_portrait": "Look da studio senza tempo.",
  "styleName.couple_vintage_christmas": "Natale vintage",
  "styleDesc.couple_vintage_christmas": "Calore nostalgico da film.",
  "styleName.santa_pet": "Animale di Babbo Natale",
  "styleDesc.santa_pet": "Ritratto festivo ispirato a Babbo Natale.",
  "styleName.pet_cozy_christmas": "Natale accogliente",
  "styleDesc.pet_cozy_christmas": "Luce del fuoco e coperte morbide.",
  "styleName.pet_north_pole": "Polo Nord",
  "styleDesc.pet_north_pole": "Ritratto magico innevato.",
  "styleName.pet_christmas_sweater": "Maglione di Natale",
  "styleDesc.pet_christmas_sweater": "Maglia festiva senza nascondere l’identità.",
  "styleName.pet_snow_portrait": "Ritratto sulla neve",
  "styleDesc.pet_snow_portrait": "Ritratto nitido all’aperto.",
  "styleName.pet_christmas_card": "Biglietto di Natale",
  "styleDesc.pet_christmas_card": "Ritratto pronto per un biglietto.",
  "styleName.pet_royal_christmas": "Natale reale",
  "styleDesc.pet_royal_christmas": "Ritratto festivo regale.",
  "styleName.pet_vintage_christmas": "Natale vintage",
  "styleDesc.pet_vintage_christmas": "Ritratto nostalgico da film.",
};

const PT: CopyBag = {
  "upload.kicker": "Comece aqui",
  "upload.h2": "Carregue a sua foto",
  "upload.lede": "Escolha uma foto nítida e transformamo-la num retrato mágico de Natal.",
  "upload.choose": "Escolher foto",
  "upload.drop": "Ou largue uma foto aqui",
  "upload.hint": "JPEG, PNG ou WebP · menos de 15 MB",
  "upload.guidanceTitle": "Para o melhor resultado:",
  "upload.g1": "use uma foto nítida",
  "upload.g2": "os rostos devem estar visíveis",
  "upload.g3": "evite imagens muito desfocadas",
  "upload.g4": "inclua todos os que quiser no retrato",
  "upload.privacy": "O carregamento permanece privado por predefinição. Os retratos prontos estão disponíveis através do link da encomenda.",
  "subject.h2": "Quem está na foto?",
  "subject.lede": "Vamos orientar o visual de Natal para os seus sujeitos.",
  "subject.family": "Família",
  "subject.couple": "Casal",
  "subject.person": "Uma pessoa",
  "subject.pet": "Animal de estimação",
  "subject.person_pet": "Pessoa + animal",
  "subject.continue": "Continuar",
  "style.h2": "Estilos de foto de Natal",
  "style.lede": "Escolha o visual de Natal que pretende.",
  "style.back": "Voltar",
  "preview.h2": "Pronto a criar",
  "preview.lede": "Esta pré-visualização é a sua foto original, ligeiramente velada — o retrato final desbloqueia após o checkout.",
  "preview.continue": "Continuar",
  "offer.h2": "Desbloqueie o seu retrato de Natal",
  "offer.ready": "Normalmente pronto poucos minutos após o pagamento",
  "offer.private": "Privado por predefinição · descarregue pelo link da encomenda",
  "offer.email": "Email para recibo / recuperação (opcional)",
  "offer.pay": "Continuar para o pagamento",
  "offer.disabled": "O checkout está a preparar-se para o lançamento. Pode carregar, escolher um estilo e pré-visualizar — o pagamento ativa-se quando os preços estiverem disponíveis.",
  "offer.busy": "A preparar o pagamento…",
  "checkout.h2": "Pagamento seguro",
  "gen.h2": "A criar o seu retrato de Natal",
  "gen.step1": "A preparar a cena de Natal…",
  "gen.step2": "A adicionar as luzes…",
  "gen.step3": "A criar um pouco de magia de Natal…",
  "gen.step4": "O seu retrato está quase pronto…",
  "gen.note": "Pode sair desta página — reabra o link da encomenda a qualquer momento.",
  "result.h2": "O seu retrato de Natal",
  "result.download": "Descarregar",
  "result.share": "Partilhar",
  "result.another": "Criar outro",
  "result.retryStyle": "Experimentar outro estilo",
  "result.card": "Transformar num cartão de Natal",
  "result.tree": "Adicionar à árvore de Natal",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Natal",
  "error.unsupported": "Não foi possível usar esta foto. Tente uma imagem mais nítida com rostos visíveis.",
  "error.generation": "A magia de Natal não funcionou desta vez. Vamos tentar novamente.",
  "error.network": "Problema de ligação. A seleção está guardada — tente novamente.",
  "error.generic": "Algo correu mal. Tente novamente.",
  "error.paidKeepLink": "Se já pagou, guarde o link da encomenda — o suporte pode tentar novamente sem cobrar de novo.",
  "busy.working": "A trabalhar…",
  "busy.uploading": "A carregar a sua foto…",
  "hero.cta": "Criar a minha foto de Natal",
  "nav.hub": "Hub de Natal",
  "nav.family": "Família",
  "nav.couples": "Casais",
  "nav.pets": "Animais",
  "nav.dogs": "Cães",
  "nav.cats": "Gatos",
  "nav.cards": "Cartões de Natal",
  "nav.tree": "Árvore de Natal",
  "category.family": "Família",
  "category.couples": "Casais",
  "category.pets": "Animais",
  "category.aria": "Escolher uma categoria de exemplos",
  "upload.replace": "Substituir foto",
  "funnel.upload": "Carregar a sua foto",
  "funnel.style": "Escolha um estilo de Natal",
  "funnel.continueOffer": "Continuar para a oferta",
  "funnel.unlock": "Desbloqueie o seu retrato de Natal",
  "funnel.readyMinutes": "Normalmente pronto poucos minutos após o pagamento",
  "funnel.privateDownload": "Privado por predefinição · descarregue pelo link da encomenda",
  "funnel.email": "Email para recibo / recuperação (opcional)",
  "funnel.preparing": "A preparar o pagamento…",
  "funnel.checkoutDisabled": "O pagamento está a preparar-se para o lançamento. Pode carregar, escolher um estilo e pré-visualizar — o pagamento ativa-se quando os preços estiverem disponíveis.",
  "funnel.securePayment": "Pagamento seguro",
  "funnel.creating": "A criar o seu retrato",
  "funnel.magic": "Um pouco de magia de Natal…",
  "funnel.leaveNote": "Pode fechar esta página — reabra o link da encomenda a qualquer momento.",
  "funnel.download": "Descarregar",
  "funnel.share": "Partilhar",
  "funnel.card": "Transformar num cartão de Natal",
  "funnel.another": "Criar outro",
  "funnel.tryAnother": "Tentar outro:",
  "funnel.errorTitle": "Algo correu mal",
  "funnel.errorPaid": "Se já pagou, guarde o link da encomenda — o suporte pode tentar novamente sem cobrar de novo.",
  "funnel.working": "A trabalhar…",
  "funnel.yourUpload": "O seu carregamento",
  "funnel.blurredPreview": "Pré-visualização desfocada da sua foto",
  "funnel.previewLede": "A transformação de Natal está pronta a criar. Esta pré-visualização é a sua foto original, muito desfocada — o retrato IA final desbloqueia após o pagamento.",
  "funnel.styleLabel": "Estilo",
  "funnel.dogs": "Cães",
  "funnel.cats": "Gatos",
  "funnel.hub": "Hub de Natal",
  "funnel.photoGen": "Gerador de fotos de Natal com IA",
  "funnel.fileHint": "JPEG, PNG ou WebP · menos de 15 MB",
  "funnel.portraitAlt": "O seu retrato de Natal",
  "styleName.cozy_fireplace": "Natal acolhedor",
  "styleDesc.cozy_fireplace": "Lareira, luzes quentes, árvore.",
  "styleName.winter_wonderland": "País das maravilhas de inverno",
  "styleDesc.winter_wonderland": "Neve, atmosfera elegante de inverno.",
  "styleName.vintage_christmas": "Natal de luxo",
  "styleDesc.vintage_christmas": "Sala premium, detalhes dourados.",
  "styleName.christmas_movie": "Manhã de Natal",
  "styleDesc.christmas_movie": "Casa acolhedora, prendas, alegria.",
  "styleName.north_pole": "Cabana nevada",
  "styleDesc.north_pole": "Cabana de montanha, neve, lareira.",
  "styleName.classic_christmas": "Natal clássico",
  "styleDesc.classic_christmas": "Vermelho, verde e ouro tradicionais.",
  "styleName.elegant_christmas": "Natal branco elegante",
  "styleDesc.elegant_christmas": "Estilo de inverno luminoso e sofisticado.",
  "styleName.santas_workshop": "Mercado de Natal",
  "styleDesc.santas_workshop": "Luzes festivas europeias.",
  "styleName.classic_family_christmas": "Natal de família clássico",
  "styleDesc.classic_family_christmas": "Retrato de família tradicional junto à árvore.",
  "styleName.family_cozy_fireplace": "Lareira acolhedora",
  "styleDesc.family_cozy_fireplace": "Família reunida à luz do fogo.",
  "styleName.family_winter_wonderland": "País das maravilhas de inverno",
  "styleDesc.family_winter_wonderland": "Magia de Natal na neve.",
  "styleName.family_elegant_christmas": "Natal elegante",
  "styleDesc.family_elegant_christmas": "Retrato noturno refinado.",
  "styleName.family_christmas_morning": "Manhã de Natal",
  "styleDesc.family_christmas_morning": "Luz suave da manhã.",
  "styleName.family_luxury_christmas": "Natal de luxo",
  "styleDesc.family_luxury_christmas": "Retrato de família boutique.",
  "styleName.family_christmas_movie": "Filme de Natal",
  "styleDesc.family_christmas_movie": "Fotograma cinematográfico de família.",
  "styleName.family_vintage_christmas": "Natal vintage de família",
  "styleDesc.family_vintage_christmas": "Calor nostálgico de filme.",
  "styleName.romantic_snowfall": "Neve romântica",
  "styleDesc.romantic_snowfall": "Neve suave e luz íntima.",
  "styleName.couple_cozy_fireplace": "Lareira acolhedora",
  "styleDesc.couple_cozy_fireplace": "Retrato de casal ao lume.",
  "styleName.couple_christmas_movie": "Filme de Natal",
  "styleDesc.couple_christmas_movie": "Fotograma cinematográfico de casal.",
  "styleName.couple_elegant_christmas": "Natal elegante",
  "styleDesc.couple_elegant_christmas": "Retrato formal noturno.",
  "styleName.couple_winter_city": "Cidade de inverno",
  "styleDesc.couple_winter_city": "Luzes da cidade e casacos.",
  "styleName.couple_christmas_market": "Mercado de Natal",
  "styleDesc.couple_christmas_market": "Brilho festivo do mercado.",
  "styleName.couple_classic_portrait": "Retrato clássico",
  "styleDesc.couple_classic_portrait": "Aspeto de estúdio intemporal.",
  "styleName.couple_vintage_christmas": "Natal vintage",
  "styleDesc.couple_vintage_christmas": "Calor nostálgico de filme.",
  "styleName.santa_pet": "Animal do Pai Natal",
  "styleDesc.santa_pet": "Retrato festivo inspirado no Pai Natal.",
  "styleName.pet_cozy_christmas": "Natal acolhedor",
  "styleDesc.pet_cozy_christmas": "Luz da lareira e mantas macias.",
  "styleName.pet_north_pole": "Pólo Norte",
  "styleDesc.pet_north_pole": "Retrato mágico nevado.",
  "styleName.pet_christmas_sweater": "Camisola de Natal",
  "styleDesc.pet_christmas_sweater": "Malha festiva sem esconder a identidade.",
  "styleName.pet_snow_portrait": "Retrato na neve",
  "styleDesc.pet_snow_portrait": "Retrato limpo ao ar livre.",
  "styleName.pet_christmas_card": "Cartão de Natal",
  "styleDesc.pet_christmas_card": "Retrato pronto para cartão.",
  "styleName.pet_royal_christmas": "Natal real",
  "styleDesc.pet_royal_christmas": "Retrato festivo majestoso.",
  "styleName.pet_vintage_christmas": "Natal vintage",
  "styleDesc.pet_vintage_christmas": "Retrato nostálgico de filme.",
};

const NL: CopyBag = {
  "upload.kicker": "Begin hier",
  "upload.h2": "Upload je foto",
  "upload.lede": "Kies een duidelijke foto en we maken er een magisch kerstportret van.",
  "upload.choose": "Foto kiezen",
  "upload.drop": "Of sleep een foto hierheen",
  "upload.hint": "JPEG, PNG of WebP · onder 15 MB",
  "upload.guidanceTitle": "Voor het beste resultaat:",
  "upload.g1": "gebruik een duidelijke foto",
  "upload.g2": "gezichten moeten zichtbaar zijn",
  "upload.g3": "vermijd extreem wazige beelden",
  "upload.g4": "neem iedereen mee die je in het portret wilt",
  "upload.privacy": "Je upload blijft standaard privé. Afgewerkte portretten zijn beschikbaar via je bestellink.",
  "subject.h2": "Wie staat er op de foto?",
  "subject.lede": "We stemmen de kerstlook af op je onderwerpen.",
  "subject.family": "Familie",
  "subject.couple": "Stel",
  "subject.person": "Eén persoon",
  "subject.pet": "Huisdier",
  "subject.person_pet": "Persoon + huisdier",
  "subject.continue": "Doorgaan",
  "style.h2": "Kerstfotostijlen",
  "style.lede": "Kies de kerstlook die je wilt.",
  "style.back": "Terug",
  "preview.h2": "Klaar om te maken",
  "preview.lede": "Deze voorvertoning is je originele foto, licht gesluierd — het afgewerkte kerstportret ontgrendelt na checkout.",
  "preview.continue": "Doorgaan",
  "offer.h2": "Ontgrendel je kerstportret",
  "offer.ready": "Meestal klaar enkele minuten na betaling",
  "offer.private": "Standaard privé · download via je bestellink",
  "offer.email": "E-mail voor bon / herstel (optioneel)",
  "offer.pay": "Doorgaan naar betaling",
  "offer.disabled": "Checkout wordt voorbereid voor de lancering. Je kunt uploaden, een stijl kiezen en voorvertonen — betaling gaat live wanneer de prijzen beschikbaar zijn.",
  "offer.busy": "Checkout voorbereiden…",
  "checkout.h2": "Veilige betaling",
  "gen.h2": "Je kerstportret wordt gemaakt",
  "gen.step1": "Kerstscène voorbereiden…",
  "gen.step2": "Lichtjes toevoegen…",
  "gen.step3": "Een beetje kerstmagie…",
  "gen.step4": "Je portret is bijna klaar…",
  "gen.note": "Je kunt deze pagina verlaten — open je bestellink wanneer je wilt opnieuw.",
  "result.h2": "Jouw kerstportret",
  "result.download": "Downloaden",
  "result.share": "Delen",
  "result.another": "Nog een maken",
  "result.retryStyle": "Andere stijl proberen",
  "result.card": "Maak er een kerstkaart van",
  "result.tree": "Toevoegen aan je kerstboom",
  "result.toggleOriginal": "Origineel",
  "result.toggleChristmas": "Kerst",
  "error.unsupported": "We konden deze foto niet gebruiken. Probeer een duidelijker beeld met zichtbare gezichten.",
  "error.generation": "De kerstmagie werkte die keer niet. Laten we het opnieuw proberen.",
  "error.network": "Verbindingsprobleem. Je selectie is opgeslagen — probeer opnieuw.",
  "error.generic": "Er ging iets mis. Probeer opnieuw.",
  "error.paidKeepLink": "Als je al hebt betaald, bewaar je bestellink — support kan opnieuw proberen zonder opnieuw te factureren.",
  "busy.working": "Bezig…",
  "busy.uploading": "Je foto uploaden…",
  "hero.cta": "Maak mijn kerstfoto",
  "nav.hub": "Kersthub",
  "nav.family": "Familie",
  "nav.couples": "Stellen",
  "nav.pets": "Huisdieren",
  "nav.dogs": "Honden",
  "nav.cats": "Katten",
  "nav.cards": "Kerstkaarten",
  "nav.tree": "Kerstboom",
  "category.family": "Familie",
  "category.couples": "Stellen",
  "category.pets": "Huisdieren",
  "category.aria": "Kies een voorbeeldcategorie",
  "upload.replace": "Foto vervangen",
  "funnel.upload": "Upload je foto",
  "funnel.style": "Kies een kerststijl",
  "funnel.continueOffer": "Doorgaan naar aanbieding",
  "funnel.unlock": "Ontgrendel je kerstportret",
  "funnel.readyMinutes": "Meestal klaar enkele minuten na betaling",
  "funnel.privateDownload": "Standaard privé · download via je bestellink",
  "funnel.email": "E-mail voor bon / herstel (optioneel)",
  "funnel.preparing": "Checkout voorbereiden…",
  "funnel.checkoutDisabled": "Checkout wordt voorbereid voor de lancering. Je kunt uploaden, een stijl kiezen en voorvertonen — betaling gaat live wanneer de prijzen beschikbaar zijn.",
  "funnel.securePayment": "Veilige betaling",
  "funnel.creating": "Je portret wordt gemaakt",
  "funnel.magic": "Een beetje kerstmagie…",
  "funnel.leaveNote": "Je kunt deze pagina sluiten — open je bestellink wanneer je wilt opnieuw.",
  "funnel.download": "Downloaden",
  "funnel.share": "Delen",
  "funnel.card": "Maak er een kerstkaart van",
  "funnel.another": "Nog een maken",
  "funnel.tryAnother": "Probeer iets anders:",
  "funnel.errorTitle": "Er ging iets mis",
  "funnel.errorPaid": "Als je al hebt betaald, bewaar je bestellink — support kan opnieuw proberen zonder opnieuw te factureren.",
  "funnel.working": "Bezig…",
  "funnel.yourUpload": "Jouw upload",
  "funnel.blurredPreview": "Vervagde voorvertoning van je foto",
  "funnel.previewLede": "Je kersttransformatie is klaar om te maken. Deze voorvertoning is je originele foto, sterk vervaagd — het afgewerkte AI-portret ontgrendelt na betaling.",
  "funnel.styleLabel": "Stijl",
  "funnel.dogs": "Honden",
  "funnel.cats": "Katten",
  "funnel.hub": "Kersthub",
  "funnel.photoGen": "AI-kerstfotogenerator",
  "funnel.fileHint": "JPEG, PNG of WebP · onder 15 MB",
  "funnel.portraitAlt": "Jouw kerstportret",
  "styleName.cozy_fireplace": "Gezellige kerst",
  "styleDesc.cozy_fireplace": "Open haard, warm licht, kerstboom.",
  "styleName.winter_wonderland": "Winterwonderland",
  "styleDesc.winter_wonderland": "Sneeuw, elegante wintersfeer.",
  "styleName.vintage_christmas": "Luxe kerst",
  "styleDesc.vintage_christmas": "Premium kamer, gouden details.",
  "styleName.christmas_movie": "Kerstochtend",
  "styleDesc.christmas_movie": "Warm huis, cadeaus, vreugde.",
  "styleName.north_pole": "Besneeuwde hut",
  "styleDesc.north_pole": "Berghut, sneeuw, haardvuur.",
  "styleName.classic_christmas": "Klassieke kerst",
  "styleDesc.classic_christmas": "Traditioneel rood, groen en goud.",
  "styleName.elegant_christmas": "Elegante witte kerst",
  "styleDesc.elegant_christmas": "Heldere, verfijnde winterstijl.",
  "styleName.santas_workshop": "Kerstmarkt",
  "styleDesc.santas_workshop": "Europese feestverlichting.",
  "styleName.classic_family_christmas": "Klassieke familiekerst",
  "styleDesc.classic_family_christmas": "Traditioneel familieportret bij de boom.",
  "styleName.family_cozy_fireplace": "Gezellige haard",
  "styleDesc.family_cozy_fireplace": "Familie bij het vuur.",
  "styleName.family_winter_wonderland": "Winterwonderland",
  "styleDesc.family_winter_wonderland": "Besneeuwde kerstmagie buiten.",
  "styleName.family_elegant_christmas": "Elegante kerst",
  "styleDesc.family_elegant_christmas": "Verfijnd avondportret.",
  "styleName.family_christmas_morning": "Kerstochtend",
  "styleDesc.family_christmas_morning": "Zacht ochtendlicht.",
  "styleName.family_luxury_christmas": "Luxe kerst",
  "styleDesc.family_luxury_christmas": "Gepolijst boutique-familieportret.",
  "styleName.family_christmas_movie": "Kerstfilm",
  "styleDesc.family_christmas_movie": "Filmisch familiestill.",
  "styleName.family_vintage_christmas": "Vintage familiekerst",
  "styleDesc.family_vintage_christmas": "Nostalgische filmwarmte.",
  "styleName.romantic_snowfall": "Romantische sneeuwval",
  "styleDesc.romantic_snowfall": "Zachte sneeuw en intiem licht.",
  "styleName.couple_cozy_fireplace": "Gezellige haard",
  "styleDesc.couple_cozy_fireplace": "Koppelportret bij het vuur.",
  "styleName.couple_christmas_movie": "Kerstfilm",
  "styleDesc.couple_christmas_movie": "Filmisch koppelstill.",
  "styleName.couple_elegant_christmas": "Elegante kerst",
  "styleDesc.couple_elegant_christmas": "Formeel avondportret.",
  "styleName.couple_winter_city": "Winterstad",
  "styleDesc.couple_winter_city": "Stadslichten en winterjassen.",
  "styleName.couple_christmas_market": "Kerstmarkt",
  "styleDesc.couple_christmas_market": "Feestelijke marktglow.",
  "styleName.couple_classic_portrait": "Klassiek portret",
  "styleDesc.couple_classic_portrait": "Tijdloze studio-look.",
  "styleName.couple_vintage_christmas": "Vintage kerst",
  "styleDesc.couple_vintage_christmas": "Nostalgische filmwarmte.",
  "styleName.santa_pet": "Kerstmanhuisdier",
  "styleDesc.santa_pet": "Feestelijk kerstmanportret.",
  "styleName.pet_cozy_christmas": "Gezellige kerst",
  "styleDesc.pet_cozy_christmas": "Vuurlicht en zachte dekens.",
  "styleName.pet_north_pole": "Noordpool",
  "styleDesc.pet_north_pole": "Besneeuwd magisch portret.",
  "styleName.pet_christmas_sweater": "Kersttrui",
  "styleDesc.pet_christmas_sweater": "Feestelijke brei zonder identiteit te verbergen.",
  "styleName.pet_snow_portrait": "Sneeuwportret",
  "styleDesc.pet_snow_portrait": "Helder buitenportret in de sneeuw.",
  "styleName.pet_christmas_card": "Kerstkaart",
  "styleDesc.pet_christmas_card": "Kaartklaar huisdierportret.",
  "styleName.pet_royal_christmas": "Koninklijke kerst",
  "styleDesc.pet_royal_christmas": "Vorstelijk feestportret.",
  "styleName.pet_vintage_christmas": "Vintage kerst",
  "styleDesc.pet_vintage_christmas": "Nostalgisch filmportret.",
};

const PL: CopyBag = {
  "upload.kicker": "Zacznij tutaj",
  "upload.h2": "Prześlij zdjęcie",
  "upload.lede": "Wybierz wyraźne zdjęcie — zamienimy je w magiczny świąteczny portret.",
  "upload.choose": "Wybierz zdjęcie",
  "upload.drop": "Lub upuść zdjęcie tutaj",
  "upload.hint": "JPEG, PNG lub WebP · poniżej 15 MB",
  "upload.guidanceTitle": "Aby uzyskać najlepszy efekt:",
  "upload.g1": "użyj wyraźnego zdjęcia",
  "upload.g2": "twarze powinny być widoczne",
  "upload.g3": "unikaj bardzo rozmazanych obrazów",
  "upload.g4": "uwzględnij wszystkich, których chcesz na portrecie",
  "upload.privacy": "Przesłanie pozostaje domyślnie prywatne. Gotowe portrety są dostępne przez link zamówienia.",
  "subject.h2": "Kto jest na zdjęciu?",
  "subject.lede": "Dopasujemy świąteczny look do Twoich obiektów.",
  "subject.family": "Rodzina",
  "subject.couple": "Para",
  "subject.person": "Jedna osoba",
  "subject.pet": "Zwierzak",
  "subject.person_pet": "Osoba + zwierzak",
  "subject.continue": "Kontynuuj",
  "style.h2": "Style świątecznych zdjęć",
  "style.lede": "Wybierz świąteczny wygląd, którego chcesz.",
  "style.back": "Wstecz",
  "preview.h2": "Gotowe do stworzenia",
  "preview.lede": "Ten podgląd to Twoje oryginalne zdjęcie, lekko zasłonięte — gotowy świąteczny portret odblokuje się po checkout.",
  "preview.continue": "Kontynuuj",
  "offer.h2": "Odblokuj swój świąteczny portret",
  "offer.ready": "Zwykle gotowe kilka minut po płatności",
  "offer.private": "Domyślnie prywatne · pobierz z linku zamówienia",
  "offer.email": "E-mail na potwierdzenie / odzyskanie (opcjonalnie)",
  "offer.pay": "Przejdź do płatności",
  "offer.disabled": "Checkout przygotowuje się do startu. Możesz przesłać, wybrać styl i zobaczyć podgląd — płatność włączy się, gdy ceny będą dostępne.",
  "offer.busy": "Przygotowujemy płatność…",
  "checkout.h2": "Bezpieczna płatność",
  "gen.h2": "Tworzymy Twój świąteczny portret",
  "gen.step1": "Przygotowujemy świąteczną scenę…",
  "gen.step2": "Dodajemy światła…",
  "gen.step3": "Tworzymy odrobinę świątecznej magii…",
  "gen.step4": "Twój portret jest prawie gotowy…",
  "gen.note": "Możesz opuścić tę stronę — otwórz link zamówienia w dowolnym momencie.",
  "result.h2": "Twój świąteczny portret",
  "result.download": "Pobierz",
  "result.share": "Udostępnij",
  "result.another": "Stwórz kolejny",
  "result.retryStyle": "Spróbuj innego stylu",
  "result.card": "Zamień w kartkę świąteczną",
  "result.tree": "Dodaj do choinki",
  "result.toggleOriginal": "Oryginał",
  "result.toggleChristmas": "Święta",
  "error.unsupported": "Nie mogliśmy użyć tego zdjęcia. Spróbuj wyraźniejszego obrazu z widocznymi twarzami.",
  "error.generation": "Świąteczna magia tym razem nie zadziałała. Spróbujmy ponownie.",
  "error.network": "Problem z połączeniem. Twój wybór jest zapisany — spróbuj ponownie.",
  "error.generic": "Coś poszło nie tak. Spróbuj ponownie.",
  "error.paidKeepLink": "Jeśli już zapłaciłeś, zachowaj link zamówienia — wsparcie może spróbować ponownie bez ponownego obciążenia.",
  "busy.working": "Pracujemy…",
  "busy.uploading": "Przesyłanie zdjęcia…",
  "hero.cta": "Stwórz moje świąteczne zdjęcie",
  "nav.hub": "Hub świąteczny",
  "nav.family": "Rodzina",
  "nav.couples": "Pary",
  "nav.pets": "Zwierzęta",
  "nav.dogs": "Psy",
  "nav.cats": "Koty",
  "nav.cards": "Kartki świąteczne",
  "nav.tree": "Choinka",
  "category.family": "Rodzina",
  "category.couples": "Pary",
  "category.pets": "Zwierzęta",
  "category.aria": "Wybierz kategorię przykładów",
  "upload.replace": "Zamień zdjęcie",
  "funnel.upload": "Prześlij zdjęcie",
  "funnel.style": "Wybierz świąteczny styl",
  "funnel.continueOffer": "Przejdź do oferty",
  "funnel.unlock": "Odblokuj swój świąteczny portret",
  "funnel.readyMinutes": "Zwykle gotowe kilka minut po płatności",
  "funnel.privateDownload": "Domyślnie prywatne · pobierz z linku zamówienia",
  "funnel.email": "E-mail na potwierdzenie / odzyskanie (opcjonalnie)",
  "funnel.preparing": "Przygotowujemy płatność…",
  "funnel.checkoutDisabled": "Płatność przygotowuje się do startu. Możesz przesłać, wybrać styl i zobaczyć podgląd — płatność włączy się, gdy ceny będą dostępne.",
  "funnel.securePayment": "Bezpieczna płatność",
  "funnel.creating": "Tworzymy Twój portret",
  "funnel.magic": "Odrobina świątecznej magii…",
  "funnel.leaveNote": "Możesz zamknąć tę stronę — otwórz link zamówienia w dowolnym momencie.",
  "funnel.download": "Pobierz",
  "funnel.share": "Udostępnij",
  "funnel.card": "Zamień w kartkę świąteczną",
  "funnel.another": "Stwórz kolejny",
  "funnel.tryAnother": "Spróbuj innego:",
  "funnel.errorTitle": "Coś poszło nie tak",
  "funnel.errorPaid": "Jeśli już zapłaciłeś, zachowaj link zamówienia — wsparcie może spróbować ponownie bez ponownego obciążenia.",
  "funnel.working": "Pracujemy…",
  "funnel.yourUpload": "Twój upload",
  "funnel.blurredPreview": "Rozmyty podgląd Twojego zdjęcia",
  "funnel.previewLede": "Świąteczna transformacja jest gotowa do stworzenia. Ten podgląd to Twoje oryginalne zdjęcie, mocno rozmyte — gotowy portret AI odblokuje się po płatności.",
  "funnel.styleLabel": "Styl",
  "funnel.dogs": "Psy",
  "funnel.cats": "Koty",
  "funnel.hub": "Hub świąteczny",
  "funnel.photoGen": "Generator świątecznych zdjęć AI",
  "funnel.fileHint": "JPEG, PNG lub WebP · poniżej 15 MB",
  "funnel.portraitAlt": "Twój świąteczny portret",
  "styleName.cozy_fireplace": "Przytulne święta",
  "styleDesc.cozy_fireplace": "Kominek, ciepłe światła, choinka.",
  "styleName.winter_wonderland": "Zimowa kraina czarów",
  "styleDesc.winter_wonderland": "Śnieg, elegancka zimowa atmosfera.",
  "styleName.vintage_christmas": "Luksusowe święta",
  "styleDesc.vintage_christmas": "Premium wnętrze, złote detale.",
  "styleName.christmas_movie": "Poranek Bożego Narodzenia",
  "styleDesc.christmas_movie": "Ciepły dom, prezenty, radość.",
  "styleName.north_pole": "Ośnieżona chatka",
  "styleDesc.north_pole": "Chatka w górach, śnieg, blask kominka.",
  "styleName.classic_christmas": "Klasyczne święta",
  "styleDesc.classic_christmas": "Tradycyjna czerwień, zieleń i złoto.",
  "styleName.elegant_christmas": "Eleganckie białe święta",
  "styleDesc.elegant_christmas": "Jasny, wyrafinowany zimowy styl.",
  "styleName.santas_workshop": "Jarmark świąteczny",
  "styleDesc.santas_workshop": "Europejskie świąteczne światła.",
  "styleName.classic_family_christmas": "Klasyczne święta rodzinne",
  "styleDesc.classic_family_christmas": "Tradycyjny portret rodzinny przy choince.",
  "styleName.family_cozy_fireplace": "Przytulny kominek",
  "styleDesc.family_cozy_fireplace": "Rodzina w blasku ognia.",
  "styleName.family_winter_wonderland": "Zimowa kraina czarów",
  "styleDesc.family_winter_wonderland": "Świąteczna magia na śniegu.",
  "styleName.family_elegant_christmas": "Eleganckie święta",
  "styleDesc.family_elegant_christmas": "Wyrafinowany wieczorny portret.",
  "styleName.family_christmas_morning": "Poranek Bożego Narodzenia",
  "styleDesc.family_christmas_morning": "Miękkie poranne światło.",
  "styleName.family_luxury_christmas": "Luksusowe święta",
  "styleDesc.family_luxury_christmas": "Boutique’owy portret rodzinny.",
  "styleName.family_christmas_movie": "Świąteczny film",
  "styleDesc.family_christmas_movie": "Filmowa klatka rodzinna.",
  "styleName.family_vintage_christmas": "Vintage święta rodzinne",
  "styleDesc.family_vintage_christmas": "Nostalgiczne ciepło filmu.",
  "styleName.romantic_snowfall": "Romantyczny śnieg",
  "styleDesc.romantic_snowfall": "Delikatny śnieg i intymne światło.",
  "styleName.couple_cozy_fireplace": "Przytulny kominek",
  "styleDesc.couple_cozy_fireplace": "Portret pary przy ogniu.",
  "styleName.couple_christmas_movie": "Świąteczny film",
  "styleDesc.couple_christmas_movie": "Filmowa klatka pary.",
  "styleName.couple_elegant_christmas": "Eleganckie święta",
  "styleDesc.couple_elegant_christmas": "Formalny wieczorny portret.",
  "styleName.couple_winter_city": "Zimowe miasto",
  "styleDesc.couple_winter_city": "Światła miasta i zimowe płaszcze.",
  "styleName.couple_christmas_market": "Jarmark świąteczny",
  "styleDesc.couple_christmas_market": "Świąteczny blask jarmarku.",
  "styleName.couple_classic_portrait": "Klasyczny portret",
  "styleDesc.couple_classic_portrait": "Ponadczasowy wygląd studyjny.",
  "styleName.couple_vintage_christmas": "Vintage święta",
  "styleDesc.couple_vintage_christmas": "Nostalgiczne ciepło filmu.",
  "styleName.santa_pet": "Pupil Świętego Mikołaja",
  "styleDesc.santa_pet": "Świąteczny portret inspirowany Mikołajem.",
  "styleName.pet_cozy_christmas": "Przytulne święta",
  "styleDesc.pet_cozy_christmas": "Blask ognia i miękkie koce.",
  "styleName.pet_north_pole": "Biegun Północny",
  "styleDesc.pet_north_pole": "Ośnieżony magiczny portret.",
  "styleName.pet_christmas_sweater": "Świąteczny sweter",
  "styleDesc.pet_christmas_sweater": "Świąteczny sweter bez ukrywania tożsamości.",
  "styleName.pet_snow_portrait": "Portret w śniegu",
  "styleDesc.pet_snow_portrait": "Czysty plenerowy portret.",
  "styleName.pet_christmas_card": "Kartka świąteczna",
  "styleDesc.pet_christmas_card": "Portret gotowy na kartkę.",
  "styleName.pet_royal_christmas": "Królewskie święta",
  "styleDesc.pet_royal_christmas": "Majestatyczny świąteczny portret.",
  "styleName.pet_vintage_christmas": "Vintage święta",
  "styleDesc.pet_vintage_christmas": "Nostalgiczny filmowy portret.",
};

export const PACKS: Record<PhotoGenLocale, CopyBag> = {
  en: EN, ro: RO, de: DE, fr: FR, es: ES, it: IT, pt: PT, nl: NL, pl: PL,
};

export const PHOTO_GEN_UI_KEYS = ["upload.kicker","upload.h2","upload.lede","upload.choose","upload.drop","upload.hint","upload.guidanceTitle","upload.g1","upload.g2","upload.g3","upload.g4","upload.privacy","subject.h2","subject.lede","subject.family","subject.couple","subject.person","subject.pet","subject.person_pet","subject.continue","style.h2","style.lede","style.back","preview.h2","preview.lede","preview.continue","offer.h2","offer.ready","offer.private","offer.email","offer.pay","offer.disabled","offer.busy","checkout.h2","gen.h2","gen.step1","gen.step2","gen.step3","gen.step4","gen.note","result.h2","result.download","result.share","result.another","result.retryStyle","result.card","result.tree","result.toggleOriginal","result.toggleChristmas","error.unsupported","error.generation","error.network","error.generic","error.paidKeepLink","busy.working","busy.uploading","hero.cta","nav.hub","nav.family","nav.couples","nav.pets","nav.dogs","nav.cats","nav.cards","nav.tree","category.family","category.couples","category.pets","category.aria","upload.replace","funnel.upload","funnel.style","funnel.continueOffer","funnel.unlock","funnel.readyMinutes","funnel.privateDownload","funnel.email","funnel.preparing","funnel.checkoutDisabled","funnel.securePayment","funnel.creating","funnel.magic","funnel.leaveNote","funnel.download","funnel.share","funnel.card","funnel.another","funnel.tryAnother","funnel.errorTitle","funnel.errorPaid","funnel.working","funnel.yourUpload","funnel.blurredPreview","funnel.previewLede","funnel.styleLabel","funnel.dogs","funnel.cats","funnel.hub","funnel.photoGen","funnel.fileHint","funnel.portraitAlt","styleName.cozy_fireplace","styleDesc.cozy_fireplace","styleName.winter_wonderland","styleDesc.winter_wonderland","styleName.vintage_christmas","styleDesc.vintage_christmas","styleName.christmas_movie","styleDesc.christmas_movie","styleName.north_pole","styleDesc.north_pole","styleName.classic_christmas","styleDesc.classic_christmas","styleName.elegant_christmas","styleDesc.elegant_christmas","styleName.santas_workshop","styleDesc.santas_workshop","styleName.classic_family_christmas","styleDesc.classic_family_christmas","styleName.family_cozy_fireplace","styleDesc.family_cozy_fireplace","styleName.family_winter_wonderland","styleDesc.family_winter_wonderland","styleName.family_elegant_christmas","styleDesc.family_elegant_christmas","styleName.family_christmas_morning","styleDesc.family_christmas_morning","styleName.family_luxury_christmas","styleDesc.family_luxury_christmas","styleName.family_christmas_movie","styleDesc.family_christmas_movie","styleName.family_vintage_christmas","styleDesc.family_vintage_christmas","styleName.romantic_snowfall","styleDesc.romantic_snowfall","styleName.couple_cozy_fireplace","styleDesc.couple_cozy_fireplace","styleName.couple_christmas_movie","styleDesc.couple_christmas_movie","styleName.couple_elegant_christmas","styleDesc.couple_elegant_christmas","styleName.couple_winter_city","styleDesc.couple_winter_city","styleName.couple_christmas_market","styleDesc.couple_christmas_market","styleName.couple_classic_portrait","styleDesc.couple_classic_portrait","styleName.couple_vintage_christmas","styleDesc.couple_vintage_christmas","styleName.santa_pet","styleDesc.santa_pet","styleName.pet_cozy_christmas","styleDesc.pet_cozy_christmas","styleName.pet_north_pole","styleDesc.pet_north_pole","styleName.pet_christmas_sweater","styleDesc.pet_christmas_sweater","styleName.pet_snow_portrait","styleDesc.pet_snow_portrait","styleName.pet_christmas_card","styleDesc.pet_christmas_card","styleName.pet_royal_christmas","styleDesc.pet_royal_christmas","styleName.pet_vintage_christmas","styleDesc.pet_vintage_christmas"] as const;

for (const loc of PHOTO_GEN_LOCALES) {
  for (const key of PHOTO_GEN_UI_KEYS) {
    if (!PACKS[loc][key]) throw new Error(`Photo generator UI missing ${key} for ${loc}`);
  }
}

export function photoGenT(
  key: string,
  locale: PhotoGenLocale = PHOTO_GEN_DEFAULT_LOCALE,
): string {
  return PACKS[locale]?.[key] ?? EN[key] ?? key;
}

export function photoStyleLabel(
  styleKey: string,
  locale: PhotoGenLocale = PHOTO_GEN_DEFAULT_LOCALE,
  fallback?: string,
): string {
  const key = `styleName.${styleKey}`;
  return PACKS[locale]?.[key] ?? EN[key] ?? fallback ?? styleKey;
}

export function photoStyleDescription(
  styleKey: string,
  locale: PhotoGenLocale = PHOTO_GEN_DEFAULT_LOCALE,
  fallback?: string,
): string {
  const key = `styleDesc.${styleKey}`;
  return PACKS[locale]?.[key] ?? EN[key] ?? fallback ?? "";
}

export function photoGenDir(locale: string): "ltr" | "rtl" {
  return PHOTO_GEN_LOCALE_DIR[locale] ?? "ltr";
}

export const PHOTO_GEN_COPY_KEYS = Object.keys(EN);

export const PHOTO_GEN_FAQS = [
  { qKey: "faq.1.q", aKey: "faq.1.a" },
  { qKey: "faq.2.q", aKey: "faq.2.a" },
  { qKey: "faq.3.q", aKey: "faq.3.a" },
  { qKey: "faq.4.q", aKey: "faq.4.a" },
  { qKey: "faq.5.q", aKey: "faq.5.a" },
  { qKey: "faq.6.q", aKey: "faq.6.a" },
  { qKey: "faq.7.q", aKey: "faq.7.a" },
  { qKey: "faq.8.q", aKey: "faq.8.a" },
  { qKey: "faq.9.q", aKey: "faq.9.a" },
] as const;
