/** Compact original TDG recipe specs. Traditional dish names are culinary facts; methods are original. */

export function d(spec) {
  return {
    region: spec.region || "",
    cuisine: spec.cuisine || spec.country,
    dietary: spec.dietary || [],
    allergens: spec.allergens || [],
    entitlementKey: spec.entitlementKey || "recipes",
    teaser: Boolean(spec.teaser),
    notes: spec.notes || "",
    tags: spec.tags || [],
    occasions: spec.occasions || ["christmas"],
    costBand: spec.costBand || "mid",
    ...spec,
  };
}

export const NAMED_DISHES = [
  d({
    slug: "herb-butter-roast-turkey",
    title: "Herb-butter roast turkey",
    country: "united-states",
    region: "midwest",
    cuisine: "american",
    course: "main",
    category: "christmas_dinner",
    difficulty: "advanced",
    prepMinutes: 40,
    cookMinutes: 210,
    servings: 12,
    costBand: "high",
    description: "A whole turkey roasted over onions and citrus, with thyme-sage butter under the skin so the breast stays juicy.",
    tags: ["christmas", "christmas-dinner", "traditional", "thanksgiving"],
    occasions: ["christmas", "christmas-dinner", "thanksgiving"],
    allergens: ["dairy"],
    ingredients: [
      [1, "piece", "whole turkey"],
      [150, "g", "unsalted butter"],
      [12, "g", "fresh thyme"],
      [8, "g", "fresh sage"],
      [4, "clove", "garlic"],
      [2, "piece", "onion"],
      [1, "piece", "lemon"],
      [12, "g", "kosher salt"],
      [4, "g", "black pepper"],
    ],
    steps: [
      "Heat the oven to 180°C. Pat the turkey dry inside and out, then season the cavity with salt.",
      "Mash the butter with chopped thyme, sage, garlic, salt and pepper. Loosen the breast skin and spread most of the butter underneath.",
      "Tuck onion wedges and lemon halves into the cavity. Set the turkey on a rack over the remaining onion.",
      "Roast until the thickest thigh reads 75°C, tenting the breast with foil if it browns too fast.",
      "Rest the turkey 30 minutes before carving so the juices settle back into the meat.",
    ],
    notes: "Plan about 15 minutes per 500 g after the first hour. Save the pan juices for gravy.",
  }),
  d({
    slug: "maple-glazed-ham",
    title: "Maple-glazed baked ham",
    country: "united-states",
    region: "new-england",
    cuisine: "american",
    course: "main",
    category: "christmas_dinner",
    difficulty: "medium",
    prepMinutes: 20,
    cookMinutes: 120,
    servings: 12,
    costBand: "high",
    description: "A smoked ham scored and lacquered with maple, mustard and clove for Christmas or Sunday supper.",
    tags: ["christmas", "christmas-dinner", "traditional"],
    occasions: ["christmas", "christmas-dinner"],
    allergens: ["mustard"],
    ingredients: [
      [3, "kg", "smoked ham"],
      [120, "ml", "maple syrup"],
      [40, "g", "brown sugar"],
      [30, "g", "dijon mustard"],
      [12, "piece", "whole cloves"],
      [15, "ml", "apple cider vinegar"],
    ],
    steps: [
      "Heat the oven to 160°C. Score the ham fat in a diamond pattern and stud a few intersections with cloves.",
      "Stir maple syrup, brown sugar, mustard and vinegar into a thick glaze.",
      "Bake the ham covered for 70 minutes, then uncover and brush with glaze every 15 minutes.",
      "Finish until the crust is glossy and the centre is piping hot.",
      "Rest 15 minutes, then slice across the grain so each piece keeps a ribbon of glaze.",
    ],
    notes: "Use leftover bone for a pot of beans the next day.",
  }),
  d({
    slug: "sausage-sage-stuffing",
    title: "Sausage and sage stuffing",
    country: "united-states",
    region: "midwest",
    cuisine: "american",
    course: "side",
    category: "side_dishes",
    difficulty: "easy",
    prepMinutes: 25,
    cookMinutes: 45,
    servings: 10,
    costBand: "mid",
    description: "Toasted bread, browned sausage and lots of sage baked until the edges crisp and the centre stays moist.",
    tags: ["christmas", "christmas-dinner", "thanksgiving", "traditional"],
    occasions: ["christmas", "thanksgiving"],
    allergens: ["gluten", "dairy"],
    ingredients: [
      [500, "g", "country bread"],
      [400, "g", "pork sausage"],
      [80, "g", "unsalted butter"],
      [2, "piece", "onion"],
      [3, "piece", "celery stalk"],
      [12, "g", "fresh sage"],
      [400, "ml", "chicken stock"],
      [2, "piece", "eggs"],
    ],
    steps: [
      "Heat the oven to 180°C. Tear the bread into chunks and dry them on a tray for 10 minutes.",
      "Brown the sausage, then soften onion and celery in the butter with chopped sage.",
      "Toss bread with the pan mixture, beaten eggs and enough stock to moisten without soupiness.",
      "Bake in a buttered dish until the top is deep gold and the centre is set.",
      "Rest 10 minutes so slices hold together on the plate.",
    ],
    notes: "Bake separately rather than inside the bird so both cook evenly.",
  }),
  d({
    slug: "creamy-mashed-potatoes",
    title: "Creamy mashed potatoes",
    country: "united-states",
    region: "midwest",
    cuisine: "american",
    course: "side",
    category: "side_dishes",
    difficulty: "easy",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 8,
    costBand: "low",
    description: "Floury potatoes mashed with warm butter and milk until they sit in soft peaks.",
    tags: ["christmas", "christmas-dinner", "thanksgiving", "budget"],
    occasions: ["christmas", "thanksgiving"],
    allergens: ["dairy"],
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      [1500, "g", "floury potatoes"],
      [80, "g", "unsalted butter"],
      [180, "ml", "whole milk"],
      [8, "g", "kosher salt"],
      [2, "g", "white pepper"],
    ],
    steps: [
      "Peel the potatoes, cut into even chunks and start them in cold salted water.",
      "Simmer until a knife slides through, then drain thoroughly and return to the hot pan to steam dry.",
      "Warm the milk with butter. Mash the potatoes and beat in the dairy until smooth.",
      "Season with salt and white pepper. Do not add cold milk or the mash turns gluey.",
      "Cover and keep warm; loosen with a splash more hot milk just before serving.",
    ],
    notes: "500 g plus 1 kg potatoes in other recipes will merge on the grocery list.",
  }),
  d({
    slug: "brown-butter-green-beans",
    title: "Brown-butter green beans with almonds",
    country: "united-states",
    region: "pacific",
    cuisine: "american",
    course: "side",
    category: "side_dishes",
    difficulty: "easy",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 8,
    costBand: "mid",
    description: "Blanched beans tossed in nutty brown butter and toasted almonds · a lighter Christmas side.",
    tags: ["christmas", "quick", "vegetarian"],
    occasions: ["christmas", "christmas-dinner"],
    allergens: ["dairy", "nuts"],
    dietary: ["vegetarian", "gluten-free"],
    ingredients: [
      [800, "g", "green beans"],
      [60, "g", "unsalted butter"],
      [40, "g", "flaked almonds"],
      [1, "piece", "lemon"],
      [6, "g", "salt"],
    ],
    steps: [
      "Trim the beans and boil in salted water until just tender, then plunge into ice water.",
      "Toast the almonds in a dry pan until they smell sweet, then tip them out.",
      "Melt the butter in the same pan and cook until the milk solids turn hazelnut brown.",
      "Toss in the drained beans, lemon zest and almonds. Finish with lemon juice and salt.",
      "Serve immediately so the butter stays foamy and the beans stay bright.",
    ],
    notes: "Skip almonds if anyone at the table has a nut allergy.",
  }),
  d({
    slug: "jellied-cranberry-sauce",
    title: "Jellied cranberry sauce",
    country: "united-states",
    region: "new-england",
    cuisine: "american",
    course: "side",
    category: "side_dishes",
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 10,
    costBand: "low",
    description: "Fresh cranberries cooked with orange and sugar until they set into a sliceable sauce.",
    tags: ["christmas", "thanksgiving", "make-ahead", "budget"],
    occasions: ["christmas", "thanksgiving"],
    dietary: ["vegan", "vegetarian", "gluten-free"],
    ingredients: [
      [350, "g", "fresh cranberries"],
      [150, "g", "sugar"],
      [120, "ml", "orange juice"],
      [1, "piece", "orange"],
      [1, "pinch", "salt"],
    ],
    steps: [
      "Combine cranberries, sugar, orange juice, a strip of orange zest and salt in a saucepan.",
      "Cook over medium heat until the berries burst and the liquid looks syrupy.",
      "Mash lightly, then simmer 3 minutes more so the natural pectin can set.",
      "Pour into a small bowl, cool, then refrigerate until firm enough to unmould.",
      "Slice or spoon beside roast meat. It keeps 5 days chilled.",
    ],
    notes: "Make this two days ahead; the flavour rounds out overnight.",
  }),
  d({
    slug: "sweet-potato-pecan-bake",
    title: "Sweet potato bake with pecan crumb",
    country: "united-states",
    region: "south",
    cuisine: "american",
    course: "side",
    category: "side_dishes",
    difficulty: "medium",
    prepMinutes: 25,
    cookMinutes: 40,
    servings: 10,
    costBand: "mid",
    description: "Mashed sweet potato under a pecan-oat crumb · festive without marshmallow.",
    tags: ["christmas", "thanksgiving", "vegetarian"],
    occasions: ["christmas", "thanksgiving"],
    allergens: ["nuts", "dairy", "gluten"],
    dietary: ["vegetarian"],
    ingredients: [
      [1200, "g", "sweet potatoes"],
      [60, "g", "unsalted butter"],
      [80, "ml", "maple syrup"],
      [80, "g", "pecans"],
      [40, "g", "rolled oats"],
      [2, "g", "cinnamon"],
      [4, "g", "salt"],
    ],
    steps: [
      "Heat the oven to 190°C. Roast or boil the sweet potatoes until completely soft, then mash with half the butter, maple, cinnamon and salt.",
      "Spread the mash in a baking dish.",
      "Chop pecans and rub them with oats and the remaining butter into a rough crumb.",
      "Scatter the crumb on top and bake until the nuts smell toasted and the edges bubble.",
      "Rest 10 minutes so scoops stay neat.",
    ],
    notes: "Use gluten-free oats if needed.",
  }),
  d({
    slug: "classic-pumpkin-pie",
    title: "Classic pumpkin pie",
    country: "united-states",
    region: "midwest",
    cuisine: "american",
    course: "dessert",
    category: "desserts",
    difficulty: "medium",
    prepMinutes: 30,
    cookMinutes: 55,
    servings: 8,
    costBand: "low",
    description: "Spiced pumpkin custard in a short crust · the Thanksgiving close that also belongs on a winter table.",
    tags: ["thanksgiving", "christmas", "traditional", "budget"],
    occasions: ["thanksgiving", "christmas"],
    allergens: ["gluten", "dairy", "eggs"],
    dietary: ["vegetarian"],
    ingredients: [
      [250, "g", "plain flour"],
      [125, "g", "cold butter"],
      [425, "g", "pumpkin puree"],
      [150, "ml", "evaporated milk"],
      [100, "g", "brown sugar"],
      [2, "piece", "eggs"],
      [4, "g", "pumpkin spice"],
      [3, "g", "salt"],
    ],
    steps: [
      "Rub butter into flour and salt, add a spoon of ice water, and rest the dough 30 minutes.",
      "Line a pie tin, prick the base, and chill while you beat pumpkin, milk, sugar, eggs and spice.",
      "Blind-bake the crust 12 minutes at 190°C, then lower the oven to 170°C.",
      "Pour in the filling and bake until the centre barely wobbles.",
      "Cool completely so the custard slices cleanly. Serve at cool room temperature.",
    ],
    notes: "Use plain pumpkin puree, not pumpkin pie filling.",
  }),
  d({
    slug: "pecan-pie",
    title: "Pecan pie",
    country: "united-states",
    region: "south",
    cuisine: "american",
    course: "dessert",
    category: "desserts",
    difficulty: "medium",
    prepMinutes: 25,
    cookMinutes: 50,
    servings: 8,
    costBand: "mid",
    description: "A buttery crust holding a dark sugar filling and a tight layer of pecans.",
    tags: ["thanksgiving", "christmas", "traditional"],
    occasions: ["thanksgiving", "christmas"],
    allergens: ["nuts", "gluten", "eggs", "dairy"],
    dietary: ["vegetarian"],
    ingredients: [
      [250, "g", "plain flour"],
      [125, "g", "cold butter"],
      [200, "g", "pecan halves"],
      [150, "g", "dark brown sugar"],
      [120, "ml", "golden syrup"],
      [3, "piece", "eggs"],
      [40, "g", "melted butter"],
      [5, "ml", "vanilla extract"],
      [2, "g", "salt"],
    ],
    steps: [
      "Make a short crust, line a tin, and chill it while the oven heats to 180°C.",
      "Whisk eggs, brown sugar, syrup, melted butter, vanilla and salt until smooth.",
      "Scatter pecans in the shell and pour the filling over so nuts rise to the top.",
      "Bake until the centre is just set and the nuts look lacquered.",
      "Cool to room temperature before slicing; the filling finishes setting as it cools.",
    ],
    notes: "A pinch of salt in the filling keeps the pie from tasting flat.",
  }),
  d({
    slug: "spiced-apple-cider",
    title: "Spiced apple cider",
    country: "united-states",
    region: "new-england",
    cuisine: "american",
    course: "drink",
    category: "drinks",
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 8,
    costBand: "low",
    description: "Fresh cider simmered with orange, cinnamon and clove · alcohol-free and house-filling.",
    tags: ["christmas", "drinks", "quick", "budget"],
    occasions: ["christmas", "christmas-eve"],
    dietary: ["vegan", "vegetarian", "gluten-free"],
    ingredients: [
      [1500, "ml", "apple cider"],
      [1, "piece", "orange"],
      [3, "piece", "cinnamon stick"],
      [6, "piece", "whole cloves"],
      [2, "piece", "star anise"],
      [20, "g", "brown sugar"],
    ],
    steps: [
      "Pour the cider into a pot with orange slices, cinnamon, cloves, star anise and sugar.",
      "Bring to a bare simmer · do not boil or the cider turns harsh.",
      "Steep 20 minutes, then taste and add a little more sugar only if the apples were very tart.",
      "Strain into mugs or a thermos.",
      "Keep extra on the lowest heat with the spices parked in a tea ball.",
    ],
    notes: "Use fresh cider, not apple juice from concentrate, if you can.",
  }),
];
