export {
  DEFAULT_INTERNAL_COUNTRY_CODES,
  DEFAULT_INTERNAL_GA4_COUNTRIES,
  clientIpFromHeaders,
  countryCodeFromHeaders,
  countryCodeIsInternal,
  hostnameMatchesExcludedCountryTld,
  hostnameMatchesTestMarkers,
  resolveClientIpHostname,
  resolveFunnelIsTest,
  resolveFunnelIsTestSync,
  utmCampaignIsTestMarker,
  utmSourceIsTestMarker,
  type WriteEnvironment,
} from "../petFunnelTrafficExclude";
