export const occasions = [
  {
    id: "christmas",
    title: "Christmas",
    category: "occasions",
    label: "Cozy snowy magic",
    description: "Turn any photo into a warm, cinematic Christmas card.",
    gradientFrom: "from-[#020617]",
    gradientTo: "to-[#1d4ed8]",
    image:
      "https://images.unsplash.com/photo-1514377006585-6e7975371bd6?q=80&w=3088&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "new-years-eve",
    title: "New Year's Eve",
    category: "occasions",
    label: "Gold & fireworks",
    description: "Sparkling countdown vibes with neon lights and confetti.",
    gradientFrom: "from-[#020617]",
    gradientTo: "to-[#f97316]",
    image:
      "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=400&h=300&fit=crop",
  },
  {
    id: "thanksgiving",
    title: "Thanksgiving",
    category: "occasions",
    label: "Warm & cozy dinner",
    description: "Autumn colors, candles and a grateful, family feel.",
    gradientFrom: "from-[#7c2d12]",
    gradientTo: "to-[#f97316]",
    image:
      "https://images.unsplash.com/photo-1574672280600-4accfa5b6f98?w=400&h=300&fit=crop",
  },
  {
    id: "birthday",
    title: "Happy Birthday",
    category: "occasions",
    label: "Party & confetti",
    description: "Balloons, cake and bright birthday energy.",
    gradientFrom: "from-[#4f46e5]",
    gradientTo: "to-[#ec4899]",
    image:
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=300&fit=crop",
  },
  {
    id: "baby-reveal",
    title: "Baby Reveal",
    category: "occasions",
    label: "Soft pastel surprise",
    description: "Gender reveal or baby news with dreamy pastel tones.",
    gradientFrom: "from-[#4c1d95]",
    gradientTo: "to-[#22c55e]",
    image:
      "https://images.unsplash.com/photo-1635388114403-e1c51f9493db?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "new-born",
    title: "New Born",
    category: "occasions",
    label: "Gentle & creamy",
    description: "Minimal, clean layouts that keep the baby in focus.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#22c55e]",
    image:
      "https://images.unsplash.com/photo-1504151932400-72d4384f04b3?w=400&h=300&fit=crop",
  },
  {
    id: "pregnancy",
    title: "Pregnancy",
    category: "occasions",
    label: "Soft glow",
    description: "Elegant silhouettes, warm light and calm tones.",
    gradientFrom: "from-[#581c87]",
    gradientTo: "to-[#f97316]",
    image:
      "https://images.unsplash.com/photo-1528218635780-5952720c9729?q=80&w=2076&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "wedding",
    title: "Wedding",
    category: "occasions",
    label: "Timeless & elegant",
    description: "Luxury, editorial-style wedding announcement cards.",
    gradientFrom: "from-[#020617]",
    gradientTo: "to-[#a855f7]",
    image:
      "https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=300&fit=crop",
  },
  {
    id: "easter",
    title: "Easter",
    category: "occasions",
    label: "Spring & pastel",
    description: "Fresh colors, flowers and soft daylight.",
    gradientFrom: "from-[#16a34a]",
    gradientTo: "to-[#22c55e]",
    image:
      "https://images.unsplash.com/photo-1522071901873-411886a10004?w=400&h=300&fit=crop",
  },
  {
    id: "valentines-day",
    title: "Valentine's Day",
    category: "occasions",
    label: "Romantic glow",
    description: "Cinematic couples, roses and candlelight.",
    gradientFrom: "from-[#7f1d1d]",
    gradientTo: "to-[#db2777]",
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400&h=300&fit=crop",
  },
  {
    id: "anniversary",
    title: "Anniversary",
    category: "occasions",
    label: "Classy & intimate",
    description: "Elegant layouts to celebrate any milestone.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#64748b]",
    image:
      "https://images.unsplash.com/photo-1525328302834-764f32276842?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "mothers-day",
    title: "Mother's Day",
    category: "occasions",
    label: "Soft & floral",
    description: "Delicate florals and warm light for mom.",
    gradientFrom: "from-[#be123c]",
    gradientTo: "to-[#fb7185]",
    image:
      "https://plus.unsplash.com/premium_photo-1676032285986-ae00bcd59bd2?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "fathers-day",
    title: "Father's Day",
    category: "occasions",
    label: "Bold & clean",
    description: "Minimal, modern layouts with strong contrast.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#334155]",
    image:
      "https://plus.unsplash.com/premium_photo-1723867282153-b4bdcdeeca87?q=80&w=2015&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: "graduation",
    title: "Graduation",
    category: "occasions",
    label: "Caps & confetti",
    description: "Sharp, modern cards to celebrate the big day.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#22c55e]",
    image:
      "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=400&h=300&fit=crop",
  },
  {
    id: "sorry",
    title: "Sorry",
    category: "personal",
    label: "Emotional apology",
    description: "Create a heartfelt apology card with soft, honest emotion.",
    gradientFrom: "from-[#7f1d1d]",
    gradientTo: "to-[#fb7185]",
    image: "/images/occasions/sorry.png",
  },
  {
    id: "name-cards",
    title: "Name Cards",
    category: "personal",
    label: "Made for one person",
    description: "Personal cards built around a name and a meaningful message.",
    gradientFrom: "from-[#312e81]",
    gradientTo: "to-[#ec4899]",
    image: "/images/occasions/default.png",
  },
  {
    id: "kids",
    title: "Kids",
    category: "personal",
    label: "Sweet & playful",
    description: "Colorful cards for children, family and joyful memories.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#38bdf8]",
    image: "/images/occasions/default.png",
  },
  {
    id: "bible-verses",
    title: "Bible Verses",
    category: "spiritual",
    label: "Faith & hope",
    description: "Beautiful spiritual cards with meaningful Bible-inspired messages.",
    gradientFrom: "from-[#312e81]",
    gradientTo: "to-[#f59e0b]",
    image: "/images/occasions/default.png",
  },
  {
    id: "prayer",
    title: "Prayer",
    category: "spiritual",
    label: "Warm encouragement",
    description: "Prayer cards for comfort, gratitude, hope and peace.",
    gradientFrom: "from-[#1e1b4b]",
    gradientTo: "to-[#a855f7]",
    image: "/images/occasions/default.png",
  },
  {
    id: "dogs",
    title: "Dogs",
    category: "pets",
    label: "Cute dog moments",
    description: "Funny, emotional and adorable cards for dog lovers.",
    gradientFrom: "from-[#431407]",
    gradientTo: "to-[#f97316]",
    image: "/images/occasions/default.png",
  },
  {
    id: "cats",
    title: "Cats",
    category: "pets",
    label: "Playful cat cards",
    description: "Sweet and funny cards for cat memories.",
    gradientFrom: "from-[#0f172a]",
    gradientTo: "to-[#22c55e]",
    image: "/images/occasions/default.png",
  },
  {
    id: "pet-loss",
    title: "Pet Loss",
    category: "pets",
    label: "Gentle remembrance",
    description: "Soft emotional cards for remembering a loved pet.",
    gradientFrom: "from-[#111827]",
    gradientTo: "to-[#64748b]",
    image: "/images/occasions/default.png",
  },
] as const;