export const TEMPLATES = [
  {
    id: "classic-grand-evergreen-portrait",
    title: "Grand Evergreen Portrait",
    category: "Classic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/d9eae752-a6f1-4f21-87d1-8371531fffc1",
    prompt:
      'Edit the uploaded photo so it matches the "Grand Evergreen Portrait" Classic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Classic Christmas tree with ornaments and warm bokeh lights; elegant living room.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive classic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["classic", "couple / duo", "portrait", "tree"],
  },
  {
    id: "classic-festive-dinner-table",
    title: "Festive Dinner Table",
    category: "Classic",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/24a44325-ec92-48b5-a1e7-a2ecd7c5cc0a",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Festive Dinner Table" Classic template.\n- Replace the environment with: Candle-lit table setting with crystal glasses, red-green accents, shallow depth of field.\n- Use lighting style: warm practicals.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 24,
    tags: ["candle", "classic", "landscape", "scene / no people", "table"],
  },
  {
    id: "classic-red-and-gold-card",
    title: "Red & Gold Card",
    category: "Classic",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/ca70f1d4-3b3e-487a-a646-da9954cff8c4",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Red & Gold Card" template.\n- Focus on creating a polished card layout with: Minimal red-gold border, snowflake corners, ample text area.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: [
      "card",
      "card / no people",
      "classic",
      "minimal",
      "portrait",
      "snow",
    ],
  },
  {
    id: "classic-wreath-entrance",
    title: "Wreath Entrance",
    category: "Classic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/1f71710d-4f78-4692-884b-0ddbff6580f8",
    prompt:
      'Edit the uploaded photo so it matches the "Wreath Entrance" Classic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family by door with wreath; warm porch lights; light snowfall bokeh.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive classic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["classic", "couple / duo", "family", "landscape", "snow", "wreath"],
  },
  {
    id: "classic-gift-unwrapping-moment",
    title: "Gift Unwrapping Moment",
    category: "Classic",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/00459fe1-633a-4d39-b25d-a74952141e50",
    prompt:
      'Edit the uploaded photo so it matches the "Gift Unwrapping Moment" Classic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Candid unwrapping near tree; sparkly ribbons; warm ambient.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive classic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["classic", "family / group", "landscape", "tree"],
  },
  {
    id: "classic-classic-ornaments-macro",
    title: "Classic Ornaments Macro",
    category: "Classic",
    subCategory: "Card / No people",
    type: "card",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/c1995c6f-5cda-4911-8e23-2f033c24f8ae",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Classic Ornaments Macro" template.\n- Focus on creating a polished card layout with: Macro baubles with soft glitter background.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "classic", "square"],
  },
  {
    id: "classic-golden-garland-frame",
    title: "Golden Garland Frame",
    category: "Classic",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/167599d6-a9b9-4fce-9a20-e3d8ae55aa1d",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Golden Garland Frame" template.\n- Focus on creating a polished card layout with: Ornate garland frame around photo cutout; text panel below.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "classic", "portrait"],
  },
  {
    id: "classic-choir-by-the-tree",
    title: "Choir by the Tree",
    category: "Classic",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/f4a2fbea-d09e-4498-8f61-0de3358488e1",
    prompt:
      'Edit the uploaded photo so it matches the "Choir by the Tree" Classic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Small group singing carols beside tall tree; soft haze.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive classic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["classic", "family / group", "landscape", "tree"],
  },
  {
    id: "classic-vintage-postcard",
    title: "Vintage Postcard",
    category: "Classic",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/6aaff2a7-206f-448b-bca2-9e17b8edd984",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Vintage Postcard" template.\n- Focus on creating a polished card layout with: Aged paper texture, postal stamp, classic serif typography.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "classic", "portrait"],
  },
  {
    id: "classic-candlelit-fireplace",
    title: "Candlelit Fireplace",
    category: "Classic",
    subCategory: "Couple / Duo",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/b58e7925-27cb-4964-a874-6eac7ac23f64",
    prompt:
      'Edit the uploaded photo so it matches the "Candlelit Fireplace" Classic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Subtle camera push on fireplace and tree, flickering candles, light falling ash.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive classic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 9,
    tags: [
      "candle",
      "classic",
      "couple / duo",
      "fireplace",
      "landscape",
      "tree",
      "image",
    ],
  },
  {
    id: "cozy-by-the-hearth",
    title: "By the Hearth",
    category: "Cozy",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/619e7fee-e45f-4d2a-9e29-9e1aad59b843",
    prompt:
      'Edit the uploaded photo so it matches the "By the Hearth" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple on rug near crackling fireplace, knit blankets, warm tones.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple", "couple / duo", "cozy", "fireplace", "landscape"],
  },
  {
    id: "cozy-choosing-the-star",
    title: "Choosing the Star",
    category: "Cozy",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/47e9a32b-e629-4601-a72e-d65f32f553b2",
    prompt:
      'Edit the uploaded photo so it matches the "Choosing the Star" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Parents lifting child to place star on tree; joyful candid.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["cozy", "family / group", "portrait", "tree"],
  },
  {
    id: "cozy-knitted-sweater-card",
    title: "Knitted Sweater Card",
    category: "Cozy",
    subCategory: "Card / No people",
    type: "card",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/ea5b32cc-3122-4054-8faa-b13a0098645a",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Knitted Sweater Card" template.\n- Focus on creating a polished card layout with: Knitted texture background with stitched border and text area.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "cozy", "square"],
  },
  {
    id: "cozy-cocoa-and-marshmallows",
    title: "Cocoa & Marshmallows",
    category: "Cozy",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/5a6677d5-82cf-4d97-b35d-c7f2518baad1",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Cocoa & Marshmallows" Cozy template.\n- Replace the environment with: Close-up mugs with marshmallows, cinnamon sticks; cozy steam.\n- Use lighting style: warm practicals.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 6,
    tags: ["cozy", "portrait", "scene / no people"],
  },
  {
    id: "cozy-fuzzy-socks-evening",
    title: "Fuzzy Socks Evening",
    category: "Cozy",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/abceb918-66ec-43f8-b3b6-eff92e9f2e3b",
    prompt:
      'Edit the uploaded photo so it matches the "Fuzzy Socks Evening" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family feet in socks by fire; bokeh lights in background.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple / duo", "cozy", "family", "landscape"],
  },
  {
    id: "cozy-story-time",
    title: "Story Time",
    category: "Cozy",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/b04f04c6-a3f9-41fe-916f-e50fcedd66d7",
    prompt:
      'Edit the uploaded photo so it matches the "Story Time" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Parent reading book to kids by fireplace; gentle rim light.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["cozy", "family / group", "fireplace", "landscape"],
  },
  {
    id: "cozy-cozy-cabin-window",
    title: "Cozy Cabin Window",
    category: "Cozy",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/446d9932-e88e-4077-9928-a862e3199c50",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Cozy Cabin Window" template.\n- Focus on creating a polished card layout with: Frosted window frame with interior glow; text on frosty pane.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "cozy", "portrait", "window"],
  },
  {
    id: "cozy-sweater-weather",
    title: "Sweater Weather",
    category: "Cozy",
    subCategory: "Couple / Duo",
    type: "image",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/bd5977e9-6ff0-4da6-ba7b-5507055213da",
    prompt:
      'Edit the uploaded photo so it matches the "Sweater Weather" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Slow pan across couple under blanket; embers floating.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 8,
    tags: ["couple", "couple / duo", "cozy", "portrait", "image"],
  },
  {
    id: "cozy-hot-cocoa",
    title: "Hot Cocoa",
    category: "Cozy",
    subCategory: "Scene / No people",
    type: "image",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/ff463228-cefe-4194-a1a1-22a8ac762a0e",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Hot Cocoa" Cozy template.\n- Replace the environment with: Micro-loop of steam swirling from mug; subtle snowfall overlay.\n- Use lighting style: warm practicals.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 9,
    tags: ["cozy", "scene / no people", "snow", "square", "image"],
  },
  {
    id: "cozy-pajama-morning",
    title: "Pajama Morning",
    category: "Cozy",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/1baf320a-49f0-400d-9053-769b1cd2cf2a",
    prompt:
      'Edit the uploaded photo so it matches the "Pajama Morning" Cozy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family in matching pajamas opening stockings by mantel.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive cozy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["cozy", "family", "family / group", "landscape"],
  },
  {
    id: "snowy-snowman-builders",
    title: "Snowman Builders",
    category: "Snowy",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/e4ef9707-597c-4ebc-a94c-d6b2381a66fe",
    prompt:
      'Edit the uploaded photo so it matches the "Snowman Builders" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family building snowman; rosy cheeks; visible happy faces.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family", "family / group", "landscape", "snow", "snowy"],
  },
  {
    id: "snowy-sledding-hill",
    title: "Sledding Hill",
    category: "Snowy",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/8af35e81-724b-40d6-88e4-c716c74b0ec9",
    prompt:
      'Edit the uploaded photo so it matches the "Sledding Hill" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Kids on sleds mid-slope; motion blur; sunset sky.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["couple / duo", "landscape", "snowy"],
  },
  {
    id: "snowy-snow-angels",
    title: "Snow Angels",
    category: "Snowy",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/8f5127ef-0d06-420f-8e9c-1a586fa31df6",
    prompt:
      'Edit the uploaded photo so it matches the "Snow Angels" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Top-down of kids making snow angels; aerial framing.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple / duo", "portrait", "snow", "snowy"],
  },
  {
    id: "snowy-night-snow-walk",
    title: "Night Snow Walk",
    category: "Snowy",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/534fc097-174c-41eb-91be-c5aff56c87eb",
    prompt:
      'Edit the uploaded photo so it matches the "Night Snow Walk" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Evening street with falling snow; warm shop windows; candid smiles.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: [
      "couple / duo",
      "landscape",
      "snow",
      "snowy",
      "street",
      "tree",
      "window",
    ],
  },
  {
    id: "snowy-frozen-lake-card",
    title: "Frozen Lake Card",
    category: "Snowy",
    subCategory: "Card / No people",
    type: "card",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/5eb743a3-1926-4a14-8015-a3cd7e64eaa0",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Frozen Lake Card" template.\n- Focus on creating a polished card layout with: Minimal icy gradient, delicate snowflakes, text centered.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "landscape", "minimal", "snow", "snowy"],
  },
  {
    id: "snowy-cabin-arrival",
    title: "Cabin Arrival",
    category: "Snowy",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/dd620481-138d-4e7b-b84e-2ec807597383",
    prompt:
      'Edit the uploaded photo so it matches the "Cabin Arrival" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family with luggage approaching snowy cabin; light breath vapor.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family", "family / group", "landscape", "snow", "snowy"],
  },
  {
    id: "snowy-snowfall-portrait",
    title: "Snowfall Portrait",
    category: "Snowy",
    subCategory: "Single Portrait",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/5b942485-95cf-48b6-b0c0-70c70773ffa8",
    prompt:
      'Edit the uploaded photo so it matches the "Snowfall Portrait" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Single subject with knit beanie; flakes sharp in foreground.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["portrait", "single portrait", "snowy"],
  },
  {
    id: "snowy-snowy-street",
    title: "Snowy Street",
    category: "Snowy",
    subCategory: "Scene / No people",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/90b6bb5a-744d-45db-9284-abfa508444ac",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Snowy Street" Snowy template.\n- Replace the environment with: Looped snowfall over lampposts; light parallax drift.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 36,
    tags: ["landscape", "scene / no people", "snow", "snowy", "image"],
  },
  {
    id: "snowy-derdelus",
    title: "Derdelus",
    category: "Snowy",
    subCategory: "Single Portrait",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/dc5742ae-1e5f-498f-8859-ab1fff16ea95",
    prompt:
      'Edit the uploaded photo so it matches the "Derdelus" Snowy Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: POV sled ride through snowy path; gentle camera sway.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive snowy Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 9,
    tags: ["landscape", "single portrait", "snow", "snowy", "image"],
  },
  {
    id: "snowy-snow-globe-card",
    title: "Snow Globe Card",
    category: "Snowy",
    subCategory: "Card / No people",
    type: "card",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/aeb36c4a-776d-4b3d-96de-d219635c72ba",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Snow Globe Card" template.\n- Focus on creating a polished card layout with: Snow globe frame with insert window and bottom ribbon text.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "snow", "snowy", "square", "window"],
  },
  {
    id: "romantic-mistletoe-kiss",
    title: "Mistletoe Kiss",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/eb12a7f4-e5cf-468d-9b40-a0cf8156c13b",
    prompt:
      'Edit the uploaded photo so it matches the "Mistletoe Kiss" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple kissing under mistletoe; soft backlight and flare.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["couple", "couple / duo", "portrait", "romantic"],
  },
  {
    id: "romantic-baking-together",
    title: "Baking Together",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/18e5f0b6-a5de-4b18-b984-bef33dd269c1",
    prompt:
      'Edit the uploaded photo so it matches the "Baking Together" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple making cookies; flour dust in air; warm kitchen.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: [
      "cookies",
      "couple",
      "couple / duo",
      "kitchen",
      "landscape",
      "romantic",
    ],
  },
  {
    id: "romantic-sleigh-ride-duo",
    title: "Sleigh Ride Duo",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/4178d214-dbea-4f25-84dd-9eed4bd934b3",
    prompt:
      'Edit the uploaded photo so it matches the "Sleigh Ride Duo" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple on horse sleigh; snowy pines; motion blur.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["couple", "couple / duo", "landscape", "romantic", "snow"],
  },
  {
    id: "romantic-atv-under-lights",
    title: "ATV Under Lights",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/6dd96c52-1f69-4335-81a2-03a033df3a80",
    prompt:
      'Edit the uploaded photo so it matches the "ATV Under Lights" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple on ATV with string lights; playful vibe.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["couple", "couple / duo", "landscape", "romantic"],
  },
  {
    id: "romantic-minimal-love-card",
    title: "Minimal Love Card",
    category: "Romantic",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/22d022ea-104f-492e-a55b-bffd291be759",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Minimal Love Card" template.\n- Focus on creating a polished card layout with: Thin heart outline with holly; text column right.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "portrait", "romantic"],
  },
  {
    id: "romantic-city-lights-stroll",
    title: "City Lights Stroll",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/9da4a0ae-61e4-47d3-9fe6-ea2649f66f55",
    prompt:
      'Edit the uploaded photo so it matches the "City Lights Stroll" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Night city, festive lights overhead; shallow DOF.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["couple / duo", "portrait", "romantic"],
  },
  {
    id: "romantic-sparkler-hearts",
    title: "Sparkler Hearts",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/f834c678-eec5-448a-a98c-1447a7151e8a",
    prompt:
      'Edit the uploaded photo so it matches the "Sparkler Hearts" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Long-exposure heart shapes with sparklers; bokeh lights.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple / duo", "landscape", "romantic"],
  },
  {
    id: "romantic-starlit-kiss",
    title: "Starlit Kiss",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "image",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/9d87f208-788f-4baa-950b-af359c0c7482",
    prompt:
      'Edit the uploaded photo so it matches the "Starlit Kiss" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Slow-motion kiss; animated twinkling stars; soft vignette.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 9,
    tags: ["couple / duo", "portrait", "romantic", "image"],
  },
  {
    id: "romantic-winter-proposal",
    title: "Winter Proposal",
    category: "Romantic",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/ecd91923-abfc-429f-b0b9-3b75d61faffa",
    prompt:
      'Edit the uploaded photo so it matches the "Winter Proposal" Romantic Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Proposal moment in snowy park; fairy lights; candid emotion.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive romantic Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 18,
    tags: ["couple / duo", "portrait", "romantic", "snow"],
  },
  {
    id: "religious-nativity-illustration",
    title: "Nativity Illustration",
    category: "Religious",
    subCategory: "Card / No people",
    type: "card",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/6e0ddae2-dd66-4a94-b45f-8fdc01a3aea9",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Nativity Illustration" template.\n- Focus on creating a polished card layout with: Stylized nativity scene; warm glow around manger; scripture panel.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 24,
    tags: ["card", "card / no people", "landscape", "nativity", "religious"],
  },
  {
    id: "religious-guiding-star",
    title: "Guiding Star",
    category: "Religious",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/a1505d63-0f29-4dcb-a8a3-7e153ab7e365",
    prompt:
      "Edit the uploaded photo into a Christmas scene that matches the \"Guiding Star\" Religious template.\n- Replace the environment with: Bright star over Bethlehem silhouette; text below: 'Christ is Born!'\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.",
    creditCost: 12,
    tags: ["portrait", "religious", "scene / no people"],
  },
  {
    id: "religious-shepherds-field",
    title: "Shepherds\u2019 Field",
    category: "Religious",
    subCategory: "Card / No people",
    type: "card",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl:
      "https://giddy-swan-737.convex.cloud/api/storage/29e2bc03-14c3-4fe4-aeac-9bbe6361b89a",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Shepherds\u2019 Field" template.\n- Focus on creating a polished card layout with: Pastoral scene with shepherds; Luke 2:8\u201312 excerpt.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "landscape", "religious"],
  },
  {
    id: "religious-three-magi-journey",
    title: "Three Magi Journey",
    category: "Religious",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Three Magi Journey" Religious template.\n- Replace the environment with: Desert night with three magi and star trail; elegant serif text.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 24,
    tags: ["landscape", "religious", "scene / no people"],
  },
  {
    id: "religious-candle-and-cross-minimal",
    title: "Candle & Cross Minimal",
    category: "Religious",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Candle & Cross Minimal" template.\n- Focus on creating a polished card layout with: Single candle beside subtle cross; ample verse space.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["candle", "card", "card / no people", "portrait", "religious"],
  },
  {
    id: "religious-church-choir",
    title: "Church Choir",
    category: "Religious",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Church Choir" Religious Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family/duo in church aisle; stained glass glow; reverent tone.\n- Use lighting style: natural / ambient.\n- Update outfits only to fit a festive religious Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["church", "couple / duo", "family", "landscape", "religious"],
  },
  {
    id: "religious-he-is-born!",
    title: "He Is Born!",
    category: "Religious",
    subCategory: "Scene / No people",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "He Is Born!" Religious template.\n- Replace the environment with: Subtle star rays pulsing over skyline; scripture fade-in/out.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 8,
    tags: ["landscape", "religious", "scene / no people", "image"],
  },
  {
    id: "religious-advent-wreath",
    title: "Advent Wreath",
    category: "Religious",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Advent Wreath" Religious template.\n- Replace the environment with: Four candles on wreath; soft bokeh; caption area.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 12,
    tags: ["candle", "religious", "scene / no people", "square", "wreath"],
  },
  {
    id: "religious-hallelujah-card",
    title: "Hallelujah Card",
    category: "Religious",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      "Edit the uploaded image into a clean Christmas greeting card that matches the \"Hallelujah Card\" template.\n- Focus on creating a polished card layout with: Clean white with gold 'Hallelujah'; subtitle for verse.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.",
    creditCost: 6,
    tags: ["card", "card / no people", "portrait", "religious"],
  },
  {
    id: "religious-manger-night",
    title: "Manger Night",
    category: "Religious",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Manger Night" Religious template.\n- Replace the environment with: Rustic stable doorway, warm light within; silent night feel.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 24,
    tags: ["landscape", "religious", "scene / no people", "table"],
  },
  {
    id: "minimalist-single-candle",
    title: "Single Candle",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Single Candle" template.\n- Focus on creating a polished card layout with: Matte background, single candle, sans-serif message.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["candle", "card", "card / no people", "minimalist", "portrait"],
  },
  {
    id: "minimalist-modern-hearth-lineart",
    title: "Modern Hearth Lineart",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Modern Hearth Lineart" template.\n- Focus on creating a polished card layout with: Line-art fireplace icon; small text block right.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "fireplace", "landscape", "minimalist"],
  },
  {
    id: "minimalist-two-tone-noel",
    title: "Two-Tone Noel",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Two-Tone Noel" template.\n- Focus on creating a polished card layout with: Two-tone block with NO\u00cbL; small editable caption.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "minimalist", "square", "table"],
  },
  {
    id: "minimalist-negative-space-tree",
    title: "Negative Space Tree",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Negative Space Tree" template.\n- Focus on creating a polished card layout with: Tree formed by negative space stars; restrained palette.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "minimalist", "portrait", "tree"],
  },
  {
    id: "minimalist-geometric-ornaments",
    title: "Geometric Ornaments",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Geometric Ornaments" template.\n- Focus on creating a polished card layout with: Flat geometric baubles; text ribbon area.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "landscape", "minimalist"],
  },
  {
    id: "minimalist-minimal-mantel",
    title: "Minimal Mantel",
    category: "Minimalist",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Minimal Mantel" Minimalist template.\n- Replace the environment with: Modern mantel, single garland; clean text plate.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 12,
    tags: ["landscape", "minimalist", "scene / no people"],
  },
  {
    id: "minimalist-candle-trio",
    title: "Candle Trio",
    category: "Minimalist",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Candle Trio" Minimalist template.\n- Replace the environment with: Three pillar candles; soft gradient; vertical caption.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 6,
    tags: ["candle", "minimalist", "portrait", "scene / no people"],
  },
  {
    id: "minimalist-monochrome-snow",
    title: "Monochrome Snow",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Monochrome Snow" template.\n- Focus on creating a polished card layout with: Monochrome snow dots; centered greeting.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "minimalist", "snow", "square"],
  },
  {
    id: "minimalist-elegant-serif-card",
    title: "Elegant Serif Card",
    category: "Minimalist",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Elegant Serif Card" template.\n- Focus on creating a polished card layout with: Large serif greeting; small family name line.\n- Use lighting style: natural / ambient.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 12,
    tags: ["card", "card / no people", "family", "minimalist", "portrait"],
  },
  {
    id: "minimalist-line-tree",
    title: "Line Tree",
    category: "Minimalist",
    subCategory: "Scene / No people",
    type: "image",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Line Tree" Minimalist template.\n- Replace the environment with: Animated line drawing of tree appearing stroke-by-stroke.\n- Use lighting style: natural / ambient.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 18,
    tags: ["minimalist", "scene / no people", "square", "tree", "image"],
  },
  {
    id: "homey-family-on-sofa",
    title: "Family on Sofa",
    category: "Homey",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Family on Sofa" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family on couch, tree behind; space for caption.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family", "family / group", "homey", "landscape", "tree"],
  },
  {
    id: "homey-milk-and-cookies",
    title: "Milk & Cookies",
    category: "Homey",
    subCategory: "Single Portrait",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Milk & Cookies" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Cookies & milk on coffee table; tree bokeh; note card area.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["cookies", "homey", "portrait", "single portrait", "table", "tree"],
  },
  {
    id: "homey-outdoor-lights-house",
    title: "Outdoor Lights House",
    category: "Homey",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Outdoor Lights House" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family in front of decorated house; warm exterior lights.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family", "family / group", "homey", "landscape"],
  },
  {
    id: "homey-board-games-night",
    title: "Board Games Night",
    category: "Homey",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Board Games Night" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Game night vibes; candid smiles; cozy lamps.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["family / group", "homey", "landscape"],
  },
  {
    id: "homey-stockings-by-mantel",
    title: "Stockings by Mantel",
    category: "Homey",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Stockings by Mantel" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family hanging stockings; soft fireplace glow.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple / duo", "family", "fireplace", "homey", "portrait"],
  },
  {
    id: "homey-wrapping-station",
    title: "Wrapping Station",
    category: "Homey",
    subCategory: "Scene / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a Christmas scene that matches the "Wrapping Station" Homey template.\n- Replace the environment with: Top-down wrapping scene; ribbon, tags; caption strip.\n- Use lighting style: warm practicals.\n- You may overwrite most of the original background, but keep the general framing and orientation.\n- Avoid adding recognizable new people or faces.\n- If additional user preferences are provided, apply them to atmosphere, weather, colors and small decorative elements only.',
    creditCost: 6,
    tags: ["homey", "landscape", "scene / no people"],
  },
  {
    id: "homey-puppy-with-bow",
    title: "Puppy with Bow",
    category: "Homey",
    subCategory: "Single Portrait",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Puppy with Bow" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Pet with big bow; festive background; name tag area.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 6,
    tags: ["homey", "portrait", "single portrait"],
  },
  {
    id: "homey-couch-cheers",
    title: "Couch Cheers",
    category: "Homey",
    subCategory: "Family / Group",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Couch Cheers" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family clinking cocoa mugs; subtle camera sway.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 8,
    tags: ["family", "family / group", "homey", "landscape", "image"],
  },
  {
    id: "homey-decorating-porch",
    title: "Decorating Porch",
    category: "Homey",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Decorating Porch" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Stringing lights on porch; twilight; candid joy.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family / group", "homey", "landscape"],
  },
  {
    id: "homey-bedtime-story",
    title: "Bedtime Story",
    category: "Homey",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Bedtime Story" Homey Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Parents reading in bed with kids; lamp glow; quiet mood.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive homey Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family / group", "homey", "landscape"],
  },
  {
    id: "foodie-feast-spread",
    title: "Feast Spread",
    category: "Foodie",
    subCategory: "Food / No people",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a festive food-focused Christmas scene matching the "Feast Spread" template.\n- Emphasize: Overhead feast table; abundant dishes; caption ribbon.\n- Use lighting style: warm practicals.\n- If there are people in the original image, crop or blur them so the focus stays on the food and table styling.\n- Preserve the general framing, but restyle the contents to look like high-end Christmas food photography.\n- If additional user preferences are provided, apply them to plating, table props, and colors without introducing visible new characters.',
    creditCost: 24,
    tags: ["food / no people", "foodie", "landscape", "table"],
  },
  {
    id: "foodie-cookie-workshop",
    title: "Cookie Workshop",
    category: "Foodie",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Cookie Workshop" Foodie Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Kids cutting cookies; flour dust; close smiles.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive foodie Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["cookies", "family / group", "foodie", "landscape"],
  },
  {
    id: "foodie-cheers-with-mulled-wine",
    title: "Cheers with Mulled Wine",
    category: "Foodie",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Cheers with Mulled Wine" Foodie Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Couple/guests toasting mulled wine; bokeh lights.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive foodie Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple", "couple / duo", "foodie", "portrait"],
  },
  {
    id: "foodie-gingerbread-house",
    title: "Gingerbread House",
    category: "Foodie",
    subCategory: "Couple / Duo",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Gingerbread House" Foodie Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family decorating gingerbread house; colorful candies.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive foodie Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 12,
    tags: ["couple / duo", "family", "foodie", "portrait"],
  },
  {
    id: "foodie-santas-treats",
    title: "Santa\u2019s Treats",
    category: "Foodie",
    subCategory: "Food / No people",
    type: "photo",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a festive food-focused Christmas scene matching the "Santa\u2019s Treats" template.\n- Emphasize: Plate of cookies and milk by tree; note to Santa area.\n- Use lighting style: warm practicals.\n- If there are people in the original image, crop or blur them so the focus stays on the food and table styling.\n- Preserve the general framing, but restyle the contents to look like high-end Christmas food photography.\n- If additional user preferences are provided, apply them to plating, table props, and colors without introducing visible new characters.',
    creditCost: 6,
    tags: ["cookies", "food / no people", "foodie", "portrait", "tree"],
  },
  {
    id: "foodie-recipe-card",
    title: "Recipe Card",
    category: "Foodie",
    subCategory: "Card / No people",
    type: "card",
    orientation: "portrait",
    aspectRatio: "4:5",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded image into a clean Christmas greeting card that matches the "Recipe Card" template.\n- Focus on creating a polished card layout with: Recipe layout with ingredients panel and photo slot.\n- Use lighting style: warm practicals.\n- Remove or strongly de-emphasize any recognizable faces or people from the original image so the design feels like a standalone card.\n- Leave clear space where greeting text can be placed.\n- Keep the overall orientation of the original photo.\n- If additional user preferences are provided, apply them to color palette, decorative details or text mood, but do not add complex new scenes or characters.',
    creditCost: 6,
    tags: ["card", "card / no people", "foodie", "portrait"],
  },
  {
    id: "foodie-kitchen-warmth",
    title: "Kitchen Warmth",
    category: "Foodie",
    subCategory: "Family / Group",
    type: "photo",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Kitchen Warmth" Foodie Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Family cooking together; copper pans; steamy ambiance.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive foodie Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 24,
    tags: ["family", "family / group", "foodie", "landscape"],
  },
  {
    id: "foodie-cinematic-roast",
    title: "Cinematic Roast",
    category: "Foodie",
    subCategory: "Food / No people",
    type: "image",
    orientation: "landscape",
    aspectRatio: "16:9",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a festive food-focused Christmas scene matching the "Cinematic Roast" template.\n- Emphasize: Slow b-roll of roast from oven; steam and light flares.\n- Use lighting style: warm practicals.\n- If there are people in the original image, crop or blur them so the focus stays on the food and table styling.\n- Preserve the general framing, but restyle the contents to look like high-end Christmas food photography.\n- If additional user preferences are provided, apply them to plating, table props, and colors without introducing visible new characters.',
    creditCost: 8,
    tags: ["food / no people", "foodie", "landscape", "image"],
  },
  {
    id: "foodie-cookie-stop",
    title: "Cookie Stop",
    category: "Foodie",
    subCategory: "Couple / Duo",
    type: "image",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo so it matches the "Cookie Stop" Foodie Christmas template.\n- Keep the same person or people from the original image. Preserve their faces, identity, body shape, approximate age and pose.\n- Do not change the number of people or their relative positions in the frame.\n- Replace the background with: Stop-motion cookie assembly; playful captions.\n- Use lighting style: warm practicals.\n- Update outfits only to fit a festive foodie Christmas look (sweaters, coats, dresses, etc.) while keeping overall realism.\n- Maintain the original camera angle and composition as much as possible.\n- If additional user preferences are provided, treat them as secondary styling notes (colors, small props, mood) and only apply them when they do not conflict with the template layout or with preserving the subject(s).',
    creditCost: 9,
    tags: ["couple / duo", "foodie", "square", "image"],
  },
  {
    id: "foodie-cupcake-close-up",
    title: "Cupcake Close-up",
    category: "Foodie",
    subCategory: "Food / No people",
    type: "photo",
    orientation: "square",
    aspectRatio: "1:1",
    previewUrl: "https://giddy-swan-737.convex.cloud/api/storage/",
    prompt:
      'Edit the uploaded photo into a festive food-focused Christmas scene matching the "Cupcake Close-up" template.\n- Emphasize: Macro frosted cupcake with sprinkles; text band.\n- Use lighting style: warm practicals.\n- If there are people in the original image, crop or blur them so the focus stays on the food and table styling.\n- Preserve the general framing, but restyle the contents to look like high-end Christmas food photography.\n- If additional user preferences are provided, apply them to plating, table props, and colors without introducing visible new characters.',
    creditCost: 6,
    tags: ["food / no people", "foodie", "square"],
  },
];
