/**
 * Localization-ready copy for `/christmas/family`.
 * Warm, emotional, Christmas-first — AI is secondary.
 * Wave 1 UI packs: en, ro, de, fr, es, it, pt (European Portuguese), nl, pl.
 */

export const FAMILY_LOCALES = ["en", "ro", "de", "fr", "es", "it", "pt", "nl", "pl"] as const;
export type FamilyLocale = (typeof FAMILY_LOCALES)[number];
export const FAMILY_DEFAULT_LOCALE: FamilyLocale = "en";

export const FAMILY_LOCALE_DIR: Record<string, "ltr" | "rtl"> = {
  en: "ltr",
  ro: "ltr",
  de: "ltr",
  fr: "ltr",
  es: "ltr",
  it: "ltr",
  pt: "ltr",
  nl: "ltr",
  pl: "ltr",
  ar: "rtl",
  he: "rtl",
  fa: "rtl",
  ur: "rtl",
};

type CopyBag = Record<string, string>;

const EN: CopyBag = {
  "seo.title": "Family Christmas Photo Generator | Christmas Family Portraits",
  "seo.description": "Create a personalized family Christmas portrait from your favorite family photo. Choose a festive Christmas scene and turn your photo into a holiday memory.",
  "seo.h1": "Turn Your Family Photo Into a Magical Christmas Portrait",
  "seo.ogAlt": "Family Christmas portrait transformation in a cozy living room",
  "hero.kicker": "THE DIGITAL GIFTER · CHRISTMAS",
  "hero.h1": "Turn Your Family Photo Into a Magical Christmas Portrait",
  "hero.lede": "Upload a family photo, choose a Christmas style, and create a beautiful portrait made for the people you love most.",
  "hero.cta": "Upload your photo",
  "hero.privacy": "Family photos stay private by default.",
  "hero.hint": "JPEG, PNG or WebP · up to 15 MB",
  "hero.beforeLabel": "Before",
  "hero.afterLabel": "After",
  "hero.sliderAria": "Compare the everyday family photo with the Christmas portrait",
  "hero.stylesAria": "Choose a Christmas style example",
  "trust.privateTitle": "Private by default",
  "trust.privateBody": "Your family photo is not displayed publicly.",
  "trust.memoriesTitle": "Made for real memories",
  "trust.memoriesBody": "Create something worth keeping.",
  "trust.stylesTitle": "Beautiful Christmas styles",
  "trust.stylesBody": "Choose the atmosphere that feels like your family.",
  "moment.kicker": "Family Christmas",
  "moment.h2": "Create a Family Christmas Portrait",
  "moment.title": "Create the family Christmas photo you wish you’d taken.",
  "moment.lede": "Upload a group photo, pick a Christmas atmosphere, and create a portrait that aims to keep everyone in the frame. No studio booking. No matching schedules — just upload a photo and create the moment.",
  "moment.cta": "Create Our Christmas Portrait",
  "examples.h2": "Family Christmas Photo Examples",
  "examples.lede": "Warm, realistic Christmas portraits for every kind of family — from three to five-plus, babies, grandparents, and the pets who belong in the picture.",
  "examples.demoNote": "Demo examples for inspiration — not customer photos.",
  "examples.family3": "Family of 3",
  "examples.family4": "Family of 4",
  "examples.family5": "Family of 5+",
  "examples.baby": "Parents + baby",
  "examples.grandparents": "Grandparents + family",
  "examples.dog": "Family + dog",
  "examples.cat": "Family + cat",
  "examples.before": "Everyday photo",
  "examples.after": "Christmas portrait",
  "styles.h2": "Christmas Styles for Families",
  "styles.lede": "Pick the Christmas world that feels like home.",
  "styles.cozy": "Cozy Fireplace",
  "styles.cozyDesc": "Warm living room, tree, and firelight.",
  "styles.snowy": "Snowy Christmas",
  "styles.snowyDesc": "Soft snow and cool winter light.",
  "styles.classic": "Classic Christmas",
  "styles.classicDesc": "Red, green, and traditional warmth.",
  "styles.elegant": "Elegant Christmas",
  "styles.elegantDesc": "Luxury interiors with gold details.",
  "styles.morning": "Christmas Morning",
  "styles.morningDesc": "Pajamas, gifts, soft morning light.",
  "styles.cabin": "Winter Cabin",
  "styles.cabinDesc": "Wood cabin and snowy windows.",
  "styles.wonderland": "Winter Wonderland",
  "styles.wonderlandDesc": "Cinematic snowy landscape.",
  "best.h2": "What Family Photos Work Best?",
  "best.body": "Use a clear group photo where faces are visible, lighting is decent, and everyone you want in the portrait is recognizable. Avoid extreme blur, heavy crop-outs, or photos where key people are hidden.",
  "how.h2": "How It Works",
  "how.1.title": "Upload your family photo",
  "how.1.body": "Choose a clear picture with everyone you want in the portrait.",
  "how.2.title": "Choose your Christmas world",
  "how.2.body": "Pick the scene you love — fireplace, snow, morning, or classic.",
  "how.3.title": "Create your portrait",
  "how.3.body": "Turn your family into a Christmas memory worth keeping.",
  "geo.h2": "What is a family Christmas photo generator?",
  "geo.body": "A family Christmas photo generator turns one uploaded family photo into a festive group Christmas portrait. On TheDigitalGifter, you upload a clear photo of your family, choose a Christmas style made for multiple people, and create a downloadable portrait — private by default, with an option to continue into a Christmas card.",
  "geo.best": "What photos work best?",
  "geo.bestBody": "Clear group photos where faces are visible work best. Include everyone you want in the finished Christmas family picture.",
  "geo.support": "Who can be in the portrait?",
  "geo.supportBody": "Families of any size, parents with a baby, grandparents, and family-plus-pet photos. Keep everyone clearly visible in the original image.",
  "geo.privacy": "What happens to my family photo?",
  "geo.privacyBody": "Uploads and results stay private by default. There is no public gallery.",
  "faq.h2": "Frequently Asked Questions",
  "faq.1.q": "Can I create a Christmas portrait from one family photo?",
  "faq.1.a": "Yes. Upload one clear family photo, choose a Christmas style, and create your family portrait.",
  "faq.2.q": "Can multiple people be included?",
  "faq.2.a": "Yes. This route is designed for groups. Keep everyone clearly visible in the original photo.",
  "faq.3.q": "Can grandparents be included?",
  "faq.3.a": "Yes. Multi-generation photos — including grandparents and babies — are welcome when faces are visible.",
  "faq.4.q": "Can I include a family pet?",
  "faq.4.a": "Yes when the pet is clearly visible in the family photo. For pet-only portraits, use the Pets, Dogs, or Cats experiences.",
  "faq.5.q": "Which photos work best?",
  "faq.5.a": "Clear photos with visible faces, decent lighting, and everyone you want included. Avoid extreme blur.",
  "faq.6.q": "Can I try multiple Christmas styles?",
  "faq.6.a": "Yes. Choose from the family Christmas styles listed on the page, and you can try another style after creating a portrait.",
  "faq.7.q": "Can I download the finished portrait?",
  "faq.7.a": "Yes. When your portrait is ready, download it from the result screen.",
  "faq.8.q": "Can I use it in a Christmas card?",
  "faq.8.a": "Yes. Portrait handoff into the Christmas Card Maker is supported.",
  "faq.9.q": "Is my family photo private?",
  "faq.9.a": "Yes. Family photos stay private by default. We do not publish a public gallery of your portrait.",
  "upload.kicker": "Start here",
  "upload.h2": "Upload your family photo",
  "upload.lede": "A clear group photo is all you need to begin.",
  "upload.choose": "Upload your photo",
  "upload.drop": "Or drop a photo here",
  "upload.hint": "JPEG, PNG or WebP · up to 15 MB",
  "upload.privacy": "Family photos stay private by default.",
  "style.h2": "Choose your Christmas world",
  "style.lede": "Pick the atmosphere that feels like your family.",
  "style.back": "Back",
  "preview.h2": "Ready to create",
  "preview.lede": "This soft preview is your original photo — the finished Christmas portrait unlocks after checkout.",
  "preview.continue": "Continue",
  "offer.h2": "Unlock your Christmas family portrait",
  "offer.deliverable": "One Christmas family portrait optimized for multiple people.",
  "offer.ready": "Usually ready a few minutes after payment",
  "offer.private": "Private by default · download via your order link",
  "offer.email": "Email for receipt / recovery (optional)",
  "offer.pay": "Continue to payment",
  "offer.disabled": "Checkout is preparing for launch. You can still upload, choose a style, and preview — payment unlocks when pricing goes live.",
  "offer.busy": "Preparing checkout…",
  "checkout.h2": "Secure payment",
  "gen.h2": "Creating your Christmas portrait",
  "gen.step1": "Warming the fireplace…",
  "gen.step2": "Lighting the tree…",
  "gen.step3": "Gathering your family in the scene…",
  "gen.step4": "Your Christmas portrait is almost ready…",
  "gen.note": "You can leave this page — reopen your order link anytime.",
  "result.h2": "Your Christmas family portrait",
  "result.download": "Download",
  "result.share": "Share",
  "result.another": "Create another",
  "result.retryStyle": "Try another style",
  "result.card": "Turn it into a Christmas card",
  "result.tree": "Add it to your Christmas tree",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Christmas",
  "error.unsupported": "We couldn’t use this photo. Try a clearer family image with visible faces.",
  "error.generation": "The Christmas magic didn’t work that time. Let’s try again.",
  "error.network": "Connection hiccup. Your selection is saved — please try again.",
  "error.generic": "Something went wrong. Please try again.",
  "error.paidKeepLink": "If you already paid, keep your order link — support can retry fulfillment without charging again.",
  "nav.hub": "Christmas hub",
  "nav.photo": "Photo generator",
  "nav.couples": "Couples",
  "nav.pets": "Pets",
  "nav.cards": "Christmas cards",
  "nav.tree": "Christmas tree",
  "busy.uploading": "Uploading your photo…",
  "busy.working": "Working…",
  "cross.couples": "Couples Christmas",
  "cross.classic": "Classic portrait",
  "cross.pets": "Pet Christmas",
};

const RO: CopyBag = {
  "seo.title": "Generator foto de Crăciun pentru familie | Portrete de familie de Crăciun",
  "seo.description": "Creează un portret personalizat de Crăciun din fotografia de familie preferată. Alege o scenă festivă și transformă fotografia într-o amintire de sărbători.",
  "seo.h1": "Transformă fotografia de familie într-un portret magic de Crăciun",
  "seo.ogAlt": "Transformare portret de familie de Crăciun într-un living cozy",
  "hero.kicker": "THE DIGITAL GIFTER · CRĂCIUN",
  "hero.h1": "Transformă fotografia de familie într-un portret magic de Crăciun",
  "hero.lede": "Încarcă o fotografie de familie, alege un stil de Crăciun și creează un portret frumos pentru oamenii pe care îi iubești cel mai mult.",
  "hero.cta": "Încarcă fotografia",
  "hero.privacy": "Fotografiile de familie rămân private implicit.",
  "hero.hint": "JPEG, PNG sau WebP · până la 15 MB",
  "hero.beforeLabel": "Înainte",
  "hero.afterLabel": "După",
  "hero.sliderAria": "Compară fotografia de familie de zi cu zi cu portretul de Crăciun",
  "hero.stylesAria": "Alege un exemplu de stil de Crăciun",
  "trust.privateTitle": "Privat implicit",
  "trust.privateBody": "Fotografia voastră de familie nu este afișată public.",
  "trust.memoriesTitle": "Făcut pentru amintiri reale",
  "trust.memoriesBody": "Creează ceva demn de păstrat.",
  "trust.stylesTitle": "Stiluri frumoase de Crăciun",
  "trust.stylesBody": "Alege atmosfera care se potrivește familiei tale.",
  "moment.kicker": "Crăciun în familie",
  "moment.h2": "Creează un portret de familie de Crăciun",
  "moment.title": "Creează fotografia de familie de Crăciun pe care ți-ai fi dorit să o faci.",
  "moment.lede": "Încarcă o fotografie de grup, alege o atmosferă de Crăciun și creează un portret care urmărește să păstreze pe toată lumea în cadru. Fără studio. Fără programări — doar încarcă o fotografie și creează momentul.",
  "moment.cta": "Creează portretul nostru de Crăciun",
  "examples.h2": "Exemple de fotografii de familie de Crăciun",
  "examples.lede": "Portrete calde și realiste de Crăciun pentru orice fel de familie — de la trei la cinci și mai mult, bebeluși, bunici și animalele care fac parte din poză.",
  "examples.demoNote": "Exemple demonstrative pentru inspirație — nu fotografii de clienți.",
  "examples.family3": "Familie de 3",
  "examples.family4": "Familie de 4",
  "examples.family5": "Familie de 5+",
  "examples.baby": "Părinți + bebeluș",
  "examples.grandparents": "Bunici + familie",
  "examples.dog": "Familie + câine",
  "examples.cat": "Familie + pisică",
  "examples.before": "Fotografie de zi cu zi",
  "examples.after": "Portret de Crăciun",
  "styles.h2": "Stiluri de Crăciun pentru familii",
  "styles.lede": "Alege lumea de Crăciun care se simte ca acasă.",
  "styles.cozy": "Șemineu cozy",
  "styles.cozyDesc": "Living cald, brad și lumina focului.",
  "styles.snowy": "Crăciun înzăpezit",
  "styles.snowyDesc": "Zăpadă moale și lumină rece de iarnă.",
  "styles.classic": "Crăciun clasic",
  "styles.classicDesc": "Roșu, verde și căldură tradițională.",
  "styles.elegant": "Crăciun elegant",
  "styles.elegantDesc": "Interioare de lux cu detalii aurii.",
  "styles.morning": "Dimineața de Crăciun",
  "styles.morningDesc": "Pijamale, cadouri, lumină blândă de dimineață.",
  "styles.cabin": "Cabană de iarnă",
  "styles.cabinDesc": "Cabană din lemn și ferestre înzăpezite.",
  "styles.wonderland": "Țara minunilor de iarnă",
  "styles.wonderlandDesc": "Peisaj înzăpezit cinematografic.",
  "best.h2": "Ce fotografii de familie funcționează cel mai bine?",
  "best.body": "Folosește o fotografie clară de grup în care fețele sunt vizibile, lumina e decentă și toți cei pe care îi vrei în portret sunt recognoscibili. Evită blurul extrem, decupajele severe sau fotografiile în care persoane-cheie sunt ascunse.",
  "how.h2": "Cum funcționează",
  "how.1.title": "Încarcă fotografia de familie",
  "how.1.body": "Alege o imagine clară cu toți cei pe care îi vrei în portret.",
  "how.2.title": "Alege lumea ta de Crăciun",
  "how.2.body": "Alege scena pe care o iubești — șemineu, zăpadă, dimineață sau clasic.",
  "how.3.title": "Creează portretul",
  "how.3.body": "Transformă familia într-o amintire de Crăciun demnă de păstrat.",
  "geo.h2": "Ce este un generator de fotografii de familie de Crăciun?",
  "geo.body": "Un generator de fotografii de familie de Crăciun transformă o fotografie de familie încărcată într-un portret festiv de grup. Pe TheDigitalGifter încarci o fotografie clară a familiei, alegi un stil de Crăciun gândit pentru mai multe persoane și creezi un portret descărcabil — privat implicit, cu opțiunea de a continua într-un card de Crăciun.",
  "geo.best": "Ce fotografii funcționează cel mai bine?",
  "geo.bestBody": "Fotografiile clare de grup cu fețe vizibile funcționează cel mai bine. Include pe toți cei pe care îi vrei în fotografia finală de familie de Crăciun.",
  "geo.support": "Cine poate fi în portret?",
  "geo.supportBody": "Familii de orice mărime, părinți cu bebeluș, bunici și fotografii familie-plus-animal. Păstrează pe toată lumea clar vizibilă în imaginea originală.",
  "geo.privacy": "Ce se întâmplă cu fotografia mea de familie?",
  "geo.privacyBody": "Încărcările și rezultatele rămân private implicit. Nu există galerie publică.",
  "faq.h2": "Întrebări frecvente",
  "faq.1.q": "Pot crea un portret de Crăciun dintr-o singură fotografie de familie?",
  "faq.1.a": "Da. Încarcă o fotografie clară de familie, alege un stil de Crăciun și creează portretul familiei.",
  "faq.2.q": "Pot fi incluse mai multe persoane?",
  "faq.2.a": "Da. Această rută este gândită pentru grupuri. Păstrează pe toată lumea clar vizibilă în fotografia originală.",
  "faq.3.q": "Pot fi incluși bunicii?",
  "faq.3.a": "Da. Fotografiile pe mai multe generații — inclusiv bunici și bebeluși — sunt binevenite când fețele sunt vizibile.",
  "faq.4.q": "Pot include animalul familiei?",
  "faq.4.a": "Da, când animalul e clar vizibil în fotografia de familie. Pentru portrete doar cu animale, folosește experiențele Animale, Câini sau Pisici.",
  "faq.5.q": "Ce fotografii funcționează cel mai bine?",
  "faq.5.a": "Fotografii clare cu fețe vizibile, lumină decentă și toți cei pe care îi vrei incluși. Evită blurul extrem.",
  "faq.6.q": "Pot încerca mai multe stiluri de Crăciun?",
  "faq.6.a": "Da. Alege dintre stilurile de familie de Crăciun de pe pagină și poți încerca alt stil după ce creezi un portret.",
  "faq.7.q": "Pot descărca portretul final?",
  "faq.7.a": "Da. Când portretul e gata, descarcă-l din ecranul de rezultat.",
  "faq.8.q": "Îl pot folosi într-un card de Crăciun?",
  "faq.8.a": "Da. Transferul portretului în Creatorul de carduri de Crăciun este suportat.",
  "faq.9.q": "Fotografia mea de familie este privată?",
  "faq.9.a": "Da. Fotografiile de familie rămân private implicit. Nu publicăm o galerie publică a portretului tău.",
  "upload.kicker": "Începe aici",
  "upload.h2": "Încarcă fotografia de familie",
  "upload.lede": "O fotografie clară de grup este tot ce ai nevoie ca să începi.",
  "upload.choose": "Încarcă fotografia",
  "upload.drop": "Sau plasează o fotografie aici",
  "upload.hint": "JPEG, PNG sau WebP · până la 15 MB",
  "upload.privacy": "Fotografiile de familie rămân private implicit.",
  "style.h2": "Alege lumea ta de Crăciun",
  "style.lede": "Alege atmosfera care se potrivește familiei tale.",
  "style.back": "Înapoi",
  "preview.h2": "Gata de creat",
  "preview.lede": "Această previzualizare blândă este fotografia originală — portretul final de Crăciun se deblochează după plată.",
  "preview.continue": "Continuă",
  "offer.h2": "Deblochează portretul de familie de Crăciun",
  "offer.deliverable": "Un portret de familie de Crăciun optimizat pentru mai multe persoane.",
  "offer.ready": "De obicei gata în câteva minute după plată",
  "offer.private": "Privat implicit · descarcă din linkul comenzii",
  "offer.email": "Email pentru chitanță / recuperare (opțional)",
  "offer.pay": "Continuă la plată",
  "offer.disabled": "Plata se pregătește pentru lansare. Poți încărca, alege un stil și previzualiza — plata se activează când prețurile sunt live.",
  "offer.busy": "Pregătim plata…",
  "checkout.h2": "Plată securizată",
  "gen.h2": "Cream portretul tău de Crăciun",
  "gen.step1": "Încălzim șemineul…",
  "gen.step2": "Aprindem bradul…",
  "gen.step3": "Adunăm familia în scenă…",
  "gen.step4": "Portretul tău de Crăciun e aproape gata…",
  "gen.note": "Poți părăsi pagina — redeschide oricând linkul comenzii.",
  "result.h2": "Portretul vostru de familie de Crăciun",
  "result.download": "Descarcă",
  "result.share": "Distribuie",
  "result.another": "Creează altul",
  "result.retryStyle": "Încearcă alt stil",
  "result.card": "Transformă-l într-un card de Crăciun",
  "result.tree": "Adaugă-l pe bradul de Crăciun",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Crăciun",
  "error.unsupported": "Nu am putut folosi această fotografie. Încearcă o imagine de familie mai clară, cu fețe vizibile.",
  "error.generation": "Magia de Crăciun nu a funcționat de data asta. Hai să încercăm din nou.",
  "error.network": "O mică problemă de conexiune. Selecția e salvată — te rugăm să încerci din nou.",
  "error.generic": "Ceva nu a mers. Te rugăm să încerci din nou.",
  "error.paidKeepLink": "Dacă ai plătit deja, păstrează linkul comenzii — suportul poate reîncerca fără o nouă taxare.",
  "nav.hub": "Hub de Crăciun",
  "nav.photo": "Generator foto",
  "nav.couples": "Cupluri",
  "nav.pets": "Animale",
  "nav.cards": "Carduri de Crăciun",
  "nav.tree": "Brad de Crăciun",
  "busy.uploading": "Încărcăm fotografia…",
  "busy.working": "Se lucrează…",
  "cross.couples": "Cupluri de Crăciun",
  "cross.classic": "Portret clasic",
  "cross.pets": "Animale de Crăciun",
};

const DE: CopyBag = {
  "seo.title": "Familien-Weihnachtsfoto-Generator | Weihnachtsfamilienporträts",
  "seo.description": "Erstelle ein persönliches Familien-Weihnachtsporträt aus eurem Lieblingsfamilienfoto. Wähle eine festliche Weihnachtsszene und verwandle das Foto in eine Feiertagserinnerung.",
  "seo.h1": "Verwandle euer Familienfoto in ein magisches Weihnachtsporträt",
  "seo.ogAlt": "Familien-Weihnachtsporträt-Verwandlung in einem gemütlichen Wohnzimmer",
  "hero.kicker": "THE DIGITAL GIFTER · WEIHNACHTEN",
  "hero.h1": "Verwandle euer Familienfoto in ein magisches Weihnachtsporträt",
  "hero.lede": "Lade ein Familienfoto hoch, wähle einen Weihnachtsstil und erstelle ein schönes Porträt für die Menschen, die du am meisten liebst.",
  "hero.cta": "Foto hochladen",
  "hero.privacy": "Familienfotos bleiben standardmäßig privat.",
  "hero.hint": "JPEG, PNG oder WebP · bis 15 MB",
  "hero.beforeLabel": "Vorher",
  "hero.afterLabel": "Nachher",
  "hero.sliderAria": "Alltagsfamilienfoto mit dem Weihnachtsporträt vergleichen",
  "hero.stylesAria": "Weihnachtsstil-Beispiel wählen",
  "trust.privateTitle": "Standardmäßig privat",
  "trust.privateBody": "Euer Familienfoto wird nicht öffentlich angezeigt.",
  "trust.memoriesTitle": "Für echte Erinnerungen",
  "trust.memoriesBody": "Erstelle etwas, das man behalten möchte.",
  "trust.stylesTitle": "Schöne Weihnachtsstile",
  "trust.stylesBody": "Wähle die Atmosphäre, die sich nach eurer Familie anfühlt.",
  "moment.kicker": "Familienweihnachten",
  "moment.h2": "Erstelle ein Familien-Weihnachtsporträt",
  "moment.title": "Erstelle das Familien-Weihnachtsfoto, das ihr euch gewünscht hättet.",
  "moment.lede": "Lade ein Gruppenfoto hoch, wähle eine Weihnachtsatmosphäre und erstelle ein Porträt, das alle im Bild halten soll. Kein Studio. Keine Terminabstimmung — einfach Foto hochladen und den Moment schaffen.",
  "moment.cta": "Unser Weihnachtsporträt erstellen",
  "examples.h2": "Beispiele für Familien-Weihnachtsfotos",
  "examples.lede": "Warme, realistische Weihnachtsporträts für jede Familie — von drei bis fünf und mehr, Babys, Großeltern und die Haustiere, die dazu gehören.",
  "examples.demoNote": "Demo-Beispiele zur Inspiration — keine Kundenfotos.",
  "examples.family3": "Familie mit 3",
  "examples.family4": "Familie mit 4",
  "examples.family5": "Familie mit 5+",
  "examples.baby": "Eltern + Baby",
  "examples.grandparents": "Großeltern + Familie",
  "examples.dog": "Familie + Hund",
  "examples.cat": "Familie + Katze",
  "examples.before": "Alltagsfoto",
  "examples.after": "Weihnachtsporträt",
  "styles.h2": "Weihnachtsstile für Familien",
  "styles.lede": "Wähle die Weihnachtswelt, die sich wie Zuhause anfühlt.",
  "styles.cozy": "Gemütlicher Kamin",
  "styles.cozyDesc": "Warmes Wohnzimmer, Baum und Feuerlicht.",
  "styles.snowy": "Verschneites Weihnachten",
  "styles.snowyDesc": "Weicher Schnee und kühles Winterlicht.",
  "styles.classic": "Klassisches Weihnachten",
  "styles.classicDesc": "Rot, Grün und traditionelle Wärme.",
  "styles.elegant": "Elegantes Weihnachten",
  "styles.elegantDesc": "Luxusinterieurs mit Golddetails.",
  "styles.morning": "Weihnachtsmorgen",
  "styles.morningDesc": "Schlafanzüge, Geschenke, sanftes Morgenlicht.",
  "styles.cabin": "Winterhütte",
  "styles.cabinDesc": "Holzhütte und verschneite Fenster.",
  "styles.wonderland": "Winterwunderland",
  "styles.wonderlandDesc": "Filmische Schneelandschaft.",
  "best.h2": "Welche Familienfotos funktionieren am besten?",
  "best.body": "Nutze ein klares Gruppenfoto mit sichtbaren Gesichtern, anständiger Beleuchtung und erkennbaren Personen. Vermeide extreme Unschärfe, starke Ausschnitte oder Fotos, auf denen wichtige Personen verdeckt sind.",
  "how.h2": "So funktioniert’s",
  "how.1.title": "Familienfoto hochladen",
  "how.1.body": "Wähle ein klares Bild mit allen, die im Porträt sein sollen.",
  "how.2.title": "Weihnachtswelt wählen",
  "how.2.body": "Wähle die Szene, die ihr liebt — Kamin, Schnee, Morgen oder klassisch.",
  "how.3.title": "Porträt erstellen",
  "how.3.body": "Verwandelt eure Familie in eine Weihnachtserinnerung zum Bewahren.",
  "geo.h2": "Was ist ein Familien-Weihnachtsfoto-Generator?",
  "geo.body": "Ein Familien-Weihnachtsfoto-Generator verwandelt ein hochgeladenes Familienfoto in ein festliches Gruppen-Weihnachtsporträt. Bei TheDigitalGifter ladet ihr ein klares Familienfoto hoch, wählt einen Weihnachtsstil für mehrere Personen und erstellt ein herunterladbares Porträt — standardmäßig privat, mit Option zur Weihnachtskarte.",
  "geo.best": "Welche Fotos funktionieren am besten?",
  "geo.bestBody": "Klare Gruppenfotos mit sichtbaren Gesichtern funktionieren am besten. Schließt alle ein, die im fertigen Familien-Weihnachtsbild sein sollen.",
  "geo.support": "Wer kann im Porträt sein?",
  "geo.supportBody": "Familien jeder Größe, Eltern mit Baby, Großeltern und Familie-plus-Haustier. Haltet alle im Originalbild klar sichtbar.",
  "geo.privacy": "Was passiert mit meinem Familienfoto?",
  "geo.privacyBody": "Uploads und Ergebnisse bleiben standardmäßig privat. Es gibt keine öffentliche Galerie.",
  "faq.h2": "Häufig gestellte Fragen",
  "faq.1.q": "Kann ich aus einem Familienfoto ein Weihnachtsporträt erstellen?",
  "faq.1.a": "Ja. Lade ein klares Familienfoto hoch, wähle einen Weihnachtsstil und erstelle euer Familienporträt.",
  "faq.2.q": "Können mehrere Personen dabei sein?",
  "faq.2.a": "Ja. Diese Route ist für Gruppen gedacht. Haltet alle im Originalfoto klar sichtbar.",
  "faq.3.q": "Können Großeltern dabei sein?",
  "faq.3.a": "Ja. Mehrgenerationenfotos — inklusive Großeltern und Babys — sind willkommen, wenn Gesichter sichtbar sind.",
  "faq.4.q": "Kann ich ein Familienhaustier einbeziehen?",
  "faq.4.a": "Ja, wenn das Haustier im Familienfoto klar sichtbar ist. Für reine Haustierporträts nutzt die Haustier-, Hunde- oder Katzen-Erlebnisse.",
  "faq.5.q": "Welche Fotos funktionieren am besten?",
  "faq.5.a": "Klare Fotos mit sichtbaren Gesichtern, anständiger Beleuchtung und allen gewünschten Personen. Extreme Unschärfe vermeiden.",
  "faq.6.q": "Kann ich mehrere Weihnachtsstile ausprobieren?",
  "faq.6.a": "Ja. Wählt aus den Familien-Weihnachtsstilen auf der Seite und könnt nach einem Porträt einen anderen Stil versuchen.",
  "faq.7.q": "Kann ich das fertige Porträt herunterladen?",
  "faq.7.a": "Ja. Wenn euer Porträt fertig ist, ladet es vom Ergebnisbildschirm herunter.",
  "faq.8.q": "Kann ich es in einer Weihnachtskarte nutzen?",
  "faq.8.a": "Ja. Die Übergabe des Porträts in den Weihnachtskarten-Maker wird unterstützt.",
  "faq.9.q": "Ist mein Familienfoto privat?",
  "faq.9.a": "Ja. Familienfotos bleiben standardmäßig privat. Wir veröffentlichen keine öffentliche Galerie eures Porträts.",
  "upload.kicker": "Hier starten",
  "upload.h2": "Familienfoto hochladen",
  "upload.lede": "Ein klares Gruppenfoto reicht zum Start.",
  "upload.choose": "Foto hochladen",
  "upload.drop": "Oder Foto hier ablegen",
  "upload.hint": "JPEG, PNG oder WebP · bis 15 MB",
  "upload.privacy": "Familienfotos bleiben standardmäßig privat.",
  "style.h2": "Weihnachtswelt wählen",
  "style.lede": "Wähle die Atmosphäre, die sich nach eurer Familie anfühlt.",
  "style.back": "Zurück",
  "preview.h2": "Bereit zum Erstellen",
  "preview.lede": "Diese weiche Vorschau ist euer Originalfoto — das fertige Weihnachtsporträt wird nach dem Checkout freigeschaltet.",
  "preview.continue": "Weiter",
  "offer.h2": "Familien-Weihnachtsporträt freischalten",
  "offer.deliverable": "Ein Weihnachts-Familienporträt, optimiert für mehrere Personen.",
  "offer.ready": "Meist wenige Minuten nach der Zahlung fertig",
  "offer.private": "Standardmäßig privat · Download über den Bestelllink",
  "offer.email": "E-Mail für Beleg / Wiederherstellung (optional)",
  "offer.pay": "Weiter zur Zahlung",
  "offer.disabled": "Checkout wird für den Launch vorbereitet. Ihr könnt hochladen, Stil wählen und Vorschau sehen — Zahlung startet, wenn die Preise live sind.",
  "offer.busy": "Checkout wird vorbereitet…",
  "checkout.h2": "Sichere Zahlung",
  "gen.h2": "Euer Weihnachtsporträt entsteht",
  "gen.step1": "Kamin wird angewärmt…",
  "gen.step2": "Baum wird beleuchtet…",
  "gen.step3": "Familie wird in die Szene geholt…",
  "gen.step4": "Euer Weihnachtsporträt ist fast fertig…",
  "gen.note": "Ihr könnt die Seite verlassen — Bestelllink jederzeit erneut öffnen.",
  "result.h2": "Euer Familien-Weihnachtsporträt",
  "result.download": "Herunterladen",
  "result.share": "Teilen",
  "result.another": "Neues erstellen",
  "result.retryStyle": "Anderen Stil versuchen",
  "result.card": "In eine Weihnachtskarte verwandeln",
  "result.tree": "Zum Weihnachtsbaum hinzufügen",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Weihnachten",
  "error.unsupported": "Dieses Foto konnten wir nicht verwenden. Probiert ein klareres Familienbild mit sichtbaren Gesichtern.",
  "error.generation": "Die Weihnachtsmagie hat diesmal nicht geklappt. Lasst es uns erneut versuchen.",
  "error.network": "Verbindungsproblem. Eure Auswahl ist gespeichert — bitte erneut versuchen.",
  "error.generic": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
  "error.paidKeepLink": "Falls ihr schon bezahlt habt, behaltet den Bestelllink — Support kann ohne erneute Zahlung erneut versuchen.",
  "nav.hub": "Weihnachts-Hub",
  "nav.photo": "Foto-Generator",
  "nav.couples": "Paare",
  "nav.pets": "Haustiere",
  "nav.cards": "Weihnachtskarten",
  "nav.tree": "Weihnachtsbaum",
  "busy.uploading": "Foto wird hochgeladen…",
  "busy.working": "Wird bearbeitet…",
  "cross.couples": "Paar-Weihnachten",
  "cross.classic": "Klassisches Porträt",
  "cross.pets": "Haustier-Weihnachten",
};

const FR: CopyBag = {
  "seo.title": "Générateur de photos de Noël en famille | Portraits de famille de Noël",
  "seo.description": "Créez un portrait de Noël familial personnalisé à partir de votre photo de famille préférée. Choisissez une scène festive et transformez votre photo en souvenir des fêtes.",
  "seo.h1": "Transformez votre photo de famille en portrait de Noël magique",
  "seo.ogAlt": "Transformation de portrait de famille de Noël dans un salon cosy",
  "hero.kicker": "THE DIGITAL GIFTER · NOËL",
  "hero.h1": "Transformez votre photo de famille en portrait de Noël magique",
  "hero.lede": "Téléversez une photo de famille, choisissez un style de Noël et créez un beau portrait pour les personnes que vous aimez le plus.",
  "hero.cta": "Téléverser votre photo",
  "hero.privacy": "Les photos de famille restent privées par défaut.",
  "hero.hint": "JPEG, PNG ou WebP · jusqu’à 15 Mo",
  "hero.beforeLabel": "Avant",
  "hero.afterLabel": "Après",
  "hero.sliderAria": "Comparer la photo de famille du quotidien avec le portrait de Noël",
  "hero.stylesAria": "Choisir un exemple de style de Noël",
  "trust.privateTitle": "Privé par défaut",
  "trust.privateBody": "Votre photo de famille n’est pas affichée publiquement.",
  "trust.memoriesTitle": "Fait pour de vrais souvenirs",
  "trust.memoriesBody": "Créez quelque chose qui mérite d’être gardé.",
  "trust.stylesTitle": "Beaux styles de Noël",
  "trust.stylesBody": "Choisissez l’ambiance qui ressemble à votre famille.",
  "moment.kicker": "Noël en famille",
  "moment.h2": "Créez un portrait de famille de Noël",
  "moment.title": "Créez la photo de famille de Noël que vous auriez aimé prendre.",
  "moment.lede": "Téléversez une photo de groupe, choisissez une ambiance de Noël et créez un portrait qui vise à garder tout le monde dans le cadre. Pas de studio. Pas d’agendas à synchroniser — téléversez une photo et créez le moment.",
  "moment.cta": "Créer notre portrait de Noël",
  "examples.h2": "Exemples de photos de famille de Noël",
  "examples.lede": "Portraits de Noël chaleureux et réalistes pour chaque famille — de trois à cinq et plus, bébés, grands-parents et les animaux qui font partie de la photo.",
  "examples.demoNote": "Exemples démo pour inspiration — pas des photos de clients.",
  "examples.family3": "Famille de 3",
  "examples.family4": "Famille de 4",
  "examples.family5": "Famille de 5+",
  "examples.baby": "Parents + bébé",
  "examples.grandparents": "Grands-parents + famille",
  "examples.dog": "Famille + chien",
  "examples.cat": "Famille + chat",
  "examples.before": "Photo du quotidien",
  "examples.after": "Portrait de Noël",
  "styles.h2": "Styles de Noël pour les familles",
  "styles.lede": "Choisissez le monde de Noël qui fait comme à la maison.",
  "styles.cozy": "Cheminée cosy",
  "styles.cozyDesc": "Salon chaleureux, sapin et lumière du feu.",
  "styles.snowy": "Noël enneigé",
  "styles.snowyDesc": "Neige douce et lumière d’hiver fraîche.",
  "styles.classic": "Noël classique",
  "styles.classicDesc": "Rouge, vert et chaleur traditionnelle.",
  "styles.elegant": "Noël élégant",
  "styles.elegantDesc": "Intérieurs luxueux avec détails dorés.",
  "styles.morning": "Matin de Noël",
  "styles.morningDesc": "Pyjamas, cadeaux, douce lumière du matin.",
  "styles.cabin": "Chalet d’hiver",
  "styles.cabinDesc": "Chalet en bois et fenêtres enneigées.",
  "styles.wonderland": "Pays des merveilles d’hiver",
  "styles.wonderlandDesc": "Paysage enneigé cinématographique.",
  "best.h2": "Quelles photos de famille fonctionnent le mieux ?",
  "best.body": "Utilisez une photo de groupe nette où les visages sont visibles, l’éclairage est correct et chacun est reconnaissable. Évitez le flou extrême, les recadrages trop serrés ou les photos où des personnes clés sont cachées.",
  "how.h2": "Comment ça marche",
  "how.1.title": "Téléversez votre photo de famille",
  "how.1.body": "Choisissez une image nette avec toutes les personnes à inclure.",
  "how.2.title": "Choisissez votre monde de Noël",
  "how.2.body": "Choisissez la scène que vous aimez — cheminée, neige, matin ou classique.",
  "how.3.title": "Créez votre portrait",
  "how.3.body": "Transformez votre famille en souvenir de Noël à garder.",
  "geo.h2": "Qu’est-ce qu’un générateur de photos de famille de Noël ?",
  "geo.body": "Un générateur de photos de famille de Noël transforme une photo de famille téléversée en portrait de groupe festif. Sur TheDigitalGifter, vous téléversez une photo claire de votre famille, choisissez un style de Noël pensé pour plusieurs personnes et créez un portrait téléchargeable — privé par défaut, avec option de continuer vers une carte de Noël.",
  "geo.best": "Quelles photos fonctionnent le mieux ?",
  "geo.bestBody": "Les photos de groupe nettes avec des visages visibles fonctionnent le mieux. Incluez toutes les personnes souhaitées dans la photo finale.",
  "geo.support": "Qui peut être sur le portrait ?",
  "geo.supportBody": "Familles de toute taille, parents avec bébé, grands-parents et photos famille-plus-animal. Gardez tout le monde clairement visible sur l’image d’origine.",
  "geo.privacy": "Que devient ma photo de famille ?",
  "geo.privacyBody": "Les téléversements et résultats restent privés par défaut. Il n’y a pas de galerie publique.",
  "faq.h2": "Questions fréquentes",
  "faq.1.q": "Puis-je créer un portrait de Noël à partir d’une seule photo de famille ?",
  "faq.1.a": "Oui. Téléversez une photo de famille nette, choisissez un style de Noël et créez votre portrait familial.",
  "faq.2.q": "Plusieurs personnes peuvent-elles être incluses ?",
  "faq.2.a": "Oui. Ce parcours est conçu pour les groupes. Gardez tout le monde clairement visible sur la photo d’origine.",
  "faq.3.q": "Les grands-parents peuvent-ils être inclus ?",
  "faq.3.a": "Oui. Les photos multi-générations — y compris grands-parents et bébés — sont les bienvenues quand les visages sont visibles.",
  "faq.4.q": "Puis-je inclure l’animal de la famille ?",
  "faq.4.a": "Oui lorsque l’animal est clairement visible sur la photo de famille. Pour des portraits uniquement animal, utilisez les expériences Animaux, Chiens ou Chats.",
  "faq.5.q": "Quelles photos fonctionnent le mieux ?",
  "faq.5.a": "Des photos nettes avec des visages visibles, un éclairage correct et toutes les personnes souhaitées. Évitez le flou extrême.",
  "faq.6.q": "Puis-je essayer plusieurs styles de Noël ?",
  "faq.6.a": "Oui. Choisissez parmi les styles famille de Noël listés sur la page, et vous pouvez en essayer un autre après avoir créé un portrait.",
  "faq.7.q": "Puis-je télécharger le portrait terminé ?",
  "faq.7.a": "Oui. Quand votre portrait est prêt, téléchargez-le depuis l’écran de résultat.",
  "faq.8.q": "Puis-je l’utiliser dans une carte de Noël ?",
  "faq.8.a": "Oui. Le transfert du portrait vers le créateur de cartes de Noël est pris en charge.",
  "faq.9.q": "Ma photo de famille est-elle privée ?",
  "faq.9.a": "Oui. Les photos de famille restent privées par défaut. Nous ne publions pas de galerie publique de votre portrait.",
  "upload.kicker": "Commencez ici",
  "upload.h2": "Téléversez votre photo de famille",
  "upload.lede": "Une photo de groupe nette suffit pour commencer.",
  "upload.choose": "Téléverser votre photo",
  "upload.drop": "Ou déposez une photo ici",
  "upload.hint": "JPEG, PNG ou WebP · jusqu’à 15 Mo",
  "upload.privacy": "Les photos de famille restent privées par défaut.",
  "style.h2": "Choisissez votre monde de Noël",
  "style.lede": "Choisissez l’ambiance qui ressemble à votre famille.",
  "style.back": "Retour",
  "preview.h2": "Prêt à créer",
  "preview.lede": "Cet aperçu doux est votre photo originale — le portrait de Noël final se débloque après le paiement.",
  "preview.continue": "Continuer",
  "offer.h2": "Débloquez votre portrait de famille de Noël",
  "offer.deliverable": "Un portrait de famille de Noël optimisé pour plusieurs personnes.",
  "offer.ready": "Généralement prêt quelques minutes après le paiement",
  "offer.private": "Privé par défaut · téléchargement via le lien de commande",
  "offer.email": "E-mail pour reçu / récupération (optionnel)",
  "offer.pay": "Continuer vers le paiement",
  "offer.disabled": "Le paiement se prépare pour le lancement. Vous pouvez téléverser, choisir un style et prévisualiser — le paiement s’active quand les prix sont en ligne.",
  "offer.busy": "Préparation du paiement…",
  "checkout.h2": "Paiement sécurisé",
  "gen.h2": "Création de votre portrait de Noël",
  "gen.step1": "On réchauffe la cheminée…",
  "gen.step2": "On allume le sapin…",
  "gen.step3": "On rassemble la famille dans la scène…",
  "gen.step4": "Votre portrait de Noël est presque prêt…",
  "gen.note": "Vous pouvez quitter cette page — rouvrez le lien de commande à tout moment.",
  "result.h2": "Votre portrait de famille de Noël",
  "result.download": "Télécharger",
  "result.share": "Partager",
  "result.another": "Créer un autre",
  "result.retryStyle": "Essayer un autre style",
  "result.card": "En faire une carte de Noël",
  "result.tree": "L’ajouter à votre sapin de Noël",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Noël",
  "error.unsupported": "Nous n’avons pas pu utiliser cette photo. Essayez une image de famille plus nette avec des visages visibles.",
  "error.generation": "La magie de Noël n’a pas fonctionné cette fois. Réessayons.",
  "error.network": "Petit souci de connexion. Votre sélection est enregistrée — veuillez réessayer.",
  "error.generic": "Une erreur s’est produite. Veuillez réessayer.",
  "error.paidKeepLink": "Si vous avez déjà payé, gardez votre lien de commande — le support peut réessayer sans vous facturer à nouveau.",
  "nav.hub": "Hub de Noël",
  "nav.photo": "Générateur de photos",
  "nav.couples": "Couples",
  "nav.pets": "Animaux",
  "nav.cards": "Cartes de Noël",
  "nav.tree": "Sapin de Noël",
  "busy.uploading": "Téléversement de votre photo…",
  "busy.working": "Traitement…",
  "cross.couples": "Noël en couple",
  "cross.classic": "Portrait classique",
  "cross.pets": "Noël pour animaux",
};

const ES: CopyBag = {
  "seo.title": "Generador de fotos de Navidad en familia | Retratos familiares de Navidad",
  "seo.description": "Crea un retrato familiar de Navidad personalizado a partir de tu foto familiar favorita. Elige una escena festiva y convierte tu foto en un recuerdo navideño.",
  "seo.h1": "Convierte tu foto familiar en un retrato mágico de Navidad",
  "seo.ogAlt": "Transformación de retrato familiar de Navidad en un salón acogedor",
  "hero.kicker": "THE DIGITAL GIFTER · NAVIDAD",
  "hero.h1": "Convierte tu foto familiar en un retrato mágico de Navidad",
  "hero.lede": "Sube una foto familiar, elige un estilo navideño y crea un hermoso retrato para las personas que más quieres.",
  "hero.cta": "Sube tu foto",
  "hero.privacy": "Las fotos familiares se mantienen privadas por defecto.",
  "hero.hint": "JPEG, PNG o WebP · hasta 15 MB",
  "hero.beforeLabel": "Antes",
  "hero.afterLabel": "Después",
  "hero.sliderAria": "Compara la foto familiar cotidiana con el retrato de Navidad",
  "hero.stylesAria": "Elige un ejemplo de estilo navideño",
  "trust.privateTitle": "Privado por defecto",
  "trust.privateBody": "Tu foto familiar no se muestra públicamente.",
  "trust.memoriesTitle": "Hecho para recuerdos reales",
  "trust.memoriesBody": "Crea algo que merezca la pena guardar.",
  "trust.stylesTitle": "Hermosos estilos de Navidad",
  "trust.stylesBody": "Elige la atmósfera que se sienta como tu familia.",
  "moment.kicker": "Navidad en familia",
  "moment.h2": "Crea un retrato familiar de Navidad",
  "moment.title": "Crea la foto familiar de Navidad que te hubiera gustado hacer.",
  "moment.lede": "Sube una foto de grupo, elige una atmósfera navideña y crea un retrato que busca mantener a todos en el encuadre. Sin estudio. Sin coordinar agendas — solo sube una foto y crea el momento.",
  "moment.cta": "Crear nuestro retrato de Navidad",
  "examples.h2": "Ejemplos de fotos familiares de Navidad",
  "examples.lede": "Retratos navideños cálidos y realistas para todo tipo de familia — de tres a cinco o más, bebés, abuelos y las mascotas que forman parte de la foto.",
  "examples.demoNote": "Ejemplos demo de inspiración — no son fotos de clientes.",
  "examples.family3": "Familia de 3",
  "examples.family4": "Familia de 4",
  "examples.family5": "Familia de 5+",
  "examples.baby": "Padres + bebé",
  "examples.grandparents": "Abuelos + familia",
  "examples.dog": "Familia + perro",
  "examples.cat": "Familia + gato",
  "examples.before": "Foto cotidiana",
  "examples.after": "Retrato de Navidad",
  "styles.h2": "Estilos de Navidad para familias",
  "styles.lede": "Elige el mundo navideño que se sienta como en casa.",
  "styles.cozy": "Chimenea acogedora",
  "styles.cozyDesc": "Salón cálido, árbol y luz del fuego.",
  "styles.snowy": "Navidad nevada",
  "styles.snowyDesc": "Nieve suave y luz invernal fresca.",
  "styles.classic": "Navidad clásica",
  "styles.classicDesc": "Rojo, verde y calidez tradicional.",
  "styles.elegant": "Navidad elegante",
  "styles.elegantDesc": "Interiores de lujo con detalles dorados.",
  "styles.morning": "Mañana de Navidad",
  "styles.morningDesc": "Pijamas, regalos, luz suave de mañana.",
  "styles.cabin": "Cabaña de invierno",
  "styles.cabinDesc": "Cabaña de madera y ventanas nevadas.",
  "styles.wonderland": "País de las maravillas invernal",
  "styles.wonderlandDesc": "Paisaje nevado cinematográfico.",
  "best.h2": "¿Qué fotos familiares funcionan mejor?",
  "best.body": "Usa una foto de grupo nítida donde se vean las caras, la luz sea decente y todos sean reconocibles. Evita el desenfoque extremo, recortes fuertes o fotos donde falten personas clave.",
  "how.h2": "Cómo funciona",
  "how.1.title": "Sube tu foto familiar",
  "how.1.body": "Elige una imagen nítida con todos los que quieras en el retrato.",
  "how.2.title": "Elige tu mundo de Navidad",
  "how.2.body": "Elige la escena que te guste — chimenea, nieve, mañana o clásica.",
  "how.3.title": "Crea tu retrato",
  "how.3.body": "Convierte a tu familia en un recuerdo navideño para guardar.",
  "geo.h2": "¿Qué es un generador de fotos familiares de Navidad?",
  "geo.body": "Un generador de fotos familiares de Navidad convierte una foto familiar subida en un retrato grupal festivo. En TheDigitalGifter subes una foto clara de tu familia, eliges un estilo navideño pensado para varias personas y creas un retrato descargable — privado por defecto, con opción de continuar a una tarjeta de Navidad.",
  "geo.best": "¿Qué fotos funcionan mejor?",
  "geo.bestBody": "Las fotos de grupo nítidas con caras visibles funcionan mejor. Incluye a todos los que quieras en la foto familiar final.",
  "geo.support": "¿Quién puede salir en el retrato?",
  "geo.supportBody": "Familias de cualquier tamaño, padres con bebé, abuelos y fotos familia-más-mascota. Mantén a todos claramente visibles en la imagen original.",
  "geo.privacy": "¿Qué ocurre con mi foto familiar?",
  "geo.privacyBody": "Las subidas y resultados se mantienen privados por defecto. No hay galería pública.",
  "faq.h2": "Preguntas frecuentes",
  "faq.1.q": "¿Puedo crear un retrato de Navidad a partir de una sola foto familiar?",
  "faq.1.a": "Sí. Sube una foto familiar nítida, elige un estilo navideño y crea tu retrato familiar.",
  "faq.2.q": "¿Se pueden incluir varias personas?",
  "faq.2.a": "Sí. Esta ruta está pensada para grupos. Mantén a todos claramente visibles en la foto original.",
  "faq.3.q": "¿Se pueden incluir abuelos?",
  "faq.3.a": "Sí. Las fotos multigeneracionales — incluidos abuelos y bebés — son bienvenidas cuando se ven las caras.",
  "faq.4.q": "¿Puedo incluir a la mascota familiar?",
  "faq.4.a": "Sí cuando la mascota se ve claramente en la foto familiar. Para retratos solo de mascota, usa las experiencias Mascotas, Perros o Gatos.",
  "faq.5.q": "¿Qué fotos funcionan mejor?",
  "faq.5.a": "Fotos nítidas con caras visibles, buena luz y todos incluidos. Evita el desenfoque extremo.",
  "faq.6.q": "¿Puedo probar varios estilos de Navidad?",
  "faq.6.a": "Sí. Elige entre los estilos familiares de Navidad de la página y puedes probar otro estilo después de crear un retrato.",
  "faq.7.q": "¿Puedo descargar el retrato terminado?",
  "faq.7.a": "Sí. Cuando tu retrato esté listo, descárgalo desde la pantalla de resultado.",
  "faq.8.q": "¿Puedo usarlo en una tarjeta de Navidad?",
  "faq.8.a": "Sí. Se admite el traspaso del retrato al creador de tarjetas de Navidad.",
  "faq.9.q": "¿Mi foto familiar es privada?",
  "faq.9.a": "Sí. Las fotos familiares se mantienen privadas por defecto. No publicamos una galería pública de tu retrato.",
  "upload.kicker": "Empieza aquí",
  "upload.h2": "Sube tu foto familiar",
  "upload.lede": "Una foto de grupo nítida es todo lo que necesitas para empezar.",
  "upload.choose": "Sube tu foto",
  "upload.drop": "O suelta una foto aquí",
  "upload.hint": "JPEG, PNG o WebP · hasta 15 MB",
  "upload.privacy": "Las fotos familiares se mantienen privadas por defecto.",
  "style.h2": "Elige tu mundo de Navidad",
  "style.lede": "Elige la atmósfera que se sienta como tu familia.",
  "style.back": "Atrás",
  "preview.h2": "Listo para crear",
  "preview.lede": "Esta vista previa suave es tu foto original — el retrato de Navidad final se desbloquea tras el pago.",
  "preview.continue": "Continuar",
  "offer.h2": "Desbloquea tu retrato familiar de Navidad",
  "offer.deliverable": "Un retrato familiar de Navidad optimizado para varias personas.",
  "offer.ready": "Suele estar listo unos minutos después del pago",
  "offer.private": "Privado por defecto · descarga con el enlace del pedido",
  "offer.email": "Email para recibo / recuperación (opcional)",
  "offer.pay": "Continuar al pago",
  "offer.disabled": "El pago se prepara para el lanzamiento. Puedes subir, elegir estilo y previsualizar — el pago se activa cuando los precios estén en vivo.",
  "offer.busy": "Preparando el pago…",
  "checkout.h2": "Pago seguro",
  "gen.h2": "Creando tu retrato de Navidad",
  "gen.step1": "Calentando la chimenea…",
  "gen.step2": "Encendiendo el árbol…",
  "gen.step3": "Reuniendo a la familia en la escena…",
  "gen.step4": "Tu retrato de Navidad casi está listo…",
  "gen.note": "Puedes salir de esta página — reabre el enlace del pedido cuando quieras.",
  "result.h2": "Vuestro retrato familiar de Navidad",
  "result.download": "Descargar",
  "result.share": "Compartir",
  "result.another": "Crear otro",
  "result.retryStyle": "Probar otro estilo",
  "result.card": "Convertirlo en tarjeta de Navidad",
  "result.tree": "Añadirlo a vuestro árbol de Navidad",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Navidad",
  "error.unsupported": "No pudimos usar esta foto. Prueba una imagen familiar más nítida con caras visibles.",
  "error.generation": "La magia de Navidad no funcionó esta vez. Intentémoslo de nuevo.",
  "error.network": "Problema de conexión. Tu selección está guardada — inténtalo de nuevo.",
  "error.generic": "Algo salió mal. Inténtalo de nuevo.",
  "error.paidKeepLink": "Si ya pagaste, guarda el enlace del pedido — el soporte puede reintentar sin cobrarte de nuevo.",
  "nav.hub": "Hub de Navidad",
  "nav.photo": "Generador de fotos",
  "nav.couples": "Parejas",
  "nav.pets": "Mascotas",
  "nav.cards": "Tarjetas de Navidad",
  "nav.tree": "Árbol de Navidad",
  "busy.uploading": "Subiendo tu foto…",
  "busy.working": "Trabajando…",
  "cross.couples": "Navidad en pareja",
  "cross.classic": "Retrato clásico",
  "cross.pets": "Navidad de mascotas",
};

const IT: CopyBag = {
  "seo.title": "Generatore di foto di Natale in famiglia | Ritratti di famiglia di Natale",
  "seo.description": "Crea un ritratto di Natale familiare personalizzato dalla tua foto di famiglia preferita. Scegli una scena festiva e trasforma la foto in un ricordo delle feste.",
  "seo.h1": "Trasforma la tua foto di famiglia in un ritratto magico di Natale",
  "seo.ogAlt": "Trasformazione del ritratto di famiglia di Natale in un salotto accogliente",
  "hero.kicker": "THE DIGITAL GIFTER · NATALE",
  "hero.h1": "Trasforma la tua foto di famiglia in un ritratto magico di Natale",
  "hero.lede": "Carica una foto di famiglia, scegli uno stile natalizio e crea un bel ritratto per le persone che ami di più.",
  "hero.cta": "Carica la tua foto",
  "hero.privacy": "Le foto di famiglia restano private di default.",
  "hero.hint": "JPEG, PNG o WebP · fino a 15 MB",
  "hero.beforeLabel": "Prima",
  "hero.afterLabel": "Dopo",
  "hero.sliderAria": "Confronta la foto di famiglia quotidiana con il ritratto di Natale",
  "hero.stylesAria": "Scegli un esempio di stile natalizio",
  "trust.privateTitle": "Privato di default",
  "trust.privateBody": "La vostra foto di famiglia non viene mostrata pubblicamente.",
  "trust.memoriesTitle": "Fatto per ricordi veri",
  "trust.memoriesBody": "Crea qualcosa che vale la pena tenere.",
  "trust.stylesTitle": "Bellissimi stili di Natale",
  "trust.stylesBody": "Scegli l’atmosfera che sa di famiglia.",
  "moment.kicker": "Natale in famiglia",
  "moment.h2": "Crea un ritratto di famiglia di Natale",
  "moment.title": "Crea la foto di famiglia di Natale che avresti voluto scattare.",
  "moment.lede": "Carica una foto di gruppo, scegli un’atmosfera natalizia e crea un ritratto che punta a tenere tutti nel riquadro. Niente studio. Niente orari da coordinare — carica una foto e crea il momento.",
  "moment.cta": "Crea il nostro ritratto di Natale",
  "examples.h2": "Esempi di foto di famiglia di Natale",
  "examples.lede": "Ritratti natalizi caldi e realistici per ogni famiglia — da tre a cinque e oltre, neonati, nonni e gli animali che fanno parte della foto.",
  "examples.demoNote": "Esempi demo per ispirazione — non foto di clienti.",
  "examples.family3": "Famiglia di 3",
  "examples.family4": "Famiglia di 4",
  "examples.family5": "Famiglia di 5+",
  "examples.baby": "Genitori + neonato",
  "examples.grandparents": "Nonni + famiglia",
  "examples.dog": "Famiglia + cane",
  "examples.cat": "Famiglia + gatto",
  "examples.before": "Foto quotidiana",
  "examples.after": "Ritratto di Natale",
  "styles.h2": "Stili di Natale per le famiglie",
  "styles.lede": "Scegli il mondo di Natale che sa di casa.",
  "styles.cozy": "Camino accogliente",
  "styles.cozyDesc": "Soggiorno caldo, albero e luce del fuoco.",
  "styles.snowy": "Natale innevato",
  "styles.snowyDesc": "Neve soffice e luce invernale fresca.",
  "styles.classic": "Natale classico",
  "styles.classicDesc": "Rosso, verde e calore tradizionale.",
  "styles.elegant": "Natale elegante",
  "styles.elegantDesc": "Interni di lusso con dettagli dorati.",
  "styles.morning": "Mattina di Natale",
  "styles.morningDesc": "Pigiami, regali, luce morbida del mattino.",
  "styles.cabin": "Baita invernale",
  "styles.cabinDesc": "Baita di legno e finestre innevate.",
  "styles.wonderland": "Paese delle meraviglie invernale",
  "styles.wonderlandDesc": "Paesaggio innevato cinematografico.",
  "best.h2": "Quali foto di famiglia funzionano meglio?",
  "best.body": "Usa una foto di gruppo nitida con volti visibili, buona luce e tutti riconoscibili. Evita sfocature estreme, ritagli troppo stretti o foto in cui mancano persone chiave.",
  "how.h2": "Come funziona",
  "how.1.title": "Carica la tua foto di famiglia",
  "how.1.body": "Scegli un’immagine nitida con tutti quelli da includere nel ritratto.",
  "how.2.title": "Scegli il tuo mondo di Natale",
  "how.2.body": "Scegli la scena che ami — camino, neve, mattina o classico.",
  "how.3.title": "Crea il tuo ritratto",
  "how.3.body": "Trasforma la famiglia in un ricordo di Natale da tenere.",
  "geo.h2": "Cos’è un generatore di foto di famiglia di Natale?",
  "geo.body": "Un generatore di foto di famiglia di Natale trasforma una foto di famiglia caricata in un ritratto di gruppo festivo. Su TheDigitalGifter carichi una foto chiara della famiglia, scegli uno stile natalizio pensato per più persone e crei un ritratto scaricabile — privato di default, con opzione di continuare verso un biglietto di Natale.",
  "geo.best": "Quali foto funzionano meglio?",
  "geo.bestBody": "Le foto di gruppo nitide con volti visibili funzionano meglio. Includi tutti quelli che vuoi nella foto di famiglia finale.",
  "geo.support": "Chi può essere nel ritratto?",
  "geo.supportBody": "Famiglie di qualsiasi dimensione, genitori con neonato, nonni e foto famiglia-più-animale. Tieni tutti chiaramente visibili nell’immagine originale.",
  "geo.privacy": "Cosa succede alla mia foto di famiglia?",
  "geo.privacyBody": "Caricamenti e risultati restano privati di default. Non c’è una galleria pubblica.",
  "faq.h2": "Domande frequenti",
  "faq.1.q": "Posso creare un ritratto di Natale da una sola foto di famiglia?",
  "faq.1.a": "Sì. Carica una foto di famiglia nitida, scegli uno stile natalizio e crea il ritratto di famiglia.",
  "faq.2.q": "Si possono includere più persone?",
  "faq.2.a": "Sì. Questo percorso è pensato per i gruppi. Tieni tutti chiaramente visibili nella foto originale.",
  "faq.3.q": "Si possono includere i nonni?",
  "faq.3.a": "Sì. Le foto multigenerazionali — inclusi nonni e neonati — sono benvenute quando i volti sono visibili.",
  "faq.4.q": "Posso includere l’animale di famiglia?",
  "faq.4.a": "Sì quando l’animale è chiaramente visibile nella foto di famiglia. Per ritratti solo animale, usa le esperienze Animali, Cani o Gatti.",
  "faq.5.q": "Quali foto funzionano meglio?",
  "faq.5.a": "Foto nitide con volti visibili, buona luce e tutti inclusi. Evita sfocature estreme.",
  "faq.6.q": "Posso provare più stili di Natale?",
  "faq.6.a": "Sì. Scegli tra gli stili famiglia di Natale elencati nella pagina e puoi provarne un altro dopo aver creato un ritratto.",
  "faq.7.q": "Posso scaricare il ritratto finito?",
  "faq.7.a": "Sì. Quando il ritratto è pronto, scaricalo dalla schermata del risultato.",
  "faq.8.q": "Posso usarlo in un biglietto di Natale?",
  "faq.8.a": "Sì. Il passaggio del ritratto al creatore di biglietti di Natale è supportato.",
  "faq.9.q": "La mia foto di famiglia è privata?",
  "faq.9.a": "Sì. Le foto di famiglia restano private di default. Non pubblichiamo una galleria pubblica del tuo ritratto.",
  "upload.kicker": "Inizia qui",
  "upload.h2": "Carica la tua foto di famiglia",
  "upload.lede": "Una foto di gruppo nitida è tutto ciò che ti serve per iniziare.",
  "upload.choose": "Carica la tua foto",
  "upload.drop": "Oppure rilascia una foto qui",
  "upload.hint": "JPEG, PNG o WebP · fino a 15 MB",
  "upload.privacy": "Le foto di famiglia restano private di default.",
  "style.h2": "Scegli il tuo mondo di Natale",
  "style.lede": "Scegli l’atmosfera che sa di famiglia.",
  "style.back": "Indietro",
  "preview.h2": "Pronto a creare",
  "preview.lede": "Questa anteprima soft è la foto originale — il ritratto di Natale finito si sblocca dopo il pagamento.",
  "preview.continue": "Continua",
  "offer.h2": "Sblocca il tuo ritratto di famiglia di Natale",
  "offer.deliverable": "Un ritratto di famiglia di Natale ottimizzato per più persone.",
  "offer.ready": "Di solito pronto pochi minuti dopo il pagamento",
  "offer.private": "Privato di default · download dal link dell’ordine",
  "offer.email": "Email per ricevuta / recupero (opzionale)",
  "offer.pay": "Continua al pagamento",
  "offer.disabled": "Il pagamento si sta preparando al lancio. Puoi caricare, scegliere uno stile e vedere l’anteprima — il pagamento si attiva quando i prezzi sono live.",
  "offer.busy": "Preparazione del pagamento…",
  "checkout.h2": "Pagamento sicuro",
  "gen.h2": "Creazione del tuo ritratto di Natale",
  "gen.step1": "Riscaldiamo il camino…",
  "gen.step2": "Accendiamo l’albero…",
  "gen.step3": "Raduniamo la famiglia nella scena…",
  "gen.step4": "Il tuo ritratto di Natale è quasi pronto…",
  "gen.note": "Puoi lasciare questa pagina — riapri il link dell’ordine quando vuoi.",
  "result.h2": "Il vostro ritratto di famiglia di Natale",
  "result.download": "Scarica",
  "result.share": "Condividi",
  "result.another": "Creane un altro",
  "result.retryStyle": "Prova un altro stile",
  "result.card": "Trasformalo in un biglietto di Natale",
  "result.tree": "Aggiungilo al tuo albero di Natale",
  "result.toggleOriginal": "Originale",
  "result.toggleChristmas": "Natale",
  "error.unsupported": "Non abbiamo potuto usare questa foto. Prova un’immagine di famiglia più nitida con volti visibili.",
  "error.generation": "La magia di Natale non ha funzionato questa volta. Riproviamo.",
  "error.network": "Problema di connessione. La selezione è salvata — riprova.",
  "error.generic": "Qualcosa è andato storto. Riprova.",
  "error.paidKeepLink": "Se hai già pagato, conserva il link dell’ordine — il supporto può riprovare senza addebitarti di nuovo.",
  "nav.hub": "Hub di Natale",
  "nav.photo": "Generatore di foto",
  "nav.couples": "Coppie",
  "nav.pets": "Animali",
  "nav.cards": "Biglietti di Natale",
  "nav.tree": "Albero di Natale",
  "busy.uploading": "Caricamento della foto…",
  "busy.working": "Elaborazione…",
  "cross.couples": "Natale di coppia",
  "cross.classic": "Ritratto classico",
  "cross.pets": "Natale per animali",
};

const PT: CopyBag = {
  "seo.title": "Gerador de fotos de Natal em família | Retratos de família de Natal",
  "seo.description": "Crie um retrato de Natal familiar personalizado a partir da sua foto de família favorita. Escolha uma cena festiva e transforme a foto numa memória das festas.",
  "seo.h1": "Transforme a sua foto de família num retrato mágico de Natal",
  "seo.ogAlt": "Transformação de retrato de família de Natal numa sala acolhedora",
  "hero.kicker": "THE DIGITAL GIFTER · NATAL",
  "hero.h1": "Transforme a sua foto de família num retrato mágico de Natal",
  "hero.lede": "Carregue uma foto de família, escolha um estilo de Natal e crie um belo retrato para as pessoas que mais ama.",
  "hero.cta": "Carregar a sua foto",
  "hero.privacy": "As fotos de família ficam privadas por predefinição.",
  "hero.hint": "JPEG, PNG ou WebP · até 15 MB",
  "hero.beforeLabel": "Antes",
  "hero.afterLabel": "Depois",
  "hero.sliderAria": "Comparar a foto de família do dia a dia com o retrato de Natal",
  "hero.stylesAria": "Escolher um exemplo de estilo de Natal",
  "trust.privateTitle": "Privado por predefinição",
  "trust.privateBody": "A vossa foto de família não é mostrada publicamente.",
  "trust.memoriesTitle": "Feito para memórias reais",
  "trust.memoriesBody": "Crie algo que mereça ser guardado.",
  "trust.stylesTitle": "Belos estilos de Natal",
  "trust.stylesBody": "Escolha a atmosfera que parece a sua família.",
  "moment.kicker": "Natal em família",
  "moment.h2": "Crie um retrato de família de Natal",
  "moment.title": "Crie a foto de família de Natal que gostaria de ter tirado.",
  "moment.lede": "Carregue uma foto de grupo, escolha uma atmosfera de Natal e crie um retrato que procura manter todos no enquadramento. Sem estúdio. Sem agendas a combinar — basta carregar uma foto e criar o momento.",
  "moment.cta": "Criar o nosso retrato de Natal",
  "examples.h2": "Exemplos de fotos de família de Natal",
  "examples.lede": "Retratos de Natal quentes e realistas para todo o tipo de família — de três a cinco ou mais, bebés, avós e os animais que fazem parte da foto.",
  "examples.demoNote": "Exemplos de demonstração para inspiração — não são fotos de clientes.",
  "examples.family3": "Família de 3",
  "examples.family4": "Família de 4",
  "examples.family5": "Família de 5+",
  "examples.baby": "Pais + bebé",
  "examples.grandparents": "Avós + família",
  "examples.dog": "Família + cão",
  "examples.cat": "Família + gato",
  "examples.before": "Foto do dia a dia",
  "examples.after": "Retrato de Natal",
  "styles.h2": "Estilos de Natal para famílias",
  "styles.lede": "Escolha o mundo de Natal que parece casa.",
  "styles.cozy": "Lareira acolhedora",
  "styles.cozyDesc": "Sala quente, árvore e luz da lareira.",
  "styles.snowy": "Natal nevado",
  "styles.snowyDesc": "Neve suave e luz fria de inverno.",
  "styles.classic": "Natal clássico",
  "styles.classicDesc": "Vermelho, verde e calor tradicional.",
  "styles.elegant": "Natal elegante",
  "styles.elegantDesc": "Interiores de luxo com detalhes dourados.",
  "styles.morning": "Manhã de Natal",
  "styles.morningDesc": "Pijamas, prendas, luz suave da manhã.",
  "styles.cabin": "Cabana de inverno",
  "styles.cabinDesc": "Cabana de madeira e janelas nevadas.",
  "styles.wonderland": "País das maravilhas de inverno",
  "styles.wonderlandDesc": "Paisagem nevada cinematográfica.",
  "best.h2": "Que fotos de família funcionam melhor?",
  "best.body": "Use uma foto de grupo nítida com rostos visíveis, boa luz e todos reconhecíveis. Evite desfoque extremo, recortes fortes ou fotos em que faltem pessoas importantes.",
  "how.h2": "Como funciona",
  "how.1.title": "Carregue a sua foto de família",
  "how.1.body": "Escolha uma imagem nítida com todos os que quer no retrato.",
  "how.2.title": "Escolha o seu mundo de Natal",
  "how.2.body": "Escolha a cena que gosta — lareira, neve, manhã ou clássico.",
  "how.3.title": "Crie o seu retrato",
  "how.3.body": "Transforme a família numa memória de Natal para guardar.",
  "geo.h2": "O que é um gerador de fotos de família de Natal?",
  "geo.body": "Um gerador de fotos de família de Natal transforma uma foto de família carregada num retrato de grupo festivo. No TheDigitalGifter carrega uma foto clara da família, escolhe um estilo de Natal pensado para várias pessoas e cria um retrato descarregável — privado por predefinição, com opção de continuar para um cartão de Natal.",
  "geo.best": "Que fotos funcionam melhor?",
  "geo.bestBody": "Fotos de grupo nítidas com rostos visíveis funcionam melhor. Inclua todos os que quer na foto de família final.",
  "geo.support": "Quem pode estar no retrato?",
  "geo.supportBody": "Famílias de qualquer tamanho, pais com bebé, avós e fotos família-mais-animal. Mantenha todos claramente visíveis na imagem original.",
  "geo.privacy": "O que acontece à minha foto de família?",
  "geo.privacyBody": "Os carregamentos e resultados ficam privados por predefinição. Não há galeria pública.",
  "faq.h2": "Perguntas frequentes",
  "faq.1.q": "Posso criar um retrato de Natal a partir de uma só foto de família?",
  "faq.1.a": "Sim. Carregue uma foto de família nítida, escolha um estilo de Natal e crie o vosso retrato familiar.",
  "faq.2.q": "Podem ser incluídas várias pessoas?",
  "faq.2.a": "Sim. Esta rota é pensada para grupos. Mantenha todos claramente visíveis na foto original.",
  "faq.3.q": "Podem ser incluídos os avós?",
  "faq.3.a": "Sim. Fotos multigeracionais — incluindo avós e bebés — são bem-vindas quando os rostos estão visíveis.",
  "faq.4.q": "Posso incluir o animal da família?",
  "faq.4.a": "Sim quando o animal está claramente visível na foto de família. Para retratos só de animais, use as experiências Animais, Cães ou Gatos.",
  "faq.5.q": "Que fotos funcionam melhor?",
  "faq.5.a": "Fotos nítidas com rostos visíveis, boa luz e todos incluídos. Evite desfoque extremo.",
  "faq.6.q": "Posso experimentar vários estilos de Natal?",
  "faq.6.a": "Sim. Escolha entre os estilos de família de Natal listados na página e pode experimentar outro estilo depois de criar um retrato.",
  "faq.7.q": "Posso descarregar o retrato final?",
  "faq.7.a": "Sim. Quando o retrato estiver pronto, descarregue-o no ecrã de resultado.",
  "faq.8.q": "Posso usá-lo num cartão de Natal?",
  "faq.8.a": "Sim. A transferência do retrato para o criador de cartões de Natal é suportada.",
  "faq.9.q": "A minha foto de família é privada?",
  "faq.9.a": "Sim. As fotos de família ficam privadas por predefinição. Não publicamos uma galeria pública do vosso retrato.",
  "upload.kicker": "Comece aqui",
  "upload.h2": "Carregue a sua foto de família",
  "upload.lede": "Uma foto de grupo nítida é tudo o que precisa para começar.",
  "upload.choose": "Carregar a sua foto",
  "upload.drop": "Ou largue uma foto aqui",
  "upload.hint": "JPEG, PNG ou WebP · até 15 MB",
  "upload.privacy": "As fotos de família ficam privadas por predefinição.",
  "style.h2": "Escolha o seu mundo de Natal",
  "style.lede": "Escolha a atmosfera que parece a sua família.",
  "style.back": "Voltar",
  "preview.h2": "Pronto a criar",
  "preview.lede": "Esta pré-visualização suave é a foto original — o retrato de Natal final desbloqueia-se após o pagamento.",
  "preview.continue": "Continuar",
  "offer.h2": "Desbloqueie o vosso retrato de família de Natal",
  "offer.deliverable": "Um retrato de família de Natal otimizado para várias pessoas.",
  "offer.ready": "Normalmente pronto poucos minutos após o pagamento",
  "offer.private": "Privado por predefinição · descarregue pelo link da encomenda",
  "offer.email": "Email para recibo / recuperação (opcional)",
  "offer.pay": "Continuar para o pagamento",
  "offer.disabled": "O pagamento está a preparar-se para o lançamento. Pode carregar, escolher um estilo e pré-visualizar — o pagamento ativa-se quando os preços estiverem disponíveis.",
  "offer.busy": "A preparar o pagamento…",
  "checkout.h2": "Pagamento seguro",
  "gen.h2": "A criar o vosso retrato de Natal",
  "gen.step1": "A aquecer a lareira…",
  "gen.step2": "A acender a árvore…",
  "gen.step3": "A reunir a família na cena…",
  "gen.step4": "O vosso retrato de Natal está quase pronto…",
  "gen.note": "Pode sair desta página — reabra o link da encomenda a qualquer momento.",
  "result.h2": "O vosso retrato de família de Natal",
  "result.download": "Descarregar",
  "result.share": "Partilhar",
  "result.another": "Criar outro",
  "result.retryStyle": "Experimentar outro estilo",
  "result.card": "Transformá-lo num cartão de Natal",
  "result.tree": "Adicioná-lo à vossa árvore de Natal",
  "result.toggleOriginal": "Original",
  "result.toggleChristmas": "Natal",
  "error.unsupported": "Não conseguimos usar esta foto. Experimente uma imagem de família mais nítida com rostos visíveis.",
  "error.generation": "A magia de Natal não funcionou desta vez. Vamos tentar de novo.",
  "error.network": "Problema de ligação. A sua seleção está guardada — tente novamente.",
  "error.generic": "Algo correu mal. Tente novamente.",
  "error.paidKeepLink": "Se já pagou, guarde o link da encomenda — o suporte pode tentar novamente sem cobrar de novo.",
  "nav.hub": "Hub de Natal",
  "nav.photo": "Gerador de fotos",
  "nav.couples": "Casais",
  "nav.pets": "Animais",
  "nav.cards": "Cartões de Natal",
  "nav.tree": "Árvore de Natal",
  "busy.uploading": "A carregar a sua foto…",
  "busy.working": "A trabalhar…",
  "cross.couples": "Natal a dois",
  "cross.classic": "Retrato clássico",
  "cross.pets": "Natal para animais",
};

const NL: CopyBag = {
  "seo.title": "Familie kerstfoto-generator | Kerstfamilieportretten",
  "seo.description": "Maak een gepersonaliseerd familiekerstportret van jullie favoriete familiefoto. Kies een feestelijke kerstscène en maak van de foto een feestherinnering.",
  "seo.h1": "Maak van jullie familiefoto een magisch kerstportret",
  "seo.ogAlt": "Familiekerstportret-transformatie in een knusse woonkamer",
  "hero.kicker": "THE DIGITAL GIFTER · KERST",
  "hero.h1": "Maak van jullie familiefoto een magisch kerstportret",
  "hero.lede": "Upload een familiefoto, kies een kerststijl en maak een mooi portret voor de mensen van wie je het meest houdt.",
  "hero.cta": "Upload je foto",
  "hero.privacy": "Familiefoto’s blijven standaard privé.",
  "hero.hint": "JPEG, PNG of WebP · tot 15 MB",
  "hero.beforeLabel": "Voor",
  "hero.afterLabel": "Na",
  "hero.sliderAria": "Vergelijk de alledaagse familiefoto met het kerstportret",
  "hero.stylesAria": "Kies een kerststijlvoorbeeld",
  "trust.privateTitle": "Standaard privé",
  "trust.privateBody": "Jullie familiefoto wordt niet openbaar getoond.",
  "trust.memoriesTitle": "Gemaakt voor echte herinneringen",
  "trust.memoriesBody": "Maak iets dat de moeite waard is om te bewaren.",
  "trust.stylesTitle": "Mooie kerststijlen",
  "trust.stylesBody": "Kies de sfeer die bij jullie gezin past.",
  "moment.kicker": "Familiekerst",
  "moment.h2": "Maak een familiekerstportret",
  "moment.title": "Maak de familiekerstfoto die je had willen maken.",
  "moment.lede": "Upload een groepsfoto, kies een kerstsfeer en maak een portret dat iedereen in beeld wil houden. Geen studio. Geen agenda’s afstemmen — upload een foto en creëer het moment.",
  "moment.cta": "Ons kerstportret maken",
  "examples.h2": "Voorbeelden van familiekerstfoto’s",
  "examples.lede": "Warme, realistische kerstportretten voor elk gezin — van drie tot vijf-plus, baby’s, grootouders en de huisdieren die erbij horen.",
  "examples.demoNote": "Demovoorbeelden ter inspiratie — geen klantfoto’s.",
  "examples.family3": "Gezin van 3",
  "examples.family4": "Gezin van 4",
  "examples.family5": "Gezin van 5+",
  "examples.baby": "Ouders + baby",
  "examples.grandparents": "Grootouders + familie",
  "examples.dog": "Familie + hond",
  "examples.cat": "Familie + kat",
  "examples.before": "Alledaagse foto",
  "examples.after": "Kerstportret",
  "styles.h2": "Kerststijlen voor gezinnen",
  "styles.lede": "Kies de kerstwereld die als thuis voelt.",
  "styles.cozy": "Gezellige open haard",
  "styles.cozyDesc": "Warme woonkamer, boom en haardvuur.",
  "styles.snowy": "Sneeuwkerst",
  "styles.snowyDesc": "Zachte sneeuw en koel winterlicht.",
  "styles.classic": "Klassieke kerst",
  "styles.classicDesc": "Rood, groen en traditionele warmte.",
  "styles.elegant": "Elegante kerst",
  "styles.elegantDesc": "Luxe interieurs met gouden details.",
  "styles.morning": "Kerstmorgen",
  "styles.morningDesc": "Pyjama’s, cadeaus, zacht ochtendlicht.",
  "styles.cabin": "Winterchalet",
  "styles.cabinDesc": "Houten hut en besneeuwde ramen.",
  "styles.wonderland": "Winterwonderland",
  "styles.wonderlandDesc": "Filmisch besneeuwd landschap.",
  "best.h2": "Welke familiefoto’s werken het best?",
  "best.body": "Gebruik een duidelijke groepsfoto waarop gezichten zichtbaar zijn, het licht oké is en iedereen herkenbaar is. Vermijd extreme onscherpte, zware uitsnedes of foto’s waarop belangrijke mensen ontbreken.",
  "how.h2": "Hoe het werkt",
  "how.1.title": "Upload je familiefoto",
  "how.1.body": "Kies een duidelijke foto met iedereen die je in het portret wilt.",
  "how.2.title": "Kies je kerstwereld",
  "how.2.body": "Kies de scène die je leuk vindt — haard, sneeuw, ochtend of klassiek.",
  "how.3.title": "Maak je portret",
  "how.3.body": "Maak van je gezin een kerstherinnering om te bewaren.",
  "geo.h2": "Wat is een familiekerstfoto-generator?",
  "geo.body": "Een familiekerstfoto-generator verandert één geüploade familiefoto in een feestelijk groepskerstportret. Op TheDigitalGifter upload je een duidelijke familiefoto, kies je een kerststijl voor meerdere personen en maak je een downloadbaar portret — standaard privé, met optie om door te gaan naar een kerstkaart.",
  "geo.best": "Welke foto’s werken het best?",
  "geo.bestBody": "Duidelijke groepsfoto’s met zichtbare gezichten werken het best. Neem iedereen mee die je in het eindbeeld wilt.",
  "geo.support": "Wie kan op het portret?",
  "geo.supportBody": "Gezinnen van elke omvang, ouders met baby, grootouders en familie-plus-huisdierfoto’s. Houd iedereen duidelijk zichtbaar op de originele foto.",
  "geo.privacy": "Wat gebeurt er met mijn familiefoto?",
  "geo.privacyBody": "Uploads en resultaten blijven standaard privé. Er is geen openbare galerij.",
  "faq.h2": "Veelgestelde vragen",
  "faq.1.q": "Kan ik een kerstportret maken van één familiefoto?",
  "faq.1.a": "Ja. Upload één duidelijke familiefoto, kies een kerststijl en maak jullie familieportret.",
  "faq.2.q": "Kunnen meerdere mensen worden meegenomen?",
  "faq.2.a": "Ja. Deze route is gemaakt voor groepen. Houd iedereen duidelijk zichtbaar op de originele foto.",
  "faq.3.q": "Kunnen grootouders worden meegenomen?",
  "faq.3.a": "Ja. Foto’s met meerdere generaties — inclusief grootouders en baby’s — zijn welkom als gezichten zichtbaar zijn.",
  "faq.4.q": "Kan ik het familiehuisdier meenemen?",
  "faq.4.a": "Ja als het huisdier duidelijk zichtbaar is op de familiefoto. Voor alleen-huisdierportretten gebruik je de Huisdier-, Honden- of Kattenervaringen.",
  "faq.5.q": "Welke foto’s werken het best?",
  "faq.5.a": "Duidelijke foto’s met zichtbare gezichten, fatsoenlijk licht en iedereen erop. Vermijd extreme onscherpte.",
  "faq.6.q": "Kan ik meerdere kerststijlen proberen?",
  "faq.6.a": "Ja. Kies uit de familiekerststijlen op de pagina en je kunt na een portret een andere stijl proberen.",
  "faq.7.q": "Kan ik het afgewerkte portret downloaden?",
  "faq.7.a": "Ja. Als je portret klaar is, download je het vanaf het resultaatscherm.",
  "faq.8.q": "Kan ik het in een kerstkaart gebruiken?",
  "faq.8.a": "Ja. Overdracht van het portret naar de kerstkaartmaker wordt ondersteund.",
  "faq.9.q": "Is mijn familiefoto privé?",
  "faq.9.a": "Ja. Familiefoto’s blijven standaard privé. We publiceren geen openbare galerij van jullie portret.",
  "upload.kicker": "Begin hier",
  "upload.h2": "Upload je familiefoto",
  "upload.lede": "Een duidelijke groepsfoto is alles wat je nodig hebt om te beginnen.",
  "upload.choose": "Upload je foto",
  "upload.drop": "Of sleep een foto hierheen",
  "upload.hint": "JPEG, PNG of WebP · tot 15 MB",
  "upload.privacy": "Familiefoto’s blijven standaard privé.",
  "style.h2": "Kies je kerstwereld",
  "style.lede": "Kies de sfeer die bij jullie gezin past.",
  "style.back": "Terug",
  "preview.h2": "Klaar om te maken",
  "preview.lede": "Deze zachte preview is jullie originele foto — het afgewerkte kerstportret wordt na checkout vrijgegeven.",
  "preview.continue": "Doorgaan",
  "offer.h2": "Ontgrendel jullie familiekerstportret",
  "offer.deliverable": "Eén kerstfamilieportret geoptimaliseerd voor meerdere personen.",
  "offer.ready": "Meestal binnen enkele minuten na betaling klaar",
  "offer.private": "Standaard privé · download via je bestellink",
  "offer.email": "E-mail voor bon / herstel (optioneel)",
  "offer.pay": "Doorgaan naar betaling",
  "offer.disabled": "Checkout wordt voorbereid voor de lancering. Je kunt uploaden, een stijl kiezen en previewen — betaling start wanneer de prijzen live zijn.",
  "offer.busy": "Checkout voorbereiden…",
  "checkout.h2": "Veilige betaling",
  "gen.h2": "Jullie kerstportret wordt gemaakt",
  "gen.step1": "Haard wordt opgewarmd…",
  "gen.step2": "Boom wordt aangelicht…",
  "gen.step3": "Familie verzamelen in de scène…",
  "gen.step4": "Jullie kerstportret is bijna klaar…",
  "gen.note": "Je kunt deze pagina verlaten — open de bestellink wanneer je wilt opnieuw.",
  "result.h2": "Jullie familiekerstportret",
  "result.download": "Downloaden",
  "result.share": "Delen",
  "result.another": "Nog een maken",
  "result.retryStyle": "Andere stijl proberen",
  "result.card": "Maak er een kerstkaart van",
  "result.tree": "Voeg het toe aan jullie kerstboom",
  "result.toggleOriginal": "Origineel",
  "result.toggleChristmas": "Kerst",
  "error.unsupported": "We konden deze foto niet gebruiken. Probeer een duidelijkere familiefoto met zichtbare gezichten.",
  "error.generation": "De kerstmagie werkte die keer niet. Laten we het opnieuw proberen.",
  "error.network": "Verbindingsprobleem. Je selectie is opgeslagen — probeer het opnieuw.",
  "error.generic": "Er ging iets mis. Probeer het opnieuw.",
  "error.paidKeepLink": "Als je al hebt betaald, bewaar je bestellink — support kan opnieuw proberen zonder opnieuw te rekenen.",
  "nav.hub": "Kersthub",
  "nav.photo": "Fotogenerator",
  "nav.couples": "Koppels",
  "nav.pets": "Huisdieren",
  "nav.cards": "Kerstkaarten",
  "nav.tree": "Kerstboom",
  "busy.uploading": "Je foto uploaden…",
  "busy.working": "Bezig…",
  "cross.couples": "Koppelkerst",
  "cross.classic": "Klassiek portret",
  "cross.pets": "Huisdierkerst",
};

const PL: CopyBag = {
  "seo.title": "Generator świątecznych zdjęć rodzinnych | Świąteczne portrety rodzinne",
  "seo.description": "Stwórz spersonalizowany świąteczny portret rodzinny z ulubionego zdjęcia rodzinnego. Wybierz świąteczną scenę i zamień zdjęcie we wspomnienie świąt.",
  "seo.h1": "Zamień zdjęcie rodzinne w magiczny świąteczny portret",
  "seo.ogAlt": "Transformacja świątecznego portretu rodzinnego w przytulnym salonie",
  "hero.kicker": "THE DIGITAL GIFTER · ŚWIĘTA",
  "hero.h1": "Zamień zdjęcie rodzinne w magiczny świąteczny portret",
  "hero.lede": "Prześlij zdjęcie rodzinne, wybierz świąteczny styl i stwórz piękny portret dla osób, które kochasz najbardziej.",
  "hero.cta": "Prześlij swoje zdjęcie",
  "hero.privacy": "Zdjęcia rodzinne pozostają prywatne domyślnie.",
  "hero.hint": "JPEG, PNG lub WebP · do 15 MB",
  "hero.beforeLabel": "Przed",
  "hero.afterLabel": "Po",
  "hero.sliderAria": "Porównaj codzienne zdjęcie rodzinne ze świątecznym portretem",
  "hero.stylesAria": "Wybierz przykład świątecznego stylu",
  "trust.privateTitle": "Prywatne domyślnie",
  "trust.privateBody": "Wasze zdjęcie rodzinne nie jest wyświetlane publicznie.",
  "trust.memoriesTitle": "Dla prawdziwych wspomnień",
  "trust.memoriesBody": "Stwórz coś wartego zachowania.",
  "trust.stylesTitle": "Piękne świąteczne style",
  "trust.stylesBody": "Wybierz atmosferę, która pasuje do waszej rodziny.",
  "moment.kicker": "Święta rodzinne",
  "moment.h2": "Stwórz świąteczny portret rodzinny",
  "moment.title": "Stwórz świąteczne zdjęcie rodzinne, które chcielibyście mieć.",
  "moment.lede": "Prześlij zdjęcie grupowe, wybierz świąteczną atmosferę i stwórz portret, który ma utrzymać wszystkich w kadrze. Bez studia. Bez uzgadniania terminów — wystarczy przesłać zdjęcie i stworzyć chwilę.",
  "moment.cta": "Stwórz nasz świąteczny portret",
  "examples.h2": "Przykłady świątecznych zdjęć rodzinnych",
  "examples.lede": "Ciepłe, realistyczne świąteczne portrety dla każdej rodziny — od trzech do pięciu i więcej, niemowląt, dziadków i pupili, którzy należą do zdjęcia.",
  "examples.demoNote": "Przykłady demo do inspiracji — nie zdjęcia klientów.",
  "examples.family3": "Rodzina 3-osobowa",
  "examples.family4": "Rodzina 4-osobowa",
  "examples.family5": "Rodzina 5+",
  "examples.baby": "Rodzice + niemowlę",
  "examples.grandparents": "Dziadkowie + rodzina",
  "examples.dog": "Rodzina + pies",
  "examples.cat": "Rodzina + kot",
  "examples.before": "Codzienne zdjęcie",
  "examples.after": "Świąteczny portret",
  "styles.h2": "Świąteczne style dla rodzin",
  "styles.lede": "Wybierz świąteczny świat, który czuje się jak dom.",
  "styles.cozy": "Przytulny kominek",
  "styles.cozyDesc": "Ciepły salon, choinka i blask ognia.",
  "styles.snowy": "Śnieżne święta",
  "styles.snowyDesc": "Miękki śnieg i chłodne zimowe światło.",
  "styles.classic": "Klasyczne święta",
  "styles.classicDesc": "Czerwień, zieleń i tradycyjne ciepło.",
  "styles.elegant": "Eleganckie święta",
  "styles.elegantDesc": "Luksusowe wnętrza ze złotymi detalami.",
  "styles.morning": "Poranek Bożego Narodzenia",
  "styles.morningDesc": "Piżamy, prezenty, miękkie poranne światło.",
  "styles.cabin": "Zimowa chatka",
  "styles.cabinDesc": "Drewniana chatka i ośnieżone okna.",
  "styles.wonderland": "Zimowa kraina czarów",
  "styles.wonderlandDesc": "Filmowy ośnieżony krajobraz.",
  "best.h2": "Jakie zdjęcia rodzinne sprawdzają się najlepiej?",
  "best.body": "Użyj wyraźnego zdjęcia grupowego z widocznymi twarzami, przyzwoitym światłem i rozpoznawalnymi osobami. Unikaj skrajnego rozmycia, mocnych kadrów lub zdjęć, na których brakuje kluczowych osób.",
  "how.h2": "Jak to działa",
  "how.1.title": "Prześlij zdjęcie rodzinne",
  "how.1.body": "Wybierz wyraźne zdjęcie ze wszystkimi, których chcesz na portrecie.",
  "how.2.title": "Wybierz swój świąteczny świat",
  "how.2.body": "Wybierz ulubioną scenę — kominek, śnieg, poranek lub klasykę.",
  "how.3.title": "Stwórz portret",
  "how.3.body": "Zamień rodzinę w świąteczne wspomnienie warte zachowania.",
  "geo.h2": "Czym jest generator świątecznych zdjęć rodzinnych?",
  "geo.body": "Generator świątecznych zdjęć rodzinnych zamienia jedno przesłane zdjęcie rodzinne w świąteczny portret grupowy. Na TheDigitalGifter przesyłasz wyraźne zdjęcie rodziny, wybierasz świąteczny styl dla wielu osób i tworzysz portret do pobrania — prywatny domyślnie, z opcją kontynuacji do kartki świątecznej.",
  "geo.best": "Jakie zdjęcia sprawdzają się najlepiej?",
  "geo.bestBody": "Najlepiej działają wyraźne zdjęcia grupowe z widocznymi twarzami. Uwzględnij wszystkich, których chcesz na finalnym rodzinnym zdjęciu.",
  "geo.support": "Kto może być na portrecie?",
  "geo.supportBody": "Rodziny dowolnej wielkości, rodzice z niemowlęciem, dziadkowie oraz zdjęcia rodzina-plus-pupil. Utrzymaj wszystkich wyraźnie widocznych na oryginalnym zdjęciu.",
  "geo.privacy": "Co dzieje się z moim zdjęciem rodzinnym?",
  "geo.privacyBody": "Przesłania i wyniki pozostają prywatne domyślnie. Nie ma publicznej galerii.",
  "faq.h2": "Często zadawane pytania",
  "faq.1.q": "Czy mogę stworzyć świąteczny portret z jednego zdjęcia rodzinnego?",
  "faq.1.a": "Tak. Prześlij jedno wyraźne zdjęcie rodzinne, wybierz świąteczny styl i stwórz portret rodzinny.",
  "faq.2.q": "Czy można uwzględnić wiele osób?",
  "faq.2.a": "Tak. Ta trasa jest zaprojektowana dla grup. Utrzymaj wszystkich wyraźnie widocznych na oryginalnym zdjęciu.",
  "faq.3.q": "Czy można uwzględnić dziadków?",
  "faq.3.a": "Tak. Zdjęcia wielopokoleniowe — w tym dziadkowie i niemowlęta — są mile widziane, gdy twarze są widoczne.",
  "faq.4.q": "Czy mogę uwzględnić rodzinnego pupila?",
  "faq.4.a": "Tak, gdy pupil jest wyraźnie widoczny na zdjęciu rodzinnym. Do portretów tylko zwierząt użyj doświadczeń Pupile, Psy lub Koty.",
  "faq.5.q": "Jakie zdjęcia sprawdzają się najlepiej?",
  "faq.5.a": "Wyraźne zdjęcia z widocznymi twarzami, przyzwoitym światłem i wszystkimi osobami. Unikaj skrajnego rozmycia.",
  "faq.6.q": "Czy mogę wypróbować kilka świątecznych stylów?",
  "faq.6.a": "Tak. Wybierz spośród rodzinnych stylów świątecznych na stronie i możesz spróbować innego stylu po stworzeniu portretu.",
  "faq.7.q": "Czy mogę pobrać gotowy portret?",
  "faq.7.a": "Tak. Gdy portret będzie gotowy, pobierz go z ekranu wyniku.",
  "faq.8.q": "Czy mogę użyć go w kartce świątecznej?",
  "faq.8.a": "Tak. Przekazanie portretu do kreatora kartek świątecznych jest obsługiwane.",
  "faq.9.q": "Czy moje zdjęcie rodzinne jest prywatne?",
  "faq.9.a": "Tak. Zdjęcia rodzinne pozostają prywatne domyślnie. Nie publikujemy publicznej galerii waszego portretu.",
  "upload.kicker": "Zacznij tutaj",
  "upload.h2": "Prześlij zdjęcie rodzinne",
  "upload.lede": "Wyraźne zdjęcie grupowe to wszystko, czego potrzebujesz, by zacząć.",
  "upload.choose": "Prześlij swoje zdjęcie",
  "upload.drop": "Lub upuść zdjęcie tutaj",
  "upload.hint": "JPEG, PNG lub WebP · do 15 MB",
  "upload.privacy": "Zdjęcia rodzinne pozostają prywatne domyślnie.",
  "style.h2": "Wybierz swój świąteczny świat",
  "style.lede": "Wybierz atmosferę, która pasuje do waszej rodziny.",
  "style.back": "Wstecz",
  "preview.h2": "Gotowi do tworzenia",
  "preview.lede": "Ten miękki podgląd to oryginalne zdjęcie — gotowy świąteczny portret odblokuje się po płatności.",
  "preview.continue": "Kontynuuj",
  "offer.h2": "Odblokuj świąteczny portret rodzinny",
  "offer.deliverable": "Jeden świąteczny portret rodzinny zoptymalizowany pod wiele osób.",
  "offer.ready": "Zwykle gotowy kilka minut po płatności",
  "offer.private": "Prywatne domyślnie · pobierz przez link zamówienia",
  "offer.email": "E-mail na rachunek / odzyskanie (opcjonalnie)",
  "offer.pay": "Przejdź do płatności",
  "offer.disabled": "Płatność przygotowuje się do startu. Możesz przesyłać, wybierać styl i podglądać — płatność włączy się, gdy ceny będą dostępne.",
  "offer.busy": "Przygotowywanie płatności…",
  "checkout.h2": "Bezpieczna płatność",
  "gen.h2": "Tworzymy wasz świąteczny portret",
  "gen.step1": "Rozgrzewamy kominek…",
  "gen.step2": "Zapalamy choinkę…",
  "gen.step3": "Zbieramy rodzinę w scenie…",
  "gen.step4": "Wasz świąteczny portret jest prawie gotowy…",
  "gen.note": "Możesz opuścić tę stronę — otwórz link zamówienia w dowolnym momencie.",
  "result.h2": "Wasz świąteczny portret rodzinny",
  "result.download": "Pobierz",
  "result.share": "Udostępnij",
  "result.another": "Stwórz kolejny",
  "result.retryStyle": "Wypróbuj inny styl",
  "result.card": "Zamień w kartkę świąteczną",
  "result.tree": "Dodaj do choinki",
  "result.toggleOriginal": "Oryginał",
  "result.toggleChristmas": "Święta",
  "error.unsupported": "Nie mogliśmy użyć tego zdjęcia. Spróbuj wyraźniejszego zdjęcia rodzinnego z widocznymi twarzami.",
  "error.generation": "Świąteczna magia tym razem nie zadziałała. Spróbujmy ponownie.",
  "error.network": "Problem z połączeniem. Twój wybór jest zapisany — spróbuj ponownie.",
  "error.generic": "Coś poszło nie tak. Spróbuj ponownie.",
  "error.paidKeepLink": "Jeśli już zapłaciłeś, zachowaj link zamówienia — wsparcie może ponowić realizację bez ponownego obciążenia.",
  "nav.hub": "Hub świąteczny",
  "nav.photo": "Generator zdjęć",
  "nav.couples": "Pary",
  "nav.pets": "Pupile",
  "nav.cards": "Kartki świąteczne",
  "nav.tree": "Choinka",
  "busy.uploading": "Przesyłanie zdjęcia…",
  "busy.working": "Przetwarzanie…",
  "cross.couples": "Święta dla par",
  "cross.classic": "Klasyczny portret",
  "cross.pets": "Święta dla pupili",
};

export const PACKS: Record<FamilyLocale, CopyBag> = {
  en: EN,
  ro: RO,
  de: DE,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  pl: PL,
};

const _enKeySet = Object.keys(PACKS.en).sort().join("\0");
for (const loc of FAMILY_LOCALES) {
  const keys = Object.keys(PACKS[loc]);
  if (keys.length !== Object.keys(PACKS.en).length || keys.sort().join("\0") !== _enKeySet) {
    throw new Error(`Family UI copy pack ${loc} key mismatch`);
  }
}

export function familyT(
  key: string,
  locale: FamilyLocale = FAMILY_DEFAULT_LOCALE,
): string {
  return PACKS[locale]?.[key] ?? EN[key] ?? key;
}

export function familyDir(locale: string): "ltr" | "rtl" {
  return FAMILY_LOCALE_DIR[locale] ?? "ltr";
}

export const FAMILY_COPY_KEYS = Object.keys(EN);

export const FAMILY_FAQS = [
  { qKey: "faq.1.q", aKey: "faq.1.a" },
  { qKey: "faq.2.q", aKey: "faq.2.a" },
  { qKey: "faq.3.q", aKey: "faq.3.a" },
  { qKey: "faq.4.q", aKey: "faq.4.a" },
  { qKey: "faq.5.q", aKey: "faq.5.a" },
  { qKey: "faq.6.q", aKey: "faq.6.a" },
  { qKey: "faq.7.q", aKey: "faq.7.a" },
  { qKey: "faq.8.q", aKey: "faq.8.a" },
  { qKey: "faq.9.q", aKey: "faq.9.a" },
] as const;
