export type LibraryCategoryId =
  | "clip_factory"
  | "christmas_reels"
  | "christmas_marketing"
  | "pet_dog"
  | "pet_cat"
  | "pet_other";

export type LibraryKind = "reel" | "short" | "photo";

export type LibraryVideo = {
  id: string;
  title: string;
  description: string;
  src: string;
  filename: string;
  category: LibraryCategoryId;
  kind: LibraryKind;
  /** Known length in seconds. Used before the file metadata loads. */
  durationSeconds?: number;
  /** Still image shown until the first video frame paints (iOS often stays black otherwise). */
  poster?: string;
  width?: number;
  height?: number;
};

export type LibraryCategory = {
  id: LibraryCategoryId;
  label: string;
  description: string;
};

export type LibraryKindFilter = {
  id: LibraryKind;
  label: string;
  description: string;
};

export const LIBRARY_CATEGORIES: LibraryCategory[] = [
  {
    id: "clip_factory",
    label: "Clip Factory",
    description: "Vertical clips generated from long-form video, with captions and provenance.",
  },
  {
    id: "christmas_reels",
    label: "Christmas Reels",
    description:
      "Assembled Reels, short clips, and the stills used to generate them. Open Reels, Shorts, or Photos.",
  },
  {
    id: "christmas_marketing",
    label: "Christmas marketing",
    description: "Landing, Advent, and gift-tree loops used on the public site.",
  },
  {
    id: "pet_dog",
    label: "Pet · Dog",
    description: "Public dog teaser clips.",
  },
  {
    id: "pet_cat",
    label: "Pet · Cat",
    description: "Public cat teaser clips.",
  },
  {
    id: "pet_other",
    label: "Pet · Other",
    description: "Public other-pet teaser clips.",
  },
];

export const CHRISTMAS_LIBRARY_KINDS: LibraryKindFilter[] = [
  {
    id: "reel",
    label: "Reels",
    description: "Assembled vertical Reels, about 10–15 seconds.",
  },
  {
    id: "short",
    label: "Shorts",
    description: "The 3–5s clips that make up the Reels — including NYC ice and snowy village.",
  },
  {
    id: "photo",
    label: "Photos",
    description: "Source stills used to generate the Reels and Shorts.",
  },
];

const PET_CLIP_STYLES = [
  ["astronaut", "Astronaut"],
  ["beach-vacation", "Beach vacation"],
  ["christmas-portrait", "Christmas portrait"],
  ["cinema-boss", "Cinema boss"],
  ["formula-racer", "Formula racer"],
  ["head-chef", "Head chef"],
  ["luxury-ceo", "Luxury CEO"],
  ["newspaper", "Newspaper"],
  ["original-superhero", "Superhero"],
  ["renaissance", "Renaissance"],
  ["royal-portrait", "Royal portrait"],
  ["spa-bathtub", "Spa bathtub"],
] as const;

function petClips(species: "dog" | "cat" | "other", category: LibraryCategoryId): LibraryVideo[] {
  const label = species === "other" ? "Other pet" : species[0].toUpperCase() + species.slice(1);
  return PET_CLIP_STYLES.map(([slug, title]) => ({
    id: `pet-${species}-${slug}`,
    title: `${label} · ${title}`,
    description: `Public ${species} teaser clip.`,
    src: `/pet/${species}/clips/${slug}.mp4`,
    filename: `${species}-${slug}.mp4`,
    category,
    kind: "short",
    durationSeconds: 5,
    poster: `/pet/${species}/scenes/${slug}.webp`,
  }));
}

const CHRISTMAS_REELS: LibraryVideo[] = [
  {
    id: "reel-north-pole-santa",
    title: "NEW · North Pole Santa Reel",
    description:
      "13.3s 1080×1920. Higgsfield Kling 3.0 Pro silent journey: toy workshop → sleigh loading → snow globe desk → Santa sweeping. No captions.",
    src: "/assets/christmas/north-pole-santa/final/north_pole_santa_reel.mp4",
    filename: "north_pole_santa_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.37,
    poster: "/assets/christmas/north-pole-santa/posters/north_pole_santa_reel.jpg",
  },
  {
    id: "reel-global-christmas-journey",
    title: "NEW · Global Christmas journey Reel",
    description:
      "13.7s 1080×1920. Higgsfield Kling 3.0 Pro silent visual master: Lapland aurora → Alps infinity pool → humble home → The Plaza NYC → White House. No captions, no music.",
    src: "/assets/christmas/global-reel/final/global_christmas_journey_reel.mp4",
    filename: "global_christmas_journey_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.73,
    poster: "/assets/christmas/global-reel/posters/global_christmas_journey_reel.jpg",
  },
  {
    id: "reel-luxury-palace",
    title: "NEW · Luxury Christmas palace Reel",
    description:
      "14.5s 1080×1920. Higgsfield Kling 3.0 Pro silent journey: wide estate → fountain/car → open gates → grand tree hall → balcony hero. No captions.",
    src: "/assets/christmas/luxury-palace/final/luxury_christmas_palace_reel.mp4",
    filename: "luxury_christmas_palace_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.53,
    poster: "/assets/christmas/luxury-palace/posters/luxury_christmas_palace_reel.jpg",
  },
  {
    id: "reel-sep19-01",
    title: "NEW · Polar Express arrival Reel",
    description:
      "12.6s 1080×1920. Kling 3.0 Pro: locomotive 1225 → train interior → Alpine Polar Express → balcony village. Silent, no captions.",
    src: "/assets/christmas/reels/final/reel-01.mp4",
    filename: "reel-01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.6,
    poster: "/assets/christmas/reels/posters/reel-01.jpg",
  },
  {
    id: "reel-sep19-02",
    title: "NEW · Santa’s village night Reel",
    description:
      "12.4s 1080×1920. Village balcony → kids sledding → Santa’s sleigh → Santa and child watching the sky.",
    src: "/assets/christmas/reels/final/reel-02.mp4",
    filename: "reel-02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.43,
    poster: "/assets/christmas/reels/posters/reel-02.jpg",
  },
  {
    id: "reel-sep19-03",
    title: "NEW · Alps to fireside Reel",
    description:
      "12.3s 1080×1920. Sleigh over the Alps → chalet spa → cozy fireplace → Prague bakery cookies.",
    src: "/assets/christmas/reels/final/reel-03.mp4",
    filename: "reel-03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.27,
    poster: "/assets/christmas/reels/posters/reel-03.jpg",
  },
  {
    id: "reel-sep19-04",
    title: "NEW · Sleigh ride home Reel",
    description:
      "12.3s 1080×1920. Santa’s sleigh → moonlit Santa → cathedral market → Santa and child on the balcony.",
    src: "/assets/christmas/reels/final/reel-04.mp4",
    filename: "reel-04.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.27,
    poster: "/assets/christmas/reels/posters/reel-04.jpg",
  },
  {
    id: "reel-sep19-05",
    title: "NEW · Believe Christmas trailer Reel",
    description:
      "13.0s 1080×1920. Polar Express 1225 → sleigh over the village → Library train → balcony village → Santa and child. Strongest viral cut.",
    src: "/assets/christmas/reels/final/reel-05.mp4",
    filename: "reel-05.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.03,
    poster: "/assets/christmas/reels/posters/reel-05.jpg",
  },
  {
    id: "reel-christmas-cinematic-01",
    title: "NEW · Cinematic Christmas Reel",
    description:
      "15s 1080×1920. Higgsfield Kling 3.0 Pro: chalet spa → sledding village → vintage snowman → Prague bakery → NYC ice.",
    src: "/assets/christmas/reels/final/christmas_reel_cinematic_01.mp4",
    filename: "christmas_reel_cinematic_01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15,
    poster: "/assets/christmas/reels/posters/christmas_reel_cinematic_01.jpg",
  },
  {
    id: "reel-christmas-social-02",
    title: "NEW · Social-hook Christmas Reel",
    description:
      "12s 1080×1920. Higgsfield Kling 3.0 Pro. Opens on the NYC skater, then village, chalet, bakery, snowman.",
    src: "/assets/christmas/reels/final/christmas_reel_social_hook_02.mp4",
    filename: "christmas_reel_social_hook_02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.07,
    poster: "/assets/christmas/reels/posters/christmas_reel_social_hook_02.jpg",
  },
  {
    id: "reel-christmas-nostalgic-03",
    title: "NEW · Nostalgic Christmas Reel",
    description:
      "14.6s 1080×1920. Higgsfield Kling 3.0 Pro memory cut: snowman → sledding → bakery → chalet → ice.",
    src: "/assets/christmas/reels/final/christmas_reel_nostalgic_03.mp4",
    filename: "christmas_reel_nostalgic_03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.57,
    poster: "/assets/christmas/reels/posters/christmas_reel_nostalgic_03.jpg",
  },
  {
    id: "reel-cut3",
    title: "NEW · Ice · Village kids · Prague Reel",
    description:
      "15s 1080×1920. NYC ice skater → Prague Old Town → kids sledding in the village → Polar Express → Santa. Mixed with the existing 1080p Kling masters.",
    src: "/assets/christmas/instagram-reel-cut3/final_christmas_reel_cut3.mp4",
    filename: "final_christmas_reel_cut3.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15,
    poster: "/assets/christmas/instagram-reel-cut3/posters/final.jpg",
  },
  {
    id: "reel-kling-1080p-cut2",
    title: "NEW · Kling 1080p Cut 2",
    description:
      "True 1080×1920 remix, ~15.5 Mbps, 12.5s. Four clips: Santa → market → Polar Express → cozy cat. No text overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p_cut2.mp4",
    filename: "final_christmas_reel_1080p_cut2.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final_cut2.jpg",
  },
  {
    id: "reel-kling-1080p-final",
    title: "NEW · Kling 1080p Final Reel",
    description: "True 1080×1920, ~15.7 Mbps, 13.5s. Polar Express → Santa → market → chalet → cozy cat. No text overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p.mp4",
    filename: "final_christmas_reel_1080p.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final.jpg",
  },
  {
    id: "reel-kling-1080p-final-text",
    title: "NEW · Kling 1080p Final Reel (text)",
    description: "Same 1080×1920 cut with “Christmas is getting closer” overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p_text.mp4",
    filename: "final_christmas_reel_1080p_text.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final_text.jpg",
  },
  {
    id: "reel-cozy-final",
    title: "Cozy cottage Reel",
    description:
      "15s Kling cottage loop: cocoa, golden retriever, fireplace, snowy village outside the window. 1080×1920.",
    src: "/assets/christmas/cozy-reel/final_reel.mp4",
    filename: "cozy_cottage_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.13,
    poster: "/assets/christmas/cozy-reel/posters/final.jpg",
  },
  {
    id: "reel-final",
    title: "OLD · Wan 2.2 Final Reel",
    description:
      "Sep 16 test, ~13s. NYC snowy street → cottage → Rockefeller ice rink → living room → cocoa → cookies → snowy village window.",
    src: "/assets/christmas/instagram-reel/final_christmas_reel.mp4",
    filename: "final_christmas_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.4,
    poster: "/assets/christmas/instagram-reel/source/clip_01.jpg",
  },
];

const CHRISTMAS_SHORTS: LibraryVideo[] = [
  {
    id: "short-santa-01-workshop",
    title: "Santa · Toy workshop wrapping",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa tying a ribbon with elves at the workbench.",
    src: "/assets/christmas/north-pole-santa/masters/santa_01_workshop.mp4",
    filename: "santa_01_workshop.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_01_workshop.jpg",
  },
  {
    id: "short-santa-02-sleigh",
    title: "Santa · Loading the sleigh",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Aurora, reindeer, and gifts going into the sleigh.",
    src: "/assets/christmas/north-pole-santa/masters/santa_02_sleigh.mp4",
    filename: "santa_02_sleigh.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_02_sleigh.jpg",
  },
  {
    id: "short-santa-03-desk",
    title: "Santa · Snow globe desk",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa polishing a snow globe over cookies and cocoa.",
    src: "/assets/christmas/north-pole-santa/masters/santa_03_desk.mp4",
    filename: "santa_03_desk.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_03_desk.jpg",
  },
  {
    id: "short-santa-04-sweep",
    title: "Santa · Sweeping the workshop",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Closing beat: Santa sweeping snow across the floor.",
    src: "/assets/christmas/north-pole-santa/masters/santa_04_sweep.mp4",
    filename: "santa_04_sweep.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_04_sweep.jpg",
  },
  {
    id: "short-global-01-lapland",
    title: "Global · Lapland aurora igloos",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Fire pit, falling snow, moving aurora, glass lodges.",
    src: "/assets/christmas/global-reel/masters/global_01_lapland.mp4",
    filename: "global_01_lapland.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_01_lapland.jpg",
  },
  {
    id: "short-global-02-alps",
    title: "Global · Alps infinity pool",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Heated pool steam and Matterhorn hotel terrace.",
    src: "/assets/christmas/global-reel/masters/global_02_alps.mp4",
    filename: "global_02_alps.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_02_alps.jpg",
  },
  {
    id: "short-global-03-home",
    title: "Global · Humble Christmas home",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Slow walk toward a warm neighborhood cottage.",
    src: "/assets/christmas/global-reel/masters/global_03_home.mp4",
    filename: "global_03_home.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_03_home.jpg",
  },
  {
    id: "short-global-04-plaza",
    title: "Global · The Plaza New York",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Wet Fifth Avenue, carriage, and hotel canopy.",
    src: "/assets/christmas/global-reel/masters/global_04_plaza.mp4",
    filename: "global_04_plaza.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_04_plaza.jpg",
  },
  {
    id: "short-global-05-white-house",
    title: "Global · White House Christmas",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Flag, fountain, and north facade at dusk.",
    src: "/assets/christmas/global-reel/masters/global_05_white_house.mp4",
    filename: "global_05_white_house.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_05_white_house.jpg",
  },
  {
    id: "short-palace-01-establish",
    title: "Palace · Wide mansion arrival",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Slow dolly toward the snowy estate and fountain.",
    src: "/assets/christmas/luxury-palace/masters/palace_01_establish.mp4",
    filename: "palace_01_establish.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_01_establish.jpg",
  },
  {
    id: "short-palace-02-approach",
    title: "Palace · Fountain and Rolls-Royce",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Tracking toward the wreath-lit entrance.",
    src: "/assets/christmas/luxury-palace/masters/palace_02_approach.mp4",
    filename: "palace_02_approach.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_02_approach.jpg",
  },
  {
    id: "short-palace-03-gates",
    title: "Palace · Walking to the open doors",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Approach through the gates to the interior tree.",
    src: "/assets/christmas/luxury-palace/masters/palace_03_gates.mp4",
    filename: "palace_03_gates.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_03_gates.jpg",
  },
  {
    id: "short-palace-04-entrance",
    title: "Palace · Grand hall tree reveal",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Dolly through the doorway into the Christmas hall.",
    src: "/assets/christmas/luxury-palace/masters/palace_04_entrance.mp4",
    filename: "palace_04_entrance.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_04_entrance.jpg",
  },
  {
    id: "short-palace-05-hero",
    title: "Palace · Balcony hero reveal",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Elevated push toward the giant tree and open night.",
    src: "/assets/christmas/luxury-palace/masters/palace_05_hero.mp4",
    filename: "palace_05_hero.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_05_hero.jpg",
  },
  {
    id: "short-christmas-master-06",
    title: "Master · Village balcony girl",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl with teddy overlooking Santa’s village.",
    src: "/assets/christmas/reels/masters/christmas_master_06.mp4",
    filename: "christmas_master_06.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_06.jpg",
  },
  {
    id: "short-christmas-master-07",
    title: "Master · Santa and child watching sleigh",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa, child, dog, aurora, and distant sleigh.",
    src: "/assets/christmas/reels/masters/christmas_master_07.mp4",
    filename: "christmas_master_07.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_07.jpg",
  },
  {
    id: "short-christmas-master-08",
    title: "Master · Santa sleigh over alpine village",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Sleigh, reindeer, BELIEVE sign, lakeside village.",
    src: "/assets/christmas/reels/masters/christmas_master_08.mp4",
    filename: "christmas_master_08.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_08.jpg",
  },
  {
    id: "short-christmas-master-09",
    title: "Master · Polar Express interior",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl and teddy watching the castle from the train.",
    src: "/assets/christmas/reels/masters/christmas_master_09.mp4",
    filename: "christmas_master_09.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_09.jpg",
  },
  {
    id: "short-christmas-master-10",
    title: "Master · Polar Express locomotive 1225",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steam locomotive approaching a snowy station.",
    src: "/assets/christmas/reels/masters/christmas_master_10.mp4",
    filename: "christmas_master_10.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_10.jpg",
  },
  {
    id: "short-christmas-master-01",
    title: "Master · Alpine chalet hot tub",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steaming spa and Christmas chalet.",
    src: "/assets/christmas/reels/masters/christmas_master_01.mp4",
    filename: "christmas_master_01.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_01.jpg",
  },
  {
    id: "short-christmas-master-02",
    title: "Master · NYC ice skater",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Street rink and Empire State Building.",
    src: "/assets/christmas/reels/masters/christmas_master_02.mp4",
    filename: "christmas_master_02.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_02.jpg",
  },
  {
    id: "short-christmas-master-03",
    title: "Master · Village kids sledding",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Children, sleds, and a golden retriever.",
    src: "/assets/christmas/reels/masters/christmas_master_03.mp4",
    filename: "christmas_master_03.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_03.jpg",
  },
  {
    id: "short-christmas-master-04",
    title: "Master · Prague cafe cookies",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Bakery window over Charles Bridge.",
    src: "/assets/christmas/reels/masters/christmas_master_04.mp4",
    filename: "christmas_master_04.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_04.jpg",
  },
  {
    id: "short-christmas-master-05",
    title: "Master · Vintage family snowman",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Three children and a top-hat snowman.",
    src: "/assets/christmas/reels/masters/christmas_master_05.mp4",
    filename: "christmas_master_05.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_05.jpg",
  },
  {
    id: "short-ice-nyc",
    title: "NYC girl ice skating",
    description: "5s 1080×1920. The New York street-rink skater you asked for.",
    src: "/assets/christmas/instagram-reel-cut3/clip_ice_nyc.mp4",
    filename: "clip_ice_nyc.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_ice_nyc.jpg",
  },
  {
    id: "short-kids-sled",
    title: "Kids sledding in the village",
    description: "5s 1080×1920. Children on sleds and a golden retriever in a snowy Alpine village.",
    src: "/assets/christmas/instagram-reel-cut3/clip_kids_sled.mp4",
    filename: "clip_kids_sled.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_kids_sled.jpg",
  },
  {
    id: "short-prague-square",
    title: "Prague Old Town Christmas square",
    description: "5s 1080×1920. Gingerbread stall, carousel, tree, and Tyn Church.",
    src: "/assets/christmas/instagram-reel-cut3/clip_prague_square.mp4",
    filename: "clip_prague_square.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_prague_square.jpg",
  },
  {
    id: "reel-kling-01-train",
    title: "NEW · Polar Express train",
    description: "Kling v3 Pro master, 1080×1920, ~5s. White Christmas train at Alpine Valley.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_01_train_raw.mp4",
    filename: "clip_01_train_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/train.jpg",
  },
  {
    id: "reel-kling-02-santa",
    title: "NEW · Santa + sleigh + reindeer",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Moonlit Santa beside the sleigh.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_02_santa_raw.mp4",
    filename: "clip_02_santa_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/santa.jpg",
  },
  {
    id: "reel-kling-03-market",
    title: "NEW · Cathedral Christmas market",
    description: "Kling v3 Pro master, 1080×1920, ~5s. European market street and carousel.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_03_market_raw.mp4",
    filename: "clip_03_market_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/market.jpg",
  },
  {
    id: "reel-kling-04-chalet",
    title: "NEW · Luxury snowy chalet",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Twilight chalet entrance.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_04_chalet_raw.mp4",
    filename: "clip_04_chalet_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/chalet.jpg",
  },
  {
    id: "reel-kling-05-cozy",
    title: "NEW · Cozy window + snowy village",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Cat, cocoa, and a snowy village outside the window.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_05_cozy_raw.mp4",
    filename: "clip_05_cozy_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/cozy.jpg",
  },
  {
    id: "reel-01",
    title: "NYC snowy Christmas street",
    description: "Snow falling on a New York evening street with the Empire State Building in the distance.",
    src: "/assets/christmas/instagram-reel/clip_01.mp4",
    filename: "clip_01.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_01.jpg",
  },
  {
    id: "reel-06",
    title: "NYC Rockefeller ice rink",
    description:
      "Rockefeller Center at night: Christmas tree, Prometheus fountain, and people skating on the ice in New York.",
    src: "/assets/christmas/instagram-reel/clip_06.mp4",
    filename: "clip_06.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_06.jpg",
  },
  {
    id: "reel-02",
    title: "Candlelit cottage entrance",
    description: "Luxury snowy house entrance with lanterns.",
    src: "/assets/christmas/instagram-reel/clip_02.mp4",
    filename: "clip_02.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 1.2,
    poster: "/assets/christmas/instagram-reel/source/clip_02.jpg",
  },
  {
    id: "reel-03",
    title: "Cocoa by the fire",
    description: "Hot chocolate mug with fireplace and tree lights.",
    src: "/assets/christmas/instagram-reel/clip_03.mp4",
    filename: "clip_03.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_03.jpg",
  },
  {
    id: "reel-04",
    title: "Living room wonderland",
    description: "Wide cozy living room with tree, gifts, fireplace, and a snowy village outside.",
    src: "/assets/christmas/instagram-reel/clip_04.mp4",
    filename: "clip_04.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_04.jpg",
  },
  {
    id: "reel-05",
    title: "Cookie plate by the tree",
    description: "Festive cookie plate held in front of the tree.",
    src: "/assets/christmas/instagram-reel/clip_05.mp4",
    filename: "clip_05.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 1.2,
    poster: "/assets/christmas/instagram-reel/source/clip_05.jpg",
  },
  {
    id: "reel-07",
    title: "Snowy village window nook",
    description: "Cat, cocoa, and a snowy village outside the window.",
    src: "/assets/christmas/instagram-reel/clip_07.mp4",
    filename: "clip_07.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_07.jpg",
  },
  {
    id: "reel-cozy-01",
    title: "Cozy cottage · fireplace + snow",
    description: "Kling 5s. Cocoa, golden retriever, fireplace, snow falling on the village outside.",
    src: "/assets/christmas/cozy-reel/clip1.mp4",
    filename: "cozy_cottage_clip1.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip1.jpg",
  },
  {
    id: "reel-cozy-02",
    title: "Cozy cottage · cocoa + dog",
    description: "Kling 5s. Close mug of hot chocolate with a sleeping golden retriever.",
    src: "/assets/christmas/cozy-reel/clip2.mp4",
    filename: "cozy_cottage_clip2.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip2.jpg",
  },
  {
    id: "reel-cozy-03",
    title: "Cozy cottage · snowy village window",
    description: "Kling 5s. Fireplace, tree, and a snowy village through the window.",
    src: "/assets/christmas/cozy-reel/clip3.mp4",
    filename: "cozy_cottage_clip3.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip3.jpg",
  },
];

const NEW_STILL_PHOTOS: LibraryVideo[] = [
  {
    id: "photo-santa-workshop",
    title: "Photo · North Pole toy workshop",
    description: "Santa and elves wrapping gifts at the wooden workbench under workshop lights.",
    src: "/assets/christmas/north-pole-santa/source/01_workshop_wrapping_1080x1920.jpg",
    filename: "01_workshop_wrapping_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh",
    title: "Photo · Santa loading the sleigh",
    description: "Red sleigh, reindeer, aurora, and the NORTH POLE workshop doorway at night.",
    src: "/assets/christmas/north-pole-santa/source/02_sleigh_loading_1080x1920.jpg",
    filename: "02_sleigh_loading_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-desk",
    title: "Photo · Santa and the snow globe",
    description: "Warm desk with cookies, cocoa mug, checklist, and Santa polishing a snow globe.",
    src: "/assets/christmas/north-pole-santa/source/03_snow_globe_desk_1080x1920.jpg",
    filename: "03_snow_globe_desk_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sweep",
    title: "Photo · Santa sweeping the workshop",
    description: "Santa with a broom, red sack, and snowy North Pole through the open arch.",
    src: "/assets/christmas/north-pole-santa/source/04_workshop_sweeping_1080x1920.jpg",
    filename: "04_workshop_sweeping_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-lapland",
    title: "Photo · Lapland aurora igloos",
    description: "Glass igloos, fire pit, and northern lights over a frozen lake.",
    src: "/assets/christmas/global-reel/source/01_lapland_aurora_1080x1920.jpg",
    filename: "01_lapland_aurora_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-alps",
    title: "Photo · Alps infinity pool",
    description: "Bellevue Alpine Resort terrace, steaming pool, and Matterhorn sunset.",
    src: "/assets/christmas/global-reel/source/02_alps_infinity_pool_1080x1920.jpg",
    filename: "02_alps_infinity_pool_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-home",
    title: "Photo · Humble Christmas home",
    description: "Snowy cottage porch, wreath, snowman, and warm window light.",
    src: "/assets/christmas/global-reel/source/03_humble_christmas_home_1080x1920.jpg",
    filename: "03_humble_christmas_home_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-plaza",
    title: "Photo · The Plaza New York",
    description: "Christmas canopy, carriage, and wet pavement at The Plaza Hotel.",
    src: "/assets/christmas/global-reel/source/04_plaza_new_york_1080x1920.jpg",
    filename: "04_plaza_new_york_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-white-house",
    title: "Photo · White House Christmas",
    description: "North facade, flag, fountain, and THE WHITE HOUSE WASHINGTON plaque.",
    src: "/assets/christmas/global-reel/source/05_white_house_1080x1920.jpg",
    filename: "05_white_house_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-establish",
    title: "Photo · Luxury palace wide estate",
    description: "Snowy night facade, circular fountain, and black sedan used for the palace arrival short.",
    src: "/assets/christmas/luxury-palace/source/01_establish_wide_mansion_1080x1920.jpg",
    filename: "01_establish_wide_mansion_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-approach",
    title: "Photo · Palace fountain and car",
    description: "Closer entrance with wreath, spiral trees, and luxury sedan.",
    src: "/assets/christmas/luxury-palace/source/02_approach_fountain_car_1080x1920.jpg",
    filename: "02_approach_fountain_car_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-gates",
    title: "Photo · Open palace gates",
    description: "Wreath-lined gates looking through to the fountain and interior Christmas tree.",
    src: "/assets/christmas/luxury-palace/source/03_enter_open_gates_1080x1920.jpg",
    filename: "03_enter_open_gates_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-entrance",
    title: "Photo · Grand Christmas hall",
    description: "Doorway view of the enormous tree, chandelier, and marble staircase.",
    src: "/assets/christmas/luxury-palace/source/04_grand_entrance_tree_1080x1920.jpg",
    filename: "04_grand_entrance_tree_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-hero",
    title: "Photo · Palace balcony hero",
    description: "Elevated view of the Christmas palace, gift ring, chandelier, and snowy exterior.",
    src: "/assets/christmas/luxury-palace/source/05_hero_balcony_palace_1080x1920.jpg",
    filename: "05_hero_balcony_palace_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-village-balcony-girl",
    title: "Photo · Village balcony girl",
    description: "Girl with a teddy on a decorated balcony overlooking a storybook Christmas village and Santa’s sleigh.",
    src: "/assets/christmas/library-stills/01_village_balcony_girl.jpg",
    filename: "01_village_balcony_girl.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-child-aurora",
    title: "Photo · Santa and child watching sleigh",
    description: "Santa and a child pointing at a distant sleigh under the moon and aurora.",
    src: "/assets/christmas/library-stills/02_santa_child_aurora.jpg",
    filename: "02_santa_child_aurora.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh-believe",
    title: "Photo · Santa sleigh BELIEVE",
    description: "Santa driving reindeer over an alpine village with a BELIEVE plaque on the sleigh.",
    src: "/assets/christmas/library-stills/03_santa_sleigh_believe.jpg",
    filename: "03_santa_sleigh_believe.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-polar-express-interior",
    title: "Photo · Polar Express interior",
    description: "Child and teddy looking from a Polar Express carriage toward a lit castle and viaduct.",
    src: "/assets/christmas/library-stills/04_polar_express_interior.jpg",
    filename: "04_polar_express_interior.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-polar-express-station",
    title: "Photo · Polar Express locomotive 1225",
    description: "Black steam locomotive 1225 at a snowy station, child with a lantern on the platform.",
    src: "/assets/christmas/library-stills/05_polar_express_station.jpg",
    filename: "05_polar_express_station.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-nyc-ice-girl",
    title: "Photo · NYC girl ice skating",
    description:
      "New York Christmas night. Young woman skating on a street rink with the Empire State Building behind her.",
    src: "/assets/christmas/library-stills/nyc_girl_ice_skating.jpg",
    filename: "nyc_girl_ice_skating.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-village-kids-sled",
    title: "Photo · Kids sledding in the village",
    description: "Alpine village at sunset. Children on sleds, a golden retriever, snowy houses, and a lake.",
    src: "/assets/christmas/library-stills/village_kids_sledding.jpg",
    filename: "village_kids_sledding.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-carousel",
    title: "Photo · Prague Old Town carousel",
    description: "Prague Christmas market square with Tyn Church, tree, carousel, and gingerbread.",
    src: "/assets/christmas/library-stills/prague_old_town_carousel_market.jpg",
    filename: "prague_old_town_carousel_market.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-balcony",
    title: "Photo · Prague balcony dessert table",
    description: "Christmas cookies and cocoa on a balcony overlooking Prague at sunset.",
    src: "/assets/christmas/library-stills/prague_balcony_christmas_spread.jpg",
    filename: "prague_balcony_christmas_spread.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-cafe",
    title: "Photo · Prague cafe street",
    description: "Cookies, cocoa, and a snowy Prague lane toward Tyn Church.",
    src: "/assets/christmas/library-stills/prague_cafe_street_cookies.jpg",
    filename: "prague_cafe_street_cookies.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-gingerbread",
    title: "Photo · Prague gingerbread stall",
    description: "Market stall of gingerbread and cakes with Prague towers behind.",
    src: "/assets/christmas/library-stills/prague_market_gingerbread_stall.jpg",
    filename: "prague_market_gingerbread_stall.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-bakery",
    title: "Photo · Prague bakery window",
    description: "Cozy bakery table of cookies and cocoa with Charles Bridge outside.",
    src: "/assets/christmas/library-stills/prague_bakery_window.jpg",
    filename: "prague_bakery_window.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-couple",
    title: "Photo · Prague market couple",
    description: "Snowy Prague market with carousel, tree, and a couple walking with cocoa.",
    src: "/assets/christmas/library-stills/prague_market_couple_carousel.jpg",
    filename: "prague_market_couple_carousel.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-alpine-cocoa-bridge",
    title: "Photo · Alpine village cocoa",
    description: "Cocoa on a snowy balcony overlooking a lit Alpine village and stone bridge.",
    src: "/assets/christmas/library-stills/alpine_village_cocoa_bridge.jpg",
    filename: "alpine_village_cocoa_bridge.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-chalet-hot-tub",
    title: "Photo · Chalet hot tub",
    description: "Luxury snowy chalet with Christmas tree inside and a steaming outdoor spa.",
    src: "/assets/christmas/library-stills/alpine_chalet_hot_tub.jpg",
    filename: "alpine_chalet_hot_tub.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-vintage-snowman",
    title: "Photo · Vintage family snowman",
    description: "Three children building a top-hat snowman in front of a wreath-lit house and vintage cars.",
    src: "/assets/christmas/library-stills/vintage_family_snowman.jpg",
    filename: "vintage_family_snowman.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-luxury-train",
    title: "Photo · Luxury Christmas train",
    description: "Dark Orient-Express style train at an Alpine station at dusk.",
    src: "/assets/christmas/library-stills/alpine_luxury_christmas_train.jpg",
    filename: "alpine_luxury_christmas_train.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-village-square",
    title: "Photo · Santa in the village square",
    description: "Storybook village with a giant tree, Santa’s sleigh, snowman, and a stream.",
    src: "/assets/christmas/library-stills/santa_village_square.jpg",
    filename: "santa_village_square.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh-ride",
    title: "Photo · Santa sleigh ride",
    description: "Santa driving reindeer through snowy pines toward a lakeside village.",
    src: "/assets/christmas/library-stills/santa_reindeer_sleigh_ride.jpg",
    filename: "santa_reindeer_sleigh_ride.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-swiss-sleigh",
    title: "Photo · Swiss hotel horse sleigh",
    description: "Grand Swiss hotel at dusk with a horse-drawn sleigh and frozen lake.",
    src: "/assets/christmas/library-stills/swiss_hotel_horse_sleigh.jpg",
    filename: "swiss_hotel_horse_sleigh.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-matterhorn-pool",
    title: "Photo · Matterhorn infinity pool",
    description: "Luxury chalet terrace and steaming pool facing the Matterhorn at sunset.",
    src: "/assets/christmas/library-stills/matterhorn_infinity_pool.jpg",
    filename: "matterhorn_infinity_pool.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
];

const CHRISTMAS_PHOTOS: LibraryVideo[] = [
  ...NEW_STILL_PHOTOS,
  {
    id: "photo-kling-train",
    title: "Photo · Polar Express train",
    description: "Source still for the Kling Polar Express short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/alpine_valley_polar_express_at_christmas.jpg",
    filename: "alpine_valley_polar_express_at_christmas.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-santa",
    title: "Photo · Santa + sleigh",
    description: "Source still for the Kling Santa short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/santa_s_moonlit_christmas_sleigh_ride.jpg",
    filename: "santa_s_moonlit_christmas_sleigh_ride.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-market",
    title: "Photo · Cathedral Christmas market",
    description: "Source still for the Kling market short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/snowy_christmas_market_by_the_cathedral.jpg",
    filename: "snowy_christmas_market_by_the_cathedral.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-chalet",
    title: "Photo · Luxury snowy chalet",
    description: "Source still for the Kling chalet short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/snowy_christmas_chalet_at_twilight.jpg",
    filename: "snowy_christmas_chalet_at_twilight.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-village",
    title: "Photo · Snowy village window",
    description: "Source still for the Kling cozy short. Cat, cocoa, and a snowy village outside.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/cozy_christmas_reading_nook_by_snowy_village.jpg",
    filename: "cozy_christmas_reading_nook_by_snowy_village.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-nyc-street",
    title: "Photo · NYC snowy Christmas street",
    description: "Source still for the New York snow street short.",
    src: "/assets/christmas/instagram-reel/source/clip_01.jpg",
    filename: "nyc_snowy_christmas_street.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-ice-rink",
    title: "Photo · NYC Rockefeller ice rink",
    description: "Source still for the Rockefeller ice-skating short — tree, rink, and skaters in New York.",
    src: "/assets/christmas/instagram-reel/source/clip_06.jpg",
    filename: "nyc_rockefeller_ice_rink.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cottage",
    title: "Photo · Candlelit cottage",
    description: "Source still for the cottage-entrance short.",
    src: "/assets/christmas/instagram-reel/source/clip_02.jpg",
    filename: "candlelit_christmas_cottage.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cocoa",
    title: "Photo · Cocoa by the fire",
    description: "Source still for the cocoa short.",
    src: "/assets/christmas/instagram-reel/source/clip_03.jpg",
    filename: "cozy_christmas_cocoa.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-living-room",
    title: "Photo · Living room wonderland",
    description: "Source still for the living-room short.",
    src: "/assets/christmas/instagram-reel/source/clip_04.jpg",
    filename: "cozy_christmas_living_room.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cookies",
    title: "Photo · Cookie plate",
    description: "Source still for the cookie-plate short.",
    src: "/assets/christmas/instagram-reel/source/clip_05.jpg",
    filename: "cozy_christmas_cookie_plate.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-village",
    title: "Photo · Snowy village window nook",
    description: "Source still for the village-window short.",
    src: "/assets/christmas/instagram-reel/source/clip_07.jpg",
    filename: "snowy_village_window_nook.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
];

const CHRISTMAS_MARKETING: LibraryVideo[] = [
  {
    id: "cabin-hero",
    title: "Cabin hero loop",
    description: "Desktop landing loop.",
    src: "/christmas/cabin-hero-loop.mp4",
    filename: "cabin-hero-loop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "cabin-hero-720",
    title: "Cabin hero loop 720p",
    description: "Mobile landing loop.",
    src: "/christmas/cabin-hero-loop-720.mp4",
    filename: "cabin-hero-loop-720.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "advent-loop",
    title: "Advent calendar loop",
    description: "Advent product loop.",
    src: "/christmas/advent/advent-loop.mp4",
    filename: "advent-loop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "advent-loop-540",
    title: "Advent calendar loop 540p",
    description: "Smaller Advent loop.",
    src: "/christmas/advent/advent-loop-540.mp4",
    filename: "advent-loop-540.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-scene-desktop",
    title: "Gift tree · desktop",
    description: "Gift-tree landing scene.",
    src: "/christmas/gifts/scene-desktop.mp4",
    filename: "gift-tree-scene-desktop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-scene-mobile",
    title: "Gift tree · mobile",
    description: "Gift-tree landing scene (mobile crop).",
    src: "/christmas/gifts/scene-mobile.mp4",
    filename: "gift-tree-scene-mobile.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-open",
    title: "Gift open",
    description: "Gift-open motion for the tree product.",
    src: "/christmas/gifts/gift-open.mp4",
    filename: "gift-open.mp4",
    category: "christmas_marketing",
    kind: "short",
  },
];

export const LIBRARY_VIDEOS: LibraryVideo[] = [
  ...CHRISTMAS_REELS,
  ...CHRISTMAS_SHORTS,
  ...CHRISTMAS_PHOTOS,
  ...CHRISTMAS_MARKETING,
  ...petClips("dog", "pet_dog"),
  ...petClips("cat", "pet_cat"),
  ...petClips("other", "pet_other"),
];

export function librarySrcPath(src: string): string {
  if (src.includes("/api/clip-factory")) return src;
  return src.split("?")[0];
}

export function isLibraryPhoto(item: LibraryVideo): boolean {
  return item.kind === "photo" || /\.(jpe?g|png|webp)$/i.test(item.filename);
}

export function videosForCategory(
  categoryId: LibraryCategoryId | "all",
  videos: LibraryVideo[] = LIBRARY_VIDEOS,
): LibraryVideo[] {
  if (categoryId === "all") return videos;
  return videos.filter((video) => video.category === categoryId);
}

export function searchLibraryCatalog(
  videos: LibraryVideo[],
  query: string,
  categoryId: LibraryCategoryId | "all",
  kind: LibraryKind | "all" = "all",
): LibraryVideo[] {
  const needle = query.trim().toLowerCase();
  let list = videosForCategory(categoryId, videos);
  if (kind !== "all") list = list.filter((item) => item.kind === kind);
  if (!needle) return list;
  return list.filter((video) =>
    [video.title, video.description, video.filename, video.id].join(" ").toLowerCase().includes(needle),
  );
}

export function searchLibraryVideos(
  query: string,
  categoryId: LibraryCategoryId | "all",
  kind: LibraryKind | "all" = "all",
): LibraryVideo[] {
  return searchLibraryCatalog(LIBRARY_VIDEOS, query, categoryId, kind);
}

export function countChristmasKind(kind: LibraryKind): number {
  return LIBRARY_VIDEOS.filter((item) => item.category === "christmas_reels" && item.kind === kind).length;
}
