export type LibraryCategoryId =
  | "clip_factory"
  | "long_form"
  | "christmas_reels"
  | "christmas_marketing"
  | "pet_dog"
  | "pet_cat"
  | "pet_other";

export type LibraryKind = "reel" | "short" | "photo" | "long_form";

export type LibraryVideo = {
  id: string;
  title: string;
  description: string;
  src: string;
  filename: string;
  category: LibraryCategoryId;
  kind: LibraryKind;
  /** Known length in seconds. Used before the file metadata loads. */
  durationSeconds?: number;
  /** Still image shown until the first video frame paints (iOS often stays black otherwise). */
  poster?: string;
  width?: number;
  height?: number;
  tags?: string[];
  model?: string;
  jobId?: string;
  costUsd?: number;
  sourceImage?: string;
  createdAt?: string;
  fileSizeBytes?: number;
  clipsUsed?: string[];
};

export type LibraryCategory = {
  id: LibraryCategoryId;
  label: string;
  description: string;
};

export type LibraryKindFilter = {
  id: LibraryKind;
  label: string;
  description: string;
};

export const LIBRARY_CATEGORIES: LibraryCategory[] = [
  {
    id: "clip_factory",
    label: "Clip Factory",
    description: "Vertical clips generated from long-form video, with captions and provenance.",
  },
  {
    id: "long_form",
    label: "Long-form",
    description: "YouTube-length ambience productions from Long-Form Studio, with rights manifests.",
  },
  {
    id: "christmas_reels",
    label: "Christmas Reels",
    description:
      "Assembled Reels, short clips, and the stills used to generate them. Open Reels, Shorts, or Photos.",
  },
  {
    id: "christmas_marketing",
    label: "Christmas marketing",
    description: "Landing, Advent, and gift-tree loops used on the public site.",
  },
  {
    id: "pet_dog",
    label: "Pet · Dog",
    description: "Public dog teaser clips.",
  },
  {
    id: "pet_cat",
    label: "Pet · Cat",
    description: "Public cat teaser clips.",
  },
  {
    id: "pet_other",
    label: "Pet · Other",
    description: "Public other-pet teaser clips.",
  },
];

const CINEMATIC_SOURCE_TAGS = [
  "christmas",
  "reel-source",
  "cinematic",
  "viral",
  "recognizable-scene",
  "AI-generated",
];

const CINEMATIC_REEL_TAGS = [
  "christmas",
  "reel",
  "ready-to-post",
  "instagram",
  "tiktok",
  "facebook",
  "youtube-shorts",
  "viral-candidate",
];

const NPJ_FINAL_REEL_TAGS = [
  "christmas",
  "final-reel",
  "ready-to-post",
  "cinematic",
  "instagram",
  "tiktok",
  "facebook",
  "youtube-shorts",
];

export const CHRISTMAS_LIBRARY_KINDS: LibraryKindFilter[] = [
  {
    id: "reel",
    label: "Reels",
    description: "Assembled vertical Reels, about 10–15 seconds.",
  },
  {
    id: "short",
    label: "Shorts",
    description: "The 3–5s clips that make up the Reels — including NYC ice and snowy village.",
  },
  {
    id: "photo",
    label: "Photos",
    description: "Source stills used to generate the Reels and Shorts.",
  },
];

const PET_CLIP_STYLES = [
  ["astronaut", "Astronaut"],
  ["beach-vacation", "Beach vacation"],
  ["christmas-portrait", "Christmas portrait"],
  ["cinema-boss", "Cinema boss"],
  ["formula-racer", "Formula racer"],
  ["head-chef", "Head chef"],
  ["luxury-ceo", "Luxury CEO"],
  ["newspaper", "Newspaper"],
  ["original-superhero", "Superhero"],
  ["renaissance", "Renaissance"],
  ["royal-portrait", "Royal portrait"],
  ["spa-bathtub", "Spa bathtub"],
] as const;

function petClips(species: "dog" | "cat" | "other", category: LibraryCategoryId): LibraryVideo[] {
  const label = species === "other" ? "Other pet" : species[0].toUpperCase() + species.slice(1);
  return PET_CLIP_STYLES.map(([slug, title]) => ({
    id: `pet-${species}-${slug}`,
    title: `${label} · ${title}`,
    description: `Public ${species} teaser clip.`,
    src: `/pet/${species}/clips/${slug}.mp4`,
    filename: `${species}-${slug}.mp4`,
    category,
    kind: "short",
    durationSeconds: 5,
    poster: `/pet/${species}/scenes/${slug}.webp`,
  }));
}

const CHRISTMAS_REELS: LibraryVideo[] = [
  {
    id: "reel-lauren-overwhelm-master",
    title: "Lauren — Christmas Overwhelm Story 01 · MASTER",
    description:
      "31.9s 1080×1920. Voice-over corrected master (active). Buyer-persona story: love Christmas → overwhelm → discovery → relief. Warm slower narration + captions + original music. Visual stream reused; no video regeneration. Open My Christmas Planner CTA.",
    src: "/assets/christmas/lauren-overwhelm/final/lauren_overwhelm_master.mp4",
    filename: "lauren_overwhelm_master.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 31.92,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_overwhelm_master.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 22214972,
    createdAt: "2026-09-21T19:45:00Z",
    tags: [...CINEMATIC_REEL_TAGS, "planner", "lauren", "voiceover", "captions", "voiceover-corrected"],
    model: "openai gpt-4o-mini-tts coral + kling visual (reused)",
    costUsd: 1.83,
    clipsUsed: [
      "short-lauren-01-intro",
      "short-lauren-02-phone",
      "short-lauren-03-receipt",
      "short-lauren-04-peak",
      "short-lauren-05-discovery",
      "short-lauren-06-payoff",
    ],
  },
  {
    id: "reel-lauren-overwhelm-clean",
    title: "Lauren — Christmas Overwhelm Story 01 · CLEAN",
    description:
      "31.9s 1080×1920. Voice-over corrected CLEAN (no captions). Same slower human narration + music as the active master. Visual stream reused.",
    src: "/assets/christmas/lauren-overwhelm/final/lauren_overwhelm_clean.mp4",
    filename: "lauren_overwhelm_clean.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 31.92,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_overwhelm_clean.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 22738992,
    createdAt: "2026-09-21T19:45:00Z",
    tags: [...CINEMATIC_REEL_TAGS, "planner", "lauren", "voiceover", "no-captions", "voiceover-corrected"],
    model: "openai gpt-4o-mini-tts coral + kling visual (reused)",
    costUsd: 1.83,
    clipsUsed: [
      "short-lauren-01-intro",
      "short-lauren-02-phone",
      "short-lauren-03-receipt",
      "short-lauren-04-peak",
      "short-lauren-05-discovery",
      "short-lauren-06-payoff",
    ],
  },
  {
    id: "reel-lauren-overwhelm-visual",
    title: "Lauren — Christmas Overwhelm Story 01 · VISUAL",
    description:
      "31.9s 1080×1920 silent visual master for reuse. No voiceover, no captions.",
    src: "/assets/christmas/lauren-overwhelm/final/lauren_overwhelm_visual.mp4",
    filename: "lauren_overwhelm_visual.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 31.92,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_overwhelm_visual.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 23178331,
    createdAt: "2026-09-21T17:58:00Z",
    tags: [...CINEMATIC_REEL_TAGS, "planner", "lauren", "silent"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "short-lauren-01-intro",
      "short-lauren-02-phone",
      "short-lauren-03-receipt",
      "short-lauren-04-peak",
      "short-lauren-05-discovery",
      "short-lauren-06-payoff",
    ],
  },
  {
    id: "reel-np-journey-01",
    title: "The Journey — Magical Train to the North Pole",
    description:
      "36.8s 1080×1920 silent long Reel. Spectacular viaduct train → carriage window → aurora → Polar Express → station → Santa Village → workshop → sleigh → Plaza payoff. Tags: christmas, final-reel, ready-to-post, long-reel, the-journey.",
    src: "/assets/christmas/np-journey/final/the_journey_north_pole_reel_01.mp4",
    filename: "the_journey_north_pole_reel_01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 36.83,
    poster: "/assets/christmas/np-journey/posters/reel-np-journey-01.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 73428338,
    createdAt: "2026-09-20T21:05:00Z",
    tags: [...NPJ_FINAL_REEL_TAGS, "long-reel", "the-journey", "train", "north-pole"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "npj_04_viaduct_wide",
      "npj_01_train_window",
      "npj_03_aurora_window",
      "short-cinematic-polar-express",
      "npj_02_station",
      "npj_05_village_arrival",
      "npj_06_workshop_street",
      "npj_07_workshop_list",
      "npj_08_wrapping",
      "short-santa-02-sleigh",
      "npj_09_window_sleigh",
      "npj_11_plaza",
    ],
  },
  {
    id: "reel-follow-santa-02",
    title: "Follow Santa — Christmas Eve",
    description:
      "35.8s 1080×1920 silent long Reel. Workshop list → elves wrapping → reindeer street → sleigh departure → London → Rockefeller → Plaza → Home Alone house → child watching Santa. Tags: christmas, final-reel, ready-to-post, long-reel, follow-santa.",
    src: "/assets/christmas/np-journey/final/follow_santa_reel_02.mp4",
    filename: "follow_santa_reel_02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 35.83,
    poster: "/assets/christmas/np-journey/posters/reel-follow-santa-02.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 69595394,
    createdAt: "2026-09-20T21:06:00Z",
    tags: [...NPJ_FINAL_REEL_TAGS, "long-reel", "follow-santa", "santa", "sleigh"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "npj_07_workshop_list",
      "short-santa-01-workshop",
      "npj_08_wrapping",
      "npj_06_workshop_street",
      "short-santa-02-sleigh",
      "short-cinematic-santa-london",
      "short-christmas-master-08",
      "short-cinematic-rockefeller",
      "npj_11_plaza",
      "short-cinematic-home-alone-house",
      "npj_09_window_sleigh",
      "reel-cozy-01",
    ],
  },
  {
    id: "reel-magical-night-03",
    title: "One Magical Christmas Night",
    description:
      "34.3s 1080×1920 silent long Reel. Village snowman evening → home → Lapland aurora → train journey → North Pole → Santa over London → Alps → Plaza → child watching sleigh. Tags: christmas, final-reel, ready-to-post, long-reel, magical-christmas-night.",
    src: "/assets/christmas/np-journey/final/one_magical_christmas_night_reel_03.mp4",
    filename: "one_magical_christmas_night_reel_03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 34.27,
    poster: "/assets/christmas/np-journey/posters/reel-magical-night-03.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 67544930,
    createdAt: "2026-09-20T21:07:00Z",
    tags: [...NPJ_FINAL_REEL_TAGS, "long-reel", "magical-christmas-night", "cozy"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "npj_10_snowman",
      "short-global-03-home",
      "short-global-01-lapland",
      "npj_04_viaduct_wide",
      "npj_01_train_window",
      "npj_05_village_arrival",
      "short-cinematic-workshop",
      "short-cinematic-santa-london",
      "short-global-02-alps",
      "short-global-04-plaza",
      "short-christmas-master-07",
      "npj_09_window_sleigh",
    ],
  },
  {
    id: "reel-viral-short-04",
    title: "Viral Cut — Where is this train going?",
    description:
      "14.6s 1080×1920 silent short Reel. Loop-friendly WOW cut: aurora viaduct → train window mountains → North Pole arrival → Santa over London → child watching sleigh → viaduct. Tags: christmas, final-reel, ready-to-post, short-reel, viral-train-hook.",
    src: "/assets/christmas/np-journey/final/viral_train_north_pole_short_04.mp4",
    filename: "viral_train_north_pole_short_04.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.57,
    poster: "/assets/christmas/np-journey/posters/reel-viral-short-04.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 28961900,
    createdAt: "2026-09-20T21:08:00Z",
    tags: [...NPJ_FINAL_REEL_TAGS, "short-reel", "viral-train-hook", "train"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "npj_04_viaduct_wide",
      "npj_03_aurora_window",
      "npj_05_village_arrival",
      "short-cinematic-santa-london",
      "npj_09_window_sleigh",
    ],
  },
  {
    id: "reel-viral-night-05",
    title: "Viral Cut — The most magical Christmas night",
    description:
      "14.3s 1080×1920 silent short Reel. Snowman square → workshop street → wrapping → sleigh load → Plaza NYC → child watching Santa. Tags: christmas, final-reel, ready-to-post, short-reel, most-magical-night.",
    src: "/assets/christmas/np-journey/final/viral_most_magical_night_short_05.mp4",
    filename: "viral_most_magical_night_short_05.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.33,
    poster: "/assets/christmas/np-journey/posters/reel-viral-night-05.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 28239557,
    createdAt: "2026-09-20T21:09:00Z",
    tags: [...NPJ_FINAL_REEL_TAGS, "short-reel", "most-magical-night", "cozy"],
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "npj_10_snowman",
      "npj_06_workshop_street",
      "npj_08_wrapping",
      "short-santa-02-sleigh",
      "npj_11_plaza",
      "npj_09_window_sleigh",
    ],
  },
  {
    id: "reel-christmas-movie-nostalgia-01",
    title: "Christmas Movie Nostalgia — Reel 01",
    description:
      "12–15s 1080×1920 silent Reel. Home Alone-style house → Polar Express → Rockefeller → Plaza → cozy fireside → Santa and child. Tags: christmas, reel, ready-to-post, instagram, tiktok, facebook, youtube-shorts, viral-candidate.",
    src: "/assets/christmas/cinematic-sep20/final/christmas_movie_nostalgia_reel_01.mp4",
    filename: "christmas_movie_nostalgia_reel_01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.3,
    poster: "/assets/christmas/cinematic-sep20/posters/reel-nostalgia-01.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 28976501,
    createdAt: "2026-09-20T09:32:00Z",
    tags: CINEMATIC_REEL_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "cinematic_03_home_alone_house",
      "cinematic_01_polar_express",
      "cinematic_04_rockefeller",
      "cinematic_05_plaza_hotel",
      "reel-cozy-01",
      "short-christmas-master-07",
    ],
  },
  {
    id: "reel-christmas-magic-02",
    title: "Christmas Magic — Reel 02",
    description:
      "12–15s 1080×1920 silent Reel. Santa over London → Polar Express → North Pole workshop → village balcony → Coca-Cola truck → Rockefeller tree. Tags: christmas, reel, ready-to-post, instagram, tiktok, facebook, youtube-shorts, viral-candidate.",
    src: "/assets/christmas/cinematic-sep20/final/christmas_magic_reel_02.mp4",
    filename: "christmas_magic_reel_02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.4,
    poster: "/assets/christmas/cinematic-sep20/posters/reel-magic-02.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 26366775,
    createdAt: "2026-09-20T09:33:00Z",
    tags: CINEMATIC_REEL_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "cinematic_06_santa_london",
      "cinematic_01_polar_express",
      "cinematic_07_workshop",
      "short-christmas-master-06",
      "cinematic_02_coca_cola_truck",
      "cinematic_04_rockefeller",
    ],
  },
  {
    id: "reel-perfect-christmas-03",
    title: "The Perfect Christmas — Reel 03",
    description:
      "12–15s 1080×1920 silent Reel. Loop-friendly cozy cut: house → fireplace → Prague bakery → Alps terrace → humble home → house. Tags: christmas, reel, ready-to-post, instagram, tiktok, facebook, youtube-shorts, viral-candidate.",
    src: "/assets/christmas/cinematic-sep20/final/the_perfect_christmas_reel_03.mp4",
    filename: "the_perfect_christmas_reel_03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.33,
    poster: "/assets/christmas/cinematic-sep20/posters/reel-perfect-03.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 25219391,
    createdAt: "2026-09-20T09:34:00Z",
    tags: CINEMATIC_REEL_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    clipsUsed: [
      "cinematic_03_home_alone_house",
      "reel-cozy-01",
      "short-christmas-master-04",
      "short-global-02-alps",
      "short-global-03-home",
    ],
  },
  {
    id: "reel-north-pole-santa",
    title: "NEW · North Pole Santa Reel",
    description:
      "13.3s 1080×1920. Higgsfield Kling 3.0 Pro silent journey: toy workshop → sleigh loading → snow globe desk → Santa sweeping. No captions.",
    src: "/assets/christmas/north-pole-santa/final/north_pole_santa_reel.mp4",
    filename: "north_pole_santa_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.37,
    poster: "/assets/christmas/north-pole-santa/posters/north_pole_santa_reel.jpg",
  },
  {
    id: "reel-global-christmas-journey",
    title: "NEW · Global Christmas journey Reel",
    description:
      "13.7s 1080×1920. Higgsfield Kling 3.0 Pro silent visual master: Lapland aurora → Alps infinity pool → humble home → The Plaza NYC → White House. No captions, no music.",
    src: "/assets/christmas/global-reel/final/global_christmas_journey_reel.mp4",
    filename: "global_christmas_journey_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.73,
    poster: "/assets/christmas/global-reel/posters/global_christmas_journey_reel.jpg",
  },
  {
    id: "reel-luxury-palace",
    title: "NEW · Luxury Christmas palace Reel",
    description:
      "14.5s 1080×1920. Higgsfield Kling 3.0 Pro silent journey: wide estate → fountain/car → open gates → grand tree hall → balcony hero. No captions.",
    src: "/assets/christmas/luxury-palace/final/luxury_christmas_palace_reel.mp4",
    filename: "luxury_christmas_palace_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.53,
    poster: "/assets/christmas/luxury-palace/posters/luxury_christmas_palace_reel.jpg",
  },
  {
    id: "reel-sep19-01",
    title: "NEW · Polar Express arrival Reel",
    description:
      "12.6s 1080×1920. Kling 3.0 Pro: locomotive 1225 → train interior → Alpine Polar Express → balcony village. Silent, no captions.",
    src: "/assets/christmas/reels/final/reel-01.mp4",
    filename: "reel-01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.6,
    poster: "/assets/christmas/reels/posters/reel-01.jpg",
  },
  {
    id: "reel-sep19-02",
    title: "NEW · Santa’s village night Reel",
    description:
      "12.4s 1080×1920. Village balcony → kids sledding → Santa’s sleigh → Santa and child watching the sky.",
    src: "/assets/christmas/reels/final/reel-02.mp4",
    filename: "reel-02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.43,
    poster: "/assets/christmas/reels/posters/reel-02.jpg",
  },
  {
    id: "reel-sep19-03",
    title: "NEW · Alps to fireside Reel",
    description:
      "12.3s 1080×1920. Sleigh over the Alps → chalet spa → cozy fireplace → Prague bakery cookies.",
    src: "/assets/christmas/reels/final/reel-03.mp4",
    filename: "reel-03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.27,
    poster: "/assets/christmas/reels/posters/reel-03.jpg",
  },
  {
    id: "reel-sep19-04",
    title: "NEW · Sleigh ride home Reel",
    description:
      "12.3s 1080×1920. Santa’s sleigh → moonlit Santa → cathedral market → Santa and child on the balcony.",
    src: "/assets/christmas/reels/final/reel-04.mp4",
    filename: "reel-04.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.27,
    poster: "/assets/christmas/reels/posters/reel-04.jpg",
  },
  {
    id: "reel-sep19-05",
    title: "NEW · Believe Christmas trailer Reel",
    description:
      "13.0s 1080×1920. Polar Express 1225 → sleigh over the village → Library train → balcony village → Santa and child. Strongest viral cut.",
    src: "/assets/christmas/reels/final/reel-05.mp4",
    filename: "reel-05.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.03,
    poster: "/assets/christmas/reels/posters/reel-05.jpg",
  },
  {
    id: "reel-christmas-cinematic-01",
    title: "NEW · Cinematic Christmas Reel",
    description:
      "15s 1080×1920. Higgsfield Kling 3.0 Pro: chalet spa → sledding village → vintage snowman → Prague bakery → NYC ice.",
    src: "/assets/christmas/reels/final/christmas_reel_cinematic_01.mp4",
    filename: "christmas_reel_cinematic_01.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15,
    poster: "/assets/christmas/reels/posters/christmas_reel_cinematic_01.jpg",
  },
  {
    id: "reel-christmas-social-02",
    title: "NEW · Social-hook Christmas Reel",
    description:
      "12s 1080×1920. Higgsfield Kling 3.0 Pro. Opens on the NYC skater, then village, chalet, bakery, snowman.",
    src: "/assets/christmas/reels/final/christmas_reel_social_hook_02.mp4",
    filename: "christmas_reel_social_hook_02.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.07,
    poster: "/assets/christmas/reels/posters/christmas_reel_social_hook_02.jpg",
  },
  {
    id: "reel-christmas-nostalgic-03",
    title: "NEW · Nostalgic Christmas Reel",
    description:
      "14.6s 1080×1920. Higgsfield Kling 3.0 Pro memory cut: snowman → sledding → bakery → chalet → ice.",
    src: "/assets/christmas/reels/final/christmas_reel_nostalgic_03.mp4",
    filename: "christmas_reel_nostalgic_03.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 14.57,
    poster: "/assets/christmas/reels/posters/christmas_reel_nostalgic_03.jpg",
  },
  {
    id: "reel-cut3",
    title: "NEW · Ice · Village kids · Prague Reel",
    description:
      "15s 1080×1920. NYC ice skater → Prague Old Town → kids sledding in the village → Polar Express → Santa. Mixed with the existing 1080p Kling masters.",
    src: "/assets/christmas/instagram-reel-cut3/final_christmas_reel_cut3.mp4",
    filename: "final_christmas_reel_cut3.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15,
    poster: "/assets/christmas/instagram-reel-cut3/posters/final.jpg",
  },
  {
    id: "reel-kling-1080p-cut2",
    title: "NEW · Kling 1080p Cut 2",
    description:
      "True 1080×1920 remix, ~15.5 Mbps, 12.5s. Four clips: Santa → market → Polar Express → cozy cat. No text overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p_cut2.mp4",
    filename: "final_christmas_reel_1080p_cut2.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 12.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final_cut2.jpg",
  },
  {
    id: "reel-kling-1080p-final",
    title: "NEW · Kling 1080p Final Reel",
    description: "True 1080×1920, ~15.7 Mbps, 13.5s. Polar Express → Santa → market → chalet → cozy cat. No text overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p.mp4",
    filename: "final_christmas_reel_1080p.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final.jpg",
  },
  {
    id: "reel-kling-1080p-final-text",
    title: "NEW · Kling 1080p Final Reel (text)",
    description: "Same 1080×1920 cut with “Christmas is getting closer” overlay.",
    src: "/assets/christmas/instagram-reel-kling-1080p/final_christmas_reel_1080p_text.mp4",
    filename: "final_christmas_reel_1080p_text.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.5,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/final_text.jpg",
  },
  {
    id: "reel-cozy-final",
    title: "Cozy cottage Reel",
    description:
      "15s Kling cottage loop: cocoa, golden retriever, fireplace, snowy village outside the window. 1080×1920.",
    src: "/assets/christmas/cozy-reel/final_reel.mp4",
    filename: "cozy_cottage_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.13,
    poster: "/assets/christmas/cozy-reel/posters/final.jpg",
  },
  {
    id: "reel-final",
    title: "OLD · Wan 2.2 Final Reel",
    description:
      "Sep 16 test, ~13s. NYC snowy street → cottage → Rockefeller ice rink → living room → cocoa → cookies → snowy village window.",
    src: "/assets/christmas/instagram-reel/final_christmas_reel.mp4",
    filename: "final_christmas_reel.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 13.4,
    poster: "/assets/christmas/instagram-reel/source/clip_01.jpg",
  },
];

const CHRISTMAS_SHORTS: LibraryVideo[] = [
  {
    id: "short-lauren-01-intro",
    title: "Short · Lauren intro kitchen worry",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren leans on the kitchen island, mildly overloaded. Tags: christmas, lauren, planner, reel-source.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_01_intro.mp4",
    filename: "lauren_01_intro.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_01_intro.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_01_intro_kitchen_worried.jpg",
    jobId: "708c1d74-a04d-46f3-80c9-4498d948e536",
    costUsd: 0.28,
    fileSizeBytes: 11852645,
    createdAt: "2026-09-21T17:52:00Z",
  },
  {
    id: "short-lauren-02-phone",
    title: "Short · Lauren mental load phone",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren checks her phone as Christmas prep continues. Tags: christmas, lauren, planner, reel-source.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_02_phone.mp4",
    filename: "lauren_02_phone.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_02_phone.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_02_phone_mental_load.jpg",
    jobId: "96b144fb-be98-4185-9c3c-f407866df625",
    costUsd: 0.28,
    fileSizeBytes: 10607804,
    createdAt: "2026-09-21T17:53:00Z",
  },
  {
    id: "short-lauren-03-receipt",
    title: "Short · Lauren receipt and tasks",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren studies a long receipt beside her Christmas to-do list.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_03_receipt.mp4",
    filename: "lauren_03_receipt.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_03_receipt.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_03_receipt_tasks.jpg",
    jobId: "13818a98-0f53-4daa-8d4f-81df9f384b1f",
    costUsd: 0.28,
    fileSizeBytes: 11102708,
    createdAt: "2026-09-21T17:53:00Z",
  },
  {
    id: "short-lauren-04-peak",
    title: "Short · Lauren peak stress",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren stands in wrapping chaos with both hands in her hair.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_04_peak.mp4",
    filename: "lauren_04_peak.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_04_peak.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_04_peak_stress_living_room.jpg",
    jobId: "80143846-6a82-4c41-a56a-b88ecfa82b08",
    costUsd: 0.28,
    fileSizeBytes: 13014981,
    createdAt: "2026-09-21T17:53:00Z",
  },
  {
    id: "short-lauren-05-discovery",
    title: "Short · Lauren discovers the planner",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren looks at her phone; curiosity becomes relief.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_05_discovery.mp4",
    filename: "lauren_05_discovery.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_05_discovery.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_05_discovery_phone.jpg",
    jobId: "9bd92b66-c7f6-4c83-bad3-b1d5648ae9ab",
    costUsd: 0.28,
    fileSizeBytes: 11360356,
    createdAt: "2026-09-21T17:53:00Z",
  },
  {
    id: "short-lauren-06-payoff",
    title: "Short · Lauren relaxed Christmas",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Lauren sits calmly with cocoa while her family enjoys Christmas.",
    src: "/assets/christmas/lauren-overwhelm/masters/lauren_06_payoff.mp4",
    filename: "lauren_06_payoff.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/lauren-overwhelm/posters/lauren_06_payoff.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "lauren", "planner", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "lauren_06_payoff_relaxed.jpg",
    jobId: "1346b4ed-daf9-4c4f-abf3-efc33009ddca",
    costUsd: 0.28,
    fileSizeBytes: 10039253,
    createdAt: "2026-09-21T17:53:00Z",
  },
  {
    id: "short-npj-01-train-window",
    title: "Short · Magical train window",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Child leans from a lantern-lit carriage as the steam train crosses a moonlit viaduct. Tags: christmas, train, cinematic, reel-source.",
    src: "/assets/christmas/np-journey/masters/npj_01_train_window.mp4",
    filename: "npj_01_train_window.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_01_train_window.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "train", "cinematic", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_train_window_girl.jpg",
    jobId: "c02def6a-0f61-442e-811a-73da660f0125",
    costUsd: 0.28,
    fileSizeBytes: 21894858,
    createdAt: "2026-09-20T20:49:28Z",
  },
  {
    id: "short-npj-02-station",
    title: "Short · North Pole Express station",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Wreath-lit locomotive arriving at NORTH POLE EXPRESS Platform 1. Tags: christmas, train, north-pole, reel-source.",
    src: "/assets/christmas/np-journey/masters/npj_02_station.mp4",
    filename: "npj_02_station.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_02_station.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "train", "north-pole", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_north_pole_express_station.jpg",
    jobId: "596d6bd3-fbee-4a3d-98fe-e248fbb7d637",
    costUsd: 0.28,
    fileSizeBytes: 21190617,
    createdAt: "2026-09-20T20:49:33Z",
  },
  {
    id: "short-npj-03-aurora-window",
    title: "Short · Aurora from the train",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Red train on a stone viaduct under moving northern lights. Tags: christmas, train, aurora, cinematic.",
    src: "/assets/christmas/np-journey/masters/npj_03_aurora_window.mp4",
    filename: "npj_03_aurora_window.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_03_aurora_window.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "train", "aurora", "cinematic", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_aurora_from_train.jpg",
    jobId: "51960e8a-c531-4a6c-a3b9-81ea550873ab",
    costUsd: 0.28,
    fileSizeBytes: 22214463,
    createdAt: "2026-09-20T20:49:37Z",
  },
  {
    id: "short-npj-04-viaduct-wide",
    title: "Short · Train on aurora viaduct",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steam locomotive crossing a high alpine viaduct with aurora. Tags: christmas, train, aurora, cinematic.",
    src: "/assets/christmas/np-journey/masters/npj_04_viaduct_wide.mp4",
    filename: "npj_04_viaduct_wide.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_04_viaduct_wide.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "train", "aurora", "cinematic", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_viaduct_aurora_wide.jpg",
    jobId: "9a22f8b1-a64f-4e7b-8863-51818e306af4",
    costUsd: 0.28,
    fileSizeBytes: 23994187,
    createdAt: "2026-09-20T20:49:42Z",
  },
  {
    id: "short-npj-05-village-arrival",
    title: "Short · North Pole Santa Village",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Arrival under the NORTH POLE SANTA VILLAGE arch. Tags: christmas, north-pole, santa, village.",
    src: "/assets/christmas/np-journey/masters/npj_05_village_arrival.mp4",
    filename: "npj_05_village_arrival.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_05_village_arrival.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "north-pole", "santa", "village", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_santa_village_arrival.jpg",
    jobId: "31aec96a-0dd7-4494-b01b-60c8d51cc7f4",
    costUsd: 0.28,
    fileSizeBytes: 21947586,
    createdAt: "2026-09-20T20:49:47Z",
  },
  {
    id: "short-npj-06-workshop-street",
    title: "Short · Santa’s Workshop street",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Reindeer, elves, and SANTA'S WORKSHOP on a snowy North Pole street. Tags: christmas, workshop, reindeer, north-pole.",
    src: "/assets/christmas/np-journey/masters/npj_06_workshop_street.mp4",
    filename: "npj_06_workshop_street.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_06_workshop_street.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "workshop", "reindeer", "north-pole", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_workshop_street.jpg",
    jobId: "945d5014-d5dc-4c05-8da4-ee778b45ee2f",
    costUsd: 0.28,
    fileSizeBytes: 22569999,
    createdAt: "2026-09-20T20:49:52Z",
  },
  {
    id: "short-npj-07-workshop-list",
    title: "Short · Santa and the Naughty or Nice list",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa at his workshop desk with wrapping elf and sleeping dog. Tags: christmas, santa, workshop, cozy.",
    src: "/assets/christmas/np-journey/masters/npj_07_workshop_list.mp4",
    filename: "npj_07_workshop_list.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_07_workshop_list.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "santa", "workshop", "cozy", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_workshop_naughty_nice.jpg",
    jobId: "f0fdc649-800d-4577-a107-0618c1a38a40",
    costUsd: 0.28,
    fileSizeBytes: 21439715,
    createdAt: "2026-09-20T20:49:56Z",
  },
  {
    id: "short-npj-08-wrapping",
    title: "Short · Elves wrapping with Santa",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa tying a bow beside elves and the Good Children scroll. Tags: christmas, santa, workshop, elves.",
    src: "/assets/christmas/np-journey/masters/npj_08_wrapping.mp4",
    filename: "npj_08_wrapping.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_08_wrapping.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "santa", "workshop", "elves", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_workshop_wrapping.jpg",
    jobId: "b72bd994-f5ab-45c9-a737-b5333ba2aa0f",
    costUsd: 0.28,
    fileSizeBytes: 17792643,
    createdAt: "2026-09-20T20:50:01Z",
  },
  {
    id: "short-npj-09-window-sleigh",
    title: "Short · Child watching Santa’s sleigh",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl and golden retriever watch Santa fly over a moonlit village. Tags: christmas, sleigh, cozy, santa.",
    src: "/assets/christmas/np-journey/masters/npj_09_window_sleigh.mp4",
    filename: "npj_09_window_sleigh.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_09_window_sleigh.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "sleigh", "cozy", "santa", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_window_sleigh_payoff.jpg",
    jobId: "e15b2b35-9875-4a2b-80d1-8ecb569b0d68",
    costUsd: 0.28,
    fileSizeBytes: 17271103,
    createdAt: "2026-09-20T20:50:05Z",
  },
  {
    id: "short-npj-10-snowman",
    title: "Short · Village square snowman",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Child finishing a snowman’s carrot nose in a festive market. Tags: christmas, village, cozy, snowman.",
    src: "/assets/christmas/np-journey/masters/npj_10_snowman.mp4",
    filename: "npj_10_snowman.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_10_snowman.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "village", "cozy", "snowman", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_village_snowman.jpg",
    jobId: "1bf85c4e-55bb-4f6d-9ced-1fcfdb5b35db",
    costUsd: 0.28,
    fileSizeBytes: 19776833,
    createdAt: "2026-09-20T20:50:10Z",
  },
  {
    id: "short-npj-11-plaza",
    title: "Short · The Plaza New York arrival",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl and golden retriever at The Plaza canopy on snowy Fifth Avenue. Tags: christmas, new-york, plaza, cinematic.",
    src: "/assets/christmas/np-journey/masters/npj_11_plaza.mp4",
    filename: "npj_11_plaza.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/np-journey/posters/npj_11_plaza.jpg",
    width: 1080,
    height: 1920,
    tags: ["christmas", "new-york", "plaza", "cinematic", "reel-source", "AI-generated"],
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "np_journey_plaza_nyc_girl_dog.jpg",
    jobId: "757c08c5-8843-43d9-bd14-a83f4fc85b69",
    costUsd: 0.28,
    fileSizeBytes: 21486208,
    createdAt: "2026-09-20T20:50:14Z",
  },
  {
    id: "short-cinematic-polar-express",
    title: "Short · Polar Express alpine viaduct",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steam locomotive on a lit Alpine viaduct. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_01_polar_express.mp4",
    filename: "cinematic_01_polar_express.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_01_polar_express.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "polar_express_alpine_viaduct.jpg",
    jobId: "ff036768-a163-4c5b-a0de-111550dfb3ce",
    costUsd: 0.28,
    fileSizeBytes: 13525893,
    createdAt: "2026-09-20T09:12:25Z",
  },
  {
    id: "short-cinematic-coca-cola-truck",
    title: "Short · Coca-Cola Christmas truck",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Holiday truck rolling through Times Square snow. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_02_coca_cola_truck.mp4",
    filename: "cinematic_02_coca_cola_truck.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_02_coca_cola_truck.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "coca_cola_christmas_truck_times_square.jpg",
    jobId: "6aaedbe5-bcd8-4bce-80c9-61473078a7fd",
    costUsd: 0.28,
    fileSizeBytes: 18391832,
    createdAt: "2026-09-20T09:15:24Z",
  },
  {
    id: "short-cinematic-home-alone-house",
    title: "Short · Home Alone-style Christmas house",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Slow push toward house 671. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_03_home_alone_house.mp4",
    filename: "cinematic_03_home_alone_house.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_03_home_alone_house.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "home_alone_style_christmas_house.jpg",
    jobId: "5bd7e3cc-aa34-4e41-8a40-133329366f23",
    costUsd: 0.28,
    fileSizeBytes: 18714974,
    createdAt: "2026-09-20T09:17:32Z",
  },
  {
    id: "short-cinematic-rockefeller",
    title: "Short · Rockefeller Center ice rink",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Tree, Prometheus, and skaters. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_04_rockefeller.mp4",
    filename: "cinematic_04_rockefeller.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_04_rockefeller.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "rockefeller_center_ice_rink.jpg",
    jobId: "eac5b74e-cd54-4e32-a2b4-76ad548c4528",
    costUsd: 0.28,
    fileSizeBytes: 18712067,
    createdAt: "2026-09-20T09:19:33Z",
  },
  {
    id: "short-cinematic-plaza-hotel",
    title: "Short · The Plaza Hotel Fifth Avenue",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Horse carriage at The Plaza canopy. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_05_plaza_hotel.mp4",
    filename: "cinematic_05_plaza_hotel.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_05_plaza_hotel.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "plaza_hotel_fifth_avenue.jpg",
    jobId: "1aa5e426-6c6e-40cf-8dca-caa864e53873",
    costUsd: 0.28,
    fileSizeBytes: 19721355,
    createdAt: "2026-09-20T09:21:51Z",
  },
  {
    id: "short-cinematic-santa-london",
    title: "Short · Santa flying over London",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Sleigh over Big Ben and the Thames. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_06_santa_london.mp4",
    filename: "cinematic_06_santa_london.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_06_santa_london.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "santa_sleigh_over_london.jpg",
    jobId: "9ad53d6a-1d09-4682-8d20-406502b8e82c",
    costUsd: 0.28,
    fileSizeBytes: 24095954,
    createdAt: "2026-09-20T09:24:00Z",
  },
  {
    id: "short-cinematic-workshop",
    title: "Short · Santa’s Workshop North Pole",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa checking the Nice List. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_07_workshop.mp4",
    filename: "cinematic_07_workshop.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_07_workshop.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "santa_workshop_north_pole.jpg",
    jobId: "f8804f21-1c89-4dba-bf9f-24702e93f310",
    costUsd: 0.28,
    fileSizeBytes: 14205674,
    createdAt: "2026-09-20T09:26:08Z",
  },
  {
    id: "short-cinematic-grinch",
    title: "Short · Grinch over Whoville",
    description:
      "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Grinch on a rooftop above Whoville. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/cinematic-sep20/masters/cinematic_08_grinch.mp4",
    filename: "cinematic_08_grinch.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cinematic-sep20/posters/cinematic_08_grinch.jpg",
    width: 1080,
    height: 1920,
    tags: CINEMATIC_SOURCE_TAGS,
    model: "kling-video/v3.0/pro/image-to-video",
    sourceImage: "grinch_whoville_rooftop.jpg",
    jobId: "59108722-55b0-4bc7-8560-6639d7d77610",
    costUsd: 0.28,
    fileSizeBytes: 13003875,
    createdAt: "2026-09-20T09:28:16Z",
  },
  {
    id: "short-santa-01-workshop",
    title: "Santa · Toy workshop wrapping",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa tying a ribbon with elves at the workbench.",
    src: "/assets/christmas/north-pole-santa/masters/santa_01_workshop.mp4",
    filename: "santa_01_workshop.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_01_workshop.jpg",
  },
  {
    id: "short-santa-02-sleigh",
    title: "Santa · Loading the sleigh",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Aurora, reindeer, and gifts going into the sleigh.",
    src: "/assets/christmas/north-pole-santa/masters/santa_02_sleigh.mp4",
    filename: "santa_02_sleigh.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_02_sleigh.jpg",
  },
  {
    id: "short-santa-03-desk",
    title: "Santa · Snow globe desk",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa polishing a snow globe over cookies and cocoa.",
    src: "/assets/christmas/north-pole-santa/masters/santa_03_desk.mp4",
    filename: "santa_03_desk.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_03_desk.jpg",
  },
  {
    id: "short-santa-04-sweep",
    title: "Santa · Sweeping the workshop",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Closing beat: Santa sweeping snow across the floor.",
    src: "/assets/christmas/north-pole-santa/masters/santa_04_sweep.mp4",
    filename: "santa_04_sweep.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/north-pole-santa/posters/santa_04_sweep.jpg",
  },
  {
    id: "short-global-01-lapland",
    title: "Global · Lapland aurora igloos",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Fire pit, falling snow, moving aurora, glass lodges.",
    src: "/assets/christmas/global-reel/masters/global_01_lapland.mp4",
    filename: "global_01_lapland.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_01_lapland.jpg",
  },
  {
    id: "short-global-02-alps",
    title: "Global · Alps infinity pool",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Heated pool steam and Matterhorn hotel terrace.",
    src: "/assets/christmas/global-reel/masters/global_02_alps.mp4",
    filename: "global_02_alps.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_02_alps.jpg",
  },
  {
    id: "short-global-03-home",
    title: "Global · Humble Christmas home",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Slow walk toward a warm neighborhood cottage.",
    src: "/assets/christmas/global-reel/masters/global_03_home.mp4",
    filename: "global_03_home.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_03_home.jpg",
  },
  {
    id: "short-global-04-plaza",
    title: "Global · The Plaza New York",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Wet Fifth Avenue, carriage, and hotel canopy.",
    src: "/assets/christmas/global-reel/masters/global_04_plaza.mp4",
    filename: "global_04_plaza.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_04_plaza.jpg",
  },
  {
    id: "short-global-05-white-house",
    title: "Global · White House Christmas",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Flag, fountain, and north facade at dusk.",
    src: "/assets/christmas/global-reel/masters/global_05_white_house.mp4",
    filename: "global_05_white_house.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/global-reel/posters/global_05_white_house.jpg",
  },
  {
    id: "short-palace-01-establish",
    title: "Palace · Wide mansion arrival",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Slow dolly toward the snowy estate and fountain.",
    src: "/assets/christmas/luxury-palace/masters/palace_01_establish.mp4",
    filename: "palace_01_establish.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_01_establish.jpg",
  },
  {
    id: "short-palace-02-approach",
    title: "Palace · Fountain and Rolls-Royce",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Tracking toward the wreath-lit entrance.",
    src: "/assets/christmas/luxury-palace/masters/palace_02_approach.mp4",
    filename: "palace_02_approach.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_02_approach.jpg",
  },
  {
    id: "short-palace-03-gates",
    title: "Palace · Walking to the open doors",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Approach through the gates to the interior tree.",
    src: "/assets/christmas/luxury-palace/masters/palace_03_gates.mp4",
    filename: "palace_03_gates.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_03_gates.jpg",
  },
  {
    id: "short-palace-04-entrance",
    title: "Palace · Grand hall tree reveal",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Dolly through the doorway into the Christmas hall.",
    src: "/assets/christmas/luxury-palace/masters/palace_04_entrance.mp4",
    filename: "palace_04_entrance.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_04_entrance.jpg",
  },
  {
    id: "short-palace-05-hero",
    title: "Palace · Balcony hero reveal",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Elevated push toward the giant tree and open night.",
    src: "/assets/christmas/luxury-palace/masters/palace_05_hero.mp4",
    filename: "palace_05_hero.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/luxury-palace/posters/palace_05_hero.jpg",
  },
  {
    id: "short-christmas-master-06",
    title: "Master · Village balcony girl",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl with teddy overlooking Santa’s village.",
    src: "/assets/christmas/reels/masters/christmas_master_06.mp4",
    filename: "christmas_master_06.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_06.jpg",
  },
  {
    id: "short-christmas-master-07",
    title: "Master · Santa and child watching sleigh",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Santa, child, dog, aurora, and distant sleigh.",
    src: "/assets/christmas/reels/masters/christmas_master_07.mp4",
    filename: "christmas_master_07.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_07.jpg",
  },
  {
    id: "short-christmas-master-08",
    title: "Master · Santa sleigh over alpine village",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Sleigh, reindeer, BELIEVE sign, lakeside village.",
    src: "/assets/christmas/reels/masters/christmas_master_08.mp4",
    filename: "christmas_master_08.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_08.jpg",
  },
  {
    id: "short-christmas-master-09",
    title: "Master · Polar Express interior",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Girl and teddy watching the castle from the train.",
    src: "/assets/christmas/reels/masters/christmas_master_09.mp4",
    filename: "christmas_master_09.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_09.jpg",
  },
  {
    id: "short-christmas-master-10",
    title: "Master · Polar Express locomotive 1225",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steam locomotive approaching a snowy station.",
    src: "/assets/christmas/reels/masters/christmas_master_10.mp4",
    filename: "christmas_master_10.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_10.jpg",
  },
  {
    id: "short-christmas-master-01",
    title: "Master · Alpine chalet hot tub",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Steaming spa and Christmas chalet.",
    src: "/assets/christmas/reels/masters/christmas_master_01.mp4",
    filename: "christmas_master_01.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_01.jpg",
  },
  {
    id: "short-christmas-master-02",
    title: "Master · NYC ice skater",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Street rink and Empire State Building.",
    src: "/assets/christmas/reels/masters/christmas_master_02.mp4",
    filename: "christmas_master_02.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_02.jpg",
  },
  {
    id: "short-christmas-master-03",
    title: "Master · Village kids sledding",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Children, sleds, and a golden retriever.",
    src: "/assets/christmas/reels/masters/christmas_master_03.mp4",
    filename: "christmas_master_03.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_03.jpg",
  },
  {
    id: "short-christmas-master-04",
    title: "Master · Prague cafe cookies",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Bakery window over Charles Bridge.",
    src: "/assets/christmas/reels/masters/christmas_master_04.mp4",
    filename: "christmas_master_04.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_04.jpg",
  },
  {
    id: "short-christmas-master-05",
    title: "Master · Vintage family snowman",
    description: "Higgsfield Kling 3.0 Pro, 5s, 1080×1920, silent. Three children and a top-hat snowman.",
    src: "/assets/christmas/reels/masters/christmas_master_05.mp4",
    filename: "christmas_master_05.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/reels/posters/christmas_master_05.jpg",
  },
  {
    id: "short-ice-nyc",
    title: "NYC girl ice skating",
    description: "5s 1080×1920. The New York street-rink skater you asked for.",
    src: "/assets/christmas/instagram-reel-cut3/clip_ice_nyc.mp4",
    filename: "clip_ice_nyc.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_ice_nyc.jpg",
  },
  {
    id: "short-kids-sled",
    title: "Kids sledding in the village",
    description: "5s 1080×1920. Children on sleds and a golden retriever in a snowy Alpine village.",
    src: "/assets/christmas/instagram-reel-cut3/clip_kids_sled.mp4",
    filename: "clip_kids_sled.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_kids_sled.jpg",
  },
  {
    id: "short-prague-square",
    title: "Prague Old Town Christmas square",
    description: "5s 1080×1920. Gingerbread stall, carousel, tree, and Tyn Church.",
    src: "/assets/christmas/instagram-reel-cut3/clip_prague_square.mp4",
    filename: "clip_prague_square.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-cut3/posters/clip_prague_square.jpg",
  },
  {
    id: "reel-kling-01-train",
    title: "NEW · Polar Express train",
    description: "Kling v3 Pro master, 1080×1920, ~5s. White Christmas train at Alpine Valley.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_01_train_raw.mp4",
    filename: "clip_01_train_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/train.jpg",
  },
  {
    id: "reel-kling-02-santa",
    title: "NEW · Santa + sleigh + reindeer",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Moonlit Santa beside the sleigh.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_02_santa_raw.mp4",
    filename: "clip_02_santa_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/santa.jpg",
  },
  {
    id: "reel-kling-03-market",
    title: "NEW · Cathedral Christmas market",
    description: "Kling v3 Pro master, 1080×1920, ~5s. European market street and carousel.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_03_market_raw.mp4",
    filename: "clip_03_market_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/market.jpg",
  },
  {
    id: "reel-kling-04-chalet",
    title: "NEW · Luxury snowy chalet",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Twilight chalet entrance.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_04_chalet_raw.mp4",
    filename: "clip_04_chalet_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/chalet.jpg",
  },
  {
    id: "reel-kling-05-cozy",
    title: "NEW · Cozy window + snowy village",
    description: "Kling v3 Pro master, 1080×1920, ~5s. Cat, cocoa, and a snowy village outside the window.",
    src: "/assets/christmas/instagram-reel-kling-1080p/clip_05_cozy_raw.mp4",
    filename: "clip_05_cozy_raw.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/instagram-reel-kling-1080p/posters/cozy.jpg",
  },
  {
    id: "reel-01",
    title: "NYC snowy Christmas street",
    description: "Snow falling on a New York evening street with the Empire State Building in the distance.",
    src: "/assets/christmas/instagram-reel/clip_01.mp4",
    filename: "clip_01.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_01.jpg",
  },
  {
    id: "reel-06",
    title: "NYC Rockefeller ice rink",
    description:
      "Rockefeller Center at night: Christmas tree, Prometheus fountain, and people skating on the ice in New York.",
    src: "/assets/christmas/instagram-reel/clip_06.mp4",
    filename: "clip_06.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_06.jpg",
  },
  {
    id: "reel-02",
    title: "Candlelit cottage entrance",
    description: "Luxury snowy house entrance with lanterns.",
    src: "/assets/christmas/instagram-reel/clip_02.mp4",
    filename: "clip_02.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 1.2,
    poster: "/assets/christmas/instagram-reel/source/clip_02.jpg",
  },
  {
    id: "reel-03",
    title: "Cocoa by the fire",
    description: "Hot chocolate mug with fireplace and tree lights.",
    src: "/assets/christmas/instagram-reel/clip_03.mp4",
    filename: "clip_03.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_03.jpg",
  },
  {
    id: "reel-04",
    title: "Living room wonderland",
    description: "Wide cozy living room with tree, gifts, fireplace, and a snowy village outside.",
    src: "/assets/christmas/instagram-reel/clip_04.mp4",
    filename: "clip_04.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_04.jpg",
  },
  {
    id: "reel-05",
    title: "Cookie plate by the tree",
    description: "Festive cookie plate held in front of the tree.",
    src: "/assets/christmas/instagram-reel/clip_05.mp4",
    filename: "clip_05.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 1.2,
    poster: "/assets/christmas/instagram-reel/source/clip_05.jpg",
  },
  {
    id: "reel-07",
    title: "Snowy village window nook",
    description: "Cat, cocoa, and a snowy village outside the window.",
    src: "/assets/christmas/instagram-reel/clip_07.mp4",
    filename: "clip_07.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 2.2,
    poster: "/assets/christmas/instagram-reel/source/clip_07.jpg",
  },
  {
    id: "reel-cozy-01",
    title: "Cozy cottage · fireplace + snow",
    description: "Kling 5s. Cocoa, golden retriever, fireplace, snow falling on the village outside.",
    src: "/assets/christmas/cozy-reel/clip1.mp4",
    filename: "cozy_cottage_clip1.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip1.jpg",
  },
  {
    id: "reel-cozy-02",
    title: "Cozy cottage · cocoa + dog",
    description: "Kling 5s. Close mug of hot chocolate with a sleeping golden retriever.",
    src: "/assets/christmas/cozy-reel/clip2.mp4",
    filename: "cozy_cottage_clip2.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip2.jpg",
  },
  {
    id: "reel-cozy-03",
    title: "Cozy cottage · snowy village window",
    description: "Kling 5s. Fireplace, tree, and a snowy village through the window.",
    src: "/assets/christmas/cozy-reel/clip3.mp4",
    filename: "cozy_cottage_clip3.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 5.04,
    poster: "/assets/christmas/cozy-reel/posters/clip3.jpg",
  },
];

const NEW_STILL_PHOTOS: LibraryVideo[] = [
  {
    id: "photo-lauren-01-intro",
    title: "Photo · Lauren intro kitchen worry",
    description: "Lauren leans on the kitchen island, mildly overloaded, family wrapping gifts behind her.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_01_intro_kitchen_worried.jpg",
    filename: "lauren_01_intro_kitchen_worried.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-lauren-02-phone",
    title: "Photo · Lauren mental load phone",
    description: "Lauren checks her phone in the kitchen with a worried look as Christmas prep continues.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_02_phone_mental_load.jpg",
    filename: "lauren_02_phone_mental_load.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-lauren-03-receipt",
    title: "Photo · Lauren receipt and to-do list",
    description: "Lauren studies a long receipt beside a Christmas to-do list and wrapping paper.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_03_receipt_tasks.jpg",
    filename: "lauren_03_receipt_tasks.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-lauren-04-peak",
    title: "Photo · Lauren peak stress",
    description: "Lauren stands in a messy living room with both hands in her hair.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_04_peak_stress_living_room.jpg",
    filename: "lauren_04_peak_stress_living_room.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-lauren-05-discovery",
    title: "Photo · Lauren discovers the planner",
    description: "Lauren looks at her phone with a small surprised smile in the decorated kitchen.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_05_discovery_phone.jpg",
    filename: "lauren_05_discovery_phone.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-lauren-06-payoff",
    title: "Photo · Lauren relaxed Christmas",
    description: "Lauren sits calmly with cocoa and a laptop, smiling as her family enjoys Christmas.",
    src: "/assets/christmas/lauren-overwhelm/stills/lauren_06_payoff_relaxed.jpg",
    filename: "lauren_06_payoff_relaxed.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "lauren", "planner", "reel-source"],
  },
  {
    id: "photo-np-train-window",
    title: "Photo · Magical train window",
    description:
      "Child in a red knit hat leans from a lantern-lit carriage as a steam train crosses a moonlit alpine viaduct.",
    src: "/assets/christmas/library-stills/np_journey_train_window_girl.jpg",
    filename: "np_journey_train_window_girl.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "train", "cinematic", "reel-source"],
  },
  {
    id: "photo-np-express-station",
    title: "Photo · North Pole Express station",
    description:
      "Child with backpack faces a wreath-lit steam locomotive under the NORTH POLE EXPRESS station clock.",
    src: "/assets/christmas/library-stills/np_journey_north_pole_express_station.jpg",
    filename: "np_journey_north_pole_express_station.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "train", "north-pole", "reel-source"],
  },
  {
    id: "photo-np-aurora-window",
    title: "Photo · Aurora from the train",
    description: "Carriage-side view of a red steam train on a stone viaduct under green northern lights.",
    src: "/assets/christmas/library-stills/np_journey_aurora_from_train.jpg",
    filename: "np_journey_aurora_from_train.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "train", "aurora", "cinematic"],
  },
  {
    id: "photo-np-viaduct-aurora",
    title: "Photo · Train on aurora viaduct",
    description: "Wide cinematic steam train crossing a high stone viaduct above a frozen river and alpine village.",
    src: "/assets/christmas/library-stills/np_journey_viaduct_aurora_wide.jpg",
    filename: "np_journey_viaduct_aurora_wide.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "train", "aurora", "cinematic"],
  },
  {
    id: "photo-np-village-arrival",
    title: "Photo · North Pole Santa Village",
    description: "Traveler arriving under the NORTH POLE SANTA VILLAGE arch with elves, gifts, and a clock tower.",
    src: "/assets/christmas/library-stills/np_journey_santa_village_arrival.jpg",
    filename: "np_journey_santa_village_arrival.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "north-pole", "santa", "village"],
  },
  {
    id: "photo-np-workshop-street",
    title: "Photo · Santa’s Workshop street",
    description: "Child facing Santa’s Workshop with reindeer, elves, gifts, and a giant Christmas tree.",
    src: "/assets/christmas/library-stills/np_journey_workshop_street.jpg",
    filename: "np_journey_workshop_street.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "workshop", "reindeer", "north-pole"],
  },
  {
    id: "photo-np-workshop-list",
    title: "Photo · Santa and the Naughty or Nice list",
    description: "Santa at his workshop desk with the Naughty or Nice list, wrapping elf, and sleeping golden retriever.",
    src: "/assets/christmas/library-stills/np_journey_workshop_naughty_nice.jpg",
    filename: "np_journey_workshop_naughty_nice.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "santa", "workshop", "cozy"],
  },
  {
    id: "photo-np-workshop-wrapping",
    title: "Photo · Elves wrapping with Santa",
    description: "Santa tying a bow while elves wrap toys beside a Good Children Around the World scroll.",
    src: "/assets/christmas/library-stills/np_journey_workshop_wrapping.jpg",
    filename: "np_journey_workshop_wrapping.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "santa", "workshop", "elves"],
  },
  {
    id: "photo-np-window-sleigh",
    title: "Photo · Child watching Santa’s sleigh",
    description: "Girl and golden retriever at a snowy window as Santa’s sleigh flies over a moonlit village.",
    src: "/assets/christmas/library-stills/np_journey_window_sleigh_payoff.jpg",
    filename: "np_journey_window_sleigh_payoff.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "sleigh", "cozy", "santa"],
  },
  {
    id: "photo-np-village-snowman",
    title: "Photo · Village square snowman",
    description: "Child placing a carrot nose on a snowman in a festive alpine market with a golden retriever.",
    src: "/assets/christmas/library-stills/np_journey_village_snowman.jpg",
    filename: "np_journey_village_snowman.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "village", "cozy", "snowman"],
  },
  {
    id: "photo-np-plaza-girl-dog",
    title: "Photo · The Plaza New York arrival",
    description: "Girl in a red coat and golden retriever at The Plaza Hotel entrance on a snowy Fifth Avenue night.",
    src: "/assets/christmas/library-stills/np_journey_plaza_nyc_girl_dog.jpg",
    filename: "np_journey_plaza_nyc_girl_dog.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: ["christmas", "new-york", "plaza", "cinematic"],
  },
  {
    id: "photo-polar-express-viaduct",
    title: "Photo · Polar Express alpine viaduct",
    description:
      "Steam locomotive with wreath and red carriages on a lit stone viaduct at sunset. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/polar_express_alpine_viaduct.jpg",
    filename: "polar_express_alpine_viaduct.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-coca-cola-truck",
    title: "Photo · Coca-Cola Christmas truck",
    description:
      "Lit Coca-Cola holiday truck with Santa mural in Times Square snowfall. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/coca_cola_christmas_truck_times_square.jpg",
    filename: "coca_cola_christmas_truck_times_square.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-home-alone-house",
    title: "Photo · Home Alone-style Christmas house",
    description:
      "Brick colonial house 671 with warm windows, wreath, and Christmas lights in snow. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/home_alone_style_christmas_house.jpg",
    filename: "home_alone_style_christmas_house.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-rockefeller-rink",
    title: "Photo · Rockefeller Center ice rink",
    description:
      "Rockefeller Christmas tree, Prometheus fountain, and skaters in falling snow. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/rockefeller_center_ice_rink.jpg",
    filename: "rockefeller_center_ice_rink.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-plaza-hotel-carriage",
    title: "Photo · The Plaza Hotel Fifth Avenue",
    description:
      "White horse carriage at The Plaza canopy on snowy Fifth Avenue. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/plaza_hotel_fifth_avenue.jpg",
    filename: "plaza_hotel_fifth_avenue.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-santa-over-london",
    title: "Photo · Santa flying over London",
    description:
      "Santa’s sleigh and reindeer over Big Ben, Parliament, and the Thames under a full moon. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/santa_sleigh_over_london.jpg",
    filename: "santa_sleigh_over_london.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-santa-workshop-north-pole",
    title: "Photo · Santa’s Workshop North Pole",
    description:
      "Santa checking the Nice List at the workshop door with elves, reindeer, and aurora. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/santa_workshop_north_pole.jpg",
    filename: "santa_workshop_north_pole.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-grinch-whoville",
    title: "Photo · Grinch over Whoville",
    description:
      "Grinch in a Santa coat on a snowy rooftop above Whoville’s Christmas lights. Tags: christmas, reel-source, cinematic, viral, recognizable-scene, AI-generated.",
    src: "/assets/christmas/library-stills/grinch_whoville_rooftop.jpg",
    filename: "grinch_whoville_rooftop.jpg",
    category: "christmas_reels",
    kind: "photo",
    tags: CINEMATIC_SOURCE_TAGS,
  },
  {
    id: "photo-santa-workshop",
    title: "Photo · North Pole toy workshop",
    description: "Santa and elves wrapping gifts at the wooden workbench under workshop lights.",
    src: "/assets/christmas/north-pole-santa/source/01_workshop_wrapping_1080x1920.jpg",
    filename: "01_workshop_wrapping_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh",
    title: "Photo · Santa loading the sleigh",
    description: "Red sleigh, reindeer, aurora, and the NORTH POLE workshop doorway at night.",
    src: "/assets/christmas/north-pole-santa/source/02_sleigh_loading_1080x1920.jpg",
    filename: "02_sleigh_loading_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-desk",
    title: "Photo · Santa and the snow globe",
    description: "Warm desk with cookies, cocoa mug, checklist, and Santa polishing a snow globe.",
    src: "/assets/christmas/north-pole-santa/source/03_snow_globe_desk_1080x1920.jpg",
    filename: "03_snow_globe_desk_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sweep",
    title: "Photo · Santa sweeping the workshop",
    description: "Santa with a broom, red sack, and snowy North Pole through the open arch.",
    src: "/assets/christmas/north-pole-santa/source/04_workshop_sweeping_1080x1920.jpg",
    filename: "04_workshop_sweeping_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-lapland",
    title: "Photo · Lapland aurora igloos",
    description: "Glass igloos, fire pit, and northern lights over a frozen lake.",
    src: "/assets/christmas/global-reel/source/01_lapland_aurora_1080x1920.jpg",
    filename: "01_lapland_aurora_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-alps",
    title: "Photo · Alps infinity pool",
    description: "Bellevue Alpine Resort terrace, steaming pool, and Matterhorn sunset.",
    src: "/assets/christmas/global-reel/source/02_alps_infinity_pool_1080x1920.jpg",
    filename: "02_alps_infinity_pool_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-home",
    title: "Photo · Humble Christmas home",
    description: "Snowy cottage porch, wreath, snowman, and warm window light.",
    src: "/assets/christmas/global-reel/source/03_humble_christmas_home_1080x1920.jpg",
    filename: "03_humble_christmas_home_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-plaza",
    title: "Photo · The Plaza New York",
    description: "Christmas canopy, carriage, and wet pavement at The Plaza Hotel.",
    src: "/assets/christmas/global-reel/source/04_plaza_new_york_1080x1920.jpg",
    filename: "04_plaza_new_york_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-global-white-house",
    title: "Photo · White House Christmas",
    description: "North facade, flag, fountain, and THE WHITE HOUSE WASHINGTON plaque.",
    src: "/assets/christmas/global-reel/source/05_white_house_1080x1920.jpg",
    filename: "05_white_house_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-establish",
    title: "Photo · Luxury palace wide estate",
    description: "Snowy night facade, circular fountain, and black sedan used for the palace arrival short.",
    src: "/assets/christmas/luxury-palace/source/01_establish_wide_mansion_1080x1920.jpg",
    filename: "01_establish_wide_mansion_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-approach",
    title: "Photo · Palace fountain and car",
    description: "Closer entrance with wreath, spiral trees, and luxury sedan.",
    src: "/assets/christmas/luxury-palace/source/02_approach_fountain_car_1080x1920.jpg",
    filename: "02_approach_fountain_car_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-gates",
    title: "Photo · Open palace gates",
    description: "Wreath-lined gates looking through to the fountain and interior Christmas tree.",
    src: "/assets/christmas/luxury-palace/source/03_enter_open_gates_1080x1920.jpg",
    filename: "03_enter_open_gates_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-entrance",
    title: "Photo · Grand Christmas hall",
    description: "Doorway view of the enormous tree, chandelier, and marble staircase.",
    src: "/assets/christmas/luxury-palace/source/04_grand_entrance_tree_1080x1920.jpg",
    filename: "04_grand_entrance_tree_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-palace-hero",
    title: "Photo · Palace balcony hero",
    description: "Elevated view of the Christmas palace, gift ring, chandelier, and snowy exterior.",
    src: "/assets/christmas/luxury-palace/source/05_hero_balcony_palace_1080x1920.jpg",
    filename: "05_hero_balcony_palace_1080x1920.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-village-balcony-girl",
    title: "Photo · Village balcony girl",
    description: "Girl with a teddy on a decorated balcony overlooking a storybook Christmas village and Santa’s sleigh.",
    src: "/assets/christmas/library-stills/01_village_balcony_girl.jpg",
    filename: "01_village_balcony_girl.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-child-aurora",
    title: "Photo · Santa and child watching sleigh",
    description: "Santa and a child pointing at a distant sleigh under the moon and aurora.",
    src: "/assets/christmas/library-stills/02_santa_child_aurora.jpg",
    filename: "02_santa_child_aurora.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh-believe",
    title: "Photo · Santa sleigh BELIEVE",
    description: "Santa driving reindeer over an alpine village with a BELIEVE plaque on the sleigh.",
    src: "/assets/christmas/library-stills/03_santa_sleigh_believe.jpg",
    filename: "03_santa_sleigh_believe.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-polar-express-interior",
    title: "Photo · Polar Express interior",
    description: "Child and teddy looking from a Polar Express carriage toward a lit castle and viaduct.",
    src: "/assets/christmas/library-stills/04_polar_express_interior.jpg",
    filename: "04_polar_express_interior.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-polar-express-station",
    title: "Photo · Polar Express locomotive 1225",
    description: "Black steam locomotive 1225 at a snowy station, child with a lantern on the platform.",
    src: "/assets/christmas/library-stills/05_polar_express_station.jpg",
    filename: "05_polar_express_station.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-nyc-ice-girl",
    title: "Photo · NYC girl ice skating",
    description:
      "New York Christmas night. Young woman skating on a street rink with the Empire State Building behind her.",
    src: "/assets/christmas/library-stills/nyc_girl_ice_skating.jpg",
    filename: "nyc_girl_ice_skating.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-village-kids-sled",
    title: "Photo · Kids sledding in the village",
    description: "Alpine village at sunset. Children on sleds, a golden retriever, snowy houses, and a lake.",
    src: "/assets/christmas/library-stills/village_kids_sledding.jpg",
    filename: "village_kids_sledding.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-carousel",
    title: "Photo · Prague Old Town carousel",
    description: "Prague Christmas market square with Tyn Church, tree, carousel, and gingerbread.",
    src: "/assets/christmas/library-stills/prague_old_town_carousel_market.jpg",
    filename: "prague_old_town_carousel_market.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-balcony",
    title: "Photo · Prague balcony dessert table",
    description: "Christmas cookies and cocoa on a balcony overlooking Prague at sunset.",
    src: "/assets/christmas/library-stills/prague_balcony_christmas_spread.jpg",
    filename: "prague_balcony_christmas_spread.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-cafe",
    title: "Photo · Prague cafe street",
    description: "Cookies, cocoa, and a snowy Prague lane toward Tyn Church.",
    src: "/assets/christmas/library-stills/prague_cafe_street_cookies.jpg",
    filename: "prague_cafe_street_cookies.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-gingerbread",
    title: "Photo · Prague gingerbread stall",
    description: "Market stall of gingerbread and cakes with Prague towers behind.",
    src: "/assets/christmas/library-stills/prague_market_gingerbread_stall.jpg",
    filename: "prague_market_gingerbread_stall.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-bakery",
    title: "Photo · Prague bakery window",
    description: "Cozy bakery table of cookies and cocoa with Charles Bridge outside.",
    src: "/assets/christmas/library-stills/prague_bakery_window.jpg",
    filename: "prague_bakery_window.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-prague-couple",
    title: "Photo · Prague market couple",
    description: "Snowy Prague market with carousel, tree, and a couple walking with cocoa.",
    src: "/assets/christmas/library-stills/prague_market_couple_carousel.jpg",
    filename: "prague_market_couple_carousel.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-alpine-cocoa-bridge",
    title: "Photo · Alpine village cocoa",
    description: "Cocoa on a snowy balcony overlooking a lit Alpine village and stone bridge.",
    src: "/assets/christmas/library-stills/alpine_village_cocoa_bridge.jpg",
    filename: "alpine_village_cocoa_bridge.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-chalet-hot-tub",
    title: "Photo · Chalet hot tub",
    description: "Luxury snowy chalet with Christmas tree inside and a steaming outdoor spa.",
    src: "/assets/christmas/library-stills/alpine_chalet_hot_tub.jpg",
    filename: "alpine_chalet_hot_tub.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-vintage-snowman",
    title: "Photo · Vintage family snowman",
    description: "Three children building a top-hat snowman in front of a wreath-lit house and vintage cars.",
    src: "/assets/christmas/library-stills/vintage_family_snowman.jpg",
    filename: "vintage_family_snowman.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-luxury-train",
    title: "Photo · Luxury Christmas train",
    description: "Dark Orient-Express style train at an Alpine station at dusk.",
    src: "/assets/christmas/library-stills/alpine_luxury_christmas_train.jpg",
    filename: "alpine_luxury_christmas_train.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-village-square",
    title: "Photo · Santa in the village square",
    description: "Storybook village with a giant tree, Santa’s sleigh, snowman, and a stream.",
    src: "/assets/christmas/library-stills/santa_village_square.jpg",
    filename: "santa_village_square.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-santa-sleigh-ride",
    title: "Photo · Santa sleigh ride",
    description: "Santa driving reindeer through snowy pines toward a lakeside village.",
    src: "/assets/christmas/library-stills/santa_reindeer_sleigh_ride.jpg",
    filename: "santa_reindeer_sleigh_ride.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-swiss-sleigh",
    title: "Photo · Swiss hotel horse sleigh",
    description: "Grand Swiss hotel at dusk with a horse-drawn sleigh and frozen lake.",
    src: "/assets/christmas/library-stills/swiss_hotel_horse_sleigh.jpg",
    filename: "swiss_hotel_horse_sleigh.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-matterhorn-pool",
    title: "Photo · Matterhorn infinity pool",
    description: "Luxury chalet terrace and steaming pool facing the Matterhorn at sunset.",
    src: "/assets/christmas/library-stills/matterhorn_infinity_pool.jpg",
    filename: "matterhorn_infinity_pool.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
];

const CHRISTMAS_PHOTOS: LibraryVideo[] = [
  ...NEW_STILL_PHOTOS,
  {
    id: "photo-kling-train",
    title: "Photo · Polar Express train",
    description: "Source still for the Kling Polar Express short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/alpine_valley_polar_express_at_christmas.jpg",
    filename: "alpine_valley_polar_express_at_christmas.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-santa",
    title: "Photo · Santa + sleigh",
    description: "Source still for the Kling Santa short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/santa_s_moonlit_christmas_sleigh_ride.jpg",
    filename: "santa_s_moonlit_christmas_sleigh_ride.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-market",
    title: "Photo · Cathedral Christmas market",
    description: "Source still for the Kling market short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/snowy_christmas_market_by_the_cathedral.jpg",
    filename: "snowy_christmas_market_by_the_cathedral.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-chalet",
    title: "Photo · Luxury snowy chalet",
    description: "Source still for the Kling chalet short.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/snowy_christmas_chalet_at_twilight.jpg",
    filename: "snowy_christmas_chalet_at_twilight.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-kling-village",
    title: "Photo · Snowy village window",
    description: "Source still for the Kling cozy short. Cat, cocoa, and a snowy village outside.",
    src: "/assets/christmas/instagram-reel-kling-1080p/source/cozy_christmas_reading_nook_by_snowy_village.jpg",
    filename: "cozy_christmas_reading_nook_by_snowy_village.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-nyc-street",
    title: "Photo · NYC snowy Christmas street",
    description: "Source still for the New York snow street short.",
    src: "/assets/christmas/instagram-reel/source/clip_01.jpg",
    filename: "nyc_snowy_christmas_street.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-ice-rink",
    title: "Photo · NYC Rockefeller ice rink",
    description: "Source still for the Rockefeller ice-skating short — tree, rink, and skaters in New York.",
    src: "/assets/christmas/instagram-reel/source/clip_06.jpg",
    filename: "nyc_rockefeller_ice_rink.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cottage",
    title: "Photo · Candlelit cottage",
    description: "Source still for the cottage-entrance short.",
    src: "/assets/christmas/instagram-reel/source/clip_02.jpg",
    filename: "candlelit_christmas_cottage.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cocoa",
    title: "Photo · Cocoa by the fire",
    description: "Source still for the cocoa short.",
    src: "/assets/christmas/instagram-reel/source/clip_03.jpg",
    filename: "cozy_christmas_cocoa.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-living-room",
    title: "Photo · Living room wonderland",
    description: "Source still for the living-room short.",
    src: "/assets/christmas/instagram-reel/source/clip_04.jpg",
    filename: "cozy_christmas_living_room.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-cookies",
    title: "Photo · Cookie plate",
    description: "Source still for the cookie-plate short.",
    src: "/assets/christmas/instagram-reel/source/clip_05.jpg",
    filename: "cozy_christmas_cookie_plate.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
  {
    id: "photo-wan-village",
    title: "Photo · Snowy village window nook",
    description: "Source still for the village-window short.",
    src: "/assets/christmas/instagram-reel/source/clip_07.jpg",
    filename: "snowy_village_window_nook.jpg",
    category: "christmas_reels",
    kind: "photo",
  },
];

const CHRISTMAS_MARKETING: LibraryVideo[] = [
  {
    id: "cabin-hero",
    title: "Cabin hero loop",
    description: "Desktop landing loop.",
    src: "/christmas/cabin-hero-loop.mp4",
    filename: "cabin-hero-loop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "cabin-hero-720",
    title: "Cabin hero loop 720p",
    description: "Mobile landing loop.",
    src: "/christmas/cabin-hero-loop-720.mp4",
    filename: "cabin-hero-loop-720.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "advent-loop",
    title: "Advent calendar loop",
    description: "Advent product loop.",
    src: "/christmas/advent/advent-loop.mp4",
    filename: "advent-loop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "advent-loop-540",
    title: "Advent calendar loop 540p",
    description: "Smaller Advent loop.",
    src: "/christmas/advent/advent-loop-540.mp4",
    filename: "advent-loop-540.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-scene-desktop",
    title: "Gift tree · desktop",
    description: "Gift-tree landing scene.",
    src: "/christmas/gifts/scene-desktop.mp4",
    filename: "gift-tree-scene-desktop.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-scene-mobile",
    title: "Gift tree · mobile",
    description: "Gift-tree landing scene (mobile crop).",
    src: "/christmas/gifts/scene-mobile.mp4",
    filename: "gift-tree-scene-mobile.mp4",
    category: "christmas_marketing",
    kind: "reel",
  },
  {
    id: "gift-open",
    title: "Gift open",
    description: "Gift-open motion for the tree product.",
    src: "/christmas/gifts/gift-open.mp4",
    filename: "gift-open.mp4",
    category: "christmas_marketing",
    kind: "short",
  },
];

export const LIBRARY_VIDEOS: LibraryVideo[] = [
  ...CHRISTMAS_REELS,
  ...CHRISTMAS_SHORTS,
  ...CHRISTMAS_PHOTOS,
  ...CHRISTMAS_MARKETING,
  ...petClips("dog", "pet_dog"),
  ...petClips("cat", "pet_cat"),
  ...petClips("other", "pet_other"),
];

export function librarySrcPath(src: string): string {
  if (src.includes("/api/clip-factory")) return src;
  return src.split("?")[0];
}

export function isLibraryPhoto(item: LibraryVideo): boolean {
  return item.kind === "photo" || /\.(jpe?g|png|webp)$/i.test(item.filename);
}

export function videosForCategory(
  categoryId: LibraryCategoryId | "all",
  videos: LibraryVideo[] = LIBRARY_VIDEOS,
): LibraryVideo[] {
  if (categoryId === "all") return videos;
  return videos.filter((video) => video.category === categoryId);
}

export function searchLibraryCatalog(
  videos: LibraryVideo[],
  query: string,
  categoryId: LibraryCategoryId | "all",
  kind: LibraryKind | "all" = "all",
): LibraryVideo[] {
  const needle = query.trim().toLowerCase();
  let list = videosForCategory(categoryId, videos);
  if (kind !== "all") list = list.filter((item) => item.kind === kind);
  if (!needle) return list;
  return list.filter((video) =>
    [video.title, video.description, video.filename, video.id, ...(video.tags || [])]
      .join(" ")
      .toLowerCase()
      .includes(needle),
  );
}

export function searchLibraryVideos(
  query: string,
  categoryId: LibraryCategoryId | "all",
  kind: LibraryKind | "all" = "all",
): LibraryVideo[] {
  return searchLibraryCatalog(LIBRARY_VIDEOS, query, categoryId, kind);
}

export function countChristmasKind(kind: LibraryKind): number {
  return LIBRARY_VIDEOS.filter((item) => item.category === "christmas_reels" && item.kind === kind).length;
}
