/** Auto-generated from christmas-20-batch publish manifests. */
import type { LibraryVideo } from "./catalog";

const C20_TAGS = ["christmas", "christmas-20-batch", "kling-3-pro", "ready-to-publish"] as const;

export const CHRISTMAS_20_MASTERS: LibraryVideo[] = [
  {
    id: "short-c20-01-ny-awning",
    title: "Master · 01 ny awning",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-new-york-awning-snow. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-01-ny-awning.mp4",
    filename: "short-c20-01-ny-awning.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "d367af79-7568-4fcf-9923-401ab13004cd",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-02-train-nyc-clock",
    title: "Master · 02 train nyc clock",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-train-nyc-station-clock. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-02-train-nyc-clock.mp4",
    filename: "short-c20-02-train-nyc-clock.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "ce1580fb-1aed-41c6-8234-8fe58738fa49",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-06-viaduct-village",
    title: "Master · 06 viaduct village",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-train-viaduct-alpine-village. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-06-viaduct-village.mp4",
    filename: "short-c20-06-viaduct-village.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "9745d1e1-5403-4eed-8e8a-14909b98b58d",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-04-viaduct-sunset-peaks",
    title: "Master · 04 viaduct sunset peaks",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-train-viaduct-sunset-peaks. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-04-viaduct-sunset-peaks.mp4",
    filename: "short-c20-04-viaduct-sunset-peaks.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "8524553b-f1cb-449b-a784-9e3a348a373d",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-05-mansion-gwagon",
    title: "Master · 05 mansion gwagon",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-mansion-nyc-skyline-gwagon. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-05-mansion-gwagon.mp4",
    filename: "short-c20-05-mansion-gwagon.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "694b03b7-8f9f-48e1-b7ff-8e3a0b9c8341",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-07-station-traveler",
    title: "Master · 07 station traveler",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-train-station-traveler. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-07-station-traveler.mp4",
    filename: "short-c20-07-station-traveler.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "84779e26-b23f-46da-bc12-23b30ffec505",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-08-radio-city",
    title: "Master · 08 radio city",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-radio-city-snow. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-08-radio-city.mp4",
    filename: "short-c20-08-radio-city.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "b5dd2739-3e50-4761-9b18-21304682b8b9",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-09-penthouse-tom-jerry",
    title: "Master · 09 penthouse tom jerry",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-penthouse-tom-jerry-pets. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-09-penthouse-tom-jerry.mp4",
    filename: "short-c20-09-penthouse-tom-jerry.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "3170087a-6a07-4d92-b2ab-85b02f16df5a",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-10-penthouse-empire",
    title: "Master · 10 penthouse empire",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-penthouse-christmas-empire. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-10-penthouse-empire.mp4",
    filename: "short-c20-10-penthouse-empire.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "3646e379-57a3-4500-b1b6-25309d86c24b",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-11-mansion-gate",
    title: "Master · 11 mansion gate",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-mansion-gate-nyc. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-11-mansion-gate.mp4",
    filename: "short-c20-11-mansion-gate.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "a81228b9-f081-4106-9074-6b157df46c74",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-12-alpine-cabin",
    title: "Master · 12 alpine cabin",
    description: "Kling 3.0 Pro 8s master. Source: photo-alpine-cabin-tom-jerry-fireplace. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-12-alpine-cabin.mp4",
    filename: "short-c20-12-alpine-cabin.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "960fa437-e03b-4e53-b26c-94f676ffdb47",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-13-home-alone-tv",
    title: "Master · 13 home alone tv",
    description: "Kling 3.0 Pro 8s master. Source: photo-home-alone-kevin-tv-christmas. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-13-home-alone-tv.mp4",
    filename: "short-c20-13-home-alone-tv.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "fc5aa248-4f16-494e-8a19-db8371105839",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-16-library-dog",
    title: "Master · 16 library dog",
    description: "Kling 3.0 Pro 8s master. Source: photo-library-christmas-golden-retriever. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-16-library-dog.mp4",
    filename: "short-c20-16-library-dog.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "b026f8cc-564b-4cd8-9b0b-e7b9b1fb44ce",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-17-saks-rockefeller",
    title: "Master · 17 saks rockefeller",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-saks-rockefeller-snow. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-17-saks-rockefeller.mp4",
    filename: "short-c20-17-saks-rockefeller.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "54fdc9ec-ccd7-4a43-ae3f-59790fb8f6be",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-18-train-carriage",
    title: "Master · 18 train carriage",
    description: "Kling 3.0 Pro 8s master. Source: photo-train-carriage-viaduct-window. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-18-train-carriage.mp4",
    filename: "short-c20-18-train-carriage.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "dde803dc-eff6-425f-baab-2f9140ec7e9e",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-19-brownstone-vintage",
    title: "Master · 19 brownstone vintage",
    description: "Kling 3.0 Pro 8s master. Source: photo-nyc-brownstone-empire-vintage. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-19-brownstone-vintage.mp4",
    filename: "short-c20-19-brownstone-vintage.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "1ba7cf30-fd6c-4f39-80d8-707ce34b2fe8",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-20-bedroom-santa-moon",
    title: "Master · 20 bedroom santa moon",
    description: "Kling 3.0 Pro 8s master. Source: photo-magical-bedroom-santa-moon. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-20-bedroom-santa-moon.mp4",
    filename: "short-c20-20-bedroom-santa-moon.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "b5d78126-ea46-49d6-a16e-bfeb6c53a33c",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-03-train-grand-central",
    title: "Master · 03 train grand central",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-train-grand-central-chrysler. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-03-train-grand-central.mp4",
    filename: "short-c20-03-train-grand-central.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "805b6c59-60a3-4736-a424-dd551b2b7e06",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-14-stairs-morning",
    title: "Master · 14 stairs morning",
    description: "Kling 3.0 Pro 8s master. Source: photo-christmas-morning-stairs-child. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-14-stairs-morning.mp4",
    filename: "short-c20-14-stairs-morning.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "81c8daa2-bd9f-4ca0-90f6-1f3db5a673ef",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
  {
    id: "short-c20-15-family-dinner",
    title: "Master · 15 family dinner",
    description: "Kling 3.0 Pro 8s master. Source: photo-family-christmas-dinner-charlie-brown. QC pass.",
    src: "/assets/christmas/christmas-20-batch/masters/short-c20-15-family-dinner.mp4",
    filename: "short-c20-15-family-dinner.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 8,
    model: "kling-video/v3.0/pro/image-to-video",
    jobId: "cbff7813-a055-4969-b308-e20f32f1685c",
    costUsd: 0.493,
    tags: [...C20_TAGS, "short_master"],
  },
];

export const CHRISTMAS_20_FINISHED: LibraryVideo[] = [
  {
    id: "short-c20-01-ny-awning-finished",
    title: "Finished 8s · short-c20-01-ny-awning",
    description: "Christmas in New York just hits different.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-01-ny-awning.mp4",
    filename: "short-c20-01-ny-awning.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-02-train-nyc-clock-finished",
    title: "Finished 8s · short-c20-02-train-nyc-clock",
    description: "Your train leaves for Christmas at midnight.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-02-train-nyc-clock.mp4",
    filename: "short-c20-02-train-nyc-clock.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-03-train-grand-central-finished",
    title: "Finished 8s · short-c20-03-train-grand-central",
    description: "All aboard for the coziest arrival in the city.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-03-train-grand-central.mp4",
    filename: "short-c20-03-train-grand-central.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-04-viaduct-sunset-peaks-finished",
    title: "Finished 8s · short-c20-04-viaduct-sunset-peaks",
    description: "Christmas Train Journey through the peaks.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-04-viaduct-sunset-peaks.mp4",
    filename: "short-c20-04-viaduct-sunset-peaks.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-05-mansion-gwagon-finished",
    title: "Finished 8s · short-c20-05-mansion-gwagon",
    description: "Would you spend Christmas here?",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-05-mansion-gwagon.mp4",
    filename: "short-c20-05-mansion-gwagon.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-06-viaduct-village-finished",
    title: "Finished 8s · short-c20-06-viaduct-village",
    description: "Which Christmas would you choose — alpine edition.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-06-viaduct-village.mp4",
    filename: "short-c20-06-viaduct-village.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-07-station-traveler-finished",
    title: "Finished 8s · short-c20-07-station-traveler",
    description: "POV: you're catching the Christmas express.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-07-station-traveler.mp4",
    filename: "short-c20-07-station-traveler.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-08-radio-city-finished",
    title: "Finished 8s · short-c20-08-radio-city",
    description: "Radio City nights in the snow hit different.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-08-radio-city.mp4",
    filename: "short-c20-08-radio-city.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-09-penthouse-tom-jerry-finished",
    title: "Finished 8s · short-c20-09-penthouse-tom-jerry",
    description: "Imagine waking up here on Christmas morning.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-09-penthouse-tom-jerry.mp4",
    filename: "short-c20-09-penthouse-tom-jerry.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-10-penthouse-empire-finished",
    title: "Finished 8s · short-c20-10-penthouse-empire",
    description: "The coziest Christmas imaginable — city edition.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-10-penthouse-empire.mp4",
    filename: "short-c20-10-penthouse-empire.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-11-mansion-gate-finished",
    title: "Finished 8s · short-c20-11-mansion-gate",
    description: "Would you spend Christmas behind these gates?",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-11-mansion-gate.mp4",
    filename: "short-c20-11-mansion-gate.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-12-alpine-cabin-finished",
    title: "Finished 8s · short-c20-12-alpine-cabin",
    description: "The coziest Christmas imaginable — mountain edition.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-12-alpine-cabin.mp4",
    filename: "short-c20-12-alpine-cabin.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-13-home-alone-tv-finished",
    title: "Finished 8s · short-c20-13-home-alone-tv",
    description: "POV: Christmas morning and you're 8 again.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-13-home-alone-tv.mp4",
    filename: "short-c20-13-home-alone-tv.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-14-stairs-morning-finished",
    title: "Finished 8s · short-c20-14-stairs-morning",
    description: "Take me back to Christmas in the 90s.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-14-stairs-morning.mp4",
    filename: "short-c20-14-stairs-morning.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-15-family-dinner-finished",
    title: "Finished 8s · short-c20-15-family-dinner",
    description: "This is what Christmas felt like growing up.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-15-family-dinner.mp4",
    filename: "short-c20-15-family-dinner.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-16-library-dog-finished",
    title: "Finished 8s · short-c20-16-library-dog",
    description: "Imagine waking up here on Christmas morning.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-16-library-dog.mp4",
    filename: "short-c20-16-library-dog.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-17-saks-rockefeller-finished",
    title: "Finished 8s · short-c20-17-saks-rockefeller",
    description: "Christmas in New York just hits different.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-17-saks-rockefeller.mp4",
    filename: "short-c20-17-saks-rockefeller.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-18-train-carriage-finished",
    title: "Finished 8s · short-c20-18-train-carriage",
    description: "Your train leaves for Christmas at midnight.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-18-train-carriage.mp4",
    filename: "short-c20-18-train-carriage.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-19-brownstone-vintage-finished",
    title: "Finished 8s · short-c20-19-brownstone-vintage",
    description: "Take me back to Christmas in the 90s.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-19-brownstone-vintage.mp4",
    filename: "short-c20-19-brownstone-vintage.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "short-c20-20-bedroom-santa-moon-finished",
    title: "Finished 8s · short-c20-20-bedroom-santa-moon",
    description: "POV: you still believe on Christmas Eve.",
    src: "/assets/christmas/christmas-20-batch/finished/micro-8s/short-c20-20-bedroom-santa-moon.mp4",
    filename: "short-c20-20-bedroom-santa-moon.mp4",
    category: "christmas_reels",
    kind: "short",
    durationSeconds: 7.83,
    tags: [...C20_TAGS, "micro-short", "has-music"],
  },
  {
    id: "reel-c20-16s-01-nyc-streets",
    title: "Reel 16s · reel-c20-16s-01-nyc-streets",
    description: "Christmas in New York just hits different.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-01-nyc-streets.mp4",
    filename: "reel-c20-16s-01-nyc-streets.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-02-nyc-luxury",
    title: "Reel 16s · reel-c20-16s-02-nyc-luxury",
    description: "Would you spend Christmas here?",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-02-nyc-luxury.mp4",
    filename: "reel-c20-16s-02-nyc-luxury.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-03-trains-nyc",
    title: "Reel 16s · reel-c20-16s-03-trains-nyc",
    description: "Your train leaves for Christmas at midnight.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-03-trains-nyc.mp4",
    filename: "reel-c20-16s-03-trains-nyc.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-04-alpine-trains",
    title: "Reel 16s · reel-c20-16s-04-alpine-trains",
    description: "Christmas Train Journey through the Alps.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-04-alpine-trains.mp4",
    filename: "reel-c20-16s-04-alpine-trains.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-05-train-cozy",
    title: "Reel 16s · reel-c20-16s-05-train-cozy",
    description: "All aboard for the coziest ride home.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-05-train-cozy.mp4",
    filename: "reel-c20-16s-05-train-cozy.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-06-penthouse",
    title: "Reel 16s · reel-c20-16s-06-penthouse",
    description: "Imagine waking up here on Christmas morning.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-06-penthouse.mp4",
    filename: "reel-c20-16s-06-penthouse.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-07-nostalgia-morning",
    title: "Reel 16s · reel-c20-16s-07-nostalgia-morning",
    description: "POV: Christmas morning and you're 8 again.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-07-nostalgia-morning.mp4",
    filename: "reel-c20-16s-07-nostalgia-morning.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-08-family-home",
    title: "Reel 16s · reel-c20-16s-08-family-home",
    description: "This is what Christmas felt like growing up.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-08-family-home.mp4",
    filename: "reel-c20-16s-08-family-home.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-09-nyc-classic",
    title: "Reel 16s · reel-c20-16s-09-nyc-classic",
    description: "Take me back to Christmas in New York.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-09-nyc-classic.mp4",
    filename: "reel-c20-16s-09-nyc-classic.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-16s-10-magical-cozy",
    title: "Reel 16s · reel-c20-16s-10-magical-cozy",
    description: "The coziest Christmas imaginable.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-16s/reel-c20-16s-10-magical-cozy.mp4",
    filename: "reel-c20-16s-10-magical-cozy.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-16s", "has-music"],
  },
  {
    id: "reel-c20-32s-01-nyc",
    title: "Reel 32s · reel-c20-32s-01-nyc",
    description: "Christmas in New York just hits different.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-32s/reel-c20-32s-01-nyc.mp4",
    filename: "reel-c20-32s-01-nyc.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-32s", "has-music"],
  },
  {
    id: "reel-c20-32s-02-train-journey",
    title: "Reel 32s · reel-c20-32s-02-train-journey",
    description: "Your train leaves for Christmas at midnight.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-32s/reel-c20-32s-02-train-journey.mp4",
    filename: "reel-c20-32s-02-train-journey.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-32s", "has-music"],
  },
  {
    id: "reel-c20-32s-03-kid-nostalgia",
    title: "Reel 32s · reel-c20-32s-03-kid-nostalgia",
    description: "POV: Christmas morning and you're 8 again.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-32s/reel-c20-32s-03-kid-nostalgia.mp4",
    filename: "reel-c20-32s-03-kid-nostalgia.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-32s", "has-music"],
  },
  {
    id: "reel-c20-32s-04-coziest",
    title: "Reel 32s · reel-c20-32s-04-coziest",
    description: "The coziest Christmas imaginable.",
    src: "/assets/christmas/christmas-20-batch/finished/reels-32s/reel-c20-32s-04-coziest.mp4",
    filename: "reel-c20-32s-04-coziest.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-32s", "has-music"],
  },
  {
    id: "reel-c20-32s-05-pick-one",
    title: "Reel 32s · reel-c20-32s-05-pick-one",
    description: "Which Christmas would you choose?",
    src: "/assets/christmas/christmas-20-batch/finished/reels-32s/reel-c20-32s-05-pick-one.mp4",
    filename: "reel-c20-32s-05-pick-one.mp4",
    category: "christmas_reels",
    kind: "reel",
    tags: [...C20_TAGS, "reel-32s", "has-music"],
  },
];

/** Finished batch reels (16s + 32s) — listed first in Christmas Reels · Reels. */
export const CHRISTMAS_20_REELS: LibraryVideo[] = CHRISTMAS_20_FINISHED.filter((v) => v.kind === "reel");

/** Finished micro-shorts with music — listed first in Christmas Reels · Shorts. */
export const CHRISTMAS_20_PUBLISH_SHORTS: LibraryVideo[] = CHRISTMAS_20_FINISHED.filter((v) => v.kind === "short");
