/** Library montage reels assembled 2026-09-28 from existing short clips only (no new AI video). */
import type { LibraryVideo } from "./catalog";

const TAGS = ["christmas", "library-montage-sep28", "has-music", "review-only", "existing-clips-only"] as const;

export const LIBRARY_MONTAGE_SEP28_REELS: LibraryVideo[] = [
  {
    id: "reel-lib-montage-01-express-rush",
    title: "Express Rush · 17s montage",
    description: "Energetic train crescendo — flash hook → alpine hold → station payoff · 16.1s 1080×1920 H.264 + AAC. Music: joy-to-the-world-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-01-express-rush.mp4",
    filename: "reel-lib-montage-01-express-rush.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 16.10,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-01-express-rush.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 32810362,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "upbeat"],
    costUsd: 0,
    clipsUsed: ["short-cx-05-santa-gifts", "short-cx-04-aurora-viaduct", "short-npj-04-viaduct-wide", "short-c20-06-viaduct-village", "short-cx-01-night-viaduct", "short-c20-04-viaduct-sunset-peaks", "short-npj-01-train-window", "short-cx-03-station"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-02-fireside-embrace",
    title: "Fireside Embrace · 16s montage",
    description: "Cinematic emotional — slow cozy open, tender middle flashes, cabin hero · 15.6s 1080×1920 H.264 + AAC. Music: o-holy-night-lofi.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-02-fireside-embrace.mp4",
    filename: "reel-lib-montage-02-fireside-embrace.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.63,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-02-fireside-embrace.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 31643597,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "emotional"],
    costUsd: 0,
    clipsUsed: ["short-c20-16-library-dog", "short-c20-14-stairs-morning", "short-c20-13-home-alone-tv", "short-christmas-master-04", "short-cozy-04-tom-jerry-storm-sleep", "short-c20-15-family-dinner", "short-c20-12-alpine-cabin"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-03-nyc-luxe",
    title: "NYC Luxe Snow · 19s montage",
    description: "Premium Manhattan atmospheric — iconic hook stack, mansion breathing room · 17.7s 1080×1920 H.264 + AAC. Music: we-three-kings-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-03-nyc-luxe.mp4",
    filename: "reel-lib-montage-03-nyc-luxe.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 17.73,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-03-nyc-luxe.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 35447226,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "cinematic"],
    costUsd: 0,
    clipsUsed: ["short-c20-17-saks-rockefeller", "short-c20-08-radio-city", "short-nyc-winter-1990-02-rockefeller-tree", "short-c20-05-mansion-gwagon", "short-c20-10-penthouse-empire", "short-c20-01-ny-awning", "short-cinematic-plaza-hotel", "short-c20-11-mansion-gate", "short-c20-10-penthouse-empire"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-04-santa-sprint",
    title: "Santa Sprint · 16s montage",
    description: "Magical workshop energy — sleigh hook, rapid workshop montage, London hero · 15.2s 1080×1920 H.264 + AAC. Music: the-first-noel-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-04-santa-sprint.mp4",
    filename: "reel-lib-montage-04-santa-sprint.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.20,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-04-santa-sprint.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 29689412,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "magical"],
    costUsd: 0,
    clipsUsed: ["short-santa-02-sleigh", "short-cinematic-santa-london", "short-cx-05-santa-gifts", "short-npj-09-window-sleigh", "short-santa-01-workshop", "short-cinematic-workshop", "short-npj-07-workshop-list", "short-npj-06-workshop-street", "short-cinematic-santa-london", "short-santa-02-sleigh"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-05-aurora-pulse",
    title: "Aurora Pulse · 18s montage",
    description: "Slow aurora hook → accelerating North Pole middle → village payoff · 15.4s 1080×1920 H.264 + AAC. Music: auld-lang-syne-lofi.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-05-aurora-pulse.mp4",
    filename: "reel-lib-montage-05-aurora-pulse.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.40,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-05-aurora-pulse.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 31418519,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "nostalgic"],
    costUsd: 0,
    clipsUsed: ["short-npj-03-aurora-window", "short-npj-02-station", "short-npj-05-village-arrival", "short-christmas-master-10", "short-christmas-master-06", "short-npj-08-wrapping", "short-npj-10-snowman", "short-npj-11-plaza", "short-npj-05-village-arrival"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-06-alpine-dawn",
    title: "Alpine Dawn · 16s montage",
    description: "Swiss luxury calm — sunrise hook, fireplace linger, chalet outro · 15.2s 1080×1920 H.264 + AAC. Music: angels-we-have-heard-lofi.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-06-alpine-dawn.mp4",
    filename: "reel-lib-montage-06-alpine-dawn.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.17,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-06-alpine-dawn.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 30145337,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "warm"],
    costUsd: 0,
    clipsUsed: ["short-swiss-alpine-01-sunrise-chalet", "short-c20-06-viaduct-village", "short-swiss-alpine-02-fireplace", "short-pick-one-03-alpine-chalet", "short-global-02-alps", "short-swiss-alpine-03-christmas-tree", "short-c20-04-viaduct-sunset-peaks", "short-swiss-alpine-01-sunrise-chalet"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-07-global-flash",
    title: "Global Flash · 17s montage",
    description: "Rapid world tour — Lapland hook, recognizable icons, White House hold · 15.2s 1080×1920 H.264 + AAC. Music: joy-to-the-world-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-07-global-flash.mp4",
    filename: "reel-lib-montage-07-global-flash.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.17,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-07-global-flash.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 31530152,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "upbeat"],
    costUsd: 0,
    clipsUsed: ["short-global-01-lapland", "short-cinematic-polar-express", "short-global-04-plaza", "short-cinematic-coca-cola-truck", "short-global-05-white-house", "short-cinematic-santa-london", "short-global-03-home", "short-cinematic-plaza-hotel", "short-global-02-alps", "short-cinematic-home-alone-house", "short-global-04-plaza"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-08-cozy-cartoon",
    title: "Cozy Cartoon Storm · 15s montage",
    description: "Playful Tom & Jerry storm bed → family warmth → storm sleep payoff · 15.3s 1080×1920 H.264 + AAC. Music: god-rest-ye-merry-gentlemen-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-08-cozy-cartoon.mp4",
    filename: "reel-lib-montage-08-cozy-cartoon.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 15.33,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-08-cozy-cartoon.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 29481831,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "cozy"],
    costUsd: 0,
    clipsUsed: ["short-cozy-05-tom-jerry-storm-bed", "short-c20-12-alpine-cabin", "short-cozy-03-tom-jerry-living-room", "short-cozy-02-family-boardgame", "short-cozy-04-tom-jerry-storm-sleep", "short-c20-09-penthouse-tom-jerry", "short-cozy-03-tom-jerry-living-room", "short-cozy-05-tom-jerry-storm-bed"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-09-pick-your-world",
    title: "Pick Your World · 18s montage",
    description: "Luxury fantasy choices — mansion hook, pick-one rapid cuts, cabin outro · 16.3s 1080×1920 H.264 + AAC. Music: the-first-noel-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-09-pick-your-world.mp4",
    filename: "reel-lib-montage-09-pick-your-world.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 16.30,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-09-pick-your-world.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 32716365,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "magical"],
    costUsd: 0,
    clipsUsed: ["short-pick-one-04-christmas-mansion", "short-pick-one-02-nyc-penthouse", "short-pick-one-01-cozy-cabin", "short-pick-one-03-alpine-chalet", "short-c20-05-mansion-gwagon", "short-c20-19-brownstone-vintage", "short-c20-07-station-traveler", "short-pick-one-02-nyc-penthouse", "short-pick-one-01-cozy-cabin", "short-pick-one-03-alpine-chalet"],
    productionId: "library-montage-sep28",
  },
  {
    id: "reel-lib-montage-10-iconic-slowburn",
    title: "Iconic Slow Burn · 20s montage",
    description: "Premium cinematic icons — slow Rockefeller open, classic middle, workshop hero · 16.1s 1080×1920 H.264 + AAC. Music: we-three-kings-synthwave.mp3. Assembled from existing Library shorts — $0 generation.",
    src: "/assets/christmas/library-montage-sep28/final/reel-lib-montage-10-iconic-slowburn.mp4",
    filename: "reel-lib-montage-10-iconic-slowburn.mp4",
    category: "christmas_reels",
    kind: "reel",
    durationSeconds: 16.10,
    poster: "/assets/christmas/library-montage-sep28/posters/reel-lib-montage-10-iconic-slowburn.jpg",
    width: 1080,
    height: 1920,
    fileSizeBytes: 31257671,
    createdAt: "2026-09-28T19:45:00Z",
    tags: [...TAGS, "cinematic"],
    costUsd: 0,
    clipsUsed: ["short-cinematic-rockefeller", "short-cinematic-home-alone-house", "short-cinematic-grinch", "short-christmas-master-08", "short-christmas-master-09", "short-cinematic-polar-express", "short-npj-04-viaduct-wide", "short-christmas-master-01", "short-cinematic-workshop"],
    productionId: "library-montage-sep28",
  },
];

