/** i18n-ready copy for the Christmas Card Maker. Locale-aware — do not concatenate English fragments. */

import type { LocaleCode } from "./taxonomy";

type Dict = Record<string, string>;

const EN: Dict = {
  "seo.title": "Christmas Card Maker | Personalized Christmas Cards",
  "seo.description":
    "Create a personalized Christmas card they’ll want to keep — choose a design, add your message, and share or download.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Christmas",
  "breadcrumb.cards": "Cards",
  "hero.kicker": "Christmas Card Maker",
  "hero.h1": "Create a Christmas Card They’ll Want to Keep",
  "hero.lede": "Add your photo, choose a Christmas style and write something personal.",
  "hero.cta": "Create My Card",
  "hero.secondary": "See Examples",
  "hero.promise": "Create a Christmas Card That Actually Feels Personal",
  "hero.support": "Turn a favorite photo and a few words into a beautiful Christmas card for the people you love.",
  "hero.front": "Front",
  "hero.inside": "Inside",
  "hero.open": "Peek inside",
  "hero.close": "Show front",
  "examples.h2": "Christmas Card Examples",
  "examples.lede": "Curated demos — not customer cards. Family, couple, pet, elegant, funny, and portrait-to-card.",
  "examples.demoBadge": "Demo example",
  "create.h2": "Create a Personalized Christmas Card",
  "create.lede": "A simple path from photo to finished Christmas card.",
  "step.type": "Card type",
  "step.photo": "Photo",
  "step.design": "Design",
  "step.message": "Message",
  "step.preview": "Preview",
  "step.result": "Your card",
  "type.ask": "What kind of Christmas card are you creating?",
  "photo.ask": "Add a favorite photo",
  "photo.upload": "Upload Photo",
  "photo.usePortrait": "Use My Christmas Portrait",
  "photo.change": "Change photo",
  "photo.remove": "Remove photo",
  "photo.hint": "JPEG, PNG or WebP up to 8MB. Rendered on your device.",
  "photo.portraitLoaded": "Your Christmas portrait is ready for this card.",
  "photo.skipHint": "You can continue without a photo and add one later.",
  "photo.noneAvailable": "No recent Christmas portrait found on this device.",
  "photo.uploadFailed": "We couldn’t upload that photo. Please try again.",
  "design.ask": "Choose a Christmas design",
  "design.lede": "A curated set of strong directions — not a template marketplace.",
  "message.ask": "What would you like to say?",
  "message.writeOwn": "Write my own",
  "message.helpWrite": "Help me write it",
  "message.who": "Who is it for?",
  "message.tone": "Tone",
  "message.generate": "Suggest messages",
  "message.generating": "Finding the right words…",
  "message.retry": "Try again",
  "message.suggestions": "Suggestions",
  "message.useSuggestion": "Use this",
  "message.failed": "We couldn’t generate suggestions right now. Your typed message is still saved — try again anytime.",
  "message.moreInspiration": "Need inspiration? Explore Christmas Messages",
  "message.placeholder": "Write a Christmas message they’ll want to keep…",
  "message.started": "Message",
  "personalize.to": "Recipient name",
  "personalize.from": "From / family name",
  "personalize.year": "Year",
  "personalize.toPlaceholder": "e.g. Grandma",
  "personalize.fromPlaceholder": "e.g. Emma, Noah & Mum and Dad",
  "preview.h2": "Preview your Christmas card",
  "preview.lede": "The card updates as you change photo, design and message.",
  "preview.create": "Create My Christmas Card",
  "preview.creating": "Creating your card…",
  "preview.edit": "Keep editing",
  "preview.mobileEdit": "Edit",
  "preview.mobilePreview": "Preview",
  "preview.failed": "We couldn’t create that card. Your work is still here — please try again.",
  "result.h2": "Your Christmas card",
  "result.lede": "Download it, share it, or tweak anything and create again.",
  "result.download": "Download",
  "result.share": "Share",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copy page link",
  "result.copied": "Link copied",
  "result.edit": "Edit",
  "result.another": "Create Another",
  "result.shareFailed": "Sharing didn’t work this time. You can download the card or copy the page link instead.",
  "result.formatNote": "Digital PNG card — download or share. Print delivery is not included.",
  "nav.back": "Back",
  "nav.continue": "Continue",
  "nav.skipPhoto": "Continue without photo",
  "how.h2": "How to Make a Christmas Card Online",
  "how.1.title": "Add your photo",
  "how.1.body": "Use your own photo or a Christmas portrait.",
  "how.2.title": "Choose a design",
  "how.2.body": "Pick the Christmas style you love.",
  "how.3.title": "Make it personal",
  "how.3.body": "Add a message and recipient.",
  "how.4.title": "Share the magic",
  "how.4.body": "Download or send your finished Christmas card.",
  "photos.h2": "Create Cards With Your Family, Couple or Pet Photos",
  "photos.lede": "The finished card stays the hero — your photo, a Christmas design, and words that feel like you.",
  "messages.h2": "Christmas Card Messages",
  "messages.lede": "Write your own, or get a few locale-aware suggestions without leaving this page.",
  "portrait.h2": "Use Your Christmas Portrait",
  "portrait.lede":
    "Already created a Christmas portrait? Bring it into the card maker and finish with a message. Portrait handoff is supported from the Christmas Photo Generator.",
  "portrait.cta": "Use My Christmas Portrait",
  "portrait.make": "Create a Christmas portrait first",
  "geo.h2": "What is an online Christmas card maker?",
  "geo.body":
    "An online Christmas card maker lets you create a personalized Christmas card with a photo, a festive design, and your own message. On TheDigitalGifter, you can upload a photo or use a Christmas portrait, choose a style, write or get message help, then download a PNG or share the card digitally.",
  "faq.h2": "Frequently Asked Questions",
  "faq.what.q": "What is an online Christmas card maker?",
  "faq.what.a":
    "An online Christmas card maker lets you combine a photo, Christmas design and personalized message into a card that can be downloaded or shared digitally.",
  "faq.how.q": "How do I create a Christmas card?",
  "faq.how.a":
    "Choose a card type, add a photo (optional), pick a Christmas design, write or generate a message, preview the card, then download or share the finished PNG.",
  "faq.photo.q": "Can I use my own photo?",
  "faq.photo.a": "Yes. Upload a JPEG, PNG or WebP photo up to 8MB. Rendering happens on your device.",
  "faq.portrait.q": "Can I use a Christmas portrait I already created?",
  "faq.portrait.a":
    "Yes. If you created a Christmas Portrait on this device, you can use it directly — or open Cards from the portrait result with Turn This Into a Christmas Card.",
  "faq.family.q": "Can I create a family Christmas card?",
  "faq.family.a": "Yes. Choose the Family card type and a cozy or classic design, then add your family photo and message.",
  "faq.pet.q": "Can I make a pet Christmas card?",
  "faq.pet.a": "Yes. Choose Pet, add your pet photo (or pet Christmas portrait), and pick a playful premium design.",
  "faq.message.q": "Can you help me write a Christmas message?",
  "faq.message.a":
    "Yes. Use Help me write it on this page for a few suggestions, or explore the full Christmas Messages generator for more options.",
  "faq.download.q": "Can I download my card?",
  "faq.download.a": "Yes. Finished cards download as a PNG image sized for digital sharing.",
  "faq.share.q": "Can I share it online?",
  "faq.share.a":
    "Yes. Use native share when your browser supports it, or share via WhatsApp, email, or by copying the Cards page link. Public share metadata does not include your personal message or recipient name.",
  "faq.edit.q": "Can I edit it after creating it?",
  "faq.edit.a": "Yes. Use Edit to return to your draft and create again. Your message and settings stay on this device.",
  "faq.styles.q": "Which Christmas card styles are available?",
  "faq.styles.a":
    "Classic Christmas, Elegant Gold, Cozy Family, Snowy Christmas, Romantic Christmas, Funny/Pet, Minimal Christmas, and Vintage Christmas.",
  "faq.print.q": "Is it printable?",
  "faq.print.a":
    "You can download a high-resolution PNG suitable for personal printing. Print fulfillment and postal delivery are not offered on this page.",
  "faq.surfaces.q": "Does the card have a front, inside and back?",
  "faq.surfaces.a":
    "Today’s product creates a single digital PNG card (photo, greeting and message on one surface), with small TheDigitalGifter branding. Multi-page front/inside/back layouts are not supported yet.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Interactive Christmas card example",
  "a11y.livePreview": "Live Christmas card preview",
  "a11y.progress": "Card creation progress",
};

const RO: Dict = {
  "seo.title": "Creator de Carduri de Crăciun | Carduri personalizate | TheDigitalGifter",
  "seo.description":
    "Creează un card de Crăciun personalizat cu fotografia ta, un design frumos și un mesaj din suflet. Descarcă sau trimite cardul în câteva minute.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Crăciun",
  "breadcrumb.cards": "Carduri",
  "hero.kicker": "Creator de carduri de Crăciun",
  "hero.h1": "Creează un card de Crăciun pe care vor să-l păstreze",
  "hero.lede": "Adaugă fotografia, alege un stil de Crăciun și scrie ceva personal.",
  "hero.cta": "Creează cardul meu",
  "hero.secondary": "Vezi exemple",
  "hero.promise": "Creează un card de Crăciun care chiar se simte personal",
  "hero.support": "Transformă o fotografie preferată și câteva cuvinte într-un card frumos pentru cei dragi.",
  "hero.front": "Față",
  "hero.inside": "Interior",
  "hero.open": "Privește înăuntru",
  "hero.close": "Arată fața",
  "examples.h2": "Exemple de carduri de Crăciun",
  "examples.lede": "Demo-uri curate — nu carduri ale clienților. Familie, cuplu, animal, elegant, amuzant și portret → card.",
  "examples.demoBadge": "Exemplu demo",
  "create.h2": "Creează un card de Crăciun personalizat",
  "create.lede": "Un drum simplu de la fotografie la cardul final.",
  "step.type": "Tip card",
  "step.photo": "Fotografie",
  "step.design": "Design",
  "step.message": "Mesaj",
  "step.preview": "Previzualizare",
  "step.result": "Cardul tău",
  "type.ask": "Ce fel de card de Crăciun creezi?",
  "photo.ask": "Adaugă o fotografie preferată",
  "photo.upload": "Încarcă fotografia",
  "photo.usePortrait": "Folosește portretul meu de Crăciun",
  "photo.change": "Schimbă fotografia",
  "photo.remove": "Elimină fotografia",
  "photo.hint": "JPEG, PNG sau WebP până la 8MB. Randare pe dispozitivul tău.",
  "photo.portraitLoaded": "Portretul tău de Crăciun este gata pentru acest card.",
  "photo.skipHint": "Poți continua fără fotografie și să o adaugi mai târziu.",
  "photo.noneAvailable": "Nu am găsit un portret recent de Crăciun pe acest dispozitiv.",
  "photo.uploadFailed": "Nu am putut încărca fotografia. Te rugăm să încerci din nou.",
  "design.ask": "Alege un design de Crăciun",
  "design.lede": "O selecție curată de direcții puternice — nu un marketplace de template-uri.",
  "message.ask": "Ce ai vrea să spui?",
  "message.writeOwn": "Scriu eu",
  "message.helpWrite": "Ajută-mă să scriu",
  "message.who": "Pentru cine este?",
  "message.tone": "Ton",
  "message.generate": "Sugerează mesaje",
  "message.generating": "Căutăm cuvintele potrivite…",
  "message.retry": "Încearcă din nou",
  "message.suggestions": "Sugestii",
  "message.useSuggestion": "Folosește",
  "message.failed": "Nu am putut genera sugestii acum. Mesajul tău scris rămâne salvat — încearcă oricând din nou.",
  "message.moreInspiration": "Ai nevoie de inspirație? Explorează Mesaje de Crăciun",
  "message.placeholder": "Scrie un mesaj de Crăciun pe care vor să-l păstreze…",
  "message.started": "Mesaj",
  "personalize.to": "Numele destinatarului",
  "personalize.from": "De la / familia",
  "personalize.year": "Anul",
  "personalize.toPlaceholder": "ex: Bunica",
  "personalize.fromPlaceholder": "ex: Emma, Noah & Mama și Tata",
  "preview.h2": "Previzualizează cardul de Crăciun",
  "preview.lede": "Cardul se actualizează când schimbi fotografia, designul și mesajul.",
  "preview.create": "Creează cardul meu de Crăciun",
  "preview.creating": "Cream cardul…",
  "preview.edit": "Continuă editarea",
  "preview.mobileEdit": "Editează",
  "preview.mobilePreview": "Previzualizare",
  "preview.failed": "Nu am putut crea cardul. Munca ta e încă aici — încearcă din nou.",
  "result.h2": "Cardul tău de Crăciun",
  "result.lede": "Descarcă-l, trimite-l sau ajustează orice și creează din nou.",
  "result.download": "Descarcă",
  "result.share": "Trimite",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copiază linkul paginii",
  "result.copied": "Link copiat",
  "result.edit": "Editează",
  "result.another": "Creează altul",
  "result.shareFailed": "Trimiterea nu a reușit. Poți descărca cardul sau copia linkul paginii.",
  "result.formatNote": "Card digital PNG — descarcă sau trimite. Livrarea tipărită nu este inclusă.",
  "nav.back": "Înapoi",
  "nav.continue": "Continuă",
  "nav.skipPhoto": "Continuă fără fotografie",
  "how.h2": "Cum faci un card de Crăciun online",
  "how.1.title": "Adaugă fotografia",
  "how.1.body": "Folosește fotografia ta sau un portret de Crăciun.",
  "how.2.title": "Alege un design",
  "how.2.body": "Alege stilul de Crăciun care-ți place.",
  "how.3.title": "Personalizează",
  "how.3.body": "Adaugă un mesaj și destinatarul.",
  "how.4.title": "Împarte magia",
  "how.4.body": "Descarcă sau trimite cardul final.",
  "photos.h2": "Creează carduri cu fotografii de familie, cuplu sau animale",
  "photos.lede": "Cardul final rămâne eroul — fotografia ta, un design de Crăciun și cuvinte care sună ca tine.",
  "messages.h2": "Mesaje pentru carduri de Crăciun",
  "messages.lede": "Scrie tu, sau primește câteva sugestii în limba aleasă, fără să părăsești pagina.",
  "portrait.h2": "Ai creat deja un portret de Crăciun?",
  "portrait.lede":
    "Folosește portretul în makerul de carduri și termină cu un mesaj. Predarea din generatorul de portrete este suportată.",
  "portrait.cta": "Folosește portretul meu de Crăciun",
  "portrait.make": "Creează mai întâi un portret de Crăciun",
  "geo.h2": "Ce este un creator online de carduri de Crăciun?",
  "geo.body":
    "Un creator online de carduri de Crăciun îți permite să creezi un card personalizat cu o fotografie, un design festiv și mesajul tău. Pe TheDigitalGifter poți încărca o fotografie sau un portret de Crăciun, alege un stil, scrie sau cere ajutor pentru mesaj, apoi descarci PNG-ul sau îl trimiți digital.",
  "faq.h2": "Întrebări frecvente",
  "faq.what.q": "Ce este un creator online de carduri de Crăciun?",
  "faq.what.a":
    "Un creator online de carduri de Crăciun îți permite să combini o fotografie, un design de Crăciun și un mesaj personalizat într-un card pe care îl poți descărca sau trimite digital.",
  "faq.how.q": "Cum creez un card de Crăciun?",
  "faq.how.a":
    "Alegi tipul de card, adaugi o fotografie (opțional), alegi un design, scrii sau generezi un mesaj, previzualizezi, apoi descarci sau trimiți PNG-ul final.",
  "faq.photo.q": "Pot folosi fotografia mea?",
  "faq.photo.a": "Da. Încarcă un JPEG, PNG sau WebP până la 8MB. Randarea se face pe dispozitivul tău.",
  "faq.portrait.q": "Pot folosi un portret de Crăciun pe care l-am creat deja?",
  "faq.portrait.a":
    "Da. Dacă ai creat un portret pe acest dispozitiv, îl poți folosi direct — sau deschide Carduri din rezultatul portretului cu Transformă într-un card de Crăciun.",
  "faq.family.q": "Pot crea un card de Crăciun pentru familie?",
  "faq.family.a": "Da. Alege tipul Familie și un design cozy sau clasic, apoi adaugă fotografia și mesajul.",
  "faq.pet.q": "Pot face un card cu animalul de companie?",
  "faq.pet.a": "Da. Alege Pet, adaugă fotografia (sau portretul pet) și un design jucăuș, dar premium.",
  "faq.message.q": "Mă puteți ajuta să scriu un mesaj de Crăciun?",
  "faq.message.a":
    "Da. Folosește Ajută-mă să scriu pe această pagină pentru câteva sugestii, sau explorează generatorul complet de Mesaje de Crăciun.",
  "faq.download.q": "Pot descărca cardul?",
  "faq.download.a": "Da. Cardurile finalizate se descarcă ca imagine PNG, potrivită pentru trimitere digitală.",
  "faq.share.q": "Îl pot trimite online?",
  "faq.share.a":
    "Da. Folosește share-ul nativ când browserul îl suportă, sau WhatsApp, email, ori copiază linkul paginii. Metadatele publice nu includ mesajul personal sau numele destinatarului.",
  "faq.edit.q": "Pot edita după ce l-am creat?",
  "faq.edit.a": "Da. Folosește Editează ca să revii la ciornă și să creezi din nou. Mesajul și setările rămân pe acest dispozitiv.",
  "faq.styles.q": "Ce stiluri de carduri sunt disponibile?",
  "faq.styles.a":
    "Crăciun clasic, Aur elegant, Familie cozy, Crăciun înzăpezit, Crăciun romantic, Amuzant/Pet, Crăciun minimal și Crăciun vintage.",
  "faq.print.q": "Se poate tipări?",
  "faq.print.a":
    "Poți descărca un PNG la rezoluție bună, potrivit pentru tipărire personală. Livrarea tipărită și poștală nu sunt oferite pe această pagină.",
  "faq.surfaces.q": "Cardul are față, interior și spate?",
  "faq.surfaces.a":
    "Produsul de azi creează un singur card digital PNG (fotografie, urare și mesaj pe o suprafață), cu un branding mic TheDigitalGifter. Layout-urile multi-pagină față/interior/spate nu sunt încă suportate.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Exemplu interactiv de card de Crăciun",
  "a11y.livePreview": "Previzualizare live a cardului de Crăciun",
  "a11y.progress": "Progres creare card",
};

const TABLES: Partial<Record<LocaleCode, Dict>> = { en: EN, ro: RO };

export function cardsT(key: string, locale: LocaleCode = "en"): string {
  return TABLES[locale]?.[key] || TABLES.en?.[key] || key;
}

export const CARD_MAKER_FAQ_KEYS = [
  "faq.what",
  "faq.how",
  "faq.photo",
  "faq.portrait",
  "faq.family",
  "faq.pet",
  "faq.message",
  "faq.download",
  "faq.share",
  "faq.edit",
  "faq.styles",
  "faq.print",
  "faq.surfaces",
] as const;

export function cardsMakerSeo(locale: LocaleCode = "en") {
  return {
    title: cardsT("seo.title", locale),
    description: cardsT("seo.description", locale),
    url: "https://www.thedigitalgifter.com/christmas/cards",
    image: "https://www.thedigitalgifter.com/assets/christmas/christmas_card_open.webp",
  };
}

export function cardsMakerJsonLd(locale: LocaleCode = "en") {
  const seo = cardsMakerSeo(locale);
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${seo.url}#webpage`,
        url: seo.url,
        name: seo.title,
        description: seo.description,
        inLanguage: locale,
        isPartOf: { "@id": "https://www.thedigitalgifter.com/#website" },
        primaryImageOfPage: { "@type": "ImageObject", url: seo.image },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: cardsT("breadcrumb.christmas", locale),
            item: "https://www.thedigitalgifter.com/christmas",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: cardsT("breadcrumb.cards", locale),
            item: seo.url,
          },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: CARD_MAKER_FAQ_KEYS.map((base) => ({
          "@type": "Question",
          name: cardsT(`${base}.q`, locale),
          acceptedAnswer: {
            "@type": "Answer",
            text: cardsT(`${base}.a`, locale),
          },
        })),
      },
    ],
  };
}
