/** i18n-ready copy for the Christmas Card Maker. Locale-aware — do not concatenate English fragments. */

import type { LocaleCode } from "./taxonomy";

type Dict = Record<string, string>;

const EN: Dict = {
  "seo.title": "Christmas Card Maker | Create Personalized Cards | TheDigitalGifter",
  "seo.description":
    "Create a personalized Christmas card with your photo, Christmas style and heartfelt message. Download or share your finished card in minutes.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Christmas",
  "breadcrumb.cards": "Cards",
  "hero.kicker": "Christmas · Cards",
  "hero.h1": "Create a Christmas Card They’ll Want to Keep.",
  "hero.lede":
    "Choose a Christmas style, add your message and photo, then create a card ready to download or share.",
  "hero.cta": "Create My Christmas Card →",
  "hero.secondary": "Christmas Card Inspiration",
  "hero.promise": "Create a Christmas Card That Actually Feels Personal",
  "hero.support":
    "Turn a favorite photo and a few words into a beautiful Christmas card for the people you love.",
  "hero.giftNote": "A seasonal gift from TheDigitalGifter.",
  "hero.asideNote": "Small moments · Big connections",
  "hero.front": "Front",
  "hero.inside": "Inside",
  "hero.open": "Peek inside",
  "hero.close": "Show front",
  "examples.h2": "Christmas Card Inspiration",
  "examples.lede": "Editorial demos — family, couples, pets, elegant, funny, and classic keepsakes.",
  "examples.demoBadge": "Inspiration",
  "create.h2": "Create your Christmas card",
  "create.lede": "Style, message, photo — then create. The card stays the hero.",
  "step.type": "Card type",
  "step.photo": "Photo",
  "step.design": "Design",
  "step.message": "Message",
  "step.preview": "Preview",
  "step.result": "Your card",
  "type.ask": "What kind of Christmas card are you creating?",
  "photo.ask": "Add your photo",
  "photo.upload": "Upload Photo",
  "photo.usePortrait": "Use My Christmas Portrait",
  "photo.change": "Change photo",
  "photo.remove": "Remove photo",
  "photo.hint": "JPG, PNG or WebP",
  "photo.portraitLoaded": "Your Christmas portrait is ready for this card.",
  "photo.skipHint": "Optional — a photo makes the card feel like you.",
  "photo.noneAvailable": "No recent Christmas portrait found on this device.",
  "photo.uploadFailed": "We couldn’t upload that photo. Please try again.",
  "design.ask": "Christmas style",
  "design.lede": "Pick the design that fits your message.",
  "layout.ask": "Layout",
  "layout.dims": "Resolution",
  "message.ask": "Your Christmas message",
  "message.writeOwn": "Write my own",
  "message.helpWrite": "Need help writing it?",
  "message.who": "Who is it for?",
  "message.tone": "Tone",
  "message.generate": "Suggest a Message",
  "message.generating": "Finding the right words…",
  "message.retry": "Try again",
  "message.suggestions": "Suggestions",
  "message.useSuggestion": "Use this",
  "message.failed": "We couldn’t generate suggestions right now. Your typed message is still saved — try again anytime.",
  "message.moreInspiration": "Explore Christmas Messages",
  "message.placeholder":
    "Wishing you a magical Christmas filled with love, joy and unforgettable moments.",
  "message.started": "Message",
  "message.hideHelp": "Hide suggestions",
  "personalize.to": "To",
  "personalize.from": "From",
  "personalize.year": "Year",
  "personalize.toPlaceholder": "e.g. Family, Friends, Grandma…",
  "personalize.fromPlaceholder": "e.g. Paul",
  "preview.h2": "Your live Christmas card",
  "preview.lede": "Updates as you change style, message, photo, and names.",
  "preview.create": "Create My Christmas Card →",
  "preview.creating": "Creating your card…",
  "preview.edit": "Keep editing",
  "preview.mobileEdit": "Customize",
  "preview.mobilePreview": "Card",
  "preview.collapse": "Hide preview",
  "preview.expand": "Show card preview",
  "preview.failed": "We couldn’t create that card. Your work is still here — please try again.",
  "tone.elegant": "Elegant",
  "tone.short": "Short",
  "result.h2": "Your Christmas card",
  "result.lede": "Download it, share it, or tweak anything and create again.",
  "result.download": "Download",
  "result.share": "Share",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copy page link",
  "result.copied": "Link copied",
  "result.edit": "Edit",
  "result.another": "Create Another",
  "result.shareFailed": "Sharing didn’t work this time. You can download the card or copy the page link instead.",
  "result.formatNote": "Digital PNG card — download or share. Print delivery is not included.",
  "nav.back": "Back",
  "nav.continue": "Continue",
  "nav.skipPhoto": "Continue without photo",
  "how.h2": "How it works",
  "how.1.title": "Add your photo",
  "how.1.body": "Use your own photo or a TDG Christmas portrait.",
  "how.2.title": "Choose your Christmas style",
  "how.2.body": "Pick the design that fits your message.",
  "how.3.title": "Make it personal",
  "how.3.body": "Add recipient, sender and Christmas message.",
  "how.4.title": "Create & share",
  "how.4.body": "Download or send your finished card.",
  "photos.h2": "Personalized Christmas photo cards",
  "photos.lede":
    "Family Christmas cards, couple cards, pet cards — your photo stays the heart of a keepsake design.",
  "messages.h2": "Heartfelt Christmas card messages",
  "messages.lede": "Write your own, or get a few locale-aware suggestions without leaving this page.",
  "portrait.h2": "Already created a Christmas Portrait?",
  "portrait.lede": "Turn it into a beautiful Christmas card in seconds.",
  "portrait.cta": "Use My Christmas Portrait",
  "portrait.make": "Create a Christmas Portrait",
  "faq.h2": "Frequently Asked Questions",
  "faq.what.q": "What is an online Christmas card maker?",
  "faq.what.a":
    "An online Christmas card maker lets you combine a photo, Christmas design and personalized message into a card that can be downloaded or shared digitally.",
  "faq.how.q": "How do I create a Christmas card?",
  "faq.how.a":
    "Choose a Christmas style, add your message and optional photo, personalize To and From, then create your card and download or share the finished PNG.",
  "faq.photo.q": "Can I upload my own photo?",
  "faq.photo.a": "Yes. Upload a JPEG, PNG or WebP photo up to 8MB. Rendering happens on your device.",
  "faq.portrait.q": "Can I use a Christmas portrait I already created?",
  "faq.portrait.a":
    "Yes. If you created a Christmas Portrait on this device, you can use it directly — or open Cards from the portrait result with Turn This Into a Christmas Card.",
  "faq.family.q": "Can I make a family card?",
  "faq.family.a":
    "Yes. Choose a cozy or classic Christmas style, add your family photo and message, then create your card.",
  "faq.pet.q": "Can I make a pet Christmas card?",
  "faq.pet.a": "Yes. Add your pet photo (or pet Christmas portrait) and pick a playful premium design.",
  "faq.message.q": "Can you help me write the message?",
  "faq.message.a":
    "Yes. Use Need help writing it? on this page for a few suggestions, or explore the full Christmas Messages generator for more options.",
  "faq.download.q": "Can I download the finished card?",
  "faq.download.a": "Yes. Finished cards download as a PNG image sized for digital sharing.",
  "faq.share.q": "Can I share it online?",
  "faq.share.a":
    "Yes. Use native share when your browser supports it, or share via WhatsApp, email, or by copying the Cards page link. Public share metadata does not include your personal message or recipient name.",
  "faq.edit.q": "Can I edit it afterward?",
  "faq.edit.a": "Yes. Use Edit to return to your draft and create again. Your message and settings stay on this device.",
  "faq.styles.q": "Which card styles are available?",
  "faq.styles.a":
    "Classic Christmas, Elegant Gold, Cozy Christmas, Winter Wonderland, Romantic Christmas, Playful Christmas, Minimal Christmas, and Vintage Christmas.",
  "faq.print.q": "Is it printable?",
  "faq.print.a":
    "You can download a high-resolution PNG suitable for personal printing. Print fulfillment and postal delivery are not offered on this page.",
  "faq.surfaces.q": "Does the card have a front, inside and back?",
  "faq.surfaces.a":
    "Today’s product creates a single digital PNG card (photo, greeting and message on one surface), with small TheDigitalGifter branding. Multi-page front/inside/back layouts are not supported yet.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Live Christmas card creator",
  "a11y.livePreview": "Live Christmas card preview",
  "a11y.progress": "Card creation progress",
  "a11y.styleThumb": "Christmas style preview",
};

const RO: Dict = {
  "seo.title": "Creator de Carduri de Crăciun | Carduri personalizate | TheDigitalGifter",
  "seo.description":
    "Creează un card de Crăciun personalizat cu fotografia ta, stilul de Crăciun și un mesaj din suflet. Descarcă sau trimite cardul final în câteva minute.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Crăciun",
  "breadcrumb.cards": "Carduri",
  "hero.kicker": "Crăciun · Carduri",
  "hero.h1": "Creează un card de Crăciun pe care vor să-l păstreze.",
  "hero.lede":
    "Alege un stil de Crăciun, adaugă mesajul și fotografia, apoi creează un card gata de descărcat sau de trimis.",
  "hero.cta": "Creează cardul meu de Crăciun →",
  "hero.secondary": "Inspirație pentru carduri",
  "hero.promise": "Creează un card de Crăciun care chiar se simte personal",
  "hero.support": "Transformă o fotografie preferată și câteva cuvinte într-un card frumos pentru cei dragi.",
  "hero.giftNote": "Un cadou de sezon de la TheDigitalGifter.",
  "hero.asideNote": "Momente mici · Legături mari",
  "hero.front": "Față",
  "hero.inside": "Interior",
  "hero.open": "Privește înăuntru",
  "hero.close": "Arată fața",
  "examples.h2": "Inspirație pentru carduri de Crăciun",
  "examples.lede": "Demo-uri editoriale — familie, cuplu, animal, elegant, amuzant și clasic.",
  "examples.demoBadge": "Inspirație",
  "create.h2": "Creează cardul tău de Crăciun",
  "create.lede": "Stil, mesaj, fotografie — apoi creează. Cardul rămâne eroul.",
  "step.type": "Tip card",
  "step.photo": "Fotografie",
  "step.design": "Design",
  "step.message": "Mesaj",
  "step.preview": "Previzualizare",
  "step.result": "Cardul tău",
  "type.ask": "Ce fel de card de Crăciun creezi?",
  "photo.ask": "Adaugă fotografia",
  "photo.upload": "Încarcă fotografia",
  "photo.usePortrait": "Folosește portretul meu de Crăciun",
  "photo.change": "Schimbă fotografia",
  "photo.remove": "Elimină fotografia",
  "photo.hint": "JPG, PNG sau WebP",
  "photo.portraitLoaded": "Portretul tău de Crăciun este gata pentru acest card.",
  "photo.skipHint": "Opțional — o fotografie face cardul să se simtă al tău.",
  "photo.noneAvailable": "Nu am găsit un portret recent de Crăciun pe acest dispozitiv.",
  "photo.uploadFailed": "Nu am putut încărca fotografia. Te rugăm să încerci din nou.",
  "design.ask": "Stil de Crăciun",
  "design.lede": "Alege designul care se potrivește mesajului.",
  "layout.ask": "Format",
  "layout.dims": "Rezoluție",
  "message.ask": "Mesajul tău de Crăciun",
  "message.writeOwn": "Scriu eu",
  "message.helpWrite": "Ai nevoie de ajutor să-l scrii?",
  "message.who": "Pentru cine este?",
  "message.tone": "Ton",
  "message.generate": "Sugerează un mesaj",
  "message.generating": "Căutăm cuvintele potrivite…",
  "message.retry": "Încearcă din nou",
  "message.suggestions": "Sugestii",
  "message.useSuggestion": "Folosește",
  "message.failed": "Nu am putut genera sugestii acum. Mesajul tău scris rămâne salvat — încearcă oricând din nou.",
  "message.moreInspiration": "Explorează Mesaje de Crăciun",
  "message.placeholder":
    "Îți dorim un Crăciun magic, plin de iubire, bucurie și momente de neuitat.",
  "message.started": "Mesaj",
  "message.hideHelp": "Ascunde sugestiile",
  "personalize.to": "Pentru",
  "personalize.from": "De la",
  "personalize.year": "Anul",
  "personalize.toPlaceholder": "ex: Familie, Prieteni, Bunica…",
  "personalize.fromPlaceholder": "ex: Paul",
  "preview.h2": "Cardul tău live de Crăciun",
  "preview.lede": "Se actualizează când schimbi stilul, mesajul, fotografia și numele.",
  "preview.create": "Creează cardul meu de Crăciun →",
  "preview.creating": "Cream cardul…",
  "preview.edit": "Continuă editarea",
  "preview.mobileEdit": "Personalizează",
  "preview.mobilePreview": "Card",
  "preview.collapse": "Ascunde previzualizarea",
  "preview.expand": "Arată cardul",
  "preview.failed": "Nu am putut crea cardul. Munca ta e încă aici — încearcă din nou.",
  "tone.elegant": "Elegant",
  "tone.short": "Scurt",
  "result.h2": "Cardul tău de Crăciun",
  "result.lede": "Descarcă-l, trimite-l sau ajustează orice și creează din nou.",
  "result.download": "Descarcă",
  "result.share": "Trimite",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copiază linkul paginii",
  "result.copied": "Link copiat",
  "result.edit": "Editează",
  "result.another": "Creează altul",
  "result.shareFailed": "Trimiterea nu a reușit. Poți descărca cardul sau copia linkul paginii.",
  "result.formatNote": "Card digital PNG — descarcă sau trimite. Livrarea tipărită nu este inclusă.",
  "nav.back": "Înapoi",
  "nav.continue": "Continuă",
  "nav.skipPhoto": "Continuă fără fotografie",
  "how.h2": "Cum funcționează",
  "how.1.title": "Adaugă fotografia",
  "how.1.body": "Folosește fotografia ta sau un portret TDG de Crăciun.",
  "how.2.title": "Alege stilul de Crăciun",
  "how.2.body": "Alege designul care se potrivește mesajului.",
  "how.3.title": "Personalizează",
  "how.3.body": "Adaugă destinatarul, expeditorul și mesajul de Crăciun.",
  "how.4.title": "Creează & trimite",
  "how.4.body": "Descarcă sau trimite cardul final.",
  "photos.h2": "Carduri de Crăciun cu fotografia ta",
  "photos.lede":
    "Carduri de familie, cuplu sau animal — fotografia ta rămâne inima unui design de păstrat.",
  "messages.h2": "Mesaje din suflet pentru carduri de Crăciun",
  "messages.lede": "Scrie tu, sau primește câteva sugestii în limba aleasă, fără să părăsești pagina.",
  "portrait.h2": "Ai creat deja un portret de Crăciun?",
  "portrait.lede": "Transformă-l într-un card frumos în câteva secunde.",
  "portrait.cta": "Folosește portretul meu de Crăciun",
  "portrait.make": "Creează un portret de Crăciun",
  "faq.h2": "Întrebări frecvente",
  "faq.what.q": "Ce este un creator online de carduri de Crăciun?",
  "faq.what.a":
    "Un creator online de carduri de Crăciun îți permite să combini o fotografie, un design de Crăciun și un mesaj personalizat într-un card pe care îl poți descărca sau trimite digital.",
  "faq.how.q": "Cum creez un card de Crăciun?",
  "faq.how.a":
    "Alegi un stil de Crăciun, adaugi mesajul și fotografia opțională, personalizezi Pentru și De la, apoi creezi cardul și descarci sau trimiți PNG-ul final.",
  "faq.photo.q": "Pot încărca fotografia mea?",
  "faq.photo.a": "Da. Încarcă un JPEG, PNG sau WebP până la 8MB. Randarea se face pe dispozitivul tău.",
  "faq.portrait.q": "Pot folosi un portret de Crăciun pe care l-am creat deja?",
  "faq.portrait.a":
    "Da. Dacă ai creat un portret pe acest dispozitiv, îl poți folosi direct — sau deschide Carduri din rezultatul portretului cu Transformă într-un card de Crăciun.",
  "faq.family.q": "Pot face un card pentru familie?",
  "faq.family.a":
    "Da. Alege un stil cozy sau clasic, adaugă fotografia de familie și mesajul, apoi creează cardul.",
  "faq.pet.q": "Pot face un card cu animalul de companie?",
  "faq.pet.a": "Da. Adaugă fotografia (sau portretul pet) și un design jucăuș, dar premium.",
  "faq.message.q": "Mă puteți ajuta să scriu mesajul?",
  "faq.message.a":
    "Da. Folosește Ai nevoie de ajutor să-l scrii? pe această pagină pentru câteva sugestii, sau explorează generatorul complet de Mesaje de Crăciun.",
  "faq.download.q": "Pot descărca cardul final?",
  "faq.download.a": "Da. Cardurile finalizate se descarcă ca imagine PNG, potrivită pentru trimitere digitală.",
  "faq.share.q": "Îl pot trimite online?",
  "faq.share.a":
    "Da. Folosește share-ul nativ când browserul îl suportă, sau WhatsApp, email, ori copiază linkul paginii. Metadatele publice nu includ mesajul personal sau numele destinatarului.",
  "faq.edit.q": "Pot edita după ce l-am creat?",
  "faq.edit.a": "Da. Folosește Editează ca să revii la ciornă și să creezi din nou. Mesajul și setările rămân pe acest dispozitiv.",
  "faq.styles.q": "Ce stiluri de carduri sunt disponibile?",
  "faq.styles.a":
    "Crăciun clasic, Aur elegant, Crăciun cozy, Iarnă magică, Crăciun romantic, Crăciun jucăuș, Crăciun minimal și Crăciun vintage.",
  "faq.print.q": "Se poate tipări?",
  "faq.print.a":
    "Poți descărca un PNG la rezoluție bună, potrivit pentru tipărire personală. Livrarea tipărită și poștală nu sunt oferite pe această pagină.",
  "faq.surfaces.q": "Cardul are față, interior și spate?",
  "faq.surfaces.a":
    "Produsul de azi creează un singur card digital PNG (fotografie, urare și mesaj pe o suprafață), cu un branding mic TheDigitalGifter. Layout-urile multi-pagină față/interior/spate nu sunt încă suportate.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Creator live de carduri de Crăciun",
  "a11y.livePreview": "Previzualizare live a cardului de Crăciun",
  "a11y.progress": "Progres creare card",
  "a11y.styleThumb": "Previzualizare stil de Crăciun",
};

const TABLES: Record<LocaleCode, Dict> = { en: EN, ro: RO };

export function cardsT(key: string, locale: LocaleCode = "en"): string {
  return TABLES[locale][key] || TABLES.en[key] || key;
}

export const CARD_MAKER_FAQ_KEYS = [
  "faq.what",
  "faq.how",
  "faq.photo",
  "faq.portrait",
  "faq.family",
  "faq.pet",
  "faq.message",
  "faq.download",
  "faq.share",
  "faq.edit",
  "faq.styles",
  "faq.print",
  "faq.surfaces",
] as const;

export function cardsMakerSeo(locale: LocaleCode = "en") {
  return {
    title: cardsT("seo.title", locale),
    description: cardsT("seo.description", locale),
    url: "https://www.thedigitalgifter.com/christmas/cards",
    image: "https://www.thedigitalgifter.com/assets/christmas/christmas_card_open.webp",
  };
}

export function cardsMakerJsonLd(locale: LocaleCode = "en") {
  const seo = cardsMakerSeo(locale);
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${seo.url}#webpage`,
        url: seo.url,
        name: seo.title,
        description: seo.description,
        inLanguage: locale,
        isPartOf: { "@id": "https://www.thedigitalgifter.com/#website" },
        primaryImageOfPage: { "@type": "ImageObject", url: seo.image },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: cardsT("breadcrumb.christmas", locale),
            item: "https://www.thedigitalgifter.com/christmas",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: cardsT("breadcrumb.cards", locale),
            item: seo.url,
          },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: CARD_MAKER_FAQ_KEYS.map((base) => ({
          "@type": "Question",
          name: cardsT(`${base}.q`, locale),
          acceptedAnswer: {
            "@type": "Answer",
            text: cardsT(`${base}.a`, locale),
          },
        })),
      },
    ],
  };
}
