/** i18n-ready copy for the Christmas Card Maker. Locale-aware — do not concatenate English fragments. */

import type { LocaleCode } from "./taxonomy";

type Dict = Record<string, string>;


const EN: Dict = {
  "seo.title": "Christmas Card Maker | Personalized Christmas Cards",
  "seo.description":
    "Create a personalized Christmas card they’ll want to keep — choose a design, add your message, and share or download.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Christmas",
  "breadcrumb.cards": "Cards",
  "hero.kicker": "Christmas Card Maker",
  "hero.h1": "Create a Christmas Card They’ll Want to Keep",
  "hero.lede": "Add your photo, choose a Christmas style and write something personal.",
  "hero.cta": "Create My Card",
  "hero.secondary": "See Examples",
  "hero.promise": "Create a Christmas Card That Actually Feels Personal",
  "hero.support": "Turn a favorite photo and a few words into a beautiful Christmas card for the people you love.",
  "hero.front": "Front",
  "hero.inside": "Inside",
  "hero.open": "Peek inside",
  "hero.close": "Show front",
  "examples.h2": "Christmas Card Examples",
  "examples.lede": "Curated demos — not customer cards. Family, couple, pet, elegant, funny, and portrait-to-card.",
  "examples.demoBadge": "Demo example",
  "create.h2": "Create a Personalized Christmas Card",
  "create.lede": "A simple path from photo to finished Christmas card.",
  "step.type": "Card type",
  "step.photo": "Photo",
  "step.design": "Design",
  "step.message": "Message",
  "step.preview": "Preview",
  "step.result": "Your card",
  "type.ask": "What kind of Christmas card are you creating?",
  "photo.ask": "Add a favorite photo",
  "photo.upload": "Upload Photo",
  "photo.usePortrait": "Use My Christmas Portrait",
  "photo.change": "Change photo",
  "photo.remove": "Remove photo",
  "photo.hint": "JPEG, PNG or WebP up to 8MB. Rendered on your device.",
  "photo.portraitLoaded": "Your Christmas portrait is ready for this card.",
  "photo.skipHint": "You can continue without a photo and add one later.",
  "photo.noneAvailable": "No recent Christmas portrait found on this device.",
  "photo.uploadFailed": "We couldn’t upload that photo. Please try again.",
  "design.ask": "Choose a Christmas design",
  "design.lede": "A curated set of strong directions — not a template marketplace.",
  "message.ask": "What would you like to say?",
  "message.writeOwn": "Write my own",
  "message.helpWrite": "Help me write it",
  "message.who": "Who is it for?",
  "message.tone": "Tone",
  "message.generate": "Suggest messages",
  "message.generating": "Finding the right words…",
  "message.retry": "Try again",
  "message.suggestions": "Suggestions",
  "message.useSuggestion": "Use this",
  "message.failed": "We couldn’t generate suggestions right now. Your typed message is still saved — try again anytime.",
  "message.moreInspiration": "Need inspiration? Explore Christmas Messages",
  "message.placeholder": "Write a Christmas message they’ll want to keep…",
  "message.started": "Message",
  "personalize.to": "Recipient name",
  "personalize.from": "From / family name",
  "personalize.year": "Year",
  "personalize.toPlaceholder": "e.g. Grandma",
  "personalize.fromPlaceholder": "e.g. Emma, Noah & Mum and Dad",
  "preview.h2": "Preview your Christmas card",
  "preview.lede": "The card updates as you change photo, design and message.",
  "preview.create": "Create My Christmas Card",
  "preview.creating": "Creating your card…",
  "preview.edit": "Keep editing",
  "preview.mobileEdit": "Edit",
  "preview.mobilePreview": "Preview",
  "preview.failed": "We couldn’t create that card. Your work is still here — please try again.",
  "result.h2": "Your Christmas card",
  "result.lede": "Download it, share it, or tweak anything and create again.",
  "result.download": "Download",
  "result.share": "Share",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copy page link",
  "result.copied": "Link copied",
  "result.edit": "Edit",
  "result.another": "Create Another",
  "result.shareFailed": "Sharing didn’t work this time. You can download the card or copy the page link instead.",
  "result.formatNote": "Digital PNG card — download or share. Print delivery is not included.",
  "nav.back": "Back",
  "nav.continue": "Continue",
  "nav.skipPhoto": "Continue without photo",
  "how.h2": "How to Make a Christmas Card Online",
  "how.1.title": "Add your photo",
  "how.1.body": "Use your own photo or a Christmas portrait.",
  "how.2.title": "Choose a design",
  "how.2.body": "Pick the Christmas style you love.",
  "how.3.title": "Make it personal",
  "how.3.body": "Add a message and recipient.",
  "how.4.title": "Share the magic",
  "how.4.body": "Download or send your finished Christmas card.",
  "photos.h2": "Create Cards With Your Family, Couple or Pet Photos",
  "photos.lede": "The finished card stays the hero — your photo, a Christmas design, and words that feel like you.",
  "messages.h2": "Christmas Card Messages",
  "messages.lede": "Write your own, or get a few locale-aware suggestions without leaving this page.",
  "portrait.h2": "Use Your Christmas Portrait",
  "portrait.lede":
    "Already created a Christmas portrait? Bring it into the card maker and finish with a message. Portrait handoff is supported from the Christmas Photo Generator.",
  "portrait.cta": "Use My Christmas Portrait",
  "portrait.make": "Create a Christmas portrait first",
  "geo.h2": "What is an online Christmas card maker?",
  "geo.body":
    "An online Christmas card maker lets you create a personalized Christmas card with a photo, a festive design, and your own message. On TheDigitalGifter, you can upload a photo or use a Christmas portrait, choose a style, write or get message help, then download a PNG or share the card digitally.",
  "faq.h2": "Frequently Asked Questions",
  "faq.what.q": "What is an online Christmas card maker?",
  "faq.what.a":
    "An online Christmas card maker lets you combine a photo, Christmas design and personalized message into a card that can be downloaded or shared digitally.",
  "faq.how.q": "How do I create a Christmas card?",
  "faq.how.a":
    "Choose a card type, add a photo (optional), pick a Christmas design, write or generate a message, preview the card, then download or share the finished PNG.",
  "faq.photo.q": "Can I use my own photo?",
  "faq.photo.a": "Yes. Upload a JPEG, PNG or WebP photo up to 8MB. Rendering happens on your device.",
  "faq.portrait.q": "Can I use a Christmas portrait I already created?",
  "faq.portrait.a":
    "Yes. If you created a Christmas Portrait on this device, you can use it directly — or open Cards from the portrait result with Turn This Into a Christmas Card.",
  "faq.family.q": "Can I create a family Christmas card?",
  "faq.family.a": "Yes. Choose the Family card type and a cozy or classic design, then add your family photo and message.",
  "faq.pet.q": "Can I make a pet Christmas card?",
  "faq.pet.a": "Yes. Choose Pet, add your pet photo (or pet Christmas portrait), and pick a playful premium design.",
  "faq.message.q": "Can you help me write a Christmas message?",
  "faq.message.a":
    "Yes. Use Help me write it on this page for a few suggestions, or explore the full Christmas Messages generator for more options.",
  "faq.download.q": "Can I download my card?",
  "faq.download.a": "Yes. Finished cards download as a PNG image sized for digital sharing.",
  "faq.share.q": "Can I share it online?",
  "faq.share.a":
    "Yes. Use native share when your browser supports it, or share via WhatsApp, email, or by copying the Cards page link. Public share metadata does not include your personal message or recipient name.",
  "faq.edit.q": "Can I edit it after creating it?",
  "faq.edit.a": "Yes. Use Edit to return to your draft and create again. Your message and settings stay on this device.",
  "faq.styles.q": "Which Christmas card styles are available?",
  "faq.styles.a":
    "Classic Christmas, Elegant Gold, Cozy Family, Snowy Christmas, Romantic Christmas, Funny/Pet, Minimal Christmas, and Vintage Christmas.",
  "faq.print.q": "Is it printable?",
  "faq.print.a":
    "You can download a high-resolution PNG suitable for personal printing. Print fulfillment and postal delivery are not offered on this page.",
  "faq.surfaces.q": "Does the card have a front, inside and back?",
  "faq.surfaces.a":
    "Today’s product creates a single digital PNG card (photo, greeting and message on one surface), with small TheDigitalGifter branding. Multi-page front/inside/back layouts are not supported yet.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Interactive Christmas card example",
  "a11y.livePreview": "Live Christmas card preview",
  "a11y.progress": "Card creation progress",
};

const RO: Dict = {
  "seo.title": "Creator de Carduri de Crăciun | Carduri personalizate | TheDigitalGifter",
  "seo.description":
    "Creează un card de Crăciun personalizat cu fotografia ta, un design frumos și un mesaj din suflet. Descarcă sau trimite cardul în câteva minute.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Crăciun",
  "breadcrumb.cards": "Carduri",
  "hero.kicker": "Creator de carduri de Crăciun",
  "hero.h1": "Creează un card de Crăciun pe care vor să-l păstreze",
  "hero.lede": "Adaugă fotografia, alege un stil de Crăciun și scrie ceva personal.",
  "hero.cta": "Creează cardul meu",
  "hero.secondary": "Vezi exemple",
  "hero.promise": "Creează un card de Crăciun care chiar se simte personal",
  "hero.support": "Transformă o fotografie preferată și câteva cuvinte într-un card frumos pentru cei dragi.",
  "hero.front": "Față",
  "hero.inside": "Interior",
  "hero.open": "Privește înăuntru",
  "hero.close": "Arată fața",
  "examples.h2": "Exemple de carduri de Crăciun",
  "examples.lede": "Demo-uri curate — nu carduri ale clienților. Familie, cuplu, animal, elegant, amuzant și portret → card.",
  "examples.demoBadge": "Exemplu demo",
  "create.h2": "Creează un card de Crăciun personalizat",
  "create.lede": "Un drum simplu de la fotografie la cardul final.",
  "step.type": "Tip card",
  "step.photo": "Fotografie",
  "step.design": "Design",
  "step.message": "Mesaj",
  "step.preview": "Previzualizare",
  "step.result": "Cardul tău",
  "type.ask": "Ce fel de card de Crăciun creezi?",
  "photo.ask": "Adaugă o fotografie preferată",
  "photo.upload": "Încarcă fotografia",
  "photo.usePortrait": "Folosește portretul meu de Crăciun",
  "photo.change": "Schimbă fotografia",
  "photo.remove": "Elimină fotografia",
  "photo.hint": "JPEG, PNG sau WebP până la 8MB. Randare pe dispozitivul tău.",
  "photo.portraitLoaded": "Portretul tău de Crăciun este gata pentru acest card.",
  "photo.skipHint": "Poți continua fără fotografie și să o adaugi mai târziu.",
  "photo.noneAvailable": "Nu am găsit un portret recent de Crăciun pe acest dispozitiv.",
  "photo.uploadFailed": "Nu am putut încărca fotografia. Te rugăm să încerci din nou.",
  "design.ask": "Alege un design de Crăciun",
  "design.lede": "O selecție curată de direcții puternice — nu un marketplace de template-uri.",
  "message.ask": "Ce ai vrea să spui?",
  "message.writeOwn": "Scriu eu",
  "message.helpWrite": "Ajută-mă să scriu",
  "message.who": "Pentru cine este?",
  "message.tone": "Ton",
  "message.generate": "Sugerează mesaje",
  "message.generating": "Căutăm cuvintele potrivite…",
  "message.retry": "Încearcă din nou",
  "message.suggestions": "Sugestii",
  "message.useSuggestion": "Folosește",
  "message.failed": "Nu am putut genera sugestii acum. Mesajul tău scris rămâne salvat — încearcă oricând din nou.",
  "message.moreInspiration": "Ai nevoie de inspirație? Explorează Mesaje de Crăciun",
  "message.placeholder": "Scrie un mesaj de Crăciun pe care vor să-l păstreze…",
  "message.started": "Mesaj",
  "personalize.to": "Numele destinatarului",
  "personalize.from": "De la / familia",
  "personalize.year": "Anul",
  "personalize.toPlaceholder": "ex: Bunica",
  "personalize.fromPlaceholder": "ex: Emma, Noah & Mama și Tata",
  "preview.h2": "Previzualizează cardul de Crăciun",
  "preview.lede": "Cardul se actualizează când schimbi fotografia, designul și mesajul.",
  "preview.create": "Creează cardul meu de Crăciun",
  "preview.creating": "Cream cardul…",
  "preview.edit": "Continuă editarea",
  "preview.mobileEdit": "Editează",
  "preview.mobilePreview": "Previzualizare",
  "preview.failed": "Nu am putut crea cardul. Munca ta e încă aici — încearcă din nou.",
  "result.h2": "Cardul tău de Crăciun",
  "result.lede": "Descarcă-l, trimite-l sau ajustează orice și creează din nou.",
  "result.download": "Descarcă",
  "result.share": "Trimite",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copiază linkul paginii",
  "result.copied": "Link copiat",
  "result.edit": "Editează",
  "result.another": "Creează altul",
  "result.shareFailed": "Trimiterea nu a reușit. Poți descărca cardul sau copia linkul paginii.",
  "result.formatNote": "Card digital PNG — descarcă sau trimite. Livrarea tipărită nu este inclusă.",
  "nav.back": "Înapoi",
  "nav.continue": "Continuă",
  "nav.skipPhoto": "Continuă fără fotografie",
  "how.h2": "Cum faci un card de Crăciun online",
  "how.1.title": "Adaugă fotografia",
  "how.1.body": "Folosește fotografia ta sau un portret de Crăciun.",
  "how.2.title": "Alege un design",
  "how.2.body": "Alege stilul de Crăciun care-ți place.",
  "how.3.title": "Personalizează",
  "how.3.body": "Adaugă un mesaj și destinatarul.",
  "how.4.title": "Împarte magia",
  "how.4.body": "Descarcă sau trimite cardul final.",
  "photos.h2": "Creează carduri cu fotografii de familie, cuplu sau animale",
  "photos.lede": "Cardul final rămâne eroul — fotografia ta, un design de Crăciun și cuvinte care sună ca tine.",
  "messages.h2": "Mesaje pentru carduri de Crăciun",
  "messages.lede": "Scrie tu, sau primește câteva sugestii în limba aleasă, fără să părăsești pagina.",
  "portrait.h2": "Ai creat deja un portret de Crăciun?",
  "portrait.lede":
    "Folosește portretul în makerul de carduri și termină cu un mesaj. Predarea din generatorul de portrete este suportată.",
  "portrait.cta": "Folosește portretul meu de Crăciun",
  "portrait.make": "Creează mai întâi un portret de Crăciun",
  "geo.h2": "Ce este un creator online de carduri de Crăciun?",
  "geo.body":
    "Un creator online de carduri de Crăciun îți permite să creezi un card personalizat cu o fotografie, un design festiv și mesajul tău. Pe TheDigitalGifter poți încărca o fotografie sau un portret de Crăciun, alege un stil, scrie sau cere ajutor pentru mesaj, apoi descarci PNG-ul sau îl trimiți digital.",
  "faq.h2": "Întrebări frecvente",
  "faq.what.q": "Ce este un creator online de carduri de Crăciun?",
  "faq.what.a":
    "Un creator online de carduri de Crăciun îți permite să combini o fotografie, un design de Crăciun și un mesaj personalizat într-un card pe care îl poți descărca sau trimite digital.",
  "faq.how.q": "Cum creez un card de Crăciun?",
  "faq.how.a":
    "Alegi tipul de card, adaugi o fotografie (opțional), alegi un design, scrii sau generezi un mesaj, previzualizezi, apoi descarci sau trimiți PNG-ul final.",
  "faq.photo.q": "Pot folosi fotografia mea?",
  "faq.photo.a": "Da. Încarcă un JPEG, PNG sau WebP până la 8MB. Randarea se face pe dispozitivul tău.",
  "faq.portrait.q": "Pot folosi un portret de Crăciun pe care l-am creat deja?",
  "faq.portrait.a":
    "Da. Dacă ai creat un portret pe acest dispozitiv, îl poți folosi direct — sau deschide Carduri din rezultatul portretului cu Transformă într-un card de Crăciun.",
  "faq.family.q": "Pot crea un card de Crăciun pentru familie?",
  "faq.family.a": "Da. Alege tipul Familie și un design cozy sau clasic, apoi adaugă fotografia și mesajul.",
  "faq.pet.q": "Pot face un card cu animalul de companie?",
  "faq.pet.a": "Da. Alege Pet, adaugă fotografia (sau portretul pet) și un design jucăuș, dar premium.",
  "faq.message.q": "Mă puteți ajuta să scriu un mesaj de Crăciun?",
  "faq.message.a":
    "Da. Folosește Ajută-mă să scriu pe această pagină pentru câteva sugestii, sau explorează generatorul complet de Mesaje de Crăciun.",
  "faq.download.q": "Pot descărca cardul?",
  "faq.download.a": "Da. Cardurile finalizate se descarcă ca imagine PNG, potrivită pentru trimitere digitală.",
  "faq.share.q": "Îl pot trimite online?",
  "faq.share.a":
    "Da. Folosește share-ul nativ când browserul îl suportă, sau WhatsApp, email, ori copiază linkul paginii. Metadatele publice nu includ mesajul personal sau numele destinatarului.",
  "faq.edit.q": "Pot edita după ce l-am creat?",
  "faq.edit.a": "Da. Folosește Editează ca să revii la ciornă și să creezi din nou. Mesajul și setările rămân pe acest dispozitiv.",
  "faq.styles.q": "Ce stiluri de carduri sunt disponibile?",
  "faq.styles.a":
    "Crăciun clasic, Aur elegant, Familie cozy, Crăciun înzăpezit, Crăciun romantic, Amuzant/Pet, Crăciun minimal și Crăciun vintage.",
  "faq.print.q": "Se poate tipări?",
  "faq.print.a":
    "Poți descărca un PNG la rezoluție bună, potrivit pentru tipărire personală. Livrarea tipărită și poștală nu sunt oferite pe această pagină.",
  "faq.surfaces.q": "Cardul are față, interior și spate?",
  "faq.surfaces.a":
    "Produsul de azi creează un singur card digital PNG (fotografie, urare și mesaj pe o suprafață), cu un branding mic TheDigitalGifter. Layout-urile multi-pagină față/interior/spate nu sunt încă suportate.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Exemplu interactiv de card de Crăciun",
  "a11y.livePreview": "Previzualizare live a cardului de Crăciun",
  "a11y.progress": "Progres creare card",
};

const DE: Dict = {
  "seo.title": "Weihnachtskarten-Maker | Personalisierte Weihnachtskarten",
  "seo.description": "Erstelle eine personalisierte Weihnachtskarte, die sie behalten wollen — wähle ein Design, füge deine Nachricht hinzu und teile oder lade sie herunter.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Weihnachten",
  "breadcrumb.cards": "Karten",
  "hero.kicker": "Weihnachtskarten-Maker",
  "hero.h1": "Erstelle eine Weihnachtskarte, die sie behalten wollen",
  "hero.lede": "Füge dein Foto hinzu, wähle einen Weihnachtsstil und schreibe etwas Persönliches.",
  "hero.cta": "Meine Karte erstellen",
  "hero.secondary": "Beispiele ansehen",
  "hero.promise": "Erstelle eine Weihnachtskarte, die sich wirklich persönlich anfühlt",
  "hero.support": "Verwandle ein Lieblingsfoto und ein paar Worte in eine schöne Weihnachtskarte für die Menschen, die du liebst.",
  "hero.front": "Vorderseite",
  "hero.inside": "Innen",
  "hero.open": "Hineinschauen",
  "hero.close": "Vorderseite zeigen",
  "examples.h2": "Beispiele für Weihnachtskarten",
  "examples.lede": "Kuratierte Demos — keine Kundenkarten. Familie, Paar, Haustier, elegant, lustig und Porträt-zur-Karte.",
  "examples.demoBadge": "Demo-Beispiel",
  "create.h2": "Eine personalisierte Weihnachtskarte erstellen",
  "create.lede": "Ein einfacher Weg vom Foto zur fertigen Weihnachtskarte.",
  "step.type": "Kartentyp",
  "step.photo": "Foto",
  "step.design": "Design",
  "step.message": "Nachricht",
  "step.preview": "Vorschau",
  "step.result": "Deine Karte",
  "type.ask": "Welche Art von Weihnachtskarte erstellst du?",
  "photo.ask": "Füge ein Lieblingsfoto hinzu",
  "photo.upload": "Foto hochladen",
  "photo.usePortrait": "Mein Weihnachtsporträt verwenden",
  "photo.change": "Foto ändern",
  "photo.remove": "Foto entfernen",
  "photo.hint": "JPEG, PNG oder WebP bis 8MB. Wird auf deinem Gerät gerendert.",
  "photo.portraitLoaded": "Dein Weihnachtsporträt ist bereit für diese Karte.",
  "photo.skipHint": "Du kannst ohne Foto weitermachen und eines später hinzufügen.",
  "photo.noneAvailable": "Kein aktuelles Weihnachtsporträt auf diesem Gerät gefunden.",
  "photo.uploadFailed": "Wir konnten dieses Foto nicht hochladen. Bitte versuche es erneut.",
  "design.ask": "Wähle ein Weihnachtsdesign",
  "design.lede": "Eine kuratierte Auswahl starker Richtungen — kein Template-Marktplatz.",
  "message.ask": "Was möchtest du sagen?",
  "message.writeOwn": "Selbst schreiben",
  "message.helpWrite": "Hilf mir beim Schreiben",
  "message.who": "Für wen ist sie?",
  "message.tone": "Ton",
  "message.generate": "Nachrichten vorschlagen",
  "message.generating": "Wir suchen die richtigen Worte…",
  "message.retry": "Erneut versuchen",
  "message.suggestions": "Vorschläge",
  "message.useSuggestion": "Übernehmen",
  "message.failed": "Wir konnten gerade keine Vorschläge erzeugen. Deine getippte Nachricht bleibt gespeichert — versuche es jederzeit erneut.",
  "message.moreInspiration": "Brauchst du Inspiration? Entdecke Weihnachtsnachrichten",
  "message.placeholder": "Schreibe eine Weihnachtsnachricht, die sie behalten wollen…",
  "message.started": "Nachricht",
  "personalize.to": "Name des Empfängers",
  "personalize.from": "Von / Familienname",
  "personalize.year": "Jahr",
  "personalize.toPlaceholder": "z. B. Oma",
  "personalize.fromPlaceholder": "z. B. Emma, Noah & Mama und Papa",
  "preview.h2": "Vorschau deiner Weihnachtskarte",
  "preview.lede": "Die Karte aktualisiert sich, wenn du Foto, Design und Nachricht änderst.",
  "preview.create": "Meine Weihnachtskarte erstellen",
  "preview.creating": "Deine Karte wird erstellt…",
  "preview.edit": "Weiter bearbeiten",
  "preview.mobileEdit": "Bearbeiten",
  "preview.mobilePreview": "Vorschau",
  "preview.failed": "Wir konnten diese Karte nicht erstellen. Deine Arbeit ist noch da — bitte versuche es erneut.",
  "result.h2": "Deine Weihnachtskarte",
  "result.lede": "Lade sie herunter, teile sie oder passe etwas an und erstelle sie erneut.",
  "result.download": "Herunterladen",
  "result.share": "Teilen",
  "result.whatsapp": "WhatsApp",
  "result.email": "E-Mail",
  "result.copyLink": "Seitenlink kopieren",
  "result.copied": "Link kopiert",
  "result.edit": "Bearbeiten",
  "result.another": "Weitere erstellen",
  "result.shareFailed": "Das Teilen hat diesmal nicht funktioniert. Du kannst die Karte herunterladen oder den Seitenlink kopieren.",
  "result.formatNote": "Digitale PNG-Karte — herunterladen oder teilen. Druckversand ist nicht enthalten.",
  "nav.back": "Zurück",
  "nav.continue": "Weiter",
  "nav.skipPhoto": "Ohne Foto fortfahren",
  "how.h2": "So erstellst du online eine Weihnachtskarte",
  "how.1.title": "Foto hinzufügen",
  "how.1.body": "Nutze dein eigenes Foto oder ein Weihnachtsporträt.",
  "how.2.title": "Design wählen",
  "how.2.body": "Wähle den Weihnachtsstil, den du liebst.",
  "how.3.title": "Persönlich machen",
  "how.3.body": "Füge eine Nachricht und den Empfänger hinzu.",
  "how.4.title": "Die Magie teilen",
  "how.4.body": "Lade deine fertige Weihnachtskarte herunter oder sende sie.",
  "photos.h2": "Karten mit Familien-, Paar- oder Haustierfotos erstellen",
  "photos.lede": "Die fertige Karte bleibt der Held — dein Foto, ein Weihnachtsdesign und Worte, die nach dir klingen.",
  "messages.h2": "Nachrichten für Weihnachtskarten",
  "messages.lede": "Schreibe selbst, oder erhalte ein paar sprachbezogene Vorschläge, ohne die Seite zu verlassen.",
  "portrait.h2": "Dein Weihnachtsporträt verwenden",
  "portrait.lede": "Hast du schon ein Weihnachtsporträt erstellt? Bringe es in den Karten-Maker und beende es mit einer Nachricht. Die Übergabe aus dem Weihnachtsfoto-Generator wird unterstützt.",
  "portrait.cta": "Mein Weihnachtsporträt verwenden",
  "portrait.make": "Zuerst ein Weihnachtsporträt erstellen",
  "geo.h2": "Was ist ein Online-Weihnachtskarten-Maker?",
  "geo.body": "Ein Online-Weihnachtskarten-Maker lässt dich eine personalisierte Weihnachtskarte mit Foto, festlichem Design und eigener Nachricht erstellen. Bei TheDigitalGifter kannst du ein Foto hochladen oder ein Weihnachtsporträt nutzen, einen Stil wählen, selbst schreiben oder Hilfe für die Nachricht holen und dann ein PNG herunterladen oder die Karte digital teilen.",
  "faq.h2": "Häufig gestellte Fragen",
  "faq.what.q": "Was ist ein Online-Weihnachtskarten-Maker?",
  "faq.what.a": "Ein Online-Weihnachtskarten-Maker lässt dich Foto, Weihnachtsdesign und personalisierte Nachricht zu einer Karte kombinieren, die digital heruntergeladen oder geteilt werden kann.",
  "faq.how.q": "Wie erstelle ich eine Weihnachtskarte?",
  "faq.how.a": "Wähle einen Kartentyp, füge optional ein Foto hinzu, wähle ein Weihnachtsdesign, schreibe oder generiere eine Nachricht, sieh dir die Vorschau an und lade dann das fertige PNG herunter oder teile es.",
  "faq.photo.q": "Kann ich mein eigenes Foto verwenden?",
  "faq.photo.a": "Ja. Lade ein JPEG-, PNG- oder WebP-Foto bis 8MB hoch. Das Rendering erfolgt auf deinem Gerät.",
  "faq.portrait.q": "Kann ich ein bereits erstelltes Weihnachtsporträt verwenden?",
  "faq.portrait.a": "Ja. Wenn du auf diesem Gerät ein Weihnachtsporträt erstellt hast, kannst du es direkt verwenden — oder von der Porträtansicht aus Karten mit „In eine Weihnachtskarte verwandeln“ öffnen.",
  "faq.family.q": "Kann ich eine Familien-Weihnachtskarte erstellen?",
  "faq.family.a": "Ja. Wähle den Kartentyp Familie und ein gemütliches oder klassisches Design, dann füge Familienfoto und Nachricht hinzu.",
  "faq.pet.q": "Kann ich eine Haustier-Weihnachtskarte machen?",
  "faq.pet.a": "Ja. Wähle Haustier, füge dein Haustierfoto (oder Haustier-Weihnachtsporträt) hinzu und wähle ein verspieltes Premium-Design.",
  "faq.message.q": "Könnt ihr mir helfen, eine Weihnachtsnachricht zu schreiben?",
  "faq.message.a": "Ja. Nutze „Hilf mir beim Schreiben“ auf dieser Seite für ein paar Vorschläge, oder entdecke den vollständigen Generator für Weihnachtsnachrichten.",
  "faq.download.q": "Kann ich meine Karte herunterladen?",
  "faq.download.a": "Ja. Fertige Karten werden als PNG-Bild heruntergeladen, geeignet zum digitalen Teilen.",
  "faq.share.q": "Kann ich sie online teilen?",
  "faq.share.a": "Ja. Nutze die native Teilen-Funktion, wenn dein Browser sie unterstützt, oder teile über WhatsApp, E-Mail oder durch Kopieren des Karten-Seitenlinks. Öffentliche Share-Metadaten enthalten weder deine persönliche Nachricht noch den Empfängernamen.",
  "faq.edit.q": "Kann ich sie nach dem Erstellen noch bearbeiten?",
  "faq.edit.a": "Ja. Mit Bearbeiten kehrst du zum Entwurf zurück und erstellst erneut. Nachricht und Einstellungen bleiben auf diesem Gerät.",
  "faq.styles.q": "Welche Weihnachtskarten-Stile gibt es?",
  "faq.styles.a": "Klassisches Weihnachten, Elegantes Gold, Gemütliche Familie, Verschneites Weihnachten, Romantisches Weihnachten, Lustig/Haustier, Minimal Weihnachten und Vintage Weihnachten.",
  "faq.print.q": "Ist sie druckbar?",
  "faq.print.a": "Du kannst ein hochauflösendes PNG herunterladen, das sich für den persönlichen Druck eignet. Druckversand und Postlieferung werden auf dieser Seite nicht angeboten.",
  "faq.surfaces.q": "Hat die Karte Vorderseite, Innen und Rückseite?",
  "faq.surfaces.a": "Das heutige Produkt erstellt eine einzelne digitale PNG-Karte (Foto, Gruß und Nachricht auf einer Fläche), mit kleinem TheDigitalGifter-Branding. Mehrseitige Layouts Vorderseite/Innen/Rückseite werden noch nicht unterstützt.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Interaktives Beispiel einer Weihnachtskarte",
  "a11y.livePreview": "Live-Vorschau der Weihnachtskarte",
  "a11y.progress": "Fortschritt der Kartenerstellung",
};

const FR: Dict = {
  "seo.title": "Créateur de cartes de Noël | Cartes de Noël personnalisées",
  "seo.description": "Créez une carte de Noël personnalisée qu’ils auront envie de garder — choisissez un design, ajoutez votre message, puis partagez ou téléchargez.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Noël",
  "breadcrumb.cards": "Cartes",
  "hero.kicker": "Créateur de cartes de Noël",
  "hero.h1": "Créez une carte de Noël qu’ils auront envie de garder",
  "hero.lede": "Ajoutez votre photo, choisissez un style de Noël et écrivez quelque chose de personnel.",
  "hero.cta": "Créer ma carte",
  "hero.secondary": "Voir des exemples",
  "hero.promise": "Créez une carte de Noël qui paraît vraiment personnelle",
  "hero.support": "Transformez une photo préférée et quelques mots en une belle carte de Noël pour les personnes que vous aimez.",
  "hero.front": "Recto",
  "hero.inside": "Intérieur",
  "hero.open": "Regarder à l’intérieur",
  "hero.close": "Afficher le recto",
  "examples.h2": "Exemples de cartes de Noël",
  "examples.lede": "Démos sélectionnées — pas des cartes de clients. Famille, couple, animal, élégant, amusant et portrait → carte.",
  "examples.demoBadge": "Exemple démo",
  "create.h2": "Créer une carte de Noël personnalisée",
  "create.lede": "Un parcours simple de la photo à la carte terminée.",
  "step.type": "Type de carte",
  "step.photo": "Photo",
  "step.design": "Design",
  "step.message": "Message",
  "step.preview": "Aperçu",
  "step.result": "Votre carte",
  "type.ask": "Quel type de carte de Noël créez-vous ?",
  "photo.ask": "Ajoutez une photo préférée",
  "photo.upload": "Téléverser une photo",
  "photo.usePortrait": "Utiliser mon portrait de Noël",
  "photo.change": "Changer la photo",
  "photo.remove": "Supprimer la photo",
  "photo.hint": "JPEG, PNG ou WebP jusqu’à 8 Mo. Rendu sur votre appareil.",
  "photo.portraitLoaded": "Votre portrait de Noël est prêt pour cette carte.",
  "photo.skipHint": "Vous pouvez continuer sans photo et en ajouter une plus tard.",
  "photo.noneAvailable": "Aucun portrait de Noël récent trouvé sur cet appareil.",
  "photo.uploadFailed": "Nous n’avons pas pu téléverser cette photo. Veuillez réessayer.",
  "design.ask": "Choisissez un design de Noël",
  "design.lede": "Une sélection soignée de directions fortes — pas une marketplace de modèles.",
  "message.ask": "Que souhaitez-vous dire ?",
  "message.writeOwn": "Écrire moi-même",
  "message.helpWrite": "Aidez-moi à écrire",
  "message.who": "Pour qui est-ce ?",
  "message.tone": "Ton",
  "message.generate": "Suggérer des messages",
  "message.generating": "Nous cherchons les bons mots…",
  "message.retry": "Réessayer",
  "message.suggestions": "Suggestions",
  "message.useSuggestion": "Utiliser",
  "message.failed": "Nous n’avons pas pu générer de suggestions pour le moment. Votre message tapé reste enregistré — réessayez quand vous voulez.",
  "message.moreInspiration": "Besoin d’inspiration ? Explorez les messages de Noël",
  "message.placeholder": "Écrivez un message de Noël qu’ils auront envie de garder…",
  "message.started": "Message",
  "personalize.to": "Nom du destinataire",
  "personalize.from": "De / nom de famille",
  "personalize.year": "Année",
  "personalize.toPlaceholder": "ex. Grand-mère",
  "personalize.fromPlaceholder": "ex. Emma, Noah & Maman et Papa",
  "preview.h2": "Aperçu de votre carte de Noël",
  "preview.lede": "La carte se met à jour quand vous changez la photo, le design et le message.",
  "preview.create": "Créer ma carte de Noël",
  "preview.creating": "Création de votre carte…",
  "preview.edit": "Continuer à modifier",
  "preview.mobileEdit": "Modifier",
  "preview.mobilePreview": "Aperçu",
  "preview.failed": "Nous n’avons pas pu créer cette carte. Votre travail est toujours là — veuillez réessayer.",
  "result.h2": "Votre carte de Noël",
  "result.lede": "Téléchargez-la, partagez-la, ou ajustez quoi que ce soit et créez à nouveau.",
  "result.download": "Télécharger",
  "result.share": "Partager",
  "result.whatsapp": "WhatsApp",
  "result.email": "E-mail",
  "result.copyLink": "Copier le lien de la page",
  "result.copied": "Lien copié",
  "result.edit": "Modifier",
  "result.another": "Créer une autre",
  "result.shareFailed": "Le partage n’a pas fonctionné cette fois. Vous pouvez télécharger la carte ou copier le lien de la page.",
  "result.formatNote": "Carte numérique PNG — téléchargez ou partagez. La livraison imprimée n’est pas incluse.",
  "nav.back": "Retour",
  "nav.continue": "Continuer",
  "nav.skipPhoto": "Continuer sans photo",
  "how.h2": "Comment faire une carte de Noël en ligne",
  "how.1.title": "Ajoutez votre photo",
  "how.1.body": "Utilisez votre propre photo ou un portrait de Noël.",
  "how.2.title": "Choisissez un design",
  "how.2.body": "Choisissez le style de Noël que vous aimez.",
  "how.3.title": "Personnalisez",
  "how.3.body": "Ajoutez un message et un destinataire.",
  "how.4.title": "Partagez la magie",
  "how.4.body": "Téléchargez ou envoyez votre carte de Noël terminée.",
  "photos.h2": "Créez des cartes avec vos photos de famille, de couple ou d’animaux",
  "photos.lede": "La carte terminée reste le héros — votre photo, un design de Noël et des mots qui vous ressemblent.",
  "messages.h2": "Messages pour cartes de Noël",
  "messages.lede": "Écrivez le vôtre, ou obtenez quelques suggestions adaptées à la langue sans quitter cette page.",
  "portrait.h2": "Utilisez votre portrait de Noël",
  "portrait.lede": "Vous avez déjà créé un portrait de Noël ? Apportez-le dans le créateur de cartes et terminez avec un message. Le transfert depuis le générateur de photos de Noël est pris en charge.",
  "portrait.cta": "Utiliser mon portrait de Noël",
  "portrait.make": "Créer d’abord un portrait de Noël",
  "geo.h2": "Qu’est-ce qu’un créateur de cartes de Noël en ligne ?",
  "geo.body": "Un créateur de cartes de Noël en ligne vous permet de créer une carte personnalisée avec une photo, un design festif et votre propre message. Sur TheDigitalGifter, vous pouvez téléverser une photo ou utiliser un portrait de Noël, choisir un style, écrire ou obtenir de l’aide pour le message, puis télécharger un PNG ou partager la carte numériquement.",
  "faq.h2": "Questions fréquentes",
  "faq.what.q": "Qu’est-ce qu’un créateur de cartes de Noël en ligne ?",
  "faq.what.a": "Un créateur de cartes de Noël en ligne vous permet de combiner une photo, un design de Noël et un message personnalisé en une carte téléchargeable ou partageable numériquement.",
  "faq.how.q": "Comment créer une carte de Noël ?",
  "faq.how.a": "Choisissez un type de carte, ajoutez une photo (facultatif), choisissez un design de Noël, écrivez ou générez un message, prévisualisez, puis téléchargez ou partagez le PNG final.",
  "faq.photo.q": "Puis-je utiliser ma propre photo ?",
  "faq.photo.a": "Oui. Téléversez une photo JPEG, PNG ou WebP jusqu’à 8 Mo. Le rendu se fait sur votre appareil.",
  "faq.portrait.q": "Puis-je utiliser un portrait de Noël déjà créé ?",
  "faq.portrait.a": "Oui. Si vous avez créé un portrait de Noël sur cet appareil, vous pouvez l’utiliser directement — ou ouvrir Cartes depuis le résultat du portrait avec Transformer en carte de Noël.",
  "faq.family.q": "Puis-je créer une carte de Noël familiale ?",
  "faq.family.a": "Oui. Choisissez le type Famille et un design cosy ou classique, puis ajoutez votre photo de famille et votre message.",
  "faq.pet.q": "Puis-je faire une carte avec mon animal ?",
  "faq.pet.a": "Oui. Choisissez Animal, ajoutez la photo de votre animal (ou son portrait de Noël) et un design ludique mais premium.",
  "faq.message.q": "Pouvez-vous m’aider à écrire un message de Noël ?",
  "faq.message.a": "Oui. Utilisez « Aidez-moi à écrire » sur cette page pour quelques suggestions, ou explorez le générateur complet de messages de Noël.",
  "faq.download.q": "Puis-je télécharger ma carte ?",
  "faq.download.a": "Oui. Les cartes terminées se téléchargent en image PNG, adaptée au partage numérique.",
  "faq.share.q": "Puis-je la partager en ligne ?",
  "faq.share.a": "Oui. Utilisez le partage natif si votre navigateur le prend en charge, ou partagez via WhatsApp, e-mail, ou en copiant le lien de la page Cartes. Les métadonnées publiques n’incluent pas votre message personnel ni le nom du destinataire.",
  "faq.edit.q": "Puis-je la modifier après création ?",
  "faq.edit.a": "Oui. Utilisez Modifier pour revenir au brouillon et créer à nouveau. Votre message et vos réglages restent sur cet appareil.",
  "faq.styles.q": "Quels styles de cartes de Noël sont disponibles ?",
  "faq.styles.a": "Noël classique, Or élégant, Famille cosy, Noël enneigé, Noël romantique, Amusant/Animal, Noël minimal et Noël vintage.",
  "faq.print.q": "Est-ce imprimable ?",
  "faq.print.a": "Vous pouvez télécharger un PNG haute résolution adapté à une impression personnelle. L’envoi imprimé et postal n’est pas proposé sur cette page.",
  "faq.surfaces.q": "La carte a-t-elle un recto, un intérieur et un verso ?",
  "faq.surfaces.a": "Le produit actuel crée une seule carte numérique PNG (photo, vœu et message sur une surface), avec un petit branding TheDigitalGifter. Les mises en page multipages recto/intérieur/verso ne sont pas encore prises en charge.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Exemple interactif de carte de Noël",
  "a11y.livePreview": "Aperçu en direct de la carte de Noël",
  "a11y.progress": "Progression de création de la carte",
};

const ES: Dict = {
  "seo.title": "Creador de tarjetas de Navidad | Tarjetas de Navidad personalizadas",
  "seo.description": "Crea una tarjeta de Navidad personalizada que querrán guardar — elige un diseño, añade tu mensaje y compártela o descárgala.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Navidad",
  "breadcrumb.cards": "Tarjetas",
  "hero.kicker": "Creador de tarjetas de Navidad",
  "hero.h1": "Crea una tarjeta de Navidad que querrán guardar",
  "hero.lede": "Añade tu foto, elige un estilo navideño y escribe algo personal.",
  "hero.cta": "Crear mi tarjeta",
  "hero.secondary": "Ver ejemplos",
  "hero.promise": "Crea una tarjeta de Navidad que se sienta de verdad personal",
  "hero.support": "Convierte una foto favorita y unas pocas palabras en una bonita tarjeta de Navidad para las personas que amas.",
  "hero.front": "Frente",
  "hero.inside": "Interior",
  "hero.open": "Mirar dentro",
  "hero.close": "Mostrar el frente",
  "examples.h2": "Ejemplos de tarjetas de Navidad",
  "examples.lede": "Demos seleccionadas — no tarjetas de clientes. Familia, pareja, mascota, elegante, divertida y retrato → tarjeta.",
  "examples.demoBadge": "Ejemplo demo",
  "create.h2": "Crea una tarjeta de Navidad personalizada",
  "create.lede": "Un camino sencillo de la foto a la tarjeta terminada.",
  "step.type": "Tipo de tarjeta",
  "step.photo": "Foto",
  "step.design": "Diseño",
  "step.message": "Mensaje",
  "step.preview": "Vista previa",
  "step.result": "Tu tarjeta",
  "type.ask": "¿Qué tipo de tarjeta de Navidad estás creando?",
  "photo.ask": "Añade una foto favorita",
  "photo.upload": "Subir foto",
  "photo.usePortrait": "Usar mi retrato de Navidad",
  "photo.change": "Cambiar foto",
  "photo.remove": "Quitar foto",
  "photo.hint": "JPEG, PNG o WebP hasta 8MB. Se renderiza en tu dispositivo.",
  "photo.portraitLoaded": "Tu retrato de Navidad está listo para esta tarjeta.",
  "photo.skipHint": "Puedes continuar sin foto y añadir una más tarde.",
  "photo.noneAvailable": "No se encontró un retrato de Navidad reciente en este dispositivo.",
  "photo.uploadFailed": "No pudimos subir esa foto. Inténtalo de nuevo.",
  "design.ask": "Elige un diseño de Navidad",
  "design.lede": "Una selección cuidada de direcciones potentes — no un marketplace de plantillas.",
  "message.ask": "¿Qué te gustaría decir?",
  "message.writeOwn": "Escribir el mío",
  "message.helpWrite": "Ayúdame a escribirlo",
  "message.who": "¿Para quién es?",
  "message.tone": "Tono",
  "message.generate": "Sugerir mensajes",
  "message.generating": "Buscando las palabras adecuadas…",
  "message.retry": "Intentar de nuevo",
  "message.suggestions": "Sugerencias",
  "message.useSuggestion": "Usar esto",
  "message.failed": "No pudimos generar sugerencias ahora. Tu mensaje escrito sigue guardado — inténtalo cuando quieras.",
  "message.moreInspiration": "¿Necesitas inspiración? Explora Mensajes de Navidad",
  "message.placeholder": "Escribe un mensaje de Navidad que querrán guardar…",
  "message.started": "Mensaje",
  "personalize.to": "Nombre del destinatario",
  "personalize.from": "De / nombre de familia",
  "personalize.year": "Año",
  "personalize.toPlaceholder": "p. ej. Abuela",
  "personalize.fromPlaceholder": "p. ej. Emma, Noah y Mamá y Papá",
  "preview.h2": "Vista previa de tu tarjeta de Navidad",
  "preview.lede": "La tarjeta se actualiza cuando cambias la foto, el diseño y el mensaje.",
  "preview.create": "Crear mi tarjeta de Navidad",
  "preview.creating": "Creando tu tarjeta…",
  "preview.edit": "Seguir editando",
  "preview.mobileEdit": "Editar",
  "preview.mobilePreview": "Vista previa",
  "preview.failed": "No pudimos crear esa tarjeta. Tu trabajo sigue aquí — inténtalo de nuevo.",
  "result.h2": "Tu tarjeta de Navidad",
  "result.lede": "Descárgala, compártela o ajusta lo que quieras y créala de nuevo.",
  "result.download": "Descargar",
  "result.share": "Compartir",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copiar enlace de la página",
  "result.copied": "Enlace copiado",
  "result.edit": "Editar",
  "result.another": "Crear otra",
  "result.shareFailed": "Compartir no funcionó esta vez. Puedes descargar la tarjeta o copiar el enlace de la página.",
  "result.formatNote": "Tarjeta digital PNG — descarga o comparte. El envío impreso no está incluido.",
  "nav.back": "Atrás",
  "nav.continue": "Continuar",
  "nav.skipPhoto": "Continuar sin foto",
  "how.h2": "Cómo hacer una tarjeta de Navidad online",
  "how.1.title": "Añade tu foto",
  "how.1.body": "Usa tu propia foto o un retrato de Navidad.",
  "how.2.title": "Elige un diseño",
  "how.2.body": "Elige el estilo navideño que te guste.",
  "how.3.title": "Hazla personal",
  "how.3.body": "Añade un mensaje y el destinatario.",
  "how.4.title": "Comparte la magia",
  "how.4.body": "Descarga o envía tu tarjeta de Navidad terminada.",
  "photos.h2": "Crea tarjetas con fotos de familia, pareja o mascota",
  "photos.lede": "La tarjeta terminada sigue siendo la protagonista — tu foto, un diseño de Navidad y palabras que suenan a ti.",
  "messages.h2": "Mensajes para tarjetas de Navidad",
  "messages.lede": "Escribe el tuyo, o recibe unas sugerencias según el idioma sin salir de esta página.",
  "portrait.h2": "Usa tu retrato de Navidad",
  "portrait.lede": "¿Ya creaste un retrato de Navidad? Tráelo al creador de tarjetas y termínalo con un mensaje. La transferencia desde el generador de fotos de Navidad está admitida.",
  "portrait.cta": "Usar mi retrato de Navidad",
  "portrait.make": "Crea primero un retrato de Navidad",
  "geo.h2": "¿Qué es un creador online de tarjetas de Navidad?",
  "geo.body": "Un creador online de tarjetas de Navidad te permite crear una tarjeta personalizada con una foto, un diseño festivo y tu propio mensaje. En TheDigitalGifter puedes subir una foto o usar un retrato de Navidad, elegir un estilo, escribir o pedir ayuda con el mensaje y luego descargar un PNG o compartir la tarjeta digitalmente.",
  "faq.h2": "Preguntas frecuentes",
  "faq.what.q": "¿Qué es un creador online de tarjetas de Navidad?",
  "faq.what.a": "Un creador online de tarjetas de Navidad te permite combinar una foto, un diseño navideño y un mensaje personalizado en una tarjeta que se puede descargar o compartir digitalmente.",
  "faq.how.q": "¿Cómo creo una tarjeta de Navidad?",
  "faq.how.a": "Elige un tipo de tarjeta, añade una foto (opcional), elige un diseño de Navidad, escribe o genera un mensaje, previsualiza y luego descarga o comparte el PNG final.",
  "faq.photo.q": "¿Puedo usar mi propia foto?",
  "faq.photo.a": "Sí. Sube una foto JPEG, PNG o WebP de hasta 8MB. El renderizado ocurre en tu dispositivo.",
  "faq.portrait.q": "¿Puedo usar un retrato de Navidad que ya creé?",
  "faq.portrait.a": "Sí. Si creaste un Retrato de Navidad en este dispositivo, puedes usarlo directamente — o abrir Tarjetas desde el resultado del retrato con Convertir esto en una tarjeta de Navidad.",
  "faq.family.q": "¿Puedo crear una tarjeta de Navidad familiar?",
  "faq.family.a": "Sí. Elige el tipo Familia y un diseño acogedor o clásico, luego añade tu foto familiar y el mensaje.",
  "faq.pet.q": "¿Puedo hacer una tarjeta de Navidad con mi mascota?",
  "faq.pet.a": "Sí. Elige Mascota, añade la foto de tu mascota (o su retrato navideño) y elige un diseño juguetón y premium.",
  "faq.message.q": "¿Pueden ayudarme a escribir un mensaje de Navidad?",
  "faq.message.a": "Sí. Usa «Ayúdame a escribirlo» en esta página para algunas sugerencias, o explora el generador completo de Mensajes de Navidad.",
  "faq.download.q": "¿Puedo descargar mi tarjeta?",
  "faq.download.a": "Sí. Las tarjetas terminadas se descargan como imagen PNG, adecuada para compartir digitalmente.",
  "faq.share.q": "¿Puedo compartirla online?",
  "faq.share.a": "Sí. Usa el compartir nativo si tu navegador lo admite, o comparte por WhatsApp, email o copiando el enlace de la página de Tarjetas. Los metadatos públicos no incluyen tu mensaje personal ni el nombre del destinatario.",
  "faq.edit.q": "¿Puedo editarla después de crearla?",
  "faq.edit.a": "Sí. Usa Editar para volver al borrador y crear de nuevo. Tu mensaje y ajustes permanecen en este dispositivo.",
  "faq.styles.q": "¿Qué estilos de tarjetas de Navidad hay?",
  "faq.styles.a": "Navidad clásica, Oro elegante, Familia acogedora, Navidad nevada, Navidad romántica, Divertida/Mascota, Navidad minimal y Navidad vintage.",
  "faq.print.q": "¿Se puede imprimir?",
  "faq.print.a": "Puedes descargar un PNG de alta resolución apto para impresión personal. El envío impreso y postal no se ofrece en esta página.",
  "faq.surfaces.q": "¿La tarjeta tiene frente, interior y reverso?",
  "faq.surfaces.a": "El producto de hoy crea una sola tarjeta digital PNG (foto, saludo y mensaje en una superficie), con un pequeño branding TheDigitalGifter. Los layouts multipágina frente/interior/reverso aún no están admitidos.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Ejemplo interactivo de tarjeta de Navidad",
  "a11y.livePreview": "Vista previa en vivo de la tarjeta de Navidad",
  "a11y.progress": "Progreso de creación de la tarjeta",
};

const IT: Dict = {
  "seo.title": "Creatore di biglietti di Natale | Biglietti di Natale personalizzati",
  "seo.description": "Crea un biglietto di Natale personalizzato che vorranno tenere — scegli un design, aggiungi il tuo messaggio e condividilo o scaricalo.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Natale",
  "breadcrumb.cards": "Biglietti",
  "hero.kicker": "Creatore di biglietti di Natale",
  "hero.h1": "Crea un biglietto di Natale che vorranno tenere",
  "hero.lede": "Aggiungi la tua foto, scegli uno stile natalizio e scrivi qualcosa di personale.",
  "hero.cta": "Crea il mio biglietto",
  "hero.secondary": "Vedi esempi",
  "hero.promise": "Crea un biglietto di Natale che sembrerà davvero personale",
  "hero.support": "Trasforma una foto preferita e poche parole in un bel biglietto di Natale per le persone che ami.",
  "hero.front": "Fronte",
  "hero.inside": "Interno",
  "hero.open": "Guarda dentro",
  "hero.close": "Mostra il fronte",
  "examples.h2": "Esempi di biglietti di Natale",
  "examples.lede": "Demo curate — non biglietti di clienti. Famiglia, coppia, animale, elegante, divertente e ritratto → biglietto.",
  "examples.demoBadge": "Esempio demo",
  "create.h2": "Crea un biglietto di Natale personalizzato",
  "create.lede": "Un percorso semplice dalla foto al biglietto finito.",
  "step.type": "Tipo di biglietto",
  "step.photo": "Foto",
  "step.design": "Design",
  "step.message": "Messaggio",
  "step.preview": "Anteprima",
  "step.result": "Il tuo biglietto",
  "type.ask": "Che tipo di biglietto di Natale stai creando?",
  "photo.ask": "Aggiungi una foto preferita",
  "photo.upload": "Carica foto",
  "photo.usePortrait": "Usa il mio ritratto di Natale",
  "photo.change": "Cambia foto",
  "photo.remove": "Rimuovi foto",
  "photo.hint": "JPEG, PNG o WebP fino a 8MB. Rendering sul tuo dispositivo.",
  "photo.portraitLoaded": "Il tuo ritratto di Natale è pronto per questo biglietto.",
  "photo.skipHint": "Puoi continuare senza foto e aggiungerne una più tardi.",
  "photo.noneAvailable": "Nessun ritratto di Natale recente trovato su questo dispositivo.",
  "photo.uploadFailed": "Non siamo riusciti a caricare quella foto. Riprova.",
  "design.ask": "Scegli un design di Natale",
  "design.lede": "Una selezione curata di direzioni forti — non un marketplace di template.",
  "message.ask": "Cosa vorresti dire?",
  "message.writeOwn": "Scrivo io",
  "message.helpWrite": "Aiutami a scrivere",
  "message.who": "Per chi è?",
  "message.tone": "Tono",
  "message.generate": "Suggerisci messaggi",
  "message.generating": "Cerchiamo le parole giuste…",
  "message.retry": "Riprova",
  "message.suggestions": "Suggerimenti",
  "message.useSuggestion": "Usa questo",
  "message.failed": "Non siamo riusciti a generare suggerimenti adesso. Il messaggio digitato resta salvato — riprova quando vuoi.",
  "message.moreInspiration": "Serve ispirazione? Esplora i Messaggi di Natale",
  "message.placeholder": "Scrivi un messaggio di Natale che vorranno tenere…",
  "message.started": "Messaggio",
  "personalize.to": "Nome del destinatario",
  "personalize.from": "Da / nome famiglia",
  "personalize.year": "Anno",
  "personalize.toPlaceholder": "es. Nonna",
  "personalize.fromPlaceholder": "es. Emma, Noah & Mamma e Papà",
  "preview.h2": "Anteprima del tuo biglietto di Natale",
  "preview.lede": "Il biglietto si aggiorna quando cambi foto, design e messaggio.",
  "preview.create": "Crea il mio biglietto di Natale",
  "preview.creating": "Creazione del biglietto…",
  "preview.edit": "Continua a modificare",
  "preview.mobileEdit": "Modifica",
  "preview.mobilePreview": "Anteprima",
  "preview.failed": "Non siamo riusciti a creare quel biglietto. Il tuo lavoro è ancora qui — riprova.",
  "result.h2": "Il tuo biglietto di Natale",
  "result.lede": "Scaricalo, condividilo o modifica qualcosa e crealo di nuovo.",
  "result.download": "Scarica",
  "result.share": "Condividi",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copia il link della pagina",
  "result.copied": "Link copiato",
  "result.edit": "Modifica",
  "result.another": "Creane un altro",
  "result.shareFailed": "La condivisione non ha funzionato questa volta. Puoi scaricare il biglietto o copiare il link della pagina.",
  "result.formatNote": "Biglietto digitale PNG — scarica o condividi. La consegna stampata non è inclusa.",
  "nav.back": "Indietro",
  "nav.continue": "Continua",
  "nav.skipPhoto": "Continua senza foto",
  "how.h2": "Come creare un biglietto di Natale online",
  "how.1.title": "Aggiungi la tua foto",
  "how.1.body": "Usa la tua foto o un ritratto di Natale.",
  "how.2.title": "Scegli un design",
  "how.2.body": "Scegli lo stile natalizio che ami.",
  "how.3.title": "Rendilo personale",
  "how.3.body": "Aggiungi un messaggio e il destinatario.",
  "how.4.title": "Condividi la magia",
  "how.4.body": "Scarica o invia il biglietto di Natale finito.",
  "photos.h2": "Crea biglietti con foto di famiglia, coppia o animali",
  "photos.lede": "Il biglietto finito resta il protagonista — la tua foto, un design di Natale e parole che suonano come te.",
  "messages.h2": "Messaggi per biglietti di Natale",
  "messages.lede": "Scrivi il tuo, o ricevi alcuni suggerimenti nella lingua scelta senza lasciare questa pagina.",
  "portrait.h2": "Usa il tuo ritratto di Natale",
  "portrait.lede": "Hai già creato un ritratto di Natale? Portalo nel creatore di biglietti e completa con un messaggio. Il passaggio dal generatore di foto di Natale è supportato.",
  "portrait.cta": "Usa il mio ritratto di Natale",
  "portrait.make": "Crea prima un ritratto di Natale",
  "geo.h2": "Cos’è un creatore online di biglietti di Natale?",
  "geo.body": "Un creatore online di biglietti di Natale ti permette di creare un biglietto personalizzato con una foto, un design festivo e il tuo messaggio. Su TheDigitalGifter puoi caricare una foto o usare un ritratto di Natale, scegliere uno stile, scrivere o ricevere aiuto per il messaggio, poi scaricare un PNG o condividere il biglietto digitalmente.",
  "faq.h2": "Domande frequenti",
  "faq.what.q": "Cos’è un creatore online di biglietti di Natale?",
  "faq.what.a": "Un creatore online di biglietti di Natale ti permette di combinare una foto, un design natalizio e un messaggio personalizzato in un biglietto scaricabile o condividibile digitalmente.",
  "faq.how.q": "Come creo un biglietto di Natale?",
  "faq.how.a": "Scegli un tipo di biglietto, aggiungi una foto (opzionale), scegli un design di Natale, scrivi o genera un messaggio, anteprima, poi scarica o condividi il PNG finale.",
  "faq.photo.q": "Posso usare la mia foto?",
  "faq.photo.a": "Sì. Carica una foto JPEG, PNG o WebP fino a 8MB. Il rendering avviene sul tuo dispositivo.",
  "faq.portrait.q": "Posso usare un ritratto di Natale già creato?",
  "faq.portrait.a": "Sì. Se hai creato un Ritratto di Natale su questo dispositivo, puoi usarlo direttamente — oppure aprire Biglietti dal risultato del ritratto con Trasforma in un biglietto di Natale.",
  "faq.family.q": "Posso creare un biglietto di Natale per la famiglia?",
  "faq.family.a": "Sì. Scegli il tipo Famiglia e un design accogliente o classico, poi aggiungi la foto di famiglia e il messaggio.",
  "faq.pet.q": "Posso fare un biglietto con il mio animale?",
  "faq.pet.a": "Sì. Scegli Animale, aggiungi la foto del tuo animale (o il ritratto natalizio) e scegli un design giocoso ma premium.",
  "faq.message.q": "Potete aiutarmi a scrivere un messaggio di Natale?",
  "faq.message.a": "Sì. Usa «Aiutami a scrivere» in questa pagina per alcuni suggerimenti, oppure esplora il generatore completo di Messaggi di Natale.",
  "faq.download.q": "Posso scaricare il biglietto?",
  "faq.download.a": "Sì. I biglietti finiti si scaricano come immagine PNG, adatta alla condivisione digitale.",
  "faq.share.q": "Posso condividerlo online?",
  "faq.share.a": "Sì. Usa la condivisione nativa se il browser la supporta, oppure condividi via WhatsApp, email o copiando il link della pagina Biglietti. I metadati pubblici non includono il messaggio personale né il nome del destinatario.",
  "faq.edit.q": "Posso modificarlo dopo averlo creato?",
  "faq.edit.a": "Sì. Usa Modifica per tornare alla bozza e creare di nuovo. Messaggio e impostazioni restano su questo dispositivo.",
  "faq.styles.q": "Quali stili di biglietti di Natale sono disponibili?",
  "faq.styles.a": "Natale classico, Oro elegante, Famiglia accogliente, Natale innevato, Natale romantico, Divertente/Animale, Natale minimal e Natale vintage.",
  "faq.print.q": "Si può stampare?",
  "faq.print.a": "Puoi scaricare un PNG ad alta risoluzione adatto alla stampa personale. La spedizione stampata e postale non è offerta in questa pagina.",
  "faq.surfaces.q": "Il biglietto ha fronte, interno e retro?",
  "faq.surfaces.a": "Il prodotto di oggi crea un unico biglietto digitale PNG (foto, augurio e messaggio su una superficie), con un piccolo branding TheDigitalGifter. I layout multipagina fronte/interno/retro non sono ancora supportati.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Esempio interattivo di biglietto di Natale",
  "a11y.livePreview": "Anteprima live del biglietto di Natale",
  "a11y.progress": "Progresso creazione biglietto",
};

const PT: Dict = {
  "seo.title": "Criador de Cartões de Natal | Cartões de Natal personalizados",
  "seo.description": "Crie um cartão de Natal personalizado que vão querer guardar — escolha um design, adicione a sua mensagem e partilhe ou descarregue.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Natal",
  "breadcrumb.cards": "Cartões",
  "hero.kicker": "Criador de cartões de Natal",
  "hero.h1": "Crie um cartão de Natal que vão querer guardar",
  "hero.lede": "Adicione a sua fotografia, escolha um estilo de Natal e escreva algo pessoal.",
  "hero.cta": "Criar o meu cartão",
  "hero.secondary": "Ver exemplos",
  "hero.promise": "Crie um cartão de Natal que realmente parece pessoal",
  "hero.support": "Transforme uma fotografia favorita e algumas palavras num belo cartão de Natal para as pessoas de quem gosta.",
  "hero.front": "Frente",
  "hero.inside": "Interior",
  "hero.open": "Espiar o interior",
  "hero.close": "Mostrar a frente",
  "examples.h2": "Exemplos de cartões de Natal",
  "examples.lede": "Demos selecionadas — não cartões de clientes. Família, casal, animal, elegante, engraçado e retrato → cartão.",
  "examples.demoBadge": "Exemplo demo",
  "create.h2": "Crie um cartão de Natal personalizado",
  "create.lede": "Um caminho simples da fotografia ao cartão final.",
  "step.type": "Tipo de cartão",
  "step.photo": "Fotografia",
  "step.design": "Design",
  "step.message": "Mensagem",
  "step.preview": "Pré-visualização",
  "step.result": "O seu cartão",
  "type.ask": "Que tipo de cartão de Natal está a criar?",
  "photo.ask": "Adicione uma fotografia favorita",
  "photo.upload": "Carregar fotografia",
  "photo.usePortrait": "Usar o meu retrato de Natal",
  "photo.change": "Alterar fotografia",
  "photo.remove": "Remover fotografia",
  "photo.hint": "JPEG, PNG ou WebP até 8MB. Renderizado no seu dispositivo.",
  "photo.portraitLoaded": "O seu retrato de Natal está pronto para este cartão.",
  "photo.skipHint": "Pode continuar sem fotografia e adicionar uma mais tarde.",
  "photo.noneAvailable": "Não foi encontrado um retrato de Natal recente neste dispositivo.",
  "photo.uploadFailed": "Não conseguimos carregar essa fotografia. Tente novamente.",
  "design.ask": "Escolha um design de Natal",
  "design.lede": "Uma seleção cuidada de direções fortes — não um marketplace de modelos.",
  "message.ask": "O que gostaria de dizer?",
  "message.writeOwn": "Escrever a minha",
  "message.helpWrite": "Ajude-me a escrever",
  "message.who": "Para quem é?",
  "message.tone": "Tom",
  "message.generate": "Sugerir mensagens",
  "message.generating": "A procurar as palavras certas…",
  "message.retry": "Tentar novamente",
  "message.suggestions": "Sugestões",
  "message.useSuggestion": "Usar esta",
  "message.failed": "Não conseguimos gerar sugestões agora. A mensagem que escreveu continua guardada — tente quando quiser.",
  "message.moreInspiration": "Precisa de inspiração? Explore Mensagens de Natal",
  "message.placeholder": "Escreva uma mensagem de Natal que vão querer guardar…",
  "message.started": "Mensagem",
  "personalize.to": "Nome do destinatário",
  "personalize.from": "De / nome da família",
  "personalize.year": "Ano",
  "personalize.toPlaceholder": "ex. Avó",
  "personalize.fromPlaceholder": "ex. Emma, Noah & Mãe e Pai",
  "preview.h2": "Pré-visualize o seu cartão de Natal",
  "preview.lede": "O cartão atualiza-se quando altera a fotografia, o design e a mensagem.",
  "preview.create": "Criar o meu cartão de Natal",
  "preview.creating": "A criar o seu cartão…",
  "preview.edit": "Continuar a editar",
  "preview.mobileEdit": "Editar",
  "preview.mobilePreview": "Pré-visualização",
  "preview.failed": "Não conseguimos criar esse cartão. O seu trabalho continua aqui — tente novamente.",
  "result.h2": "O seu cartão de Natal",
  "result.lede": "Descarregue-o, partilhe-o ou ajuste o que quiser e crie de novo.",
  "result.download": "Descarregar",
  "result.share": "Partilhar",
  "result.whatsapp": "WhatsApp",
  "result.email": "Email",
  "result.copyLink": "Copiar ligação da página",
  "result.copied": "Ligação copiada",
  "result.edit": "Editar",
  "result.another": "Criar outro",
  "result.shareFailed": "A partilha não funcionou desta vez. Pode descarregar o cartão ou copiar a ligação da página.",
  "result.formatNote": "Cartão digital PNG — descarregue ou partilhe. A entrega impressa não está incluída.",
  "nav.back": "Voltar",
  "nav.continue": "Continuar",
  "nav.skipPhoto": "Continuar sem fotografia",
  "how.h2": "Como fazer um cartão de Natal online",
  "how.1.title": "Adicione a sua fotografia",
  "how.1.body": "Use a sua fotografia ou um retrato de Natal.",
  "how.2.title": "Escolha um design",
  "how.2.body": "Escolha o estilo de Natal de que gosta.",
  "how.3.title": "Torne-o pessoal",
  "how.3.body": "Adicione uma mensagem e o destinatário.",
  "how.4.title": "Partilhe a magia",
  "how.4.body": "Descarregue ou envie o cartão de Natal finalizado.",
  "photos.h2": "Crie cartões com fotografias de família, casal ou animais",
  "photos.lede": "O cartão finalizado continua a ser o protagonista — a sua fotografia, um design de Natal e palavras que soam a si.",
  "messages.h2": "Mensagens para cartões de Natal",
  "messages.lede": "Escreva a sua, ou receba algumas sugestões no idioma escolhido sem sair desta página.",
  "portrait.h2": "Use o seu retrato de Natal",
  "portrait.lede": "Já criou um retrato de Natal? Traga-o para o criador de cartões e termine com uma mensagem. A transferência a partir do gerador de fotografias de Natal é suportada.",
  "portrait.cta": "Usar o meu retrato de Natal",
  "portrait.make": "Crie primeiro um retrato de Natal",
  "geo.h2": "O que é um criador online de cartões de Natal?",
  "geo.body": "Um criador online de cartões de Natal permite-lhe criar um cartão personalizado com uma fotografia, um design festivo e a sua própria mensagem. No TheDigitalGifter pode carregar uma fotografia ou usar um retrato de Natal, escolher um estilo, escrever ou pedir ajuda para a mensagem e depois descarregar um PNG ou partilhar o cartão digitalmente.",
  "faq.h2": "Perguntas frequentes",
  "faq.what.q": "O que é um criador online de cartões de Natal?",
  "faq.what.a": "Um criador online de cartões de Natal permite-lhe combinar uma fotografia, um design de Natal e uma mensagem personalizada num cartão que pode ser descarregado ou partilhado digitalmente.",
  "faq.how.q": "Como crio um cartão de Natal?",
  "faq.how.a": "Escolha um tipo de cartão, adicione uma fotografia (opcional), escolha um design de Natal, escreva ou gere uma mensagem, pré-visualize e depois descarregue ou partilhe o PNG final.",
  "faq.photo.q": "Posso usar a minha própria fotografia?",
  "faq.photo.a": "Sim. Carregue uma fotografia JPEG, PNG ou WebP até 8MB. A renderização acontece no seu dispositivo.",
  "faq.portrait.q": "Posso usar um retrato de Natal que já criei?",
  "faq.portrait.a": "Sim. Se criou um Retrato de Natal neste dispositivo, pode usá-lo diretamente — ou abrir Cartões a partir do resultado do retrato com Transformar isto num cartão de Natal.",
  "faq.family.q": "Posso criar um cartão de Natal de família?",
  "faq.family.a": "Sim. Escolha o tipo Família e um design acolhedor ou clássico, depois adicione a fotografia de família e a mensagem.",
  "faq.pet.q": "Posso fazer um cartão de Natal com o meu animal?",
  "faq.pet.a": "Sim. Escolha Animal, adicione a fotografia do animal (ou o retrato de Natal) e escolha um design divertido mas premium.",
  "faq.message.q": "Podem ajudar-me a escrever uma mensagem de Natal?",
  "faq.message.a": "Sim. Use «Ajude-me a escrever» nesta página para algumas sugestões, ou explore o gerador completo de Mensagens de Natal.",
  "faq.download.q": "Posso descarregar o meu cartão?",
  "faq.download.a": "Sim. Os cartões finalizados descarregam-se como imagem PNG, adequada para partilha digital.",
  "faq.share.q": "Posso partilhá-lo online?",
  "faq.share.a": "Sim. Use a partilha nativa quando o browser a suportar, ou partilhe via WhatsApp, email ou copiando a ligação da página de Cartões. Os metadados públicos não incluem a sua mensagem pessoal nem o nome do destinatário.",
  "faq.edit.q": "Posso editá-lo depois de o criar?",
  "faq.edit.a": "Sim. Use Editar para voltar ao rascunho e criar de novo. A mensagem e as definições ficam neste dispositivo.",
  "faq.styles.q": "Que estilos de cartões de Natal estão disponíveis?",
  "faq.styles.a": "Natal clássico, Ouro elegante, Família acolhedora, Natal nevado, Natal romântico, Engraçado/Animal, Natal minimal e Natal vintage.",
  "faq.print.q": "É possível imprimir?",
  "faq.print.a": "Pode descarregar um PNG de alta resolução adequado para impressão pessoal. O cumprimento de impressão e o envio postal não são oferecidos nesta página.",
  "faq.surfaces.q": "O cartão tem frente, interior e verso?",
  "faq.surfaces.a": "O produto de hoje cria um único cartão digital PNG (fotografia, saudação e mensagem numa superfície), com um pequeno branding TheDigitalGifter. Layouts multipágina frente/interior/verso ainda não são suportados.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Exemplo interativo de cartão de Natal",
  "a11y.livePreview": "Pré-visualização em direto do cartão de Natal",
  "a11y.progress": "Progresso de criação do cartão",
};

const NL: Dict = {
  "seo.title": "Kerstkaartenmaker | Gepersonaliseerde kerstkaarten",
  "seo.description": "Maak een gepersonaliseerde kerstkaart die ze willen bewaren — kies een ontwerp, voeg je bericht toe en deel of download.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Kerst",
  "breadcrumb.cards": "Kaarten",
  "hero.kicker": "Kerstkaartenmaker",
  "hero.h1": "Maak een kerstkaart die ze willen bewaren",
  "hero.lede": "Voeg je foto toe, kies een kerststijl en schrijf iets persoonlijks.",
  "hero.cta": "Maak mijn kaart",
  "hero.secondary": "Bekijk voorbeelden",
  "hero.promise": "Maak een kerstkaart die écht persoonlijk aanvoelt",
  "hero.support": "Maak van een favoriete foto en een paar woorden een mooie kerstkaart voor de mensen van wie je houdt.",
  "hero.front": "Voorkant",
  "hero.inside": "Binnenkant",
  "hero.open": "Kijk naar binnen",
  "hero.close": "Toon voorkant",
  "examples.h2": "Voorbeelden van kerstkaarten",
  "examples.lede": "Geselecteerde demo’s — geen kaarten van klanten. Familie, stel, huisdier, elegant, grappig en portret-naar-kaart.",
  "examples.demoBadge": "Demo-voorbeeld",
  "create.h2": "Maak een gepersonaliseerde kerstkaart",
  "create.lede": "Een eenvoudig pad van foto naar afgewerkte kerstkaart.",
  "step.type": "Kaarttype",
  "step.photo": "Foto",
  "step.design": "Ontwerp",
  "step.message": "Bericht",
  "step.preview": "Voorbeeld",
  "step.result": "Jouw kaart",
  "type.ask": "Wat voor kerstkaart maak je?",
  "photo.ask": "Voeg een favoriete foto toe",
  "photo.upload": "Foto uploaden",
  "photo.usePortrait": "Mijn kerstportret gebruiken",
  "photo.change": "Foto wijzigen",
  "photo.remove": "Foto verwijderen",
  "photo.hint": "JPEG, PNG of WebP tot 8MB. Wordt op je apparaat gerenderd.",
  "photo.portraitLoaded": "Je kerstportret is klaar voor deze kaart.",
  "photo.skipHint": "Je kunt doorgaan zonder foto en er later een toevoegen.",
  "photo.noneAvailable": "Geen recent kerstportret gevonden op dit apparaat.",
  "photo.uploadFailed": "We konden die foto niet uploaden. Probeer het opnieuw.",
  "design.ask": "Kies een kerstontwerp",
  "design.lede": "Een zorgvuldig gekozen set sterke richtingen — geen template-marktplaats.",
  "message.ask": "Wat wil je zeggen?",
  "message.writeOwn": "Zelf schrijven",
  "message.helpWrite": "Help me schrijven",
  "message.who": "Voor wie is het?",
  "message.tone": "Toon",
  "message.generate": "Berichten voorstellen",
  "message.generating": "De juiste woorden zoeken…",
  "message.retry": "Opnieuw proberen",
  "message.suggestions": "Suggesties",
  "message.useSuggestion": "Deze gebruiken",
  "message.failed": "We konden nu geen suggesties genereren. Je getypte bericht blijft bewaard — probeer het wanneer je wilt.",
  "message.moreInspiration": "Inspiratie nodig? Ontdek Kerstberichten",
  "message.placeholder": "Schrijf een kerstbericht dat ze willen bewaren…",
  "message.started": "Bericht",
  "personalize.to": "Naam ontvanger",
  "personalize.from": "Van / familienaam",
  "personalize.year": "Jaar",
  "personalize.toPlaceholder": "bijv. Oma",
  "personalize.fromPlaceholder": "bijv. Emma, Noah & Mama en Papa",
  "preview.h2": "Bekijk je kerstkaart",
  "preview.lede": "De kaart werkt bij wanneer je foto, ontwerp en bericht wijzigt.",
  "preview.create": "Maak mijn kerstkaart",
  "preview.creating": "Je kaart wordt gemaakt…",
  "preview.edit": "Verder bewerken",
  "preview.mobileEdit": "Bewerken",
  "preview.mobilePreview": "Voorbeeld",
  "preview.failed": "We konden die kaart niet maken. Je werk staat er nog — probeer het opnieuw.",
  "result.h2": "Jouw kerstkaart",
  "result.lede": "Download hem, deel hem, of pas iets aan en maak opnieuw.",
  "result.download": "Downloaden",
  "result.share": "Delen",
  "result.whatsapp": "WhatsApp",
  "result.email": "E-mail",
  "result.copyLink": "Paginalink kopiëren",
  "result.copied": "Link gekopieerd",
  "result.edit": "Bewerken",
  "result.another": "Nog een maken",
  "result.shareFailed": "Delen lukte deze keer niet. Je kunt de kaart downloaden of de paginalink kopiëren.",
  "result.formatNote": "Digitale PNG-kaart — download of deel. Printbezorging is niet inbegrepen.",
  "nav.back": "Terug",
  "nav.continue": "Doorgaan",
  "nav.skipPhoto": "Doorgaan zonder foto",
  "how.h2": "Hoe maak je online een kerstkaart",
  "how.1.title": "Voeg je foto toe",
  "how.1.body": "Gebruik je eigen foto of een kerstportret.",
  "how.2.title": "Kies een ontwerp",
  "how.2.body": "Kies de kerststijl die je mooi vindt.",
  "how.3.title": "Maak het persoonlijk",
  "how.3.body": "Voeg een bericht en ontvanger toe.",
  "how.4.title": "Deel de magie",
  "how.4.body": "Download of stuur je afgewerkte kerstkaart.",
  "photos.h2": "Maak kaarten met familie-, stel- of huisdierfoto’s",
  "photos.lede": "De afgewerkte kaart blijft de held — jouw foto, een kerstontwerp en woorden die als jij klinken.",
  "messages.h2": "Berichten voor kerstkaarten",
  "messages.lede": "Schrijf zelf, of krijg een paar taalbewuste suggesties zonder deze pagina te verlaten.",
  "portrait.h2": "Gebruik je kerstportret",
  "portrait.lede": "Al een kerstportret gemaakt? Breng het naar de kaartenmaker en rond af met een bericht. Overdracht vanuit de kerstfotogenerator wordt ondersteund.",
  "portrait.cta": "Mijn kerstportret gebruiken",
  "portrait.make": "Maak eerst een kerstportret",
  "geo.h2": "Wat is een online kerstkaartenmaker?",
  "geo.body": "Een online kerstkaartenmaker laat je een gepersonaliseerde kerstkaart maken met een foto, een feestelijk ontwerp en je eigen bericht. Bij TheDigitalGifter kun je een foto uploaden of een kerstportret gebruiken, een stijl kiezen, zelf schrijven of hulp bij het bericht krijgen, en dan een PNG downloaden of de kaart digitaal delen.",
  "faq.h2": "Veelgestelde vragen",
  "faq.what.q": "Wat is een online kerstkaartenmaker?",
  "faq.what.a": "Een online kerstkaartenmaker laat je een foto, kerstontwerp en gepersonaliseerd bericht combineren tot een kaart die digitaal gedownload of gedeeld kan worden.",
  "faq.how.q": "Hoe maak ik een kerstkaart?",
  "faq.how.a": "Kies een kaarttype, voeg optioneel een foto toe, kies een kerstontwerp, schrijf of genereer een bericht, bekijk het voorbeeld en download of deel daarna de afgewerkte PNG.",
  "faq.photo.q": "Kan ik mijn eigen foto gebruiken?",
  "faq.photo.a": "Ja. Upload een JPEG-, PNG- of WebP-foto tot 8MB. Het renderen gebeurt op je apparaat.",
  "faq.portrait.q": "Kan ik een kerstportret gebruiken dat ik al heb gemaakt?",
  "faq.portrait.a": "Ja. Als je op dit apparaat een Kerstportret hebt gemaakt, kun je het direct gebruiken — of open Kaarten vanuit het portretresultaat met Maak hier een kerstkaart van.",
  "faq.family.q": "Kan ik een familiekerstkaart maken?",
  "faq.family.a": "Ja. Kies het type Familie en een knus of klassiek ontwerp, voeg dan je familiefoto en bericht toe.",
  "faq.pet.q": "Kan ik een kerstkaart met mijn huisdier maken?",
  "faq.pet.a": "Ja. Kies Huisdier, voeg je huisdierfoto (of huisdier-kerstportret) toe en kies een speels premium ontwerp.",
  "faq.message.q": "Kunnen jullie me helpen een kerstbericht te schrijven?",
  "faq.message.a": "Ja. Gebruik «Help me schrijven» op deze pagina voor een paar suggesties, of ontdek de volledige Kerstberichten-generator.",
  "faq.download.q": "Kan ik mijn kaart downloaden?",
  "faq.download.a": "Ja. Afgewerkte kaarten downloaden als PNG-afbeelding, geschikt om digitaal te delen.",
  "faq.share.q": "Kan ik hem online delen?",
  "faq.share.a": "Ja. Gebruik native delen als je browser dat ondersteunt, of deel via WhatsApp, e-mail of door de link van de Kaartenpagina te kopiëren. Openbare deelmetadata bevat je persoonlijke bericht of ontvangersnaam niet.",
  "faq.edit.q": "Kan ik hem na het maken nog bewerken?",
  "faq.edit.a": "Ja. Gebruik Bewerken om terug te gaan naar je concept en opnieuw te maken. Bericht en instellingen blijven op dit apparaat.",
  "faq.styles.q": "Welke kerstkaartstijlen zijn beschikbaar?",
  "faq.styles.a": "Klassieke kerst, Elegant goud, Knusse familie, Besneeuwde kerst, Romantische kerst, Grappig/Huisdier, Minimale kerst en Vintage kerst.",
  "faq.print.q": "Is hij printbaar?",
  "faq.print.a": "Je kunt een hoge-resolutie PNG downloaden die geschikt is voor persoonlijk printen. Printverzending en postbezorging worden op deze pagina niet aangeboden.",
  "faq.surfaces.q": "Heeft de kaart een voorkant, binnenkant en achterkant?",
  "faq.surfaces.a": "Het huidige product maakt één digitale PNG-kaart (foto, groet en bericht op één vlak), met kleine TheDigitalGifter-branding. Meerpagina-layouts voorkant/binnenkant/achterkant worden nog niet ondersteund.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Interactief voorbeeld van een kerstkaart",
  "a11y.livePreview": "Live voorbeeld van de kerstkaart",
  "a11y.progress": "Voortgang kaartcreatie",
};

const PL: Dict = {
  "seo.title": "Kreator kartek świątecznych | Spersonalizowane kartki na Boże Narodzenie",
  "seo.description": "Stwórz spersonalizowaną kartkę świąteczną, którą będą chcieli zachować — wybierz projekt, dodaj wiadomość i udostępnij lub pobierz.",
  "brand": "TheDigitalGifter",
  "breadcrumb.christmas": "Boże Narodzenie",
  "breadcrumb.cards": "Kartki",
  "hero.kicker": "Kreator kartek świątecznych",
  "hero.h1": "Stwórz kartkę świąteczną, którą będą chcieli zachować",
  "hero.lede": "Dodaj zdjęcie, wybierz świąteczny styl i napisz coś osobistego.",
  "hero.cta": "Stwórz moją kartkę",
  "hero.secondary": "Zobacz przykłady",
  "hero.promise": "Stwórz kartkę świąteczną, która naprawdę brzmi osobiście",
  "hero.support": "Zamień ulubione zdjęcie i kilka słów w piękną kartkę świąteczną dla osób, które kochasz.",
  "hero.front": "Przód",
  "hero.inside": "Wnętrze",
  "hero.open": "Zerknij do środka",
  "hero.close": "Pokaż przód",
  "examples.h2": "Przykłady kartek świątecznych",
  "examples.lede": "Wybrane dema — nie kartki klientów. Rodzina, para, zwierzak, elegancka, zabawna oraz portret → kartka.",
  "examples.demoBadge": "Przykład demo",
  "create.h2": "Stwórz spersonalizowaną kartkę świąteczną",
  "create.lede": "Prosta ścieżka od zdjęcia do gotowej kartki świątecznej.",
  "step.type": "Typ kartki",
  "step.photo": "Zdjęcie",
  "step.design": "Projekt",
  "step.message": "Wiadomość",
  "step.preview": "Podgląd",
  "step.result": "Twoja kartka",
  "type.ask": "Jaki rodzaj kartki świątecznej tworzysz?",
  "photo.ask": "Dodaj ulubione zdjęcie",
  "photo.upload": "Prześlij zdjęcie",
  "photo.usePortrait": "Użyj mojego świątecznego portretu",
  "photo.change": "Zmień zdjęcie",
  "photo.remove": "Usuń zdjęcie",
  "photo.hint": "JPEG, PNG lub WebP do 8MB. Renderowane na Twoim urządzeniu.",
  "photo.portraitLoaded": "Twój świąteczny portret jest gotowy do tej kartki.",
  "photo.skipHint": "Możesz kontynuować bez zdjęcia i dodać je później.",
  "photo.noneAvailable": "Nie znaleziono niedawnego świątecznego portretu na tym urządzeniu.",
  "photo.uploadFailed": "Nie udało się przesłać tego zdjęcia. Spróbuj ponownie.",
  "design.ask": "Wybierz świąteczny projekt",
  "design.lede": "Starannie dobrany zestaw mocnych kierunków — nie marketplace szablonów.",
  "message.ask": "Co chcesz napisać?",
  "message.writeOwn": "Napiszę sam(a)",
  "message.helpWrite": "Pomóż mi napisać",
  "message.who": "Dla kogo to jest?",
  "message.tone": "Ton",
  "message.generate": "Zaproponuj wiadomości",
  "message.generating": "Szukamy właściwych słów…",
  "message.retry": "Spróbuj ponownie",
  "message.suggestions": "Propozycje",
  "message.useSuggestion": "Użyj tej",
  "message.failed": "Nie udało się teraz wygenerować propozycji. Wpisana wiadomość pozostaje zapisana — spróbuj kiedy chcesz.",
  "message.moreInspiration": "Potrzebujesz inspiracji? Odkryj Wiadomości świąteczne",
  "message.placeholder": "Napisz wiadomość świąteczną, którą będą chcieli zachować…",
  "message.started": "Wiadomość",
  "personalize.to": "Imię odbiorcy",
  "personalize.from": "Od / nazwa rodziny",
  "personalize.year": "Rok",
  "personalize.toPlaceholder": "np. Babcia",
  "personalize.fromPlaceholder": "np. Emma, Noah oraz Mama i Tata",
  "preview.h2": "Podgląd Twojej kartki świątecznej",
  "preview.lede": "Kartka aktualizuje się, gdy zmieniasz zdjęcie, projekt i wiadomość.",
  "preview.create": "Stwórz moją kartkę świąteczną",
  "preview.creating": "Tworzymy Twoją kartkę…",
  "preview.edit": "Kontynuuj edycję",
  "preview.mobileEdit": "Edytuj",
  "preview.mobilePreview": "Podgląd",
  "preview.failed": "Nie udało się utworzyć tej kartki. Twoja praca nadal tu jest — spróbuj ponownie.",
  "result.h2": "Twoja kartka świąteczna",
  "result.lede": "Pobierz ją, udostępnij albo popraw coś i stwórz ponownie.",
  "result.download": "Pobierz",
  "result.share": "Udostępnij",
  "result.whatsapp": "WhatsApp",
  "result.email": "E-mail",
  "result.copyLink": "Skopiuj link do strony",
  "result.copied": "Link skopiowany",
  "result.edit": "Edytuj",
  "result.another": "Stwórz kolejną",
  "result.shareFailed": "Udostępnianie tym razem nie zadziałało. Możesz pobrać kartkę lub skopiować link do strony.",
  "result.formatNote": "Cyfrowa kartka PNG — pobierz lub udostępnij. Dostawa wydruków nie jest wliczona.",
  "nav.back": "Wstecz",
  "nav.continue": "Dalej",
  "nav.skipPhoto": "Kontynuuj bez zdjęcia",
  "how.h2": "Jak zrobić kartkę świąteczną online",
  "how.1.title": "Dodaj zdjęcie",
  "how.1.body": "Użyj własnego zdjęcia lub świątecznego portretu.",
  "how.2.title": "Wybierz projekt",
  "how.2.body": "Wybierz świąteczny styl, który lubisz.",
  "how.3.title": "Spersonalizuj",
  "how.3.body": "Dodaj wiadomość i odbiorcę.",
  "how.4.title": "Podziel się magią",
  "how.4.body": "Pobierz lub wyślij gotową kartkę świąteczną.",
  "photos.h2": "Twórz kartki ze zdjęć rodziny, pary lub pupila",
  "photos.lede": "Gotowa kartka pozostaje bohaterem — Twoje zdjęcie, świąteczny projekt i słowa, które brzmią jak Ty.",
  "messages.h2": "Wiadomości do kartek świątecznych",
  "messages.lede": "Napisz własną albo otrzymaj kilka sugestii w wybranym języku, bez opuszczania tej strony.",
  "portrait.h2": "Użyj swojego świątecznego portretu",
  "portrait.lede": "Masz już świąteczny portret? Przenieś go do kreatora kartek i dokończ wiadomością. Przekazanie z generatora świątecznych zdjęć jest obsługiwane.",
  "portrait.cta": "Użyj mojego świątecznego portretu",
  "portrait.make": "Najpierw stwórz świąteczny portret",
  "geo.h2": "Czym jest internetowy kreator kartek świątecznych?",
  "geo.body": "Internetowy kreator kartek świątecznych pozwala stworzyć spersonalizowaną kartkę ze zdjęciem, świątecznym projektem i własną wiadomością. W TheDigitalGifter możesz przesłać zdjęcie lub użyć świątecznego portretu, wybrać styl, napisać wiadomość lub uzyskać pomoc, a potem pobrać PNG albo udostępnić kartkę cyfrowo.",
  "faq.h2": "Często zadawane pytania",
  "faq.what.q": "Czym jest internetowy kreator kartek świątecznych?",
  "faq.what.a": "Internetowy kreator kartek świątecznych pozwala połączyć zdjęcie, świąteczny projekt i spersonalizowaną wiadomość w kartkę, którą można pobrać lub udostępnić cyfrowo.",
  "faq.how.q": "Jak stworzyć kartkę świąteczną?",
  "faq.how.a": "Wybierz typ kartki, dodaj zdjęcie (opcjonalnie), wybierz świąteczny projekt, napisz lub wygeneruj wiadomość, podejrzyj kartkę, a potem pobierz lub udostępnij gotowy PNG.",
  "faq.photo.q": "Czy mogę użyć własnego zdjęcia?",
  "faq.photo.a": "Tak. Prześlij zdjęcie JPEG, PNG lub WebP do 8MB. Renderowanie odbywa się na Twoim urządzeniu.",
  "faq.portrait.q": "Czy mogę użyć świątecznego portretu, który już stworzyłem?",
  "faq.portrait.a": "Tak. Jeśli stworzyłeś Świąteczny Portret na tym urządzeniu, możesz użyć go bezpośrednio — albo otwórz Kartki z wyniku portretu przez Zamien to w kartkę świąteczną.",
  "faq.family.q": "Czy mogę stworzyć rodzinną kartkę świąteczną?",
  "faq.family.a": "Tak. Wybierz typ Rodzina i przytulny lub klasyczny projekt, potem dodaj rodzinne zdjęcie i wiadomość.",
  "faq.pet.q": "Czy mogę zrobić kartkę ze zwierzakiem?",
  "faq.pet.a": "Tak. Wybierz Zwierzak, dodaj zdjęcie pupila (lub świąteczny portret) i wybierz zabawny, ale premium projekt.",
  "faq.message.q": "Czy możecie pomóc napisać wiadomość świąteczną?",
  "faq.message.a": "Tak. Użyj „Pomóż mi napisać” na tej stronie, aby dostać kilka propozycji, albo odkryj pełny generator Wiadomości świątecznych.",
  "faq.download.q": "Czy mogę pobrać kartkę?",
  "faq.download.a": "Tak. Gotowe kartki pobierają się jako obraz PNG, odpowiedni do cyfrowego udostępniania.",
  "faq.share.q": "Czy mogę udostępnić ją online?",
  "faq.share.a": "Tak. Użyj natywnego udostępniania, gdy przeglądarka je obsługuje, albo udostępnij przez WhatsApp, e-mail lub kopiując link do strony Kartki. Publiczne metadane udostępniania nie zawierają Twojej osobistej wiadomości ani imienia odbiorcy.",
  "faq.edit.q": "Czy mogę edytować po utworzeniu?",
  "faq.edit.a": "Tak. Użyj Edytuj, aby wrócić do szkicu i stworzyć ponownie. Wiadomość i ustawienia pozostają na tym urządzeniu.",
  "faq.styles.q": "Jakie style kartek świątecznych są dostępne?",
  "faq.styles.a": "Klasyczne Boże Narodzenie, Eleganckie złoto, Przytulna rodzina, Śnieżne święta, Romantyczne święta, Zabawne/Zwierzak, Minimalne święta i Vintage święta.",
  "faq.print.q": "Czy można wydrukować?",
  "faq.print.a": "Możesz pobrać PNG w wysokiej rozdzielczości, odpowiedni do osobistego druku. Realizacja druku i dostawa pocztowa nie są oferowane na tej stronie.",
  "faq.surfaces.q": "Czy kartka ma przód, wnętrze i tył?",
  "faq.surfaces.a": "Dzisiejszy produkt tworzy jedną cyfrową kartkę PNG (zdjęcie, życzenia i wiadomość na jednej powierzchni), z małym brandingiem TheDigitalGifter. Wielostronicowe układy przód/wnętrze/tył nie są jeszcze obsługiwane.",
  "lang.en": "English",
  "lang.ro": "Română",
  "a11y.heroCard": "Interaktywny przykład kartki świątecznej",
  "a11y.livePreview": "Podgląd na żywo kartki świątecznej",
  "a11y.progress": "Postęp tworzenia kartki",
};

export const TABLES: Partial<Record<LocaleCode, Dict>> = {
  en: EN,
  ro: RO,
  de: DE,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  pl: PL,
};

const WAVE1_LOCALES: LocaleCode[] = ["en", "ro", "de", "fr", "es", "it", "pt", "nl", "pl"];

/** Product UI keys that must be localized for Wave 1 (P3D coverage). */
export const REQUIRED_UI_KEYS = [
  "hero.h1",
  "hero.cta",
  "photo.upload",
  "message.generate",
  "message.who",
  "preview.create",
  "result.download",
  "result.share",
  "nav.continue",
  "nav.back",
  "personalize.to",
  "preview.failed",
] as const;

// Assert key parity: every Wave 1 pack must match EN key set.
const _enKeySet = Object.keys(TABLES.en!).sort().join("\0");
for (const loc of WAVE1_LOCALES) {
  const pack = TABLES[loc];
  if (!pack) throw new Error(`Missing Christmas card maker pack: ${loc}`);
  const keys = Object.keys(pack);
  if (keys.length !== Object.keys(TABLES.en!).length || keys.sort().join("\0") !== _enKeySet) {
    throw new Error(`Christmas card maker UI pack key mismatch for locale: ${loc}`);
  }
}

export function cardsT(key: string, locale: LocaleCode = "en"): string {
  const table = TABLES[locale] || TABLES.en;
  return table?.[key] || TABLES.en?.[key] || key;
}

export const CARD_MAKER_FAQ_KEYS = [
  "faq.what",
  "faq.how",
  "faq.photo",
  "faq.portrait",
  "faq.family",
  "faq.pet",
  "faq.message",
  "faq.download",
  "faq.share",
  "faq.edit",
  "faq.styles",
  "faq.print",
  "faq.surfaces",
] as const;

export function cardsMakerSeo(locale: LocaleCode = "en") {
  return {
    title: cardsT("seo.title", locale),
    description: cardsT("seo.description", locale),
    url: "https://www.thedigitalgifter.com/christmas/cards",
    image: "https://www.thedigitalgifter.com/assets/christmas/christmas_card_open.webp",
  };
}

export function cardsMakerJsonLd(locale: LocaleCode = "en") {
  const seo = cardsMakerSeo(locale);
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${seo.url}#webpage`,
        url: seo.url,
        name: seo.title,
        description: seo.description,
        inLanguage: locale,
        isPartOf: { "@id": "https://www.thedigitalgifter.com/#website" },
        primaryImageOfPage: { "@type": "ImageObject", url: seo.image },
      },
      {
        "@type": "BreadcrumbList",
        itemListElement: [
          {
            "@type": "ListItem",
            position: 1,
            name: cardsT("breadcrumb.christmas", locale),
            item: "https://www.thedigitalgifter.com/christmas",
          },
          {
            "@type": "ListItem",
            position: 2,
            name: cardsT("breadcrumb.cards", locale),
            item: seo.url,
          },
        ],
      },
      {
        "@type": "FAQPage",
        mainEntity: CARD_MAKER_FAQ_KEYS.map((base) => ({
          "@type": "Question",
          name: cardsT(`${base}.q`, locale),
          acceptedAnswer: {
            "@type": "Answer",
            text: cardsT(`${base}.a`, locale),
          },
        })),
      },
    ],
  };
}
