#!/usr/bin/env python3
"""Christmas Factory 200 — unique MOMENT matrix.

Distribution (exactly 200):
  joy 60 · nostalgia 40 · santa 30 · nyc 20 · europe 10 · cozy 20 · wow 10 · moody 10
"""

from __future__ import annotations

BUCKETS = {
    "joy": 60,
    "nostalgia": 40,
    "santa": 30,
    "nyc": 20,
    "europe": 10,
    "cozy": 20,
    "wow": 10,
    "moody": 10,
}


def _s(bucket: str, n: int, slug: str, title: str, happening: str, emotion: str, image: str, motion: str) -> dict:
    return {
        "id": f"cf200_{n:03d}_{slug}",
        "index": n,
        "bucket": bucket,
        "title": title,
        "happening": happening,
        "emotion": emotion,
        "image_core": image,
        "motion_core": motion,
    }


def build_scenes() -> list[dict]:
    scenes: list[dict] = []
    n = 0

    def add(bucket: str, slug: str, title: str, happening: str, emotion: str, image: str, motion: str) -> None:
        nonlocal n
        n += 1
        scenes.append(_s(bucket, n, slug, title, happening, emotion, image, motion))

    # --- 60 PURE CHRISTMAS JOY ---
    joy = [
        (
            "siblings_rush_presents",
            "Siblings rush the tree",
            "Two children in pajamas sprint toward presents under a glowing tree as parents laugh in the doorway.",
            "uncontainable Christmas morning joy",
            "Two excited children in Christmas pajamas rush toward a mountain of brightly wrapped presents beneath a huge glowing Christmas tree while their parents enter behind them laughing, fireplace burning, morning snow bright in large windows, golden fairy lights and creamy white room, red bows, rich evergreen, warm skin tones.",
            "SUBJECT: children run and drop to their knees at the gifts, faces lighting up. ENVIRONMENT: fire flickers, tree lights shimmer, wrapping paper shifts, snow falls outside the window. CAMERA: gentle forward tracking into the joy.",
        ),
        (
            "child_opens_first_gift",
            "First gift opened",
            "A child tears wrapping paper off a gift and gasps while a golden retriever wags beside her.",
            "discovery and delight",
            "A delighted little girl in red pajamas tears gold wrapping paper on the living-room floor while a golden retriever wags and her mother smiles from the couch, huge tree blazing with warm lights, fireplace, bright snowy window, red and gold presents, creamy white walls.",
            "SUBJECT: child rips paper and lifts the toy with a real gasp-smile. ENVIRONMENT: dog tail wags, fire flickers, tree lights glow, paper rustles. CAMERA: tiny handheld push toward her face.",
        ),
        (
            "grandma_cookies",
            "Grandma bakes cookies",
            "Grandmother and granddaughter frost Christmas cookies together, flour on their noses, laughing.",
            "cozy kitchen love",
            "A grandmother and granddaughter laugh while frosting star cookies in a bright warm kitchen, flour on noses, cooling racks of cookies, red mixer, window snow, fairy lights over cabinets, candles on the counter, evergreen wreath, healthy warm skin.",
            "SUBJECT: they spread frosting and giggle, granddaughter licks a spoon. ENVIRONMENT: oven steam, candle flicker, lights shimmer, snow outside. CAMERA: slow gentle push across the counter.",
        ),
        (
            "tree_decorating",
            "Family decorates the tree",
            "A family hangs ornaments together, a child lifted to place the star.",
            "together at last",
            "A father lifts a delighted child to place a gold star on a tall glowing Christmas tree while mother and older sibling hang red ornaments, living room luminous with fairy lights, fireplace, wrapped gifts, bright snow in windows, warm wood floors.",
            "SUBJECT: child places the star and the family cheers. ENVIRONMENT: fire flickers, tree lights shimmer, ornaments sway, snow outside. CAMERA: gentle upward tracking with the lift.",
        ),
        (
            "hot_cocoa_laugh",
            "Hot cocoa laugh",
            "Friends in knits clink cocoa mugs on a snowy porch strung with lights and burst out laughing.",
            "friendship glow",
            "Three friends in colorful knit hats laugh on a snowy porch, steaming cocoa with whipped cream, golden fairy lights overhead, wreath on the door, bright clean snow, warm windows behind them, red scarves, evergreens.",
            "SUBJECT: they clink mugs and laugh, steam from cocoa. ENVIRONMENT: snow falls at several depths, lights shimmer, door wreath ribbon moves slightly. CAMERA: gentle push onto the group.",
        ),
        (
            "snowball_fight",
            "Snowball fight in lights",
            "Kids throw snowballs in a yard completely wrapped in Christmas lights.",
            "playful Christmas energy",
            "Children throw snowballs in a suburban yard blazing with Christmas lights on the house, trees, and fence, bright snow, red coats, laughing faces, warm windows, wreath on the door, clean white snow not gray.",
            "SUBJECT: kids pack and throw snowballs, one ducks laughing. ENVIRONMENT: snowfall, house lights twinkle, distant cars. CAMERA: energetic but stable tracking among them.",
        ),
        (
            "shop_window_child",
            "Shop window wonder",
            "A child presses mittened hands to a glowing toy-shop window while parents smile behind her.",
            "I want that Christmas",
            "A delighted child in a red coat presses mittened hands against a glowing toy-shop window full of teddy bears, a model train, and wrapped gifts while her parents smile behind her, warm gold reflecting on fresh bright snow, street decorations, storefront glow.",
            "SUBJECT: child leans closer and points; parents smile and squeeze her shoulders. ENVIRONMENT: train moves in the window, lights shimmer, snow falls, a passerby walks. CAMERA: gentle push toward the glass.",
        ),
        (
            "ice_skate_first",
            "First ice skate",
            "A parent steadies a child on a rink under a giant Christmas tree as the child grins.",
            "brave first Christmas thrill",
            "A parent holds a grinning child's hands on an outdoor ice rink beneath an enormous glowing Christmas tree, warm string lights, festive crowd, bright snow banks, red scarves, creamy lights, evergreen wreaths around the rink.",
            "SUBJECT: child glides a few wobbly happy steps. ENVIRONMENT: skaters pass, tree lights shimmer, snow falls, breath steam. CAMERA: gentle side track with them.",
        ),
        (
            "dog_present",
            "Dog and the present",
            "A family dog investigates a wrapped gift with a bow on its collar while kids laugh.",
            "silly Christmas love",
            "A golden retriever with a red bow sniffs a large wrapped present under a glowing tree while two children on the rug laugh, fireplace, bright window snow, fairy lights, warm wood, healthy fur and skin.",
            "SUBJECT: dog paws the box and kids lean in laughing. ENVIRONMENT: tail wags, fire flickers, lights glow, paper crinkles. CAMERA: low gentle push toward the dog.",
        ),
        (
            "arrive_home_gifts",
            "Arriving home with gifts",
            "A family piles out of a car carrying presents toward a house blazing with Christmas lights.",
            "we're home for Christmas",
            "A family in winter coats carries armfuls of wrapped gifts from a snowy driveway toward a house glowing with Christmas lights, wreath, warm windows, clean bright snow, red front door, evergreen bushes, kids running ahead laughing.",
            "SUBJECT: kids run to the door, parents follow with gifts. ENVIRONMENT: snowfall, house lights twinkle, breath steam, door opens spilling warm light. CAMERA: low behind them tracking toward the house.",
        ),
        (
            "carolers_porch",
            "Carolers on the porch",
            "Neighbors sing on a porch while a family opens the door with cookies and smiles.",
            "neighborhood Christmas joy",
            "Carolers in scarves sing on a brightly lit porch as a family opens the door holding a plate of cookies, golden lights, wreath, candles in windows, falling bright snow, red ribbons, happy faces.",
            "SUBJECT: mouths sing, door family laughs and offers cookies. ENVIRONMENT: snow, lights shimmer, candle flicker. CAMERA: gentle push onto the porch.",
        ),
        (
            "matching_pj_dance",
            "Matching PJs dance",
            "A family in matching Christmas pajamas dances in the living room around the tree.",
            "goofy holiday happiness",
            "A family in matching red-and-white Christmas pajamas dances around a glowing tree, fireplace, fairy lights, bright lamps, snow in the window, gifts, warm wood, real laughter not posed smiles.",
            "SUBJECT: they spin and clap, a toddler bounces. ENVIRONMENT: tree lights, fire, a record or TV glow. CAMERA: tiny handheld circling energy without wild spins.",
        ),
        (
            "sleigh_ride_kids",
            "Horse sleigh ride",
            "Children laugh on a horse-drawn sleigh through a village strung with Christmas lights.",
            "magical outing",
            "Laughing children bundled in blankets ride a horse-drawn sleigh through a bright village square full of Christmas lights, wreaths, market stalls, clean snow, warm gold, red blankets, evergreen.",
            "SUBJECT: kids wave and bounce with the sleigh. ENVIRONMENT: horse walks, bells, snow, stall lights shimmer, people wave. CAMERA: tracking beside the sleigh.",
        ),
        (
            "letter_to_santa_mail",
            "Mailing Santa's letter",
            "A child stands on tiptoe to drop a letter into a red mailbox while dad films.",
            "hopeful excitement",
            "A child on tiptoe posts a handwritten letter into a bright red mailbox wrapped with a wreath on a snowy street of warm lights, dad filming with a smile, storefront glow, fresh snow, golden bulbs.",
            "SUBJECT: child pushes the letter in and turns with a huge smile. ENVIRONMENT: snow, lights, a car passes. CAMERA: gentle push to the mailbox then her face.",
        ),
        (
            "christmas_market_churros",
            "Market treats",
            "A couple shares a paper cone of roasted chestnuts in a packed luminous Christmas market.",
            "warmth in the crowd",
            "A couple laughs sharing roasted chestnuts in a packed European Christmas market overflowing with warm incandescent lights, wooden stalls, giant tree, bright snow, red mugs, evergreen garlands, steam, crowd life.",
            "SUBJECT: they eat and laugh, she steals a chestnut. ENVIRONMENT: crowd walks, stall lights shimmer, snow, steam from food. CAMERA: among-the-crowd slow drift.",
        ),
        (
            "tree_lighting_countdown",
            "Tree lighting countdown",
            "A crowd counts down as a huge city Christmas tree bursts into light and a child jumps.",
            "communal wow",
            "A packed snowy city square counts down as an enormous Christmas tree ignites in gold, a child on a parent's shoulders jumping, bright snow, red coats, surrounding buildings with wreaths, luminous not dark.",
            "SUBJECT: child throws arms up as lights bloom. ENVIRONMENT: tree lights cascade on, crowd cheers, snow. CAMERA: gentle rise toward the tree.",
        ),
        (
            "puppy_first_tree",
            "Puppy's first tree",
            "A puppy stares up at a glittering tree while a child crawls beside it, both amazed.",
            "first Christmas wonder",
            "A puppy and a toddler sit on a rug staring up at a tall glittering Christmas tree, fireplace, bright window, gifts, fairy lights, warm wood, creamy whites, red ornaments.",
            "SUBJECT: puppy tilts head, toddler claps. ENVIRONMENT: lights shimmer, fire, snow outside. CAMERA: low push from behind them up the tree.",
        ),
        (
            "wrapping_chaos",
            "Wrapping chaos",
            "Parents frantically wrap gifts at the table while kids peek from the hallway giggling.",
            "happy chaos",
            "Parents at a dining table covered in gold paper, ribbons, and tape wrap gifts under warm lamps and fairy lights while two kids peek giggling from a hallway, tree glowing behind, bright kitchen beyond.",
            "SUBJECT: parents tape a box, kids peek and duck. ENVIRONMENT: paper unrolls, lights, a cat bats ribbon. CAMERA: gentle push from hallway toward the table.",
        ),
        (
            "fireplace_stockings",
            "Stockings hung",
            "Children hang stockings on a mantel while parents lift the smallest to reach.",
            "ritual joy",
            "Children hang red stockings on a stone mantel stuffed with greenery and candles while parents lift the smallest child, roaring bright fireplace, tree to the side, snowy window, gold frames, warm wood.",
            "SUBJECT: stocking is hung and they cheer. ENVIRONMENT: fire, candles, lights. CAMERA: slow push to the mantel.",
        ),
        (
            "outdoor_tree_lot",
            "Choosing the tree",
            "A family argues happily over which pine to buy at a brightly lit Christmas tree lot.",
            "this is the one",
            "A family in coats stands among rows of pines at a Christmas tree lot strung with Edison bulbs, a child hugging a tree, red lot shack, hot cocoa stand steam, bright snow, warm gold lights.",
            "SUBJECT: child hugs a tree, dad laughs and nods yes. ENVIRONMENT: lot lights, snow, other families walk, steam. CAMERA: walk-with tracking.",
        ),
        (
            "window_snowfall_watch",
            "Watching the snow",
            "A child in pajamas watches heavy snowfall through a window framed by Christmas lights.",
            "quiet wonder that still feels like Christmas",
            "A child in pajamas kneels on a window seat watching bright snowfall, Christmas lights framing the glass, warm lamp, mug of cocoa, tree reflection, creamy interior, red plaid blanket, not a dark room.",
            "SUBJECT: child breathes on the glass and smiles. ENVIRONMENT: snow at several depths, lights shimmer, tree glow behind. CAMERA: from outside looking in, tiny push.",
        ),
        (
            "school_pageant",
            "School pageant glow",
            "A child in a costume waves from a brightly lit school stage while parents film from the aisle.",
            "proud Christmas night",
            "A child in a simple angel costume waves from a school stage framed by Christmas trees and warm lights while parents in the aisle film and smile, red auditorium seats, garlands, luminous stage not gloomy.",
            "SUBJECT: child waves, parents laugh and wave back. ENVIRONMENT: stage lights, trees, audience shift. CAMERA: from the aisle gently toward the stage.",
        ),
        (
            "breakfast_pancakes",
            "Christmas pancakes",
            "Kids in pajamas eat snowman pancakes at a sunny kitchen table with a mini tree.",
            "morning feast joy",
            "Kids in pajamas eat snowman pancakes with berry smiles at a bright kitchen table, mini Christmas tree, fairy lights, sunny snow outside, red mugs, warm wood, messy happy faces.",
            "SUBJECT: fork cuts a pancake, syrup drip, kid grins. ENVIRONMENT: lights, steam from cocoa, snow outside. CAMERA: table-level gentle push.",
        ),
        (
            "neighbors_lights",
            "Best lights on the block",
            "Kids drag parents down the sidewalk to see a house exploding with Christmas lights.",
            "look at THAT",
            "Kids pull their parents' hands down a sidewalk toward a house completely covered in brilliant Christmas lights, inflatable snowman, wreaths, bright snow, other families pointing, warm gold and red, clean whites.",
            "SUBJECT: kids point and bounce, parents laugh. ENVIRONMENT: lights chase, snow, cars crawl by. CAMERA: behind them tracking to the house.",
        ),
        (
            "ice_hot_chocolate_stand",
            "Rink cocoa stand",
            "Skaters crowd a cocoa stand beside a rink, steam and Christmas lights everywhere.",
            "warm hands, cold air",
            "Skaters in scarves crowd a wooden cocoa stand beside an outdoor rink, huge tree, steam, golden lights, bright snow, red cups, evergreen, laughing faces.",
            "SUBJECT: vendor hands a cup, skater takes it smiling. ENVIRONMENT: steam, lights, skaters pass, snow. CAMERA: along the stand.",
        ),
        (
            "present_for_teacher",
            "Gift for teacher",
            "A shy child holds out a wrapped gift in a classroom decorated for Christmas.",
            "sweet bravery",
            "A shy smiling child holds a small wrapped gift toward a delighted teacher in a classroom of paper snowflakes, tree, fairy lights, construction-paper garlands, bright windows, warm winter daylight.",
            "SUBJECT: child offers the gift, teacher kneels and hugs. ENVIRONMENT: classmates clap, lights, paper snowflakes stir. CAMERA: gentle classroom push.",
        ),
        (
            "twins_identical_gifts",
            "Twins unwrap together",
            "Twins rip identical wrapping paper at the same time and scream-laugh.",
            "shared explosion of joy",
            "Twin children on a rug rip identical red wrapping paper at the same moment under a blazing tree, parents filming, fireplace, bright snow window, gold bows, warm wood.",
            "SUBJECT: paper flies, they scream-laugh and compare toys. ENVIRONMENT: fire, lights, paper scraps. CAMERA: handheld-tiny between them.",
        ),
        (
            "dad_assembly",
            "Dad builds the toy",
            "Dad on the floor assembles a toy train while kids hover excitedly with leftover wrapping.",
            "almost ready",
            "A dad in a sweater sits on the floor assembling a wooden train under the tree while kids hover with leftover gold paper, coffee mug, fireplace, bright morning window, tools, warm chaos.",
            "SUBJECT: dad snaps a piece on, kids lean in. ENVIRONMENT: fire, lights, paper, train wheels start to roll. CAMERA: low push across the rug.",
        ),
        (
            "choir_outdoors",
            "Outdoor choir",
            "A community choir sings around a glowing tree in a park as families hold candles.",
            "voices in the cold that feel warm",
            "A community choir in coats sings around a huge glowing park Christmas tree, families holding candles, bright snow, gold lights, red scarves, evergreens, luminous night not dark.",
            "SUBJECT: singers breathe and smile, a child conductor-waves. ENVIRONMENT: candles flicker, tree lights, snow, audience sways. CAMERA: slow push through the crowd.",
        ),
        (
            "cat_ornament",
            "Cat vs ornament",
            "A cat bats a low ornament while a child tries not to laugh and a parent lunges gently.",
            "household Christmas comedy",
            "An orange cat bats a gold ornament on the lowest tree branch while a child covers a laugh and a parent reaches in, bright living room, fire, gifts, fairy lights, not a dark corner.",
            "SUBJECT: cat bats, child cracks up, parent steadies the tree. ENVIRONMENT: ornament swings, lights, fire. CAMERA: low near the tree skirt.",
        ),
    ]
    # expand joy to 60 with unique variants
    joy_extra = [
        (
            "sled_hill_lights",
            "Sled hill at dusk",
            "Kids sled a hill toward a village of Christmas lights, screaming happily.",
            "speed and joy",
            "Kids on wooden sleds fly down a bright snowy hill toward a village glowing with Christmas lights, red hats, evergreens, golden windows, clean snow, dusk still luminous.",
            "SUBJECT: sleds slide, kids scream-laugh. ENVIRONMENT: snow spray, village lights, trees. CAMERA: beside the sled tracking down.",
        ),
        (
            "bakery_window_line",
            "Bakery line",
            "A family waits in line at a glowing bakery for Christmas bread, kids bouncing.",
            "almost our turn",
            "A family waits outside a warmly glowing bakery, Christmas breads in the window, wreath, fairy lights, bright snow sidewalk, red boxes, steamed windows, excited kids.",
            "SUBJECT: kids bounce, parent points at a cake. ENVIRONMENT: door opens, steam, lights, snow. CAMERA: along the line toward the window.",
        ),
        (
            "photo_with_santa_mall",
            "Mall Santa photo",
            "A slightly nervous then suddenly beaming child sits on Santa's knee in a bright grotto.",
            "it's really him",
            "A child on Santa's knee in a bright mall grotto of candy-cane columns, huge tree, gold gifts, twinkle lights, photographer, parents waving, luminous and cheerful not eerie.",
            "SUBJECT: child's face goes from shy to beam, Santa ho-hos. ENVIRONMENT: lights, tree, camera flash glow. CAMERA: gentle push to their faces.",
        ),
        (
            "ice_lantern_walk",
            "Lantern walk",
            "Families walk a path lined with ice lanterns and Christmas lights through pines.",
            "enchanted togetherness",
            "Families walk a pine path lined with glowing ice lanterns and fairy lights, children carrying lanterns, bright snow, warm gold, red coats, evergreen tunnel, luminous.",
            "SUBJECT: child swings a lantern, parents hold hands. ENVIRONMENT: lantern flicker, snow, distant carol. CAMERA: walking behind them.",
        ),
        (
            "cousin_pile",
            "Cousin pile-on",
            "A pile of cousins collapse laughing on a rug next to opened gifts.",
            "too many kids, perfect",
            "A pile of cousins in pajamas collapse laughing on a rug among opened gifts and ribbons, huge tree, fire, bright window, gold paper everywhere, warm skin, red plaid.",
            "SUBJECT: they pile on and laugh. ENVIRONMENT: paper, lights, fire, a loose bow rolls. CAMERA: high-ish gentle push down to the pile.",
        ),
        (
            "street_vendor_pretzels",
            "Holiday pretzels",
            "A vendor hands a child a huge pretzel under strings of street Christmas lights.",
            "treat taste of the season",
            "A street vendor hands a child a giant pretzel under canopy Christmas lights, bright snow, red cart, steam, storefronts, gold bulbs, happy queue.",
            "SUBJECT: child bites, salt flakes, vendor grins. ENVIRONMENT: steam, lights, pedestrians. CAMERA: cart-level push.",
        ),
        (
            "new_bike_bow",
            "Bike with a bow",
            "A child sees a bicycle with a giant red bow beside the tree and covers their mouth.",
            "no way",
            "A child covers their mouth seeing a bicycle with a giant red bow beside a glowing tree, parents in the doorway smiling, fire, bright morning snow windows, gold paper, creamy room.",
            "SUBJECT: child runs to the bike and looks back at parents. ENVIRONMENT: lights, fire, bow ribbon stirs. CAMERA: from behind child toward the bike.",
        ),
        (
            "gingerbread_house",
            "Gingerbread house disaster",
            "A family laughs as a gingerbread wall collapses and they keep decorating anyway.",
            "perfectly imperfect",
            "A family around a kitchen island laughs as a gingerbread wall slumps, icing bags, candy, fairy lights, window snow, red aprons, warm bright kitchen.",
            "SUBJECT: wall slumps, they laugh and smear more icing. ENVIRONMENT: lights, snow, oven glow. CAMERA: island-level push.",
        ),
        (
            "midnight_cookies_santa",
            "Cookies for Santa",
            "Kids arrange cookies and a carrot on the hearth, whispering, then tiptoe upstairs.",
            "we have to be good",
            "Kids in pajamas carefully arrange cookies and a carrot on a hearth plate, whispering, tree blazing, stockings, fire low and bright, lamps on, not a dark house.",
            "SUBJECT: they set the plate, whisper, tiptoe away. ENVIRONMENT: fire, lights, a clock. CAMERA: hearth-level following them to the stairs.",
        ),
        (
            "train_set_loop",
            "Train around the tree",
            "A model train loops the tree as kids lie on their stomachs watching it, delighted.",
            "hypnotic Christmas joy",
            "Kids lie on their stomachs watching a model train loop a glowing tree on bright carpet, fire, gifts, cream walls, red engine, warm wood furniture, morning light.",
            "SUBJECT: heads follow the train, one kid cheers. ENVIRONMENT: train moves, lights, fire. CAMERA: low circling a little with the train.",
        ),
        (
            "aunt_arrival",
            "Aunt at the door",
            "The door flies open to an aunt buried in gifts and the kids tackle-hug her.",
            "she's here",
            "Front door opens to an aunt buried in wrapped gifts as kids tackle-hug her, wreath, warm hall light, snow on her coat, tree visible behind, luminous entry.",
            "SUBJECT: hug collision, gifts wobble, everyone laughs. ENVIRONMENT: snow on coat, wreath, hall lights. CAMERA: from inside as the door opens.",
        ),
        (
            "fireplace_stories",
            "Story by the fire",
            "A parent reads a Christmas book while kids lean in, fire bright, tree huge.",
            "safe and sparkly",
            "A parent reads a picture book by a bright fireplace, kids leaning in, huge tree, cocoa, fairy lights, snow window, red blanket, warm wood, faces lit gold.",
            "SUBJECT: page turns, kids point at a picture. ENVIRONMENT: fire, lights, snow. CAMERA: slow push into the huddle.",
        ),
        (
            "balcony_lights_city",
            "Balcony over lights",
            "A couple steps onto a balcony and the whole street is Christmas lights; they squeeze hands.",
            "the city dressed up for us",
            "A couple in coats steps onto a balcony above a street blazing with Christmas lights, wreaths, bright snow, warm windows, red buses or cars far below, gold canopy lights.",
            "SUBJECT: they squeeze hands and laugh softly. ENVIRONMENT: snow, lights, traffic glow. CAMERA: from behind them over the railing.",
        ),
        (
            "church_steps_after",
            "After the service",
            "Families pour down church steps in snow, kids comparing cookies from the hall.",
            "community glow",
            "Families pour down snowy church steps after service, wreaths, warm doorway light, kids comparing cookies, bright snow, gold lamps, red coats, evergreens.",
            "SUBJECT: kids show cookies, parents greet. ENVIRONMENT: snow, doorway light, bells. CAMERA: at the bottom of the steps looking up.",
        ),
        (
            "ice_sculpture_touch",
            "Ice sculpture",
            "A child touches an ice sculpture of a reindeer in a plaza of Christmas lights.",
            "cold magic",
            "A child in mittens touches a glowing ice reindeer sculpture in a plaza of Christmas lights and stalls, bright snow, gold, red booths, steam, evergreen.",
            "SUBJECT: mitten slides on ice, child grins. ENVIRONMENT: sculpture lights, snow, crowd. CAMERA: close then widen slightly.",
        ),
        (
            "red_sweater_group",
            "Ugly sweater party",
            "Friends in loud Christmas sweaters toast in a living room stuffed with decorations.",
            "ridiculous and happy",
            "Friends in loud Christmas sweaters toast in a living room stuffed with decorations, tree, fire, fairy lights, bright lamps, snacks, real laughter, red and gold everywhere.",
            "SUBJECT: glasses clink, someone snorts a laugh. ENVIRONMENT: lights, fire, a sweater bell jingles. CAMERA: group push-in.",
        ),
        (
            "first_snow_recess",
            "Snow day recess",
            "School kids explode onto a playground as first snow falls and Christmas break is days away.",
            "I can't wait",
            "School kids explode onto a playground in first snow, some in Christmas hats, bright daylight, red coats, school wreath on the door, clean snow, joyful chaos.",
            "SUBJECT: kids run and catch flakes. ENVIRONMENT: snow, door wreath, a bell. CAMERA: wide playground tracking a group.",
        ),
        (
            "nativity_kids",
            "Living nativity",
            "Children in a living nativity grin when a real lamb shifts, parents filming.",
            "tender funny holy night",
            "Children in simple costumes grin in a living nativity as a lamb shifts, warm string lights, stable set, parents filming, bright not gloomy, hay, gold lamps.",
            "SUBJECT: lamb moves, kids giggle, one stays solemn then smiles. ENVIRONMENT: lights, breath, audience. CAMERA: gentle stable-level push.",
        ),
        (
            "fireplace_marshmallows",
            "Fireplace marshmallows",
            "Kids roast marshmallows in a fireplace while a parent warns and then laughs.",
            "sticky Christmas",
            "Kids roast marshmallows at a bright fireplace, parent laughing, tree to the side, stockings, gold lights, creamy room, sticky faces, snow window.",
            "SUBJECT: marshmallow browns, kid blows on it. ENVIRONMENT: fire, lights. CAMERA: hearth close push.",
        ),
        (
            "last_ornament",
            "The last ornament",
            "A couple hangs the last ornament together and kisses quickly, tree complete.",
            "we did it",
            "A couple hangs the last red ornament on a fully lit tree and shares a quick kiss, boxes empty on the floor, fire, bright lamps, snow window, warm wood.",
            "SUBJECT: ornament hooks, quick kiss, they look at the tree. ENVIRONMENT: lights, fire. CAMERA: from the side of the tree.",
        ),
        (
            "market_carousel",
            "Christmas carousel",
            "Kids ride a small carousel in a Christmas market, parents waving every rotation.",
            "again again",
            "Kids ride a small brightly lit carousel in a Christmas market, painted horses, gold bulbs, stall lights, bright snow, parents waving, evergreen wreaths.",
            "SUBJECT: kids wave every pass. ENVIRONMENT: carousel turns, lights, snow, music implied. CAMERA: from the parents' waving spot.",
        ),
        (
            "snowman_carrot",
            "Finishing the snowman",
            "A child places the carrot nose on a snowman while a dog watches, house lights behind.",
            "we made a friend",
            "A child places a carrot nose on a snowman in a bright yard, house Christmas lights behind, scarf, coal eyes, dog watching, clean snow, gold windows.",
            "SUBJECT: carrot goes in, child steps back proud. ENVIRONMENT: dog shifts, house lights, snow. CAMERA: garden-level toward house.",
        ),
        (
            "open_one_eve",
            "One gift on Christmas Eve",
            "A family lets the kids open one gift on Christmas Eve — matching pajamas — and they immediately put them on.",
            "tradition unlocked",
            "Kids rip one allowed Christmas Eve gift revealing matching pajamas and immediately pull them on in a luminous living room, tree, fire, parents clapping, bright not dim.",
            "SUBJECT: paper off, pajamas on, spin to show. ENVIRONMENT: fire, lights. CAMERA: rug-level energy.",
        ),
        (
            "train_station_reunion",
            "Station reunion",
            "Someone runs through a decorated station into a hug, gifts in hand, lights everywhere.",
            "you made it",
            "A traveler runs through a historic station dressed in Christmas wreaths and lights into a tight hug, gifts, bright platforms, gold bulbs, red coats, steam, snow on coats.",
            "SUBJECT: run, hug, bags drop. ENVIRONMENT: crowd, lights, steam, a train. CAMERA: along the platform with them.",
        ),
        (
            "rooftop_tree_small",
            "Tiny rooftop tree",
            "Roommates carry a tiny tree onto a snowy rooftop strung with lights and cheer.",
            "our first tree",
            "Roommates carry a tiny Christmas tree onto a snowy rooftop strung with cafe lights, city glow warm not cold, red ornaments, cocoa, laughing, bright bulbs.",
            "SUBJECT: they set the tree and cheer. ENVIRONMENT: snow, string lights, city. CAMERA: rooftop push to skyline and tree.",
        ),
        (
            "candlelight_wish",
            "Birthday-on-Christmas wish",
            "A child whose birthday is Christmas blows a candle on a cupcake beside the tree.",
            "double celebration",
            "A child blows a candle on a Christmas cupcake beside a glowing tree, family singing, fire, gifts, bright room, red frosting, gold plate, warm faces.",
            "SUBJECT: candle blows out, cheer. ENVIRONMENT: smoke curl, lights, fire. CAMERA: close then back to family.",
        ),
        (
            "ice_truck_cocoa",
            "Hot cocoa truck",
            "A vintage truck serving cocoa is surrounded by families in a square of lights.",
            "parked happiness",
            "A vintage truck serving cocoa is surrounded by families in a square of Christmas lights, wreaths on the grille, steam, bright snow, red cups, gold bulbs, evergreen.",
            "SUBJECT: cups handed out, kids sip. ENVIRONMENT: steam, lights, snow, queue. CAMERA: around the truck.",
        ),
        (
            "fireplace_new_puppy",
            "Puppy under the tree",
            "A puppy with a bow sits in a basket under the tree as kids freeze then explode with joy.",
            "best gift ever",
            "A puppy with a red bow sits in a basket under a glowing tree as kids freeze then explode with joy, parents filming, fire, bright morning, gold paper.",
            "SUBJECT: freeze, scream, gentle pets. ENVIRONMENT: puppy moves, fire, lights. CAMERA: from parents' filming angle.",
        ),
        (
            "bridge_lights_run",
            "Bridge of lights",
            "Kids run across a footbridge wrapped in Christmas lights, parents jogging after.",
            "don't stop",
            "Kids run across a footbridge completely wrapped in Christmas lights over bright snow, parents jogging after laughing, evergreen banks, gold reflections on water or snow.",
            "SUBJECT: kids run and look back. ENVIRONMENT: lights, snow, parents. CAMERA: behind them on the bridge.",
        ),
        (
            "ornament_memory",
            "Baby's first ornament",
            "Parents hang a 'baby's first Christmas' ornament while the baby grabs at lights.",
            "this is our year",
            "Parents hang a baby's first Christmas ornament on a glowing tree while the baby in a onesie grabs toward lights, bright room, fire, gifts, warm wood, real smiles.",
            "SUBJECT: ornament hangs, baby reaches, parents laugh. ENVIRONMENT: lights, fire. CAMERA: close on hands then baby.",
        ),
        (
            "market_ice_rink_combo",
            "Market plus rink",
            "A wide shot becomes intimate as a kid pulls a parent from market stalls onto ice.",
            "more Christmas please",
            "A child pulls a parent from packed luminous market stalls onto a small ice patch, lights everywhere, bright snow, red cheeks, gold stalls, evergreen, steam.",
            "SUBJECT: child pulls, parent slips then laughs. ENVIRONMENT: crowd, lights, snow. CAMERA: follow from stalls to ice.",
        ),
        (
            "christmas_eve_drive_in",
            "Driveway reveal",
            "Kids in a car see their house lights for the first time this year and cheer.",
            "home looks like Christmas",
            "From inside a car, kids cheer seeing their house newly covered in Christmas lights, wreath, bright snow lawn, warm windows, gold icicle lights, red door.",
            "SUBJECT: kids press to glass and cheer. ENVIRONMENT: house lights twinkle, snow, wipers. CAMERA: over-shoulder from back seat.",
        ),
        (
            "cookie_exchange",
            "Cookie exchange",
            "Neighbors swap tins of cookies in a hallway full of coats and laughter.",
            "too many cookies, perfect",
            "Neighbors in a bright hallway swap cookie tins, coats piled, wreath, lamps, kids sneaking a cookie, gold tins, red lids, warm wood stairs.",
            "SUBJECT: tins exchange, kid sneaks a cookie. ENVIRONMENT: coats, lights, chatter implied. CAMERA: hallway push.",
        ),
        (
            "star_projection",
            "Living-room stars",
            "A cheap star projector plus the tree makes kids gasp as the ceiling fills with light.",
            "our house is magic",
            "Kids gasp as a living-room ceiling fills with warm star lights plus a blazing Christmas tree, fire, gifts, parents on the couch, creamy walls catching gold, not a dark rave.",
            "SUBJECT: kids lie back and point. ENVIRONMENT: moving stars, tree lights, fire. CAMERA: from the rug upward then to faces.",
        ),
    ]
    for row in (joy + joy_extra)[:60]:
        add("joy", *row)
    assert sum(1 for s in scenes if s["bucket"] == "joy") == 60, sum(1 for s in scenes if s["bucket"] == "joy")

    nostalgia = [
        (
            "morning_1994",
            "Christmas morning 1994",
            "Kids in oversized pajamas explode into a 1990s living room as a parent films on a camcorder.",
            "the year we still believed",
            "Christmas morning 1994: kids in oversized pajamas explode into a VHS-era living room, CRT television soft in the corner, camcorder parent filming, classic toys under a glowing real tree, warm incandescent lights, bright snow windows, period furniture, no modern phones.",
            "SUBJECT: kids run to gifts, camcorder parent pans. ENVIRONMENT: CRT glow, tree lights, fire or lamp, wrapping. CAMERA: slightly handheld 90s energy, gentle.",
        ),
        (
            "vhs_living_room",
            "VHS living room",
            "A family watches a Christmas tape on a CRT while kids shake presents.",
            "static and magic",
            "A 1990s family watches a Christmas special on a wood-grain CRT, kids shaking presents, tree blazing, lamps, wallpaper, bright not dingy, camcorder on the table, warm skin, red stockings.",
            "SUBJECT: kids shake boxes, adult adjusts tracking on the VCR. ENVIRONMENT: CRT flicker, lights, snow window. CAMERA: couch-level push.",
        ),
        (
            "secret_santa_check",
            "Did Santa come?",
            "A child peeks down the stairs in the dark-that-is-still-led-by-tree-light to see if Santa came.",
            "the secret check",
            "A child in 1990s pajamas peeks down stairs toward a living room where the tree is already glowing and gifts have appeared, night-light and tree light luminous, CRT off, stockings stuffed, cream walls, not horror-dark.",
            "SUBJECT: child creeps down then grin breaks. ENVIRONMENT: tree lights, a clock, maybe a dying fire. CAMERA: from below the stairs as they appear.",
        ),
        (
            "cookie_kitchen_90s",
            "1990s cookie kitchen",
            "A mom and kids bake in a 90s kitchen — white appliances, recipe card, radio, snow window.",
            "after-school December",
            "A 1990s kitchen: white appliances, handwritten recipe card, radio, mom and kids baking Christmas cookies, snow bright in the window, wreath, warm overhead light, no smartphones, flour, red oven mitts.",
            "SUBJECT: tray goes in the oven, kids sneak dough. ENVIRONMENT: radio, snow, oven glow. CAMERA: across the laminate island.",
        ),
        (
            "camcorder_dad",
            "Dad with the camcorder",
            "Dad films Christmas morning, the red REC light on, kids performing for the camera.",
            "we'll watch this every year",
            "A 1990s dad with a bulky camcorder films kids opening gifts, red REC light, tree, fire, CRT, period couches, bright lamps, gold paper, real clutter, warm.",
            "SUBJECT: kids play to camera, dad laughs behind the lens. ENVIRONMENT: lights, fire, tape whir implied. CAMERA: the camcorder POV slightly shaky then cut to a stable side view energy in one locked composition with tiny move.",
        ),
        (
            "bedroom_snow_day",
            "Bedroom snow day",
            "A child wakes to a snow day, Christmas drawings on the wall, tree glow from the hall.",
            "no school, it's almost Christmas",
            "A child's 1990s bedroom: posters, drawings of Santa, alarm clock, they throw back a quilt to bright snow piled on the sill, hall tree glow, warm lamp, red pajamas, no modern devices.",
            "SUBJECT: child runs to the window and cheers. ENVIRONMENT: snow outside, hall lights, curtain. CAMERA: from bed to window.",
        ),
        (
            "drive_home_eve_90s",
            "Driving home Christmas Eve 1996",
            "Kids asleep then wake as the car enters a town of Christmas lights, tree on the roof.",
            "almost there",
            "A 1990s European or American family wagon drives a snowy road at dusk with a tree tied on the roof toward a town blazing with Christmas lights, kids waking in the back, warm dash lights, bright snow, luminous town.",
            "SUBJECT: child sits up and points at the town. ENVIRONMENT: car moves, snow, town lights. CAMERA: low rear three-quarter tracking.",
        ),
        (
            "tinsel_tree_80s",
            "Tinsel tree 1980s",
            "An 80s living room with a tinsel tree, kids in patterned PJs, parents in sweaters.",
            "that specific sparkle",
            "An 1980s living room: heavy tinsel tree, big ornaments, wood paneling, kids in patterned pajamas, parents in sweaters, bright lamps, gifts in department-store paper, CRT, warm and joyful not ironic.",
            "SUBJECT: kid batts tinsel and laughs. ENVIRONMENT: tinsel shimmer, CRT, lamps. CAMERA: period-still then tiny push.",
        ),
        (
            "polaroid_pile",
            "Polaroids on the fridge",
            "A 90s kitchen fridge covered in Polaroids of Christmases past as a new one is stuck on.",
            "we keep everyone",
            "A 1990s kitchen fridge plastered with Polaroids of past Christmases, a kid sticking a new one, magnets, cookie tins, wreath, warm overhead, snow window, no phones.",
            "SUBJECT: Polaroid sticks, family looks. ENVIRONMENT: fridge hum implied, lights, snow. CAMERA: fridge-close push.",
        ),
        (
            "department_store_90s",
            "Department store windows 1994",
            "A crowd of 90s coats looks at animated department-store Christmas windows.",
            "the windows are better than TV",
            "1994 city sidewalk: families in period coats stare at animated department-store Christmas windows, warm gold displays, bright snow, no smartphones, taxis or trams era-correct, kids pointing.",
            "SUBJECT: kids point at a moving display. ENVIRONMENT: snow, window animation, crowd. CAMERA: among the crowd toward glass.",
        ),
        (
            "church_pageant_90s",
            "Church pageant 1993",
            "A grain-feeling but sharp photoreal 90s church pageant, kids in tea-towel costumes, proud parents.",
            "our kid is a shepherd",
            "A 1990s church basement or sanctuary pageant: kids in tea-towel shepherd costumes, paper stars, warm string lights, metal chairs, parents with cameras, bright and kind, not gloomy.",
            "SUBJECT: little shepherd waves. ENVIRONMENT: lights, audience, paper star. CAMERA: from a parent's row.",
        ),
        (
            "wood_tv_stand",
            "TV stand gifts",
            "Gifts stacked on a 90s TV stand beside the CRT, kids counting them.",
            "more than last year",
            "Gifts stacked on a 1990s oak TV stand beside a CRT, kids counting, tree to the side, lamps, carpet, bright snow window, period remote, warm.",
            "SUBJECT: kids count and argue happily. ENVIRONMENT: CRT standby, lights. CAMERA: TV-stand level.",
        ),
        (
            "roller_rink_holiday",
            "Holiday skate 1991",
            "A roller rink Christmas party, colored lights, kids in sweaters, DJ booth wreath.",
            "December Friday night",
            "A 1991 roller rink Christmas party: colored but warm lights, wreath on the DJ booth, kids in sweaters skating, banners, bright floor, festive not neon-cyber.",
            "SUBJECT: kids skate and grab hands. ENVIRONMENT: lights, other skaters, wreath. CAMERA: rink-side tracking.",
        ),
        (
            "radio_shack_toy",
            "Toy aisle December",
            "A 90s toy aisle packed at Christmas, kid holding a box looking at a parent with hope.",
            "please please please",
            "A 1990s toy store aisle packed at Christmas, fluorescent-but-warmed by decorations, kid holding a toy box looking up with hope, garlands, no modern branding text readable, parent smiling.",
            "SUBJECT: kid lifts the box, parent nods. ENVIRONMENT: other shoppers, garlands. CAMERA: aisle push.",
        ),
        (
            "station_wagon_tree",
            "Wagon and the tree",
            "A 90s station wagon with a tree sticking out, family photo moment in the lot.",
            "it barely fits",
            "A 1990s station wagon in a tree-lot, pine sticking out the back, family laughing, lot bulbs, bright snow, red lot flags, era-correct clothes, warm dusk.",
            "SUBJECT: they shove the tree, laugh. ENVIRONMENT: lot lights, snow. CAMERA: behind the open hatch.",
        ),
        (
            "rotary_phone_grandma",
            "Calling grandma",
            "A kid on a corded phone talks to grandma, tree in the background, 90s kitchen wall.",
            "tell her I got the doll",
            "A child on a beige corded wall phone in a 1990s kitchen tells grandma what they got, tree visible in the next room, wallpaper, bright, wreath, no cell phones.",
            "SUBJECT: kid talks and hops. ENVIRONMENT: cord stretch, tree lights through doorway. CAMERA: kitchen wall push.",
        ),
        (
            "advent_calendar_90s",
            "Advent calendar door",
            "A kid opens today's cardboard advent door, chocolate, siblings crowding.",
            "only a few left",
            "Kids crowd a cardboard advent calendar on a 90s fridge or wall, one door open, chocolate, kitchen lights, snow window, period magnets, warm.",
            "SUBJECT: door opens, chocolate out, siblings lean. ENVIRONMENT: kitchen, snow. CAMERA: fridge-close.",
        ),
        (
            "tupperware_cookies",
            "Tupperware cookie tin",
            "A 90s living room, someone opens the famous tin — is it cookies or sewing — it's cookies, cheers.",
            "the good tin",
            "A 1990s coffee table, famous holiday tin opened to cookies, family cheers, tree, CRT, lamps, carpet, bright, red tin, gold tree.",
            "SUBJECT: lid off, cheer, hands grab. ENVIRONMENT: lights, CRT. CAMERA: table-level.",
        ),
        (
            "school_bus_last_day",
            "Last day before break",
            "Kids pour off a yellow bus with paper Christmas crafts, snow starting.",
            "two weeks of Christmas",
            "Kids pour off a yellow school bus with paper Christmas crafts, snow starting, wreaths on houses, 90s backpacks, bright afternoon, red hats, no phones.",
            "SUBJECT: kids run up driveways. ENVIRONMENT: bus, snow, house lights beginning. CAMERA: across the street.",
        ),
        (
            "hi8_rewatch",
            "Watching last year",
            "A family watches last Christmas on the TV, kids embarrassed and delighted.",
            "that's baby me",
            "A 90s family watches last Christmas on the CRT, kids pointing at themselves, tree current and tree on screen, lamps, couches, bright, camcorder on the shelf.",
            "SUBJECT: pointing and laughing. ENVIRONMENT: CRT motion, tree lights. CAMERA: couch toward TV.",
        ),
    ]
    nostalgia_extra = [
        ("walkman_carols", "Walkman carols", "A teen in a 90s coat listens to carols on a Walkman walking a street of lights.", "private soundtrack", "A 1990s teen in a puffer coat walks a street of Christmas lights with a Walkman, bright snow, storefronts, Walkman visible, no smartphone, warm gold street.", "SUBJECT: teen walks nodding to music. ENVIRONMENT: snow, lights, cars. CAMERA: beside them."),
        ("mall_fountain", "Mall fountain December", "A 90s mall fountain with a tree, kids throw coins, food court glow.", "the mall was Christmas", "A 1990s mall atrium fountain and giant tree, kids throwing coins, food court glow, garlands, bright, period fashion, no modern stores text.", "SUBJECT: coin toss, wish. ENVIRONMENT: fountain, shoppers, tree. CAMERA: balcony looking down then closer."),
        ("paper_chains", "Paper chains", "Kids make paper chains at a school desk, construction paper, glue, 90s classroom.", "December art hour", "A 90s classroom making paper Christmas chains, construction paper, glue bottles, chalkboard wreath, bright windows, kids happy mess.", "SUBJECT: chain grows, glue strings. ENVIRONMENT: classroom bustle. CAMERA: desk-level."),
        ("fireplace_stockings_90s", "90s stockings", "Felt stockings with names on a brick fireplace, kids checking them, wood paneling.", "ours are heavier", "Felt name stockings on a brick 90s fireplace, kids checking fullness, wood paneling, tree, lamps, bright, shag or plush carpet.", "SUBJECT: hands in stockings. ENVIRONMENT: fire or glow, tree. CAMERA: mantel close."),
        ("ice_storm_lights", "Ice-storm lights still on", "After an ice storm, a house still blazing with Christmas lights, kids sliding in the yard.", "it looks like glass Christmas", "A house after ice storm still blazing with Christmas lights, kids sliding on bright ice, trees jeweled, warm windows, 90s coats, luminous.", "SUBJECT: kids slide. ENVIRONMENT: ice sparkle, lights. CAMERA: yard wide."),
        ("blockbuster_christmas", "Christmas movie night pickup", "A 90s family leaves a video store with a stack of Christmas tapes, snow, neon warm.", "we got the good ones", "A 90s family leaves a video rental store with a stack of Christmas tapes, warm neon, snow, period cars, kids arguing titles, wreath on the door.", "SUBJECT: stack of tapes, kids talk. ENVIRONMENT: snow, store glow. CAMERA: outside the door."),
        ("slide_projector", "Slide night", "Uncles run a slide projector of past Christmases, kids on the floor, tree still up.", "that's dad with hair", "A living room slide-projector night of past Christmases, beam of warm light, kids on floor, tree up, 90s furniture, bright lamp in back, laughter.", "SUBJECT: slide changes, jokes. ENVIRONMENT: projector fan, tree. CAMERA: from behind projector."),
        ("newspaper_toy_ads", "Toy catalog", "A kid circles toys in a thick catalog on the carpet, tree glow, 90s.", "the list is getting long", "A child circles toys in a thick Christmas catalog on 90s carpet, markers, tree glow, CRT, lamps, bright, no tablet.", "SUBJECT: circling, page flip. ENVIRONMENT: lights, paper. CAMERA: over-shoulder carpet."),
        ("midnight_mass_90s", "Midnight mass 1992", "Families in 90s coats leave a church at midnight into snow and a huge outdoor tree.", "peaceful then cookies", "Families in 1992 coats leave a church at midnight into bright snow and a huge outdoor Christmas tree, gold lamps, wreaths, kids half-asleep smiling.", "SUBJECT: family walks, kid leans on parent. ENVIRONMENT: snow, tree, church light. CAMERA: steps to sidewalk."),
        ("basement_train", "Basement train layout", "A 90s basement full of model-train Christmas village, kids on the stairs watching.", "grandpa's world", "A 1990s basement Christmas village and model trains, kids on stairs watching, warm lamps, fake snow, tiny houses lit, not dark dungeon — luminous layout.", "SUBJECT: trains move, kids point. ENVIRONMENT: village lights, trains. CAMERA: down the stairs toward the layout."),
        ("pantyhose_oranges", "Stocking oranges", "Kids dump stockings: oranges, candy canes, a tiny toy, 90s kitchen table.", "always an orange", "Kids dump 90s stockings on a kitchen table: oranges, candy canes, tiny toys, tree visible, bright morning, linoleum, warm.", "SUBJECT: orange rolls, candy cane unwrap. ENVIRONMENT: morning light, tree. CAMERA: table-top."),
        ("christmas_break_mall", "Break week mall", "Teens in 90s fashion hang at a mall tree, shopping bags, harmless joy.", "we lived here in December", "1990s teens hang by a mall Christmas tree with shopping bags, period fashion, bright atrium, garlands, food-court trays, smiles.", "SUBJECT: they talk and show a bag. ENVIRONMENT: shoppers, tree. CAMERA: atrium level."),
        ("food_processor_cookies", "Food processor cookies", "A 90s mom uses a huge food processor, kids watching cookie dough, radio carols.", "don't touch the blade", "1990s kitchen food processor making cookie dough, kids watching, radio, snow window, wreath, bright, period cabinets.", "SUBJECT: pulse, kids lean. ENVIRONMENT: machine, snow. CAMERA: counter."),
        ("aluminum_tree_color_wheel", "Color-wheel tree", "An aluminum tree with a color wheel in a mid-century room, kids fascinated.", "it changes color", "An aluminum Christmas tree with a color wheel washing a mid-century room, kids fascinated, bright, gifts, period furniture, magical not ironic.", "SUBJECT: wheel turns, kids watch color change. ENVIRONMENT: color wash, room lamps. CAMERA: toward the tree."),
        ("sleigh_bells_door", "Sleigh bells on the door", "Every time the 90s kitchen door opens, sleigh bells ring and kids look up hoping.", "is that him", "A 1990s kitchen door with sleigh bells, kids look up every time it opens, bright, cookies cooling, snow on boots, wreath.", "SUBJECT: door opens, bells, kids look. ENVIRONMENT: snow boots, lights. CAMERA: from the table to the door."),
        ("christmas_club_envelope", "Christmas club envelope", "A parent at a 90s kitchen table with an envelope of holiday cash, kids peeking, tree on.", "we can get the good bird", "A 1990s kitchen table, parent with a Christmas-club envelope, kids peeking, tree on in the next room, calculator, bright, warm, period.", "SUBJECT: envelope opens, kids peek. ENVIRONMENT: tree glow through door. CAMERA: table."),
        ("ice_rink_radio", "Pond radio", "Kids skate a pond with a portable radio playing carols, 80s/90s coats, house lights.", "our rink", "Kids skate a backyard pond, portable radio playing, 80s/90s coats, house Christmas lights, bright snow, thermos, evergreens.", "SUBJECT: skating, radio. ENVIRONMENT: ice, house lights, snow. CAMERA: pond edge."),
        ("tinsel_in_hair", "Tinsel in hair", "A 90s kid has tinsel stuck in their hair at dinner, everyone laughs.", "you're decorated", "A 1990s Christmas dinner table, tinsel stuck in a kid's hair, everyone laughing, ham, candles, tree behind, bright dining room, period dishes.", "SUBJECT: someone plucks tinsel, laughs. ENVIRONMENT: candles, tree. CAMERA: table."),
        ("new_years_almost", "The week after", "Kids still in Christmas PJs play with toys, tree still up, 90s, snow, not over yet.", "don't take it down", "A 90s living room the week after Christmas, tree still up, kids in PJs with new toys, snow, lamps, CRT, warm refusal to end the season.", "SUBJECT: play continues. ENVIRONMENT: lights still on, snow. CAMERA: room slow push."),
        ("church_basement_cookies", "After-service cookies", "90s church basement, folding tables, Christmas cookies, kids in dresses and clip-on ties.", "the good frosting", "A 1990s church basement, folding tables of Christmas cookies, kids in dresses and clip-on ties, garlands, bright fluorescent made warm by decorations.", "SUBJECT: cookie grab, frosting smiles. ENVIRONMENT: tables, people. CAMERA: table aisle."),
    ]
    for row in nostalgia + nostalgia_extra:
        add("nostalgia", *row)
    assert sum(1 for s in scenes if s["bucket"] == "nostalgia") == 40

    santa_rows = [
        ("santa_reads_letter", "Santa reads a letter", "Santa reads a handwritten letter beside a huge glowing tree and smiles, then reaches for a present.", "he really cares", "Santa reads a handwritten child's letter beside a huge glowing Christmas tree, smiles warmly, then reaches for a beautifully wrapped present while busy elves work behind him, workshop overflowing with toys, warm gold, red suit, luminous, not gloomy."),
        ("sleigh_prep", "Sleigh ready", "Santa's sleigh is packed as elves tighten harnesses in heavy bright snowfall.", "launch night", "Santa's sleigh packed with gifts, elves tightening harnesses, reindeer stamping, heavy bright snowfall, North Pole village blazing with lights, warm gold, red, evergreen, huge wow."),
        ("nice_list", "The nice list", "Santa checks the nice list with glasses, an elf pointing, workshop glowing.", "you're on it", "Santa with glasses checks a nice list, an elf pointing excitedly, workshop glowing with toys, candles, tree, warm wood, luminous shelves of gifts."),
        ("elf_wrapping_line", "Elf wrapping line", "A conveyor of elves wrapping gifts at speed, paper flying, joyful chaos.", "the factory of joy", "Elves wrap gifts at speed in a bright workshop, paper flying, ribbons, toys piled, warm lights, red and gold, huge tree, activity everywhere."),
        ("santa_village_square", "Santa village square", "Hundreds of warm lights in a Santa village, families arriving, cocoa, music implied.", "we found it", "A magical Santa village square filled with hundreds of warm lights, families arriving, cocoa stands, snow bright, red roofs, evergreen, stop-scroll wow."),
        ("reindeer_feed", "Feeding reindeer", "A child in the village feeds a reindeer a carrot while Santa watches smiling.", "they're real", "A child feeds a reindeer a carrot in a bright North Pole stable-yard, Santa watching smiling, lanterns, snow, gold straw light, elves, warm."),
        ("santa_desk_cookies", "Cookies on the desk", "Santa at his desk finds a plate of cookies on a letter and laughs.", "they always leave these", "Santa at a warm wooden desk finds cookies on a letter, laughs, workshop glow behind, tree, candles, maps, luminous office."),
        ("toy_test", "Toy test", "An elf tests a toy train, Santa claps, shelves of toys behind.", "it works", "An elf tests a toy train on a workshop table, Santa claps, shelves of toys, warm lights, gold, red, busy background elves."),
        ("mrs_claus_kitchen", "Mrs. Claus kitchen", "Mrs. Claus pulls cookies from an oven, elves steal one, she pretends not to see.", "the real boss", "Mrs. Claus pulls cookies from a huge oven in a bright North Pole kitchen, elves steal one, she almost smiles, copper, wreaths, warm."),
        ("gift_sack_load", "Loading the sack", "Elves toss gifts into Santa's sack, Santa hefts it with a grin.", "heavy with joy", "Elves toss wrapped gifts into Santa's enormous sack, he hefts it grinning, sleigh behind, snow, village lights, luminous night."),
        ("child_meets_santa", "First meeting", "A shy child meets Santa in a glowing grotto and then hugs him.", "it's him", "A shy child meets Santa in a glowing grotto of trees and gifts, then hugs him, parents tearing up, gold lights, bright, real."),
        ("workshop_door", "Workshop doors open", "Giant workshop doors open onto a hall of toys and elves as a visiting child gasps.", "the whole world of Christmas", "Giant red workshop doors open onto a hall overflowing with toys and busy elves, a visiting child gasps, warm gold, snow at the threshold."),
        ("aurora_sleigh", "Sleigh under aurora", "Sleigh lifts through snowfall with village lights below, joyful not ominous.", "here we go", "Santa's sleigh lifts through bright snowfall with a luminous village below, warm windows, gold, red sleigh, magical photoreal not CGI glitter storm."),
        ("map_table", "The route map", "Santa and elves lean over a glowing map of the world, pointing, excited.", "we can do it", "Santa and elves lean over a huge map table, lamps, cocoa, tree, workshop windows snow, warm wood, pointing excitedly."),
        ("broken_toy_fix", "Fixing a toy", "Santa personally repairs a wooden toy, an elf handing tools, soft smile.", "every child matters", "Santa repairs a wooden toy at a bench, elf handing tools, warm lamp, shelves, snow window, luminous, kind."),
        ("bells_harness", "Harness bells", "Elves shake harness bells to test them, reindeer ears twitch, Santa laughs.", "that's the sound", "Elves shake harness bells, reindeer ears twitch, Santa laughs, stable warm light, snow, gold brass, red leather."),
        ("north_pole_post", "North Pole post", "A mountain of letters, elves sorting, Santa picking one that makes him smile.", "this one", "Elves sort a mountain of letters in a bright post hall, Santa picks one and smiles, stamps, candles, gold, red sacks."),
        ("cookie_crumbs_roof", "Rooftop landing", "Sleigh on a snowy roof, chimney glow, Santa looks at the sleeping town lights.", "one more house", "Sleigh on a bright snowy rooftop, chimney warm glow, sleeping town of Christmas lights, Santa looks down smiling, luminous."),
        ("elf_choir", "Elf choir", "Elves sing around a workshop tree, Santa conducting with a candy cane.", "last rehearsal", "Elves sing around a huge workshop tree, Santa conducting with a candy cane, lights, toys, snow windows, joyful."),
        ("gift_inspection", "Gift inspection", "Santa inspects a perfectly wrapped gift, ribbon, nods, stamp of approval.", "that's the one", "Santa inspects a perfectly wrapped gold gift, nods, workshop glow, elves waiting, luminous table."),
        ("child_letter_writing", "Writing to Santa", "A child writes a letter at a kitchen table, decorations everywhere, hopeful face.", "dear Santa", "A child writes a letter to Santa at a kitchen table, decorations, cocoa, snow window, tree in the next room, warm, hopeful smile."),
        ("santa_wave_parade", "Santa parade wave", "Santa waves from a fire truck or sleigh float in a bright small-town parade.", "there he is", "Santa waves from a bright small-town parade float, crowds, Christmas lights, kids on shoulders, snow, gold, red, luminous day-to-dusk."),
        ("stable_morning", "Reindeer morning", "Elves brush reindeer in a bright stable, dust in warm light, cheerful.", "game day", "Elves brush reindeer in a bright stable, warm dust light, snow in the door, bells, red tack, cheerful work."),
        ("toy_mountain", "Mountain of toys", "A wow pile of toys in the workshop, elves climbing ladders, Santa tiny at the top smiling.", "we made enough", "A wow-scale mountain of toys in a luminous workshop, elves on ladders, Santa at the top smiling, gold, red, evergreen."),
        ("sleigh_keys", "The sleigh key", "An elf presents a huge ceremonial key, Santa pockets it, doors open to snow.", "time", "An elf presents a ceremonial key, Santa pockets it, workshop doors open to bright snow and waiting sleigh, lights, red, gold."),
        ("hot_cocoa_elves", "Elf break", "Elves on a cocoa break, boots up, then jump back to work as a bell rings.", "thirty seconds", "Elves on a cocoa break in a warm alcove, then jump back to work as a bell rings, lights, snow window, pastries, joy."),
        ("santa_mirror", "Suit check", "Santa checks his suit in a mirror, Mrs. Claus straightens the belt, they laugh.", "still fits", "Santa checks his suit in a tall mirror, Mrs. Claus straightens the belt, they laugh, warm room, tree, luminous."),
        ("first_gift_of_night", "First chimney", "Santa places the first gift of the night under a family tree, smiles, finger to lips.", "it begins", "Santa places the first gift under a family's glowing tree, finger to lips, fire, stockings, luminous living room, snow at the window."),
        ("north_pole_sunrise", "North Pole dawn", "After the night, Santa drinks cocoa on a porch watching village lights and a pale dawn.", "we did it again", "Santa drinks cocoa on a North Pole porch at pale dawn, village still lit, snow bright, warm, relieved smile, not exhausted-grim."),
        ("kid_mailbox_santa", "Letter in the red box", "A child posts a letter in a special Santa mailbox in a glowing town square.", "on its way", "A child posts a letter in a special Santa mailbox in a glowing town square, wreaths, lights, parents, bright snow, gold."),
    ]
    for i, (slug, title, happening, emotion, image) in enumerate(santa_rows):
        motion = (
            f"SUBJECT: {happening} continues naturally for five seconds. "
            "ENVIRONMENT: workshop or village lights shimmer, snow or fire or toys move, elves or family activity. "
            "CAMERA: gentle forward tracking. Complete the still. No frozen people."
        )
        add("santa", slug, title, happening, emotion, image, motion)
    assert sum(1 for s in scenes if s["bucket"] == "santa") == 30

    nyc_rows = [
        ("rockefeller_child", "Rockefeller first look", "A child sees the Rockefeller tree and stops mid-sidewalk, parents grinning.", "too big to be real", "A child stops mid-sidewalk seeing the enormous Rockefeller Christmas tree, parents grinning, bright ice-rink glow, flags, gold, clean snow, yellow cabs, luminous night."),
        ("fifth_ave_shopping", "Fifth Avenue bags", "A family with shopping bags laughs under Fifth Avenue snow and store lights.", "we got everyone", "A family with shopping bags laughs on Fifth Avenue, store windows glowing, wreaths, bright snow, cabs, gold canopies, 90s-to-timeless coats, no phones in hands."),
        ("cab_in_snow", "Yellow cab Christmas", "A yellow cab passes a brownstone block dripping with Christmas lights, couple kissing on stoop.", "movie New York", "A yellow cab passes a brownstone block dripping with Christmas lights, couple laughing on a stoop with a wreath, bright snow, gold windows, red bows, wet reflections."),
        ("plaza_steps", "Plaza steps", "Kids run up slushy bright steps toward a hotel dripping with wreaths.", "we're staying HERE", "Kids run up bright slushy steps toward a grand hotel dripping with wreaths and lights, doorman smiling, cabs, gold canopy, snow, red carpet hint."),
        ("central_park_carriage", "Park carriage", "A carriage ride through Central Park lamps and snow, riders bundled and laughing.", "this is the scene", "A horse carriage through Central Park lamps and snow, riders bundled laughing, wreaths on the carriage, warm lamps, bright snow, skyline sparkle."),
        ("brooklyn_stoop", "Brooklyn stoop lights", "Neighbors on a stoop with cocoa, every brownstone window a Christmas tree.", "our block", "Neighbors on a Brooklyn stoop with cocoa, every brownstone window showing a tree, lights on rails, bright snow, gold, red doors."),
        ("times_square_soft", "Times Square snow", "Not grimy: snow softening Times Square, a family pointing at Christmas ads and lights, joyful.", "so loud and so Christmas", "Snow softening Times Square, a family pointing at Christmas lights and displays, bright, cabs, red coats, luminous, no readable logos."),
        ("saks_windows", "Saks windows", "Kids press into Saks holiday windows, crowd, gold, snow, delight.", "the windows", "Kids press into glowing holiday windows on Fifth, crowd, gold displays, bright snow, cabs, wreaths, photoreal, no readable store text."),
        ("subway_musician", "Station musician", "A musician plays carols in a station with a tree, commuters smiling, kid dancing.", "even the subway", "A musician plays in a station decorated with a tree and lights, commuters smiling, a kid dancing, warm bulbs, not grimy-dark."),
        ("ice_rink_skyline", "Rink and skyline", "Skaters on a rink with NYC skyline and a huge tree, kid waving.", "city winter joy", "Skaters on a rink with NYC skyline and a huge Christmas tree, a kid waving, gold lights, bright ice, red scarves."),
        ("radio_city", "Radio City snow", "Crowds in snow outside a glowing marquee, families, Christmas week.", "the show", "Crowds in bright snow outside a glowing theater marquee, families, wreaths, gold, cabs, festive week energy, no readable titles."),
        ("chelsea_market_lights", "Market hall lights", "A food-hall winter market of lights, cocoa, couples, wreaths.", "warm indoors", "An indoor market hall of Christmas lights, cocoa, couples, wreaths, steam, gold, red, bright."),
        ("queens_house_lights", "Queens house display", "A house in Queens covered in lights, neighbors in the street watching, kids running.", "they win every year", "A Queens house covered in brilliant Christmas lights, neighbors in the street, kids running, bright snow, inflatables, gold, joyful."),
        ("grand_central_wreath", "Grand Central wreath", "Travelers look up at a huge wreath and lights, a reunion hug in the foreground.", "under the clock Christmas", "Travelers look up at huge holiday wreaths and lights in a grand concourse, a reunion hug in the foreground, luminous, gold, red coats."),
        ("staten_ferry_tree", "Harbor tree", "From a ferry, a city Christmas tree and skyline, family at the rail pointing.", "that's our city", "A family at a ferry rail pointing at a city Christmas tree and warm skyline, bright harbor, gold windows, red hats, snow in air."),
        ("soho_fire_escape", "Fire-escape wreaths", "Wreaths on fire escapes, a couple walking with a tree, SoHo snow, lights.", "we carried it home", "A couple carries a small tree through SoHo snow, wreaths on fire escapes, gallery-warm windows, gold, bright snow."),
        ("lincoln_center_tree", "Plaza tree", "A huge plaza tree, families in coats, bright, fountain-adjacent winter joy.", "civic Christmas", "A huge plaza Christmas tree, families in coats, bright snow, gold, red, elegant but joyful, not moody-empty."),
        ("dynasty_avenue_90s", "90s Manhattan dusk", "1990s Manhattan dusk, cab, tree lots on the avenue, kid in a puffer.", "the city in 1994", "1990s Manhattan dusk, yellow cab, sidewalk tree lot, kid in a puffer pointing, wreaths, bright, no smartphones, gold bulbs."),
        ("park_slope_cookies", "Park Slope cookies", "A stoop cookie exchange, trees in every window, kids on scooters with Santa hats.", "block party December", "A stoop cookie exchange, trees in every window, kids in Santa hats, bright snow, gold windows, red tins."),
        ("empire_window", "Apartment skyline tree", "Inside a cozy apartment, tree vs skyline, someone hangs a last ornament laughing.", "we live inside a postcard", "Inside a cozy Manhattan apartment, Christmas tree versus warm skyline, someone hangs a last ornament laughing, lamps, gifts, CRT optional, bright interior."),
    ]
    for slug, title, happening, emotion, image in nyc_rows:
        add(
            "nyc",
            slug,
            title,
            happening,
            emotion,
            image,
            f"SUBJECT: {happening} continues. ENVIRONMENT: snowfall, cabs or people moving, Christmas lights shimmer, steam. CAMERA: gentle street-level or room push. Complete the moment.",
        )
    assert sum(1 for s in scenes if s["bucket"] == "nyc") == 20

    europe_rows = [
        ("london_lights_child", "London lights child", "A child points at Regent-style lights as a black cab passes, parents laughing.", "London is Christmas", "A child points at warm suspended street Christmas lights as a classic black cab passes, shop windows glowing, bright snow, gold reflections, 90s coats, luminous London night."),
        ("paris_cafe_toast", "Paris café toast", "A couple toasts cocoa in a glowing café window, awning, snow, tree inside.", "nous voilà", "A couple toasts cocoa in a glowing Paris café window, red awning, small tree inside, bright snow, gold interior, street lights, real laughs."),
        ("vienna_market", "Vienna market", "A packed luminous market, choir, giant tree, child on shoulders.", "the square is singing", "A packed luminous Central European market, giant tree, child on shoulders, stalls, gold, red, bright snow, steam, life."),
        ("prague_old_town", "Old Town glow", "Families in an old-town square of lights, astronomical-feeling architecture, joy.", "storybook but real", "Families in a historic European square blazing with Christmas lights, bright snow, stalls, gold, red, architecture, joy, no gloom."),
        ("stockholm_sauna_window", "Nordic cocoa", "A family in knits at a bright window with advent stars, snow, candles, smiling.", "advent light", "A Nordic family in knits at a bright window of advent stars and candles, snow outside, tree, warm wood, smiles, luminous hygge."),
        ("rome_presepio", "Rome lights", "A family around a street nativity and lights, gelato in winter, laughing.", "Christmas in the south too", "A family around a street nativity and Christmas lights, winter evening still bright with bulbs, gold, red, stone, smiles."),
        ("edinburgh_close", "Close of lights", "Kids run a narrow close strung with lights toward a square tree.", "this way", "Kids run a narrow historic close strung with Christmas lights toward a square tree, bright snow, gold, red scarves."),
        ("amsterdam_canal", "Canal lights", "Bikes, canal reflections of Christmas lights, couple walking with a tree.", "reflections", "A couple walks a canal with a small tree, Christmas lights reflecting on water, bright, bikes, gold windows, snow dust."),
        ("munich_ stalls", "Munich stalls", "Crowded bright stalls, pretzel, steins of cocoa, giant tree.", "gemütlich joy", "Crowded bright German Christmas stalls, pretzel, cocoa, giant tree, gold, red, snow, smiles, steam."),
        ("alps_chalet_arrival", "Chalet arrival joy", "Kids run from a wagon toward a chalet blazing with Christmas windows.", "we're here", "Kids run from a snowy wagon toward a wooden chalet blazing with Christmas windows and a tree inside, bright snow, gold, smoke, luminous dusk not blue-black."),
    ]
    for slug, title, happening, emotion, image in europe_rows:
        add("europe", slug, title, happening, emotion, image, f"SUBJECT: {happening} continues. ENVIRONMENT: snow, lights, people, steam. CAMERA: gentle push. Complete the moment.")
    assert sum(1 for s in scenes if s["bucket"] == "europe") == 10

    cozy_rows = [
        ("couple_tree_lights", "Couple and the switch", "A couple flips the tree lights on for the first time in their apartment and kisses.", "our tree", "A couple flips on their first tree in a small apartment, lamps, snow window, gifts, warm wood, real kiss-laugh, luminous."),
        ("grandma_story", "Grandma's story", "Grandma tells a story, grandkids on the rug, fire, tree, cocoa.", "tell it again", "Grandma tells a story, grandkids on the rug, bright fire, huge tree, cocoa, gold, red blanket, warm faces."),
        ("couple_market_hands", "Gloves held", "A couple holds gloved hands through a market, swinging bags, laughing.", "don't let go", "A couple holds gloved hands through a luminous market, swinging bags, laughing, gold, snow, stalls."),
        ("cat_lap_fire", "Cat in the glow", "Someone reads, cat on lap, fire, tree, snow window, peace that is still Christmas.", "this is the feeling", "Someone reads with a cat on their lap, bright fire, tree, snow window, lamp, cocoa, gold, not empty-sad."),
        ("new_parents_tree", "New parents", "New parents hang a tiny stocking, baby asleep, tree soft-bright.", "first Christmas of three", "New parents hang a tiny stocking, baby asleep in a bassinet, tree soft-bright, lamps, gifts, warm, happy tired smiles."),
        ("friendsgiving_xmas", "Friends' Christmas", "A found-family dinner, mismatched chairs, tree, toasts, laughter.", "we chose each other", "A found-family Christmas dinner, mismatched chairs, tree, toasts, laughter, candles, gold, red, bright dining room."),
        ("proposal_tree", "Proposal by the tree", "A proposal by a public tree, she laughs then cries, crowd claps.", "yes", "A proposal by a huge public Christmas tree, she laughs then cries, crowd claps, gold, snow, luminous, real."),
        ("dog_walk_lights", "Night dog walk", "A couple walks a dog through a neighborhood of lights, steam, smiles.", "one more block", "A couple walks a dog through a neighborhood of Christmas lights, steam, smiles, bright snow, gold windows, red leash."),
        ("long_distance_video", "Long-distance tree", "Two apartments, two trees, a laptop video call, both decorating, laughing.", "same time", "Two luminous rooms implied in one composition: a person video-calls while decorating a tree, laptop showing another tree, warm, joyful, 2010s-ok but cozy, no ugly UI text."),
        ("baking_couple", "Couple baking", "A couple dances while cookies bake, flour, fairy lights, radio.", "timer's not done", "A couple dances in a kitchen while cookies bake, flour, fairy lights, radio, snow window, gold, red aprons."),
        ("inlaws_arrival", "In-laws at the door", "Nervous then warm hug at a wreath door, pie in hands, snow.", "they brought pie", "Nervous then warm hug at a wreath-hung door, pie in hands, snow, hall tree glow, gold, bright."),
        ("pet_stockings", "Pet stockings", "A dog and cat have stockings, kids hanging them, chaos, love.", "they get presents too", "Kids hang pet stockings, dog and cat in frame, tree, fire, bright, gold, red, chaos-love."),
        ("widow_neighbor", "Neighbor invitation", "A neighbor invites someone in from the cold to a bright table with extra place.", "you shouldn't be alone", "A neighbor invites someone in to a bright Christmas table with an extra place, tree, candles, warm faces, gold, kind joy."),
        ("adopted_tree", "First tree together", "Roommates or a couple carry a tree up stairs, laughing, stuck in a turn.", "pivot", "A couple or roommates carry a tree up bright stairwell, stuck in a turn, laughing, wreaths on doors, gold, snow on the tree."),
        ("bath_robe_cocoa", "Robes and cocoa", "Two people in robes on a couch, tree, fire, snow, talking close.", "stay up", "Two people in robes on a couch with cocoa, tree, fire, snow window, talking close, lamps, gold, intimate-warm not sad."),
        ("kids_asleep_parents", "Kids asleep", "Parents look at sleeping kids under the tree glow, then sneak wrapping.", "we still have time", "Parents look at sleeping kids in tree glow, then sneak leftover wrapping, lamps on, luminous, smiling conspiracy."),
        ("letter_from_friend", "Card pile", "Someone reads a Christmas card and laughs, pile of cards, tree.", "they remembered", "Someone reads a Christmas card and laughs, pile of cards on a mantel, tree, candles, gold, bright."),
        ("shared_playlist", "Kitchen dance", "A small kitchen dance while the tree is visible, snow, speakers, joy.", "this song", "A small kitchen dance, tree visible through the door, snow, warm, gold, red, laughter."),
        ("fireplace_two_dogs", "Two dogs", "Two dogs asleep by the fire, tree, someone tiptoes with gifts.", "don't wake them", "Two dogs asleep by a bright fire, tree, someone tiptoes with gifts, gold, cream rug, warm."),
        ("breakfast_in_bed_xmas", "Breakfast in bed", "Kids bring parents breakfast in bed on Christmas, crumbs, tree down the hall.", "we made toast", "Kids bring parents breakfast in bed on Christmas, crumbs, tree glow down the hall, lamps, pajamas, laughter."),
    ]
    for slug, title, happening, emotion, image in cozy_rows:
        add("cozy", slug, title, happening, emotion, image, f"SUBJECT: {happening} continues. ENVIRONMENT: fire or lights or snow, small life. CAMERA: intimate gentle push. Complete the moment.")
    assert sum(1 for s in scenes if s["bucket"] == "cozy") == 20

    wow_rows = [
        ("city_square_giant_tree", "Giant square tree", "A child seeing an enormous city-square tree for the first time, crowd, snow, explosion of lights.", "STOP", "A child seeing an enormous decorated Christmas tree in a snowy city square for the first time, crowd, bright snow, gold cascade of lights, red, evergreen, immediate stop-scroll."),
        ("santa_village_huge", "Santa village huge", "Wide vertical of a Santa village with hundreds of warm lights and moving people.", "we found the North Pole", "A huge Santa village filled with hundreds of warm lights, moving families, workshops, snow bright, gold, red roofs, wow scale, photoreal."),
        ("workshop_overflow", "Workshop overflow", "A workshop so full of toys and elves it feels infinite, luminous.", "infinite Christmas", "A Santa workshop overflowing with toys and activity, elves everywhere, gold lamps, red, huge tree, luminous, wow."),
        ("manhattan_from_above_alive", "Manhattan Christmas canopy", "Snow-covered Manhattan glowing with Christmas decorations, a sleigh-level but real rooftop view, life in streets.", "the city dressed", "Snow-covered Manhattan glowing with Christmas decorations, streets alive, gold, red, wreaths, luminous, photoreal rooftop-wide vertical."),
        ("luxury_chalet_decked", "Luxury chalet decked", "A huge alpine chalet completely decorated, guests arriving with gifts, windows blazing.", "the house is a gift", "A huge luxury chalet decorated for Christmas, guests arriving with gifts, windows blazing, tree visible, bright snow, gold, wow."),
        ("hotel_lobby_transformed", "Hotel lobby Christmas", "A grand hotel lobby transformed: tree to the ceiling, children spinning, luggage, lights.", "the lobby is a forest of gold", "A grand hotel lobby transformed for Christmas, tree to the ceiling, children spinning, luggage, gold, red, luminous, wow."),
        ("sleigh_departure_heavy_snow", "Sleigh departure", "Sleigh launching through heavy bright snowfall from a glowing village.", "go", "Santa sleigh preparing to leave through heavy bright snowfall, village glowing, elves waving, gold, red, wow, photoreal."),
        ("market_packed_life", "Market packed", "A European market so packed with lights and life it feels like the center of the world.", "the heart of December", "A European Christmas market packed with lights and life, giant tree, steam, gold, red, bright snow, wow density."),
        ("street_fully_lit", "Street fully lit", "A street completely illuminated by Christmas decorations, people walking, snow, taxis.", "no dark left", "A snowy street completely illuminated by Christmas decorations, people walking, taxis, gold canopy lights, storefronts, wow."),
        ("kids_huge_tree_first", "Kids vs giant tree", "Children looking up at an indoor mall or palace tree that fills the frame.", "our necks hurt", "Children looking up at an enormous indoor Christmas tree filling the 9:16 frame, gold, red, shoppers, luminous, wow first-time faces."),
    ]
    for slug, title, happening, emotion, image in wow_rows:
        add("wow", slug, title, happening, emotion, image, f"SUBJECT: {happening} continues with human motion. ENVIRONMENT: massive light shimmer, snow, crowd. CAMERA: slow awe push. Complete the moment.")
    assert sum(1 for s in scenes if s["bucket"] == "wow") == 10

    moody_rows = [
        ("candlelit_choir", "Candlelit but luminous", "A candlelit choir, faces warm gold, not crushed black, a child smiling.", "quiet wow", "A candlelit choir, faces warm gold, church still luminous, greenery, gold, a child smiling, elegant not depressing."),
        ("first_snow_alone_then", "First snow then a friend", "Someone watches first snow, then a friend arrives with cocoa, both smile.", "I thought I'd be alone", "Someone watches first snow from a warmly lit window, then a friend arrives with cocoa, both smile, tree, gold, elegant, not sad-ending."),
        ("empty_square_then_lights", "Square before the rush", "An elegant square just as lights come on, then people appear laughing.", "it's starting", "An elegant square as Christmas lights come on, then people appear laughing, bright snow, gold, 5% moody then alive."),
        ("piano_living_room", "Piano carols", "Someone plays piano carols, family listens, fire, tree, refined warmth.", "that song", "Someone plays piano carols, family listens, bright fire, tree, lamps, gold, elegant warmth, smiles."),
        ("hotel_bar_wreath", "Hotel bar wreath", "A couple at a hotel bar with a wreath, toast, warm, dressed up, happy.", "we got a sitter", "A couple toast at a hotel bar with a wreath and tree, warm gold, dressed up, happy, luminous, not noir."),
        ("library_tree", "Library tree", "A grand library with a tree, a child finds a book and shows a parent, gold lamps.", "found it", "A grand library with a Christmas tree, a child finds a book and shows a parent, gold lamps, warm wood, luminous, elegant."),
        ("opera_steps_snow", "Opera steps", "Dressed families on bright snowy opera-house steps, wreaths, laughing.", "after the matinee", "Dressed families on bright snowy opera-house steps, wreaths, laughing, gold lamps, elegant joy not grim prestige."),
        ("single_candle_table", "Two-place table", "A beautifully set two-place Christmas table, couple sitting down smiling, candles, tree.", "just us", "A beautifully set two-place Christmas table, couple sitting down smiling, candles, tree, gold, cream, luminous intimate."),
        ("snow_globe_hands", "Snow globe", "Hands turn a snow globe by a window of city lights, a smile in the glass reflection.", "the tiny world", "Hands turn a snow globe by a window of warm city Christmas lights, a smile in the glass, lamp, cream, elegant, not empty."),
        ("midnight_street_elegant", "Elegant midnight street", "A couple in coats walks a quietly luminous street of wreaths, still colorful, still Christmas.", "the long way home", "A couple in coats walks a quietly luminous street of wreaths and gold lamps, still colorful Christmas, bright snow, elegant 5% moody maximum."),
    ]
    for slug, title, happening, emotion, image in moody_rows:
        add(
            "moody",
            slug,
            title,
            happening,
            emotion,
            image,
            f"SUBJECT: {happening} continues with a smile or approach. ENVIRONMENT: candles or lamps shimmer, gentle snow. CAMERA: slow elegant push. Keep it luminous.",
        )
    assert sum(1 for s in scenes if s["bucket"] == "moody") == 10
    assert n == 200, n
    counts = {k: 0 for k in BUCKETS}
    for s in scenes:
        counts[s["bucket"]] += 1
    assert counts == BUCKETS, counts
    return scenes


if __name__ == "__main__":
    built = build_scenes()
    print({"count": len(built), "buckets": {k: sum(1 for s in built if s["bucket"] == k) for k in BUCKETS}})
