/**
 * Digital Christmas Tree UI copy — Wave 1 locale packs.
 * Message-gift focused. pt = European Portuguese.
 */

export type TreeLocale = "en" | "ro" | "de" | "fr" | "es" | "it" | "pt" | "nl" | "pl";

export const TREE_UI_LOCALES: TreeLocale[] = [
  "en",
  "ro",
  "de",
  "fr",
  "es",
  "it",
  "pt",
  "nl",
  "pl",
];

type Dict = Record<string, string>;

const EN: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Your Christmas Tree",
  "title.shared": "A Christmas Tree",
  "title.fallback": "A Christmas Tree is waiting for you",
  "lede.create": "I've made you a Christmas tree — tap a gift.",
  "lede.shared": "Tap a gift to open it",
  "lede.from": "From {name}",
  "lede.shareMeta": "Someone made you a Christmas tree — tap a gift.",
  "unavailable.title": "This tree is private",
  "unavailable.body": "Ask the sender for a fresh share link, or build your own.",
  "unavailable.metaTitle": "Christmas Tree unavailable",
  "unavailable.metaDesc": "This Christmas Tree is private or no longer available.",
  "unavailable.cta": "Build your Christmas Tree",
  "gifts.heading": "Gifts under the tree",
  "gifts.empty": "No gifts yet",
  "gifts.openAria": "Open gift {name}",
  "gifts.fallbackName": "Gift {n}",
  "gifts.moveEarlier": "Move gift earlier",
  "gifts.moveLater": "Move gift later",
  "gifts.up": "Up",
  "gifts.down": "Down",
  "gifts.count": "{count} gifts",
  "gifts.countOne": "1 gift",
  "editor.aria": "Tree editor",
  "editor.style": "Tree style",
  "editor.lights": "Lights",
  "editor.snow": "Snow",
  "editor.topper": "Topper",
  "editor.ornaments": "Ornaments",
  "editor.title": "Title",
  "editor.greeting": "Greeting",
  "editor.from": "From",
  "editor.saveCreate": "Save my Christmas Tree",
  "editor.saving": "Saving…",
  "editor.saveChanges": "Save changes",
  "topper.star": "Star",
  "topper.angel": "Angel",
  "topper.bow": "Bow",
  "topper.none": "None",
  "ornaments.classic": "Classic",
  "ornaments.gold": "Gold",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Colorful",
  "treeStyle.classic": "Classic",
  "treeStyle.snowy": "Snowy",
  "treeStyle.gold": "Gold",
  "treeStyle.cozy": "Cozy",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Magical",
  "gift.add": "Add a gift",
  "gift.for": "For",
  "gift.message": "Message",
  "gift.box": "Box",
  "gift.addCta": "Add gift",
  "gift.defaultName": "Gift",
  "gift.crossPortrait": "Add a Christmas Portrait",
  "gift.crossSanta": "Create a Santa Video",
  "gift.wantMore": "Want more?",
  "box.red": "Red",
  "box.gold": "Gold",
  "box.green": "Green",
  "box.blue": "Blue",
  "box.snow": "Snow",
  "share.heading": "Send your Christmas Tree",
  "share.privacy": "Private by default. Sharing turns on a secure link — it never grants edit access.",
  "share.enable": "Enable sharing",
  "share.link": "Share link",
  "share.off": "Turn sharing off",
  "share.copied": "Link copied",
  "share.nativeTitle": "Send your Christmas Tree",
  "share.nativeText": "I've made you a Christmas tree — tap a gift.",
  "reveal.aria": "Gift opened",
  "reveal.close": "Close",
  "nav.makeOwn": "Make your own Christmas Tree",
  "nav.advent": "Advent",
  "nav.openAdvent": "Open Advent Calendar",
  "nav.build": "Build your Christmas Tree",
  "loading": "Loading…",
  "error.load": "Could not load tree",
  "error.create": "Create failed",
  "error.save": "Save failed",
  "error.addGift": "Add gift failed",
  "error.reorder": "Reorder failed",
  "error.share": "Share update failed",
  "error.open": "Could not open gift",
  "defaults.title": "My Christmas Tree",
  "defaults.message": "I've made you a Christmas tree — tap a gift.",
};

const RO: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Bradul tău de Crăciun",
  "title.shared": "Un brad de Crăciun",
  "title.fallback": "Te așteaptă un brad de Crăciun",
  "lede.create": "Ți-am făcut un brad de Crăciun — atinge un cadou.",
  "lede.shared": "Atinge un cadou ca să-l deschizi",
  "lede.from": "De la {name}",
  "lede.shareMeta": "Cineva ți-a făcut un brad de Crăciun — atinge un cadou.",
  "unavailable.title": "Acest brad este privat",
  "unavailable.body": "Cere expeditorului un link nou sau creează-ți propriul brad.",
  "unavailable.metaTitle": "Brad de Crăciun indisponibil",
  "unavailable.metaDesc": "Acest brad de Crăciun este privat sau nu mai este disponibil.",
  "unavailable.cta": "Creează-ți bradul de Crăciun",
  "gifts.heading": "Cadouri sub brad",
  "gifts.empty": "Niciun cadou încă",
  "gifts.openAria": "Deschide cadoul {name}",
  "gifts.fallbackName": "Cadou {n}",
  "gifts.moveEarlier": "Mută cadoul mai sus",
  "gifts.moveLater": "Mută cadoul mai jos",
  "gifts.up": "Sus",
  "gifts.down": "Jos",
  "gifts.count": "{count} cadouri",
  "gifts.countOne": "1 cadou",
  "editor.aria": "Editor brad",
  "editor.style": "Stilul bradului",
  "editor.lights": "Luminițe",
  "editor.snow": "Zăpadă",
  "editor.topper": "Vârf",
  "editor.ornaments": "Ornamente",
  "editor.title": "Titlu",
  "editor.greeting": "Mesaj",
  "editor.from": "De la",
  "editor.saveCreate": "Salvează bradul meu de Crăciun",
  "editor.saving": "Se salvează…",
  "editor.saveChanges": "Salvează modificările",
  "topper.star": "Stea",
  "topper.angel": "Înger",
  "topper.bow": "Fundă",
  "topper.none": "Niciunul",
  "ornaments.classic": "Clasic",
  "ornaments.gold": "Auriu",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Colorat",
  "treeStyle.classic": "Clasic",
  "treeStyle.snowy": "Înzăpezit",
  "treeStyle.gold": "Auriu",
  "treeStyle.cozy": "Confortabil",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Magic",
  "gift.add": "Adaugă un cadou",
  "gift.for": "Pentru",
  "gift.message": "Mesaj",
  "gift.box": "Cutie",
  "gift.addCta": "Adaugă cadou",
  "gift.defaultName": "Cadou",
  "gift.crossPortrait": "Adaugă un portret de Crăciun",
  "gift.crossSanta": "Creează un video cu Moș Crăciun",
  "gift.wantMore": "Vrei mai mult?",
  "box.red": "Roșu",
  "box.gold": "Auriu",
  "box.green": "Verde",
  "box.blue": "Albastru",
  "box.snow": "Zăpadă",
  "share.heading": "Trimite bradul de Crăciun",
  "share.privacy": "Privat implicit. Partajarea activează un link securizat — nu oferă niciodată drepturi de editare.",
  "share.enable": "Activează partajarea",
  "share.link": "Partajează linkul",
  "share.off": "Oprește partajarea",
  "share.copied": "Link copiat",
  "share.nativeTitle": "Trimite bradul tău de Crăciun",
  "share.nativeText": "Ți-am făcut un brad de Crăciun — atinge un cadou.",
  "reveal.aria": "Cadou deschis",
  "reveal.close": "Închide",
  "nav.makeOwn": "Creează-ți propriul brad de Crăciun",
  "nav.advent": "Advent",
  "nav.openAdvent": "Deschide calendarul de Advent",
  "nav.build": "Creează-ți bradul de Crăciun",
  "loading": "Se încarcă…",
  "error.load": "Nu am putut încărca bradul",
  "error.create": "Crearea a eșuat",
  "error.save": "Salvarea a eșuat",
  "error.addGift": "Adăugarea cadoului a eșuat",
  "error.reorder": "Reordonarea a eșuat",
  "error.share": "Actualizarea partajării a eșuat",
  "error.open": "Nu am putut deschide cadoul",
  "defaults.title": "Bradul meu de Crăciun",
  "defaults.message": "Ți-am făcut un brad de Crăciun — atinge un cadou.",
};

const DE: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Dein Weihnachtsbaum",
  "title.shared": "Ein Weihnachtsbaum",
  "title.fallback": "Ein Weihnachtsbaum wartet auf dich",
  "lede.create": "Ich habe dir einen Weihnachtsbaum gemacht — tippe auf ein Geschenk.",
  "lede.shared": "Tippe auf ein Geschenk, um es zu öffnen",
  "lede.from": "Von {name}",
  "lede.shareMeta": "Jemand hat dir einen Weihnachtsbaum gemacht — tippe auf ein Geschenk.",
  "unavailable.title": "Dieser Baum ist privat",
  "unavailable.body": "Bitte den Absender um einen neuen Share-Link oder erstelle deinen eigenen.",
  "unavailable.metaTitle": "Weihnachtsbaum nicht verfügbar",
  "unavailable.metaDesc": "Dieser Weihnachtsbaum ist privat oder nicht mehr verfügbar.",
  "unavailable.cta": "Weihnachtsbaum erstellen",
  "gifts.heading": "Geschenke unter dem Baum",
  "gifts.empty": "Noch keine Geschenke",
  "gifts.openAria": "Geschenk öffnen {name}",
  "gifts.fallbackName": "Geschenk {n}",
  "gifts.moveEarlier": "Geschenk nach vorne",
  "gifts.moveLater": "Geschenk nach hinten",
  "gifts.up": "Hoch",
  "gifts.down": "Runter",
  "gifts.count": "{count} Geschenke",
  "gifts.countOne": "1 Geschenk",
  "editor.aria": "Baum-Editor",
  "editor.style": "Baumstil",
  "editor.lights": "Lichter",
  "editor.snow": "Schnee",
  "editor.topper": "Spitze",
  "editor.ornaments": "Schmuck",
  "editor.title": "Titel",
  "editor.greeting": "Gruß",
  "editor.from": "Von",
  "editor.saveCreate": "Meinen Weihnachtsbaum speichern",
  "editor.saving": "Speichern…",
  "editor.saveChanges": "Änderungen speichern",
  "topper.star": "Stern",
  "topper.angel": "Engel",
  "topper.bow": "Schleife",
  "topper.none": "Keine",
  "ornaments.classic": "Klassisch",
  "ornaments.gold": "Gold",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Bunt",
  "treeStyle.classic": "Klassisch",
  "treeStyle.snowy": "Verschneit",
  "treeStyle.gold": "Gold",
  "treeStyle.cozy": "Gemütlich",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Magisch",
  "gift.add": "Geschenk hinzufügen",
  "gift.for": "Für",
  "gift.message": "Nachricht",
  "gift.box": "Schachtel",
  "gift.addCta": "Geschenk hinzufügen",
  "gift.defaultName": "Geschenk",
  "gift.crossPortrait": "Weihnachtsporträt hinzufügen",
  "gift.crossSanta": "Weihnachtsmann-Video erstellen",
  "gift.wantMore": "Mehr gewünscht?",
  "box.red": "Rot",
  "box.gold": "Gold",
  "box.green": "Grün",
  "box.blue": "Blau",
  "box.snow": "Schnee",
  "share.heading": "Weihnachtsbaum senden",
  "share.privacy": "Standardmäßig privat. Teilen aktiviert einen sicheren Link — ohne Bearbeitungsrechte.",
  "share.enable": "Teilen aktivieren",
  "share.link": "Link teilen",
  "share.off": "Teilen ausschalten",
  "share.copied": "Link kopiert",
  "share.nativeTitle": "Weihnachtsbaum senden",
  "share.nativeText": "Ich habe dir einen Weihnachtsbaum gemacht — tippe auf ein Geschenk.",
  "reveal.aria": "Geschenk geöffnet",
  "reveal.close": "Schließen",
  "nav.makeOwn": "Eigenen Weihnachtsbaum erstellen",
  "nav.advent": "Advent",
  "nav.openAdvent": "Adventskalender öffnen",
  "nav.build": "Weihnachtsbaum erstellen",
  "loading": "Laden…",
  "error.load": "Baum konnte nicht geladen werden",
  "error.create": "Erstellen fehlgeschlagen",
  "error.save": "Speichern fehlgeschlagen",
  "error.addGift": "Geschenk hinzufügen fehlgeschlagen",
  "error.reorder": "Neu ordnen fehlgeschlagen",
  "error.share": "Teilen-Update fehlgeschlagen",
  "error.open": "Geschenk konnte nicht geöffnet werden",
  "defaults.title": "Mein Weihnachtsbaum",
  "defaults.message": "Ich habe dir einen Weihnachtsbaum gemacht — tippe auf ein Geschenk.",
};

const FR: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Votre sapin de Noël",
  "title.shared": "Un sapin de Noël",
  "title.fallback": "Un sapin de Noël vous attend",
  "lede.create": "Je t’ai fait un sapin de Noël — touche un cadeau.",
  "lede.shared": "Touchez un cadeau pour l’ouvrir",
  "lede.from": "De {name}",
  "lede.shareMeta": "Quelqu’un vous a fait un sapin de Noël — touchez un cadeau.",
  "unavailable.title": "Ce sapin est privé",
  "unavailable.body": "Demandez un nouveau lien au destinataire, ou créez le vôtre.",
  "unavailable.metaTitle": "Sapin de Noël indisponible",
  "unavailable.metaDesc": "Ce sapin de Noël est privé ou n’est plus disponible.",
  "unavailable.cta": "Créer votre sapin de Noël",
  "gifts.heading": "Cadeaux sous le sapin",
  "gifts.empty": "Pas encore de cadeaux",
  "gifts.openAria": "Ouvrir le cadeau {name}",
  "gifts.fallbackName": "Cadeau {n}",
  "gifts.moveEarlier": "Déplacer le cadeau plus haut",
  "gifts.moveLater": "Déplacer le cadeau plus bas",
  "gifts.up": "Haut",
  "gifts.down": "Bas",
  "gifts.count": "{count} cadeaux",
  "gifts.countOne": "1 cadeau",
  "editor.aria": "Éditeur de sapin",
  "editor.style": "Style du sapin",
  "editor.lights": "Lumières",
  "editor.snow": "Neige",
  "editor.topper": "Cimier",
  "editor.ornaments": "Ornements",
  "editor.title": "Titre",
  "editor.greeting": "Message",
  "editor.from": "De",
  "editor.saveCreate": "Enregistrer mon sapin de Noël",
  "editor.saving": "Enregistrement…",
  "editor.saveChanges": "Enregistrer les modifications",
  "topper.star": "Étoile",
  "topper.angel": "Ange",
  "topper.bow": "Nœud",
  "topper.none": "Aucun",
  "ornaments.classic": "Classique",
  "ornaments.gold": "Or",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Coloré",
  "treeStyle.classic": "Classique",
  "treeStyle.snowy": "Enneigé",
  "treeStyle.gold": "Or",
  "treeStyle.cozy": "Cosy",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Magique",
  "gift.add": "Ajouter un cadeau",
  "gift.for": "Pour",
  "gift.message": "Message",
  "gift.box": "Boîte",
  "gift.addCta": "Ajouter le cadeau",
  "gift.defaultName": "Cadeau",
  "gift.crossPortrait": "Ajouter un portrait de Noël",
  "gift.crossSanta": "Créer une vidéo du Père Noël",
  "gift.wantMore": "Envie de plus ?",
  "box.red": "Rouge",
  "box.gold": "Or",
  "box.green": "Vert",
  "box.blue": "Bleu",
  "box.snow": "Neige",
  "share.heading": "Envoyer votre sapin de Noël",
  "share.privacy": "Privé par défaut. Le partage active un lien sécurisé — sans jamais donner d’accès en édition.",
  "share.enable": "Activer le partage",
  "share.link": "Partager le lien",
  "share.off": "Désactiver le partage",
  "share.copied": "Lien copié",
  "share.nativeTitle": "Envoyer votre sapin de Noël",
  "share.nativeText": "Je t’ai fait un sapin de Noël — touche un cadeau.",
  "reveal.aria": "Cadeau ouvert",
  "reveal.close": "Fermer",
  "nav.makeOwn": "Créer votre propre sapin de Noël",
  "nav.advent": "Avent",
  "nav.openAdvent": "Ouvrir le calendrier de l’Avent",
  "nav.build": "Créer votre sapin de Noël",
  "loading": "Chargement…",
  "error.load": "Impossible de charger le sapin",
  "error.create": "Création échouée",
  "error.save": "Enregistrement échoué",
  "error.addGift": "Ajout du cadeau échoué",
  "error.reorder": "Réorganisation échouée",
  "error.share": "Mise à jour du partage échouée",
  "error.open": "Impossible d’ouvrir le cadeau",
  "defaults.title": "Mon sapin de Noël",
  "defaults.message": "Je t’ai fait un sapin de Noël — touche un cadeau.",
};

const ES: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Tu árbol de Navidad",
  "title.shared": "Un árbol de Navidad",
  "title.fallback": "Te espera un árbol de Navidad",
  "lede.create": "Te he hecho un árbol de Navidad — toca un regalo.",
  "lede.shared": "Toca un regalo para abrirlo",
  "lede.from": "De {name}",
  "lede.shareMeta": "Alguien te hizo un árbol de Navidad — toca un regalo.",
  "unavailable.title": "Este árbol es privado",
  "unavailable.body": "Pide al remitente un enlace nuevo o crea el tuyo.",
  "unavailable.metaTitle": "Árbol de Navidad no disponible",
  "unavailable.metaDesc": "Este árbol de Navidad es privado o ya no está disponible.",
  "unavailable.cta": "Crea tu árbol de Navidad",
  "gifts.heading": "Regalos bajo el árbol",
  "gifts.empty": "Aún no hay regalos",
  "gifts.openAria": "Abrir regalo {name}",
  "gifts.fallbackName": "Regalo {n}",
  "gifts.moveEarlier": "Mover regalo antes",
  "gifts.moveLater": "Mover regalo después",
  "gifts.up": "Arriba",
  "gifts.down": "Abajo",
  "gifts.count": "{count} regalos",
  "gifts.countOne": "1 regalo",
  "editor.aria": "Editor del árbol",
  "editor.style": "Estilo del árbol",
  "editor.lights": "Luces",
  "editor.snow": "Nieve",
  "editor.topper": "Cúspide",
  "editor.ornaments": "Adornos",
  "editor.title": "Título",
  "editor.greeting": "Mensaje",
  "editor.from": "De",
  "editor.saveCreate": "Guardar mi árbol de Navidad",
  "editor.saving": "Guardando…",
  "editor.saveChanges": "Guardar cambios",
  "topper.star": "Estrella",
  "topper.angel": "Ángel",
  "topper.bow": "Lazo",
  "topper.none": "Ninguno",
  "ornaments.classic": "Clásico",
  "ornaments.gold": "Dorado",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Colorido",
  "treeStyle.classic": "Clásico",
  "treeStyle.snowy": "Nevado",
  "treeStyle.gold": "Dorado",
  "treeStyle.cozy": "Acogedor",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Mágico",
  "gift.add": "Añadir un regalo",
  "gift.for": "Para",
  "gift.message": "Mensaje",
  "gift.box": "Caja",
  "gift.addCta": "Añadir regalo",
  "gift.defaultName": "Regalo",
  "gift.crossPortrait": "Añadir un retrato de Navidad",
  "gift.crossSanta": "Crear un vídeo de Papá Noel",
  "gift.wantMore": "¿Quieres más?",
  "box.red": "Rojo",
  "box.gold": "Dorado",
  "box.green": "Verde",
  "box.blue": "Azul",
  "box.snow": "Nieve",
  "share.heading": "Envía tu árbol de Navidad",
  "share.privacy": "Privado por defecto. Compartir activa un enlace seguro — nunca concede acceso de edición.",
  "share.enable": "Activar compartir",
  "share.link": "Compartir enlace",
  "share.off": "Desactivar compartir",
  "share.copied": "Enlace copiado",
  "share.nativeTitle": "Envía tu árbol de Navidad",
  "share.nativeText": "Te he hecho un árbol de Navidad — toca un regalo.",
  "reveal.aria": "Regalo abierto",
  "reveal.close": "Cerrar",
  "nav.makeOwn": "Crea tu propio árbol de Navidad",
  "nav.advent": "Adviento",
  "nav.openAdvent": "Abrir calendario de Adviento",
  "nav.build": "Crea tu árbol de Navidad",
  "loading": "Cargando…",
  "error.load": "No se pudo cargar el árbol",
  "error.create": "Error al crear",
  "error.save": "Error al guardar",
  "error.addGift": "Error al añadir el regalo",
  "error.reorder": "Error al reordenar",
  "error.share": "Error al actualizar el compartir",
  "error.open": "No se pudo abrir el regalo",
  "defaults.title": "Mi árbol de Navidad",
  "defaults.message": "Te he hecho un árbol de Navidad — toca un regalo.",
};

const IT: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Il tuo albero di Natale",
  "title.shared": "Un albero di Natale",
  "title.fallback": "Ti aspetta un albero di Natale",
  "lede.create": "Ti ho fatto un albero di Natale — tocca un regalo.",
  "lede.shared": "Tocca un regalo per aprirlo",
  "lede.from": "Da {name}",
  "lede.shareMeta": "Qualcuno ti ha fatto un albero di Natale — tocca un regalo.",
  "unavailable.title": "Questo albero è privato",
  "unavailable.body": "Chiedi al mittente un nuovo link, oppure crea il tuo.",
  "unavailable.metaTitle": "Albero di Natale non disponibile",
  "unavailable.metaDesc": "Questo albero di Natale è privato o non è più disponibile.",
  "unavailable.cta": "Crea il tuo albero di Natale",
  "gifts.heading": "Regali sotto l’albero",
  "gifts.empty": "Ancora nessun regalo",
  "gifts.openAria": "Apri regalo {name}",
  "gifts.fallbackName": "Regalo {n}",
  "gifts.moveEarlier": "Sposta il regalo prima",
  "gifts.moveLater": "Sposta il regalo dopo",
  "gifts.up": "Su",
  "gifts.down": "Giù",
  "gifts.count": "{count} regali",
  "gifts.countOne": "1 regalo",
  "editor.aria": "Editor dell’albero",
  "editor.style": "Stile dell’albero",
  "editor.lights": "Luci",
  "editor.snow": "Neve",
  "editor.topper": "Punta",
  "editor.ornaments": "Ornamenti",
  "editor.title": "Titolo",
  "editor.greeting": "Messaggio",
  "editor.from": "Da",
  "editor.saveCreate": "Salva il mio albero di Natale",
  "editor.saving": "Salvataggio…",
  "editor.saveChanges": "Salva modifiche",
  "topper.star": "Stella",
  "topper.angel": "Angelo",
  "topper.bow": "Fiocco",
  "topper.none": "Nessuno",
  "ornaments.classic": "Classico",
  "ornaments.gold": "Oro",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Colorato",
  "treeStyle.classic": "Classico",
  "treeStyle.snowy": "Innevato",
  "treeStyle.gold": "Oro",
  "treeStyle.cozy": "Accogliente",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Magico",
  "gift.add": "Aggiungi un regalo",
  "gift.for": "Per",
  "gift.message": "Messaggio",
  "gift.box": "Scatola",
  "gift.addCta": "Aggiungi regalo",
  "gift.defaultName": "Regalo",
  "gift.crossPortrait": "Aggiungi un ritratto di Natale",
  "gift.crossSanta": "Crea un video di Babbo Natale",
  "gift.wantMore": "Vuoi di più?",
  "box.red": "Rosso",
  "box.gold": "Oro",
  "box.green": "Verde",
  "box.blue": "Blu",
  "box.snow": "Neve",
  "share.heading": "Invia il tuo albero di Natale",
  "share.privacy": "Privato di default. La condivisione attiva un link sicuro — senza mai dare accesso in modifica.",
  "share.enable": "Attiva la condivisione",
  "share.link": "Condividi link",
  "share.off": "Disattiva la condivisione",
  "share.copied": "Link copiato",
  "share.nativeTitle": "Invia il tuo albero di Natale",
  "share.nativeText": "Ti ho fatto un albero di Natale — tocca un regalo.",
  "reveal.aria": "Regalo aperto",
  "reveal.close": "Chiudi",
  "nav.makeOwn": "Crea il tuo albero di Natale",
  "nav.advent": "Avvento",
  "nav.openAdvent": "Apri il calendario dell’Avvento",
  "nav.build": "Crea il tuo albero di Natale",
  "loading": "Caricamento…",
  "error.load": "Impossibile caricare l’albero",
  "error.create": "Creazione non riuscita",
  "error.save": "Salvataggio non riuscito",
  "error.addGift": "Aggiunta del regalo non riuscita",
  "error.reorder": "Riordino non riuscito",
  "error.share": "Aggiornamento condivisione non riuscito",
  "error.open": "Impossibile aprire il regalo",
  "defaults.title": "Il mio albero di Natale",
  "defaults.message": "Ti ho fatto un albero di Natale — tocca un regalo.",
};

const PT: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "A sua árvore de Natal",
  "title.shared": "Uma árvore de Natal",
  "title.fallback": "Uma árvore de Natal está à sua espera",
  "lede.create": "Fiz-te uma árvore de Natal — toca num presente.",
  "lede.shared": "Toque num presente para o abrir",
  "lede.from": "De {name}",
  "lede.shareMeta": "Alguém fez-lhe uma árvore de Natal — toque num presente.",
  "unavailable.title": "Esta árvore é privada",
  "unavailable.body": "Peça ao remetente um novo link ou crie a sua própria.",
  "unavailable.metaTitle": "Árvore de Natal indisponível",
  "unavailable.metaDesc": "Esta árvore de Natal é privada ou já não está disponível.",
  "unavailable.cta": "Crie a sua árvore de Natal",
  "gifts.heading": "Presentes debaixo da árvore",
  "gifts.empty": "Ainda sem presentes",
  "gifts.openAria": "Abrir presente {name}",
  "gifts.fallbackName": "Presente {n}",
  "gifts.moveEarlier": "Mover presente para cima",
  "gifts.moveLater": "Mover presente para baixo",
  "gifts.up": "Cima",
  "gifts.down": "Baixo",
  "gifts.count": "{count} presentes",
  "gifts.countOne": "1 presente",
  "editor.aria": "Editor da árvore",
  "editor.style": "Estilo da árvore",
  "editor.lights": "Luzes",
  "editor.snow": "Neve",
  "editor.topper": "Topo",
  "editor.ornaments": "Enfeites",
  "editor.title": "Título",
  "editor.greeting": "Mensagem",
  "editor.from": "De",
  "editor.saveCreate": "Guardar a minha árvore de Natal",
  "editor.saving": "A guardar…",
  "editor.saveChanges": "Guardar alterações",
  "topper.star": "Estrela",
  "topper.angel": "Anjo",
  "topper.bow": "Laço",
  "topper.none": "Nenhum",
  "ornaments.classic": "Clássico",
  "ornaments.gold": "Ouro",
  "ornaments.minimal": "Minimal",
  "ornaments.colorful": "Colorido",
  "treeStyle.classic": "Clássico",
  "treeStyle.snowy": "Nevado",
  "treeStyle.gold": "Ouro",
  "treeStyle.cozy": "Acolhedor",
  "treeStyle.minimal": "Minimal",
  "treeStyle.magical": "Mágico",
  "gift.add": "Adicionar um presente",
  "gift.for": "Para",
  "gift.message": "Mensagem",
  "gift.box": "Caixa",
  "gift.addCta": "Adicionar presente",
  "gift.defaultName": "Presente",
  "gift.crossPortrait": "Adicionar um retrato de Natal",
  "gift.crossSanta": "Criar um vídeo do Pai Natal",
  "gift.wantMore": "Quer mais?",
  "box.red": "Vermelho",
  "box.gold": "Ouro",
  "box.green": "Verde",
  "box.blue": "Azul",
  "box.snow": "Neve",
  "share.heading": "Enviar a sua árvore de Natal",
  "share.privacy": "Privada por predefinição. Partilhar ativa um link seguro — nunca concede acesso de edição.",
  "share.enable": "Ativar partilha",
  "share.link": "Partilhar link",
  "share.off": "Desativar partilha",
  "share.copied": "Link copiado",
  "share.nativeTitle": "Enviar a sua árvore de Natal",
  "share.nativeText": "Fiz-te uma árvore de Natal — toca num presente.",
  "reveal.aria": "Presente aberto",
  "reveal.close": "Fechar",
  "nav.makeOwn": "Crie a sua própria árvore de Natal",
  "nav.advent": "Advento",
  "nav.openAdvent": "Abrir calendário de Advento",
  "nav.build": "Crie a sua árvore de Natal",
  "loading": "A carregar…",
  "error.load": "Não foi possível carregar a árvore",
  "error.create": "Falha ao criar",
  "error.save": "Falha ao guardar",
  "error.addGift": "Falha ao adicionar o presente",
  "error.reorder": "Falha ao reordenar",
  "error.share": "Falha ao atualizar a partilha",
  "error.open": "Não foi possível abrir o presente",
  "defaults.title": "A minha árvore de Natal",
  "defaults.message": "Fiz-te uma árvore de Natal — toca num presente.",
};

const NL: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Jouw kerstboom",
  "title.shared": "Een kerstboom",
  "title.fallback": "Er wacht een kerstboom op je",
  "lede.create": "Ik heb een kerstboom voor je gemaakt — tik op een cadeau.",
  "lede.shared": "Tik op een cadeau om het te openen",
  "lede.from": "Van {name}",
  "lede.shareMeta": "Iemand heeft een kerstboom voor je gemaakt — tik op een cadeau.",
  "unavailable.title": "Deze boom is privé",
  "unavailable.body": "Vraag de afzender om een nieuwe deellink, of maak je eigen boom.",
  "unavailable.metaTitle": "Kerstboom niet beschikbaar",
  "unavailable.metaDesc": "Deze kerstboom is privé of niet meer beschikbaar.",
  "unavailable.cta": "Maak je kerstboom",
  "gifts.heading": "Cadeaus onder de boom",
  "gifts.empty": "Nog geen cadeaus",
  "gifts.openAria": "Open cadeau {name}",
  "gifts.fallbackName": "Cadeau {n}",
  "gifts.moveEarlier": "Cadeau naar voren",
  "gifts.moveLater": "Cadeau naar achteren",
  "gifts.up": "Omhoog",
  "gifts.down": "Omlaag",
  "gifts.count": "{count} cadeaus",
  "gifts.countOne": "1 cadeau",
  "editor.aria": "Boomeditor",
  "editor.style": "Boomstijl",
  "editor.lights": "Lichtjes",
  "editor.snow": "Sneeuw",
  "editor.topper": "Piek",
  "editor.ornaments": "Versiering",
  "editor.title": "Titel",
  "editor.greeting": "Bericht",
  "editor.from": "Van",
  "editor.saveCreate": "Mijn kerstboom opslaan",
  "editor.saving": "Opslaan…",
  "editor.saveChanges": "Wijzigingen opslaan",
  "topper.star": "Ster",
  "topper.angel": "Engel",
  "topper.bow": "Strik",
  "topper.none": "Geen",
  "ornaments.classic": "Klassiek",
  "ornaments.gold": "Goud",
  "ornaments.minimal": "Minimaal",
  "ornaments.colorful": "Kleurrijk",
  "treeStyle.classic": "Klassiek",
  "treeStyle.snowy": "Besneeuwd",
  "treeStyle.gold": "Goud",
  "treeStyle.cozy": "Gezellig",
  "treeStyle.minimal": "Minimaal",
  "treeStyle.magical": "Magisch",
  "gift.add": "Cadeau toevoegen",
  "gift.for": "Voor",
  "gift.message": "Bericht",
  "gift.box": "Doos",
  "gift.addCta": "Cadeau toevoegen",
  "gift.defaultName": "Cadeau",
  "gift.crossPortrait": "Kerstportret toevoegen",
  "gift.crossSanta": "Kerstmanvideo maken",
  "gift.wantMore": "Meer gewenst?",
  "box.red": "Rood",
  "box.gold": "Goud",
  "box.green": "Groen",
  "box.blue": "Blauw",
  "box.snow": "Sneeuw",
  "share.heading": "Stuur je kerstboom",
  "share.privacy": "Standaard privé. Delen zet een veilige link aan — zonder bewerkingsrechten.",
  "share.enable": "Delen inschakelen",
  "share.link": "Link delen",
  "share.off": "Delen uitzetten",
  "share.copied": "Link gekopieerd",
  "share.nativeTitle": "Stuur je kerstboom",
  "share.nativeText": "Ik heb een kerstboom voor je gemaakt — tik op een cadeau.",
  "reveal.aria": "Cadeau geopend",
  "reveal.close": "Sluiten",
  "nav.makeOwn": "Maak je eigen kerstboom",
  "nav.advent": "Advent",
  "nav.openAdvent": "Open adventskalender",
  "nav.build": "Maak je kerstboom",
  "loading": "Laden…",
  "error.load": "Boom kon niet worden geladen",
  "error.create": "Aanmaken mislukt",
  "error.save": "Opslaan mislukt",
  "error.addGift": "Cadeau toevoegen mislukt",
  "error.reorder": "Herordenen mislukt",
  "error.share": "Deel-update mislukt",
  "error.open": "Cadeau kon niet worden geopend",
  "defaults.title": "Mijn kerstboom",
  "defaults.message": "Ik heb een kerstboom voor je gemaakt — tik op een cadeau.",
};

const PL: Dict = {
  "brand": "The Digital Gifter",
  "title.create": "Twoja choinka",
  "title.shared": "Choinka",
  "title.fallback": "Czeka na Ciebie choinka",
  "lede.create": "Zrobiłem Ci choinkę — stuknij w prezent.",
  "lede.shared": "Stuknij w prezent, aby go otworzyć",
  "lede.from": "Od {name}",
  "lede.shareMeta": "Ktoś zrobił Ci choinkę — stuknij w prezent.",
  "unavailable.title": "Ta choinka jest prywatna",
  "unavailable.body": "Poproś nadawcę o nowy link albo stwórz własną.",
  "unavailable.metaTitle": "Choinka niedostępna",
  "unavailable.metaDesc": "Ta choinka jest prywatna lub już niedostępna.",
  "unavailable.cta": "Stwórz swoją choinkę",
  "gifts.heading": "Prezenty pod choinką",
  "gifts.empty": "Brak prezentów",
  "gifts.openAria": "Otwórz prezent {name}",
  "gifts.fallbackName": "Prezent {n}",
  "gifts.moveEarlier": "Przesuń prezent wyżej",
  "gifts.moveLater": "Przesuń prezent niżej",
  "gifts.up": "W górę",
  "gifts.down": "W dół",
  "gifts.count": "{count} prezentów",
  "gifts.countOne": "1 prezent",
  "editor.aria": "Edytor choinki",
  "editor.style": "Styl choinki",
  "editor.lights": "Światełka",
  "editor.snow": "Śnieg",
  "editor.topper": "Czubek",
  "editor.ornaments": "Ozdoby",
  "editor.title": "Tytuł",
  "editor.greeting": "Wiadomość",
  "editor.from": "Od",
  "editor.saveCreate": "Zapisz moją choinkę",
  "editor.saving": "Zapisywanie…",
  "editor.saveChanges": "Zapisz zmiany",
  "topper.star": "Gwiazda",
  "topper.angel": "Anioł",
  "topper.bow": "Kokarda",
  "topper.none": "Brak",
  "ornaments.classic": "Klasyczne",
  "ornaments.gold": "Złote",
  "ornaments.minimal": "Minimalne",
  "ornaments.colorful": "Kolorowe",
  "treeStyle.classic": "Klasyczna",
  "treeStyle.snowy": "Ośnieżona",
  "treeStyle.gold": "Złota",
  "treeStyle.cozy": "Przytulna",
  "treeStyle.minimal": "Minimalna",
  "treeStyle.magical": "Magiczna",
  "gift.add": "Dodaj prezent",
  "gift.for": "Dla",
  "gift.message": "Wiadomość",
  "gift.box": "Pudełko",
  "gift.addCta": "Dodaj prezent",
  "gift.defaultName": "Prezent",
  "gift.crossPortrait": "Dodaj świąteczny portret",
  "gift.crossSanta": "Stwórz wideo ze Świętym Mikołajem",
  "gift.wantMore": "Chcesz więcej?",
  "box.red": "Czerwone",
  "box.gold": "Złote",
  "box.green": "Zielone",
  "box.blue": "Niebieskie",
  "box.snow": "Śnieżne",
  "share.heading": "Wyślij swoją choinkę",
  "share.privacy": "Domyślnie prywatna. Udostępnianie włącza bezpieczny link — nigdy nie daje prawa do edycji.",
  "share.enable": "Włącz udostępnianie",
  "share.link": "Udostępnij link",
  "share.off": "Wyłącz udostępnianie",
  "share.copied": "Link skopiowany",
  "share.nativeTitle": "Wyślij swoją choinkę",
  "share.nativeText": "Zrobiłem Ci choinkę — stuknij w prezent.",
  "reveal.aria": "Prezent otwarty",
  "reveal.close": "Zamknij",
  "nav.makeOwn": "Stwórz własną choinkę",
  "nav.advent": "Adwent",
  "nav.openAdvent": "Otwórz kalendarz adwentowy",
  "nav.build": "Stwórz swoją choinkę",
  "loading": "Ładowanie…",
  "error.load": "Nie udało się wczytać choinki",
  "error.create": "Tworzenie nie powiodło się",
  "error.save": "Zapisywanie nie powiodło się",
  "error.addGift": "Dodawanie prezentu nie powiodło się",
  "error.reorder": "Zmiana kolejności nie powiodła się",
  "error.share": "Aktualizacja udostępniania nie powiodła się",
  "error.open": "Nie udało się otworzyć prezentu",
  "defaults.title": "Moja choinka",
  "defaults.message": "Zrobiłem Ci choinkę — stuknij w prezent.",
};

export const TABLES: Record<TreeLocale, Dict> = {
  en: EN,
  ro: RO,
  de: DE,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  pl: PL,
};

/** Product UI keys that must be localized for Wave 1 (P3D coverage). */
export const REQUIRED_UI_KEYS = [
  "title.create",
  "lede.create",
  "gift.addCta",
  "share.link",
  "share.enable",
  "editor.saveCreate",
  "unavailable.cta",
  "nav.makeOwn",
  "error.load",
] as const;

const _enKeySet = Object.keys(TABLES.en).sort().join("\0");
for (const loc of TREE_UI_LOCALES) {
  const pack = TABLES[loc];
  const keys = Object.keys(pack);
  if (keys.length !== Object.keys(TABLES.en).length || keys.sort().join("\0") !== _enKeySet) {
    throw new Error(`Christmas tree UI pack key mismatch for locale: ${loc}`);
  }
}

export function treeT(
  key: string,
  locale: TreeLocale = "en",
  vars?: Record<string, string>,
): string {
  let text = TABLES[locale]?.[key] || TABLES.en[key] || key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replaceAll(`{${k}}`, v);
    }
  }
  return text;
}
