/**
 * Localization-ready copy for the /christmas flagship landing.
 * Wave 1 packs: en, ro, de, fr, es, it, pt (pt-PT), nl, pl.
 * Longer translated strings should wrap via CSS, not truncation.
 *
 * Santa: en/ro keep spoken-product CTAs. Other Wave 1 locales use soft
 * "Meet Santa" wording — hub may still link to a usable noindex shell,
 * but copy must not claim verified native spoken Santa support.
 */

export const CHRISTMAS_LANDING_LOCALES = [
  "en",
  "ro",
  "de",
  "fr",
  "es",
  "it",
  "pt",
  "nl",
  "pl",
] as const;
export type ChristmasLandingLocale = (typeof CHRISTMAS_LANDING_LOCALES)[number];

export const CHRISTMAS_LANDING_DEFAULT_LOCALE: ChristmasLandingLocale = "en";

/** Locales with verified spoken Santa video product support. */
export const CHRISTMAS_LANDING_SPOKEN_SANTA_LOCALES: readonly ChristmasLandingLocale[] = [
  "en",
  "ro",
] as const;

export function landingHasSpokenSanta(locale: ChristmasLandingLocale): boolean {
  return (CHRISTMAS_LANDING_SPOKEN_SANTA_LOCALES as readonly string[]).includes(locale);
}

/** Future RTL locales (ar, he, …) should flip this map — do not hardcode dir in scenes. */
export const LANDING_LOCALE_DIR: Record<string, "ltr" | "rtl"> = {
  en: "ltr",
  ro: "ltr",
  de: "ltr",
  fr: "ltr",
  es: "ltr",
  it: "ltr",
  pt: "ltr",
  nl: "ltr",
  pl: "ltr",
  ar: "rtl",
  he: "rtl",
  fa: "rtl",
  ur: "rtl",
};

type CopyBag = Record<string, string>;


const EN: CopyBag = {
  "seo.title": "Christmas Gifts, Portraits & Santa Messages | TheDigitalGifter",
  "seo.description": "Create an unforgettable Christmas: find the perfect gift, turn a photo into a Christmas portrait, send a Santa video that says their name, share a wishlist, decorate a tree, open Advent, and write a card that feels personal.",
  "hero.eyebrow": "Christmas at The Digital Gifter",
  "hero.h1": "Create something they’ll remember.",
  "hero.lede": "Step into a living Christmas world — gifts under the tree, portraits by the fire, and a message from Santa made just for them.",
  "hero.cta": "Start creating",
  "hero.secondary": "Explore this Christmas",
  "hero.alt": "A luxury mountain cabin at Christmas with floor-to-ceiling windows, a stone fireplace, and a glowing tree",
  "hero.countdown.eyebrow": "Christmas is coming",
  "hero.countdown.days": "Days",
  "hero.countdown.hours": "Hours",
  "hero.countdown.minutes": "Minutes",
  "hero.countdown.seconds": "Seconds",
  "hero.countdown.until": "until Christmas",
  "hero.countdown.arrived": "Merry Christmas — the magic is here.",
  "transition.kicker": "Christmas is more than one gift.",
  "transition.h2": "Turn this season into something magical.",
  "transition.lede": "Keep scrolling. The same room opens into every Christmas moment you might need.",
  "gifts.kicker": "Christmas gifts",
  "gifts.h2": "Open a gift under the tree.",
  "gifts.lede": "Tap a glowing present. Reveal a free Christmas surprise — portraits, cards, credits, and more.",
  "gifts.cta": "Find the Perfect Gift",
  "gifts.mom": "Mom",
  "gifts.dad": "Dad",
  "gifts.partner": "Partner",
  "gifts.friend": "Friend",
  "gifts.kids": "Kids",
  "gifts.hint": "Choose a person. The gifts will answer.",
  "gifts.react.mom": "Something thoughtful, warm, and a little luxurious — just for her.",
  "gifts.react.dad": "Useful, surprising, and chosen with care — he’ll notice.",
  "gifts.react.partner": "A gift that feels like a memory, not a receipt.",
  "gifts.react.friend": "The kind of present that makes a friend feel seen.",
  "gifts.react.kids": "Wonder first. Then the smile they can’t fake.",
  "finder.kicker": "Christmas Gift Finder",
  "finder.h2": "Find the Perfect Christmas Gift",
  "finder.lede": "Not sure what to buy? Use the Christmas Gift Finder to match ideas to the person, their interests, and your budget — including thoughtful options for someone who already seems to have everything. Save favorites to a wishlist when you’re ready.",
  "finder.cta": "Find a Christmas gift they’ll actually love",
  "finder.hint": "Choose who you’re shopping for, then continue into the finder.",
  "portraits.kicker": "Christmas portraits",
  "portraits.h2": "Create Magical Christmas Photos",
  "portraits.lede": "Upload a clear photo and turn it into a festive Christmas portrait for family, couples, or pets — including dog and cat paths. Download privately, or carry a portrait into a Christmas card.",
  "portraits.cta": "Turn your photo into Christmas magic",
  "portraits.family": "Family",
  "portraits.couples": "Couples",
  "portraits.pets": "Pets",
  "portraits.alt.family": "Family transformed into a cozy fireplace Christmas portrait",
  "portraits.alt.couples": "Couple transformed into a romantic Christmas portrait",
  "portraits.alt.pets": "Pet transformed into a festive Christmas portrait",
  "portraits.alt.before": "An everyday family photo before it becomes a Christmas portrait",
  "santa.kicker": "Santa video",
  "santa.h2": "Get a Personalized Message From Santa",
  "santa.h2Personalized": "Santa has a message for {name}...",
  "santa.lede": "Create a personalized Christmas video from Santa. Include their name and optional details like age, something they did well, a hobby, or a Christmas wish — then download and share the video.",
  "santa.bubble": "Ho ho ho, I’m Santa!",
  "santa.bubblePersonalized": "{name}? I know that name...",
  "santa.label": "Your kid’s name",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Create a personalized Santa video",
  "santa.ctaPersonalized": "Create {name}'s Santa Message",
  "santa.reassurance": "It only takes a moment to create the magic.",
  "santa.alt": "Santa standing in the Christmas room, speaking a personal greeting",
  "santa.error": "Please enter a first name using letters, spaces, hyphens, or apostrophes.",
  "wishlist.kicker": "Wishlist",
  "wishlist.h2": "Create and Share a Christmas Wishlist",
  "wishlist.lede": "Add wishes from product links or free text, share one simple link with family, and let people reserve gifts so Christmas shopping stays coordinated without spoiling the surprise.",
  "wishlist.cta": "Create a Christmas wishlist",
  "wishlist.alt": "A handwritten letter to Santa slipping from a cream envelope",
  "tree.kicker": "Christmas tree",
  "tree.h2": "Build a Christmas tree filled with gifts, memories and surprises.",
  "tree.lede": "Share it with someone you love. Lights, ornaments, and little messages that appear as they open it.",
  "tree.cta": "Create Your Christmas Tree",
  "advent.kicker": "Advent",
  "advent.h2": "A little Christmas magic every day.",
  "advent.lede": "Open today’s surprise. Come back tomorrow. The season becomes a ritual, not a rush.",
  "advent.cta": "Open Today’s Door",
  "advent.alt": "An elegant wooden Advent calendar with one glowing door for today",
  "advent.today": "Today’s door",
  "cards.kicker": "Christmas cards",
  "cards.h2": "Create a Personalized Christmas Card",
  "cards.lede": "Combine a photo, a festive design, and a personal message into a Christmas card you can download or share digitally. Some messages deserve more than a text.",
  "cards.cta": "Create a Christmas card they’ll want to keep",
  "cards.elegant": "Elegant",
  "cards.family": "Family",
  "cards.romantic": "Romantic",
  "cards.funny": "Funny",
  "cards.alt": "An open Christmas card on a wooden table beside pine and candlelight",
  "messages.kicker": "Messages",
  "messages.h2": "Sometimes you know what you feel.",
  "messages.lede": "You just don’t know how to say it. We’ll help you find the words — then you make them yours.",
  "messages.cta": "Write My Christmas Message",
  "messages.for": "For",
  "messages.tone": "Tone",
  "messages.heartfelt": "Heartfelt",
  "messages.funny": "Funny",
  "messages.warm": "Warm",
  "finale.kicker": "This Christmas",
  "finale.h2": "Make this Christmas unforgettable.",
  "finale.lede": "The room is fuller now. The lights are on. Start creating — a gift, a portrait, a message, a moment.",
  "finale.cta": "Start creating",
  "finale.alt": "The same Christmas living room, warmer and more complete, with lights and gifts",
  "geo.h2": "What can you create with TheDigitalGifter for Christmas?",
  "geo.body": "TheDigitalGifter is a Christmas creation hub. You can find gift ideas with the Gift Finder, turn a photo into a Christmas portrait for family, couples, or pets, create a personalized Santa video that can include a recipient’s name, build a shareable Christmas wishlist, design a Christmas card with your photo and message, write Christmas wishes, decorate a digital Christmas tree, and open daily Advent surprises.",
  "faq.h2": "Frequently Asked Questions",
  "faq.1.q": "What can I create for Christmas with TheDigitalGifter?",
  "faq.1.a": "Gift ideas, Christmas portraits for families, couples and pets, a personalized Santa video, a shareable wishlist, Christmas cards, Christmas messages, a digital tree, and an Advent calendar.",
  "faq.2.q": "Can Santa say my child’s name?",
  "faq.2.a": "Yes. Start with their first name on the Christmas page or Santa Video experience, then add optional details before creating the video.",
  "faq.3.q": "Do I need design skills?",
  "faq.3.a": "No. Each Christmas experience is guided — upload a photo, answer a few questions, or start with a name.",
  "faq.4.q": "Is this for digital gifts, physical gifts, or both?",
  "faq.4.a": "Both. Use the Gift Finder and wishlist for shopping anywhere, and create digital portraits, cards, and Santa videos to send.",
  "faq.5.q": "Will this work on my phone?",
  "faq.5.a": "Yes. The Christmas hub and product experiences are designed to work on phones as well as desktops.",
  "nav.gifts": "Gifts under the tree",
  "nav.finder": "Gift finder",
  "nav.portraits": "Portraits",
  "nav.santa": "Santa",
  "nav.wishlist": "Wishlist",
  "nav.tree": "Tree",
  "nav.advent": "Advent",
  "nav.cards": "Cards",
  "nav.messages": "Messages",
};

const RO: CopyBag = {
  "seo.title": "Cadouri de Crăciun, Portrete & Mesaje de la Moș | TheDigitalGifter",
  "seo.description": "Creează un Crăciun de neuitat: găsește cadoul potrivit, transformă o fotografie într-un portret de Crăciun, trimite un video de la Moș care spune numele lor, partajează o listă de dorințe, decoră un brad, deschide Adventul și scrie o felicitare cu suflet.",
  "hero.eyebrow": "Crăciun la The Digital Gifter",
  "hero.h1": "Creează ceva ce vor ține minte.",
  "hero.lede": "Intră într-o lume vie de Crăciun — cadouri sub brad, portrete lângă foc și un mesaj de la Moș făcut special pentru ei.",
  "hero.cta": "Începe să creezi",
  "hero.secondary": "Explorează acest Crăciun",
  "hero.alt": "O cabană de lux la munte de Crăciun, cu ferestre mari, șemineu de piatră și un brad luminos",
  "hero.countdown.eyebrow": "Crăciunul se apropie",
  "hero.countdown.days": "Zile",
  "hero.countdown.hours": "Ore",
  "hero.countdown.minutes": "Minute",
  "hero.countdown.seconds": "Secunde",
  "hero.countdown.until": "până la Crăciun",
  "hero.countdown.arrived": "Crăciun fericit — magia e aici.",
  "transition.kicker": "Crăciunul e mai mult decât un cadou.",
  "transition.h2": "Transformă sezonul într-un moment magic.",
  "transition.lede": "Continuă să derulezi. Aceeași cameră se deschide către fiecare moment de Crăciun de care ai nevoie.",
  "gifts.kicker": "Cadouri de Crăciun",
  "gifts.h2": "Deschide un cadou sub brad.",
  "gifts.lede": "Atinge un cadou luminos. Descoperă o surpriză de Crăciun gratuită — portrete, felicitări, credite și altele.",
  "gifts.cta": "Găsește Cadoul Perfect",
  "gifts.mom": "Mama",
  "gifts.dad": "Tata",
  "gifts.partner": "Partener",
  "gifts.friend": "Prieten",
  "gifts.kids": "Copii",
  "gifts.hint": "Alege o persoană. Cadourile răspund.",
  "gifts.react.mom": "Ceva atent, cald și puțin luxos — doar pentru ea.",
  "gifts.react.dad": "Util, surprinzător și ales cu grijă — va observa.",
  "gifts.react.partner": "Un cadou care pare o amintire, nu o chitanță.",
  "gifts.react.friend": "Genul de cadou care face un prieten să se simtă văzut.",
  "gifts.react.kids": "Mai întâi uimirea. Apoi zâmbetul pe care nu-l pot ascunde.",
  "finder.kicker": "Găsitorul de Cadouri de Crăciun",
  "finder.h2": "Găsește Cadoul Perfect de Crăciun",
  "finder.lede": "Nu știi ce să cumperi? Folosește Găsitorul de Cadouri de Crăciun ca să potrivești idei cu persoana, interesele și bugetul tău — inclusiv opțiuni gândite pentru cineva care pare să aibă deja de toate. Salvează favoritele într-o listă de dorințe când ești gata.",
  "finder.cta": "Găsește un cadou de Crăciun pe care chiar îl vor iubi",
  "finder.hint": "Alege pentru cine cumperi, apoi continuă în găsitor.",
  "portraits.kicker": "Portrete de Crăciun",
  "portraits.h2": "Creează Poze Magice de Crăciun",
  "portraits.lede": "Încarcă o fotografie clară și transform-o într-un portret festiv de Crăciun pentru familie, cupluri sau animale — inclusiv căi pentru câini și pisici. Descarcă privat sau du portretul într-o felicitare de Crăciun.",
  "portraits.cta": "Transformă poza în magie de Crăciun",
  "portraits.family": "Familie",
  "portraits.couples": "Cupluri",
  "portraits.pets": "Animale",
  "portraits.alt.family": "Familie transformată într-un portret de Crăciun lângă șemineu",
  "portraits.alt.couples": "Cuplu transformat într-un portret romantic de Crăciun",
  "portraits.alt.pets": "Animal de companie transformat într-un portret festiv de Crăciun",
  "portraits.alt.before": "O poză de familie obișnuită înainte să devină portret de Crăciun",
  "santa.kicker": "Video cu Moș Crăciun",
  "santa.h2": "Primește un Mesaj Personalizat de la Moș",
  "santa.h2Personalized": "Moșul are un mesaj pentru {name}...",
  "santa.lede": "Creează un video personalizat de Crăciun de la Moș. Include numele lor și detalii opționale precum vârsta, ceva ce au făcut bine, un hobby sau o dorință de Crăciun — apoi descarcă și partajează videoul.",
  "santa.bubble": "Ho ho ho, eu sunt Moș Crăciun!",
  "santa.bubblePersonalized": "{name}? Cunosc numele ăsta...",
  "santa.label": "Prenumele copilului",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Andrei|Sofia|David",
  "santa.cta": "Creează un video personalizat cu Moșul",
  "santa.ctaPersonalized": "Creează mesajul lui {name} de la Moș",
  "santa.reassurance": "E nevoie doar de un moment ca să apară magia.",
  "santa.alt": "Moș Crăciun stând în camera de Crăciun, rostind un salut personal",
  "santa.error": "Te rugăm să introduci un prenume cu litere, spații, cratime sau apostrofuri.",
  "wishlist.kicker": "Listă de dorințe",
  "wishlist.h2": "Creează și Partajează o Listă de Dorințe de Crăciun",
  "wishlist.lede": "Adaugă dorințe din linkuri de produse sau text liber, partajează un singur link simplu cu familia și lasă-i pe ceilalți să rezerve cadourile — ca shopping-ul de Crăciun să rămână coordonat, fără să strice surpriza.",
  "wishlist.cta": "Creează o listă de dorințe de Crăciun",
  "wishlist.alt": "O scrisoare scrisă de mână către Moș, alunecând dintr-un plic crem",
  "tree.kicker": "Brad de Crăciun",
  "tree.h2": "Construiește un brad de Crăciun plin de cadouri, amintiri și surprize.",
  "tree.lede": "Partajează-l cu cineva drag. Lumini, ornamente și mesaje mici care apar pe măsură ce îl deschid.",
  "tree.cta": "Creează Bradul Tău de Crăciun",
  "advent.kicker": "Advent",
  "advent.h2": "Puțină magie de Crăciun în fiecare zi.",
  "advent.lede": "Deschide surpriza de azi. Revino mâine. Sezonul devine un ritual, nu o goană.",
  "advent.cta": "Deschide Ușa de Azi",
  "advent.alt": "Un calendar de Advent din lemn elegant, cu o ușă luminată pentru azi",
  "advent.today": "Ușa de azi",
  "cards.kicker": "Felicitări de Crăciun",
  "cards.h2": "Creează o Felicitare de Crăciun Personalizată",
  "cards.lede": "Combină o fotografie, un design festiv și un mesaj personal într-o felicitare de Crăciun pe care o poți descărca sau partaja digital. Unele mesaje merită mai mult decât un text.",
  "cards.cta": "Creează o felicitare pe care vor vrea s-o păstreze",
  "cards.elegant": "Elegant",
  "cards.family": "Familie",
  "cards.romantic": "Romantic",
  "cards.funny": "Amuzant",
  "cards.alt": "O felicitare de Crăciun deschisă pe o masă de lemn, lângă brad și lumânări",
  "messages.kicker": "Mesaje",
  "messages.h2": "Uneori știi ce simți.",
  "messages.lede": "Doar nu știi cum să spui. Te ajutăm să găsești cuvintele — apoi le faci ale tale.",
  "messages.cta": "Scrie Mesajul Meu de Crăciun",
  "messages.for": "Pentru",
  "messages.tone": "Ton",
  "messages.heartfelt": "Din suflet",
  "messages.funny": "Amuzant",
  "messages.warm": "Cald",
  "finale.kicker": "În acest Crăciun",
  "finale.h2": "Fă acest Crăciun de neuitat.",
  "finale.lede": "Camera e mai plină acum. Luminile sunt aprinse. Începe să creezi — un cadou, un portret, un mesaj, un moment.",
  "finale.cta": "Începe să creezi",
  "finale.alt": "Aceeași cameră de Crăciun, mai caldă și mai completă, cu lumini și cadouri",
  "geo.h2": "Ce poți crea cu TheDigitalGifter de Crăciun?",
  "geo.body": "TheDigitalGifter este un hub de creație de Crăciun. Poți găsi idei de cadouri cu Găsitorul de Cadouri, transforma o fotografie într-un portret de Crăciun pentru familie, cupluri sau animale, crea un video personalizat de la Moș care poate include numele destinatarului, construi o listă de dorințe de partajat, proiecta o felicitare cu poza și mesajul tău, scrie urări de Crăciun, decora un brad digital și deschide surprize zilnice de Advent.",
  "faq.h2": "Întrebări frecvente",
  "faq.1.q": "Ce pot crea de Crăciun cu TheDigitalGifter?",
  "faq.1.a": "Idei de cadouri, portrete de Crăciun pentru familii, cupluri și animale, un video personalizat de la Moș, o listă de dorințe de partajat, felicitări de Crăciun, mesaje de Crăciun, un brad digital și un calendar de Advent.",
  "faq.2.q": "Poate Moșul să spună numele copilului meu?",
  "faq.2.a": "Da. Începe cu prenumele pe pagina de Crăciun sau în experiența Video cu Moș, apoi adaugă detalii opționale înainte de a crea videoul.",
  "faq.3.q": "Am nevoie de abilități de design?",
  "faq.3.a": "Nu. Fiecare experiență de Crăciun este ghidată — încarci o poză, răspunzi la câteva întrebări sau începi cu un nume.",
  "faq.4.q": "Este pentru cadouri digitale, fizice sau ambele?",
  "faq.4.a": "Ambele. Folosește Găsitorul de Cadouri și lista de dorințe pentru cumpărături oriunde, și creează portrete, felicitări și video-uri cu Moșul de trimis digital.",
  "faq.5.q": "Funcționează pe telefon?",
  "faq.5.a": "Da. Hub-ul de Crăciun și experiențele de produs sunt create să funcționeze pe telefoane, dar și pe desktop.",
  "nav.gifts": "Cadouri sub brad",
  "nav.finder": "Găsitor de cadouri",
  "nav.portraits": "Portrete",
  "nav.santa": "Moș Crăciun",
  "nav.wishlist": "Listă de dorințe",
  "nav.tree": "Brad",
  "nav.advent": "Advent",
  "nav.cards": "Felicitări",
  "nav.messages": "Mesaje",
};

const DE: CopyBag = {
  "seo.title": "Weihnachtsgeschenke, Porträts & Santa-Momente | TheDigitalGifter",
  "seo.description": "Mach Weihnachten unvergesslich: finde das passende Geschenk, verwandle ein Foto in ein Weihnachtsporträt, entdecke Santa, teile eine Wunschliste, schmücke einen Baum, öffne den Advent und gestalte eine persönliche Karte.",
  "hero.eyebrow": "Weihnachten bei The Digital Gifter",
  "hero.h1": "Schaff etwas, das bleibt.",
  "hero.lede": "Tritt ein in eine lebendige Weihnachtswelt — Geschenke unterm Baum, Porträts am Kamin und ein besonderer Moment mit Santa.",
  "hero.cta": "Jetzt gestalten",
  "hero.secondary": "Weihnachten entdecken",
  "hero.alt": "Eine luxuriöse Berghütte zu Weihnachten mit großen Fenstern, Steinkamin und leuchtendem Baum",
  "hero.countdown.eyebrow": "Weihnachten kommt",
  "hero.countdown.days": "Tage",
  "hero.countdown.hours": "Stunden",
  "hero.countdown.minutes": "Minuten",
  "hero.countdown.seconds": "Sekunden",
  "hero.countdown.until": "bis Weihnachten",
  "hero.countdown.arrived": "Frohe Weihnachten — die Magie ist da.",
  "transition.kicker": "Weihnachten ist mehr als ein Geschenk.",
  "transition.h2": "Mach aus dieser Jahreszeit etwas Magisches.",
  "transition.lede": "Scroll weiter. Derselbe Raum öffnet sich zu jedem Weihnachtsmoment, den du brauchst.",
  "gifts.kicker": "Weihnachtsgeschenke",
  "gifts.h2": "Öffne ein Geschenk unterm Baum.",
  "gifts.lede": "Tippe auf ein leuchtendes Geschenk. Entdecke eine kostenlose Weihnachtsüberraschung — Porträts, Karten, Credits und mehr.",
  "gifts.cta": "Das perfekte Geschenk finden",
  "gifts.mom": "Mama",
  "gifts.dad": "Papa",
  "gifts.partner": "Partner",
  "gifts.friend": "Freund",
  "gifts.kids": "Kinder",
  "gifts.hint": "Wähle eine Person. Die Geschenke antworten.",
  "gifts.react.mom": "Etwas Durchdachtes, Warmes und ein wenig Luxuriöses — nur für sie.",
  "gifts.react.dad": "Nützlich, überraschend und mit Bedacht gewählt — er wird es merken.",
  "gifts.react.partner": "Ein Geschenk, das sich wie eine Erinnerung anfühlt, nicht wie ein Beleg.",
  "gifts.react.friend": "Das Geschenk, das einem Freund das Gefühl gibt, gesehen zu werden.",
  "gifts.react.kids": "Zuerst das Staunen. Dann das Lächeln, das sie nicht verstecken können.",
  "finder.kicker": "Weihnachts-Geschenke-Finder",
  "finder.h2": "Finde das perfekte Weihnachtsgeschenk",
  "finder.lede": "Unsicher, was du kaufen sollst? Der Weihnachts-Geschenke-Finder pass Ideen zur Person, ihren Interessen und deinem Budget — auch für jemanden, der schon alles zu haben scheint. Speichere Favoriten auf einer Wunschliste, wenn du soweit bist.",
  "finder.cta": "Finde ein Weihnachtsgeschenk, das sie wirklich lieben",
  "finder.hint": "Wähle, für wen du einkaufst, und gehe weiter zum Finder.",
  "portraits.kicker": "Weihnachtsporträts",
  "portraits.h2": "Magische Weihnachtsfotos erstellen",
  "portraits.lede": "Lade ein klares Foto hoch und verwandle es in ein festliches Weihnachtsporträt für Familie, Paare oder Haustiere — inklusive Hund- und Katzen-Pfaden. Privat herunterladen oder das Porträt in eine Weihnachtskarte übernehmen.",
  "portraits.cta": "Verwandle dein Foto in Weihnachtsmagie",
  "portraits.family": "Familie",
  "portraits.couples": "Paare",
  "portraits.pets": "Haustiere",
  "portraits.alt.family": "Familie als gemütliches Kamin-Weihnachtsporträt",
  "portraits.alt.couples": "Paar als romantisches Weihnachtsporträt",
  "portraits.alt.pets": "Haustier als festliches Weihnachtsporträt",
  "portraits.alt.before": "Ein alltägliches Familienfoto, bevor es zum Weihnachtsporträt wird",
  "santa.kicker": "Santa",
  "santa.h2": "Triff Santa",
  "santa.h2Personalized": "Santa freut sich auf {name}...",
  "santa.lede": "Entdecke das Santa-Erlebnis. Starte mit dem Vornamen und erkunde einen weihnachtlichen Moment — ohne Versprechen zu einer gesprochenen Sprache.",
  "santa.bubble": "Ho ho ho, ich bin Santa!",
  "santa.bubblePersonalized": "{name}? Den Namen kenne ich...",
  "santa.label": "Vorname deines Kindes",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Santa treffen",
  "santa.ctaPersonalized": "Weiter mit {name}",
  "santa.reassurance": "Nur einen Moment — und die Weihnachtsstimmung beginnt.",
  "santa.alt": "Santa steht im Weihnachtszimmer und begrüßt dich",
  "santa.error": "Bitte gib einen Vornamen mit Buchstaben, Leerzeichen, Bindestrichen oder Apostrophen ein.",
  "wishlist.kicker": "Wunschliste",
  "wishlist.h2": "Erstelle und teile eine Weihnachts-Wunschliste",
  "wishlist.lede": "Füge Wünsche aus Produktlinks oder Freitext hinzu, teile einen einfachen Link mit der Familie und lass Geschenke reservieren — damit das Einkaufen koordiniert bleibt, ohne die Überraschung zu spoilern.",
  "wishlist.cta": "Weihnachts-Wunschliste erstellen",
  "wishlist.alt": "Ein handgeschriebener Brief an Santa, der aus einem cremefarbenen Umschlag gleitet",
  "tree.kicker": "Weihnachtsbaum",
  "tree.h2": "Baue einen Weihnachtsbaum voller Geschenke, Erinnerungen und Überraschungen.",
  "tree.lede": "Teile ihn mit jemandem, den du liebst. Lichter, Ornamente und kleine Nachrichten, die erscheinen, wenn er geöffnet wird.",
  "tree.cta": "Deinen Weihnachtsbaum erstellen",
  "advent.kicker": "Advent",
  "advent.h2": "Jeden Tag ein bisschen Weihnachtsmagie.",
  "advent.lede": "Öffne die Überraschung von heute. Komm morgen wieder. Die Saison wird zum Ritual, nicht zum Stress.",
  "advent.cta": "Heutige Tür öffnen",
  "advent.alt": "Ein eleganter Adventskalender aus Holz mit einer leuchtenden Tür für heute",
  "advent.today": "Heutige Tür",
  "cards.kicker": "Weihnachtskarten",
  "cards.h2": "Erstelle eine persönliche Weihnachtskarte",
  "cards.lede": "Kombiniere ein Foto, ein festliches Design und eine persönliche Nachricht zu einer Weihnachtskarte zum Download oder digitalen Teilen. Manche Botschaften verdienen mehr als eine SMS.",
  "cards.cta": "Erstelle eine Weihnachtskarte zum Aufheben",
  "cards.elegant": "Elegant",
  "cards.family": "Familie",
  "cards.romantic": "Romantisch",
  "cards.funny": "Lustig",
  "cards.alt": "Eine offene Weihnachtskarte auf einem Holztisch neben Tanne und Kerzenlicht",
  "messages.kicker": "Nachrichten",
  "messages.h2": "Manchmal weißt du, was du fühlst.",
  "messages.lede": "Du weißt nur nicht, wie du es sagen sollst. Wir helfen dir bei den Worten — dann machst du sie zu deinen.",
  "messages.cta": "Meine Weihnachtsnachricht schreiben",
  "messages.for": "Für",
  "messages.tone": "Ton",
  "messages.heartfelt": "Herzlich",
  "messages.funny": "Lustig",
  "messages.warm": "Warm",
  "finale.kicker": "Dieses Weihnachten",
  "finale.h2": "Mach dieses Weihnachten unvergesslich.",
  "finale.lede": "Der Raum ist voller. Die Lichter brennen. Fang an zu gestalten — ein Geschenk, ein Porträt, eine Nachricht, ein Moment.",
  "finale.cta": "Jetzt gestalten",
  "finale.alt": "Dasselbe Weihnachtswohnzimmer, wärmer und vollständiger, mit Lichtern und Geschenken",
  "geo.h2": "Was kannst du mit TheDigitalGifter zu Weihnachten erstellen?",
  "geo.body": "TheDigitalGifter ist ein Weihnachts-Gestaltungs-Hub. Du findest Geschenkideen mit dem Geschenke-Finder, verwandelst ein Foto in ein Weihnachtsporträt für Familie, Paare oder Haustiere, entdeckst das Santa-Erlebnis, baust eine teilbare Wunschliste, gestaltest eine Weihnachtskarte mit Foto und Nachricht, schreibst Weihnachtswünsche, schmückst einen digitalen Baum und öffnest tägliche Adventsüberraschungen.",
  "faq.h2": "Häufig gestellte Fragen",
  "faq.1.q": "Was kann ich zu Weihnachten mit TheDigitalGifter erstellen?",
  "faq.1.a": "Geschenkideen, Weihnachtsporträts für Familien, Paare und Haustiere, das Santa-Erlebnis, eine teilbare Wunschliste, Weihnachtskarten, Weihnachtsnachrichten, einen digitalen Baum und einen Adventskalender.",
  "faq.2.q": "Kann Santa den Namen meines Kindes sagen?",
  "faq.2.a": "Du kannst mit dem Vornamen auf der Weihnachtsseite oder im Santa-Erlebnis starten. Gesprochene Videos sind derzeit für Englisch und Rumänisch verfügbar — andere Sprachen folgen.",
  "faq.3.q": "Brauche ich Designkenntnisse?",
  "faq.3.a": "Nein. Jedes Weihnachtserlebnis ist geführt — lade ein Foto hoch, beantworte ein paar Fragen oder starte mit einem Namen.",
  "faq.4.q": "Geht es um digitale Geschenke, physische Geschenke oder beides?",
  "faq.4.a": "Beides. Nutze den Geschenke-Finder und die Wunschliste zum Einkaufen überall, und erstelle digitale Porträts und Karten zum Versenden.",
  "faq.5.q": "Funktioniert das auf meinem Handy?",
  "faq.5.a": "Ja. Der Weihnachts-Hub und die Produkterlebnisse sind für Handys und Desktop gemacht.",
  "nav.gifts": "Geschenke unterm Baum",
  "nav.finder": "Geschenke-Finder",
  "nav.portraits": "Porträts",
  "nav.santa": "Santa",
  "nav.wishlist": "Wunschliste",
  "nav.tree": "Baum",
  "nav.advent": "Advent",
  "nav.cards": "Karten",
  "nav.messages": "Nachrichten",
};

const FR: CopyBag = {
  "seo.title": "Cadeaux de Noël, portraits & moments avec le Père Noël | TheDigitalGifter",
  "seo.description": "Créez un Noël inoubliable : trouvez le cadeau idéal, transformez une photo en portrait de Noël, découvrez le Père Noël, partagez une liste de souhaits, décorez un sapin, ouvrez l’Avent et rédigez une carte personnelle.",
  "hero.eyebrow": "Noël chez The Digital Gifter",
  "hero.h1": "Créez quelque chose dont ils se souviendront.",
  "hero.lede": "Entrez dans un monde de Noël vivant — des cadeaux sous le sapin, des portraits près du feu, et un moment spécial avec le Père Noël.",
  "hero.cta": "Commencer à créer",
  "hero.secondary": "Explorer ce Noël",
  "hero.alt": "Un chalet de montagne luxueux à Noël, avec de grandes baies vitrées, une cheminée en pierre et un sapin lumineux",
  "hero.countdown.eyebrow": "Noël approche",
  "hero.countdown.days": "Jours",
  "hero.countdown.hours": "Heures",
  "hero.countdown.minutes": "Minutes",
  "hero.countdown.seconds": "Secondes",
  "hero.countdown.until": "avant Noël",
  "hero.countdown.arrived": "Joyeux Noël — la magie est là.",
  "transition.kicker": "Noël, c’est plus qu’un cadeau.",
  "transition.h2": "Transformez cette saison en quelque chose de magique.",
  "transition.lede": "Continuez à faire défiler. La même pièce s’ouvre sur chaque moment de Noël dont vous pourriez avoir besoin.",
  "gifts.kicker": "Cadeaux de Noël",
  "gifts.h2": "Ouvrez un cadeau sous le sapin.",
  "gifts.lede": "Touchez un cadeau lumineux. Révélez une surprise de Noël gratuite — portraits, cartes, crédits et plus encore.",
  "gifts.cta": "Trouver le cadeau parfait",
  "gifts.mom": "Maman",
  "gifts.dad": "Papa",
  "gifts.partner": "Partenaire",
  "gifts.friend": "Ami",
  "gifts.kids": "Enfants",
  "gifts.hint": "Choisissez une personne. Les cadeaux répondront.",
  "gifts.react.mom": "Quelque chose d’attentionné, chaleureux et un peu luxueux — juste pour elle.",
  "gifts.react.dad": "Utile, surprenant et choisi avec soin — il le remarquera.",
  "gifts.react.partner": "Un cadeau qui ressemble à un souvenir, pas à un ticket de caisse.",
  "gifts.react.friend": "Le genre de présent qui fait se sentir vu un ami.",
  "gifts.react.kids": "D’abord l’émerveillement. Puis le sourire qu’ils ne peuvent pas cacher.",
  "finder.kicker": "Trouveur de cadeaux de Noël",
  "finder.h2": "Trouvez le cadeau de Noël parfait",
  "finder.lede": "Vous ne savez pas quoi offrir ? Utilisez le Trouveur de cadeaux de Noël pour assortir des idées à la personne, ses centres d’intérêt et votre budget — y compris pour quelqu’un qui semble déjà tout avoir. Enregistrez vos favoris dans une liste de souhaits quand vous êtes prêt.",
  "finder.cta": "Trouver un cadeau de Noël qu’ils aimeront vraiment",
  "finder.hint": "Choisissez pour qui vous achetez, puis continuez dans le trouveur.",
  "portraits.kicker": "Portraits de Noël",
  "portraits.h2": "Créez des photos de Noël magiques",
  "portraits.lede": "Importez une photo nette et transformez-la en portrait festif pour la famille, les couples ou les animaux — y compris chiens et chats. Téléchargez en privé, ou emportez le portrait dans une carte de Noël.",
  "portraits.cta": "Transformez votre photo en magie de Noël",
  "portraits.family": "Famille",
  "portraits.couples": "Couples",
  "portraits.pets": "Animaux",
  "portraits.alt.family": "Famille transformée en portrait de Noël au coin du feu",
  "portraits.alt.couples": "Couple transformé en portrait romantique de Noël",
  "portraits.alt.pets": "Animal transformé en portrait festif de Noël",
  "portraits.alt.before": "Une photo de famille du quotidien avant de devenir un portrait de Noël",
  "santa.kicker": "Père Noël",
  "santa.h2": "Rencontrez le Père Noël",
  "santa.h2Personalized": "Le Père Noël a hâte de voir {name}...",
  "santa.lede": "Découvrez l’expérience Père Noël. Commencez par le prénom et explorez un moment de Noël — sans promesse de voix parlée dans votre langue.",
  "santa.bubble": "Ho ho ho, je suis le Père Noël !",
  "santa.bubblePersonalized": "{name} ? Je connais ce nom...",
  "santa.label": "Prénom de votre enfant",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Rencontrer le Père Noël",
  "santa.ctaPersonalized": "Continuer avec {name}",
  "santa.reassurance": "Il ne faut qu’un instant pour commencer la magie.",
  "santa.alt": "Le Père Noël dans le salon de Noël, prêt à vous accueillir",
  "santa.error": "Veuillez saisir un prénom avec des lettres, des espaces, des tirets ou des apostrophes.",
  "wishlist.kicker": "Liste de souhaits",
  "wishlist.h2": "Créez et partagez une liste de souhaits de Noël",
  "wishlist.lede": "Ajoutez des souhaits via des liens produits ou du texte libre, partagez un lien simple avec la famille, et laissez réserver les cadeaux pour que les courses restent coordonnées sans gâcher la surprise.",
  "wishlist.cta": "Créer une liste de souhaits de Noël",
  "wishlist.alt": "Une lettre manuscrite au Père Noël qui glisse d’une enveloppe crème",
  "tree.kicker": "Sapin de Noël",
  "tree.h2": "Construisez un sapin rempli de cadeaux, de souvenirs et de surprises.",
  "tree.lede": "Partagez-le avec quelqu’un que vous aimez. Lumières, ornements et petits messages qui apparaissent à l’ouverture.",
  "tree.cta": "Créer votre sapin de Noël",
  "advent.kicker": "Avent",
  "advent.h2": "Un peu de magie de Noël chaque jour.",
  "advent.lede": "Ouvrez la surprise du jour. Revenez demain. La saison devient un rituel, pas une course.",
  "advent.cta": "Ouvrir la porte du jour",
  "advent.alt": "Un élégant calendrier de l’Avent en bois avec une porte lumineuse pour aujourd’hui",
  "advent.today": "Porte du jour",
  "cards.kicker": "Cartes de Noël",
  "cards.h2": "Créez une carte de Noël personnalisée",
  "cards.lede": "Combinez une photo, un design festif et un message personnel en une carte de Noël à télécharger ou partager. Certains messages méritent mieux qu’un SMS.",
  "cards.cta": "Créer une carte qu’ils auront envie de garder",
  "cards.elegant": "Élégante",
  "cards.family": "Famille",
  "cards.romantic": "Romantique",
  "cards.funny": "Drôle",
  "cards.alt": "Une carte de Noël ouverte sur une table en bois, près du sapin et des bougies",
  "messages.kicker": "Messages",
  "messages.h2": "Parfois, vous savez ce que vous ressentez.",
  "messages.lede": "Vous ne savez juste pas comment le dire. Nous vous aidons à trouver les mots — puis vous les faites vôtres.",
  "messages.cta": "Écrire mon message de Noël",
  "messages.for": "Pour",
  "messages.tone": "Ton",
  "messages.heartfelt": "Sincère",
  "messages.funny": "Drôle",
  "messages.warm": "Chaleureux",
  "finale.kicker": "Ce Noël",
  "finale.h2": "Rendez ce Noël inoubliable.",
  "finale.lede": "La pièce est plus pleine. Les lumières sont allumées. Commencez à créer — un cadeau, un portrait, un message, un moment.",
  "finale.cta": "Commencer à créer",
  "finale.alt": "Le même salon de Noël, plus chaleureux et plus complet, avec lumières et cadeaux",
  "geo.h2": "Que pouvez-vous créer avec TheDigitalGifter pour Noël ?",
  "geo.body": "TheDigitalGifter est un hub de création de Noël. Vous pouvez trouver des idées de cadeaux avec le Trouveur, transformer une photo en portrait pour famille, couples ou animaux, découvrir l’expérience Père Noël, créer une liste de souhaits partageable, concevoir une carte avec votre photo et votre message, écrire des vœux, décorer un sapin numérique et ouvrir des surprises d’Avent quotidiennes.",
  "faq.h2": "Questions fréquentes",
  "faq.1.q": "Que puis-je créer pour Noël avec TheDigitalGifter ?",
  "faq.1.a": "Des idées de cadeaux, des portraits de Noël pour familles, couples et animaux, l’expérience Père Noël, une liste de souhaits partageable, des cartes, des messages, un sapin numérique et un calendrier de l’Avent.",
  "faq.2.q": "Le Père Noël peut-il dire le prénom de mon enfant ?",
  "faq.2.a": "Vous pouvez commencer par le prénom sur la page Noël ou dans l’expérience Père Noël. Les vidéos parlées sont disponibles aujourd’hui en anglais et en roumain — d’autres langues suivront.",
  "faq.3.q": "Ai-je besoin de compétences en design ?",
  "faq.3.a": "Non. Chaque expérience de Noël est guidée — importez une photo, répondez à quelques questions ou commencez par un prénom.",
  "faq.4.q": "Est-ce pour des cadeaux numériques, physiques, ou les deux ?",
  "faq.4.a": "Les deux. Utilisez le Trouveur et la liste de souhaits pour faire vos courses partout, et créez des portraits et cartes numériques à envoyer.",
  "faq.5.q": "Cela fonctionne-t-il sur mon téléphone ?",
  "faq.5.a": "Oui. Le hub de Noël et les expériences produit sont conçus pour les téléphones comme pour les ordinateurs.",
  "nav.gifts": "Cadeaux sous le sapin",
  "nav.finder": "Trouveur de cadeaux",
  "nav.portraits": "Portraits",
  "nav.santa": "Père Noël",
  "nav.wishlist": "Liste de souhaits",
  "nav.tree": "Sapin",
  "nav.advent": "Avent",
  "nav.cards": "Cartes",
  "nav.messages": "Messages",
};

const ES: CopyBag = {
  "seo.title": "Regalos de Navidad, retratos y momentos con Papá Noel | TheDigitalGifter",
  "seo.description": "Crea una Navidad inolvidable: encuentra el regalo perfecto, convierte una foto en un retrato navideño, descubre a Papá Noel, comparte una lista de deseos, decora un árbol, abre el Adviento y escribe una tarjeta personal.",
  "hero.eyebrow": "Navidad en The Digital Gifter",
  "hero.h1": "Crea algo que recordarán.",
  "hero.lede": "Entra en un mundo navideño vivo — regalos bajo el árbol, retratos junto al fuego y un momento especial con Papá Noel.",
  "hero.cta": "Empezar a crear",
  "hero.secondary": "Explorar esta Navidad",
  "hero.alt": "Una cabaña de montaña de lujo en Navidad, con ventanales, chimenea de piedra y un árbol luminoso",
  "hero.countdown.eyebrow": "La Navidad se acerca",
  "hero.countdown.days": "Días",
  "hero.countdown.hours": "Horas",
  "hero.countdown.minutes": "Minutos",
  "hero.countdown.seconds": "Segundos",
  "hero.countdown.until": "hasta Navidad",
  "hero.countdown.arrived": "Feliz Navidad — la magia ya está aquí.",
  "transition.kicker": "La Navidad es más que un regalo.",
  "transition.h2": "Convierte esta temporada en algo mágico.",
  "transition.lede": "Sigue bajando. La misma habitación se abre a cada momento navideño que puedas necesitar.",
  "gifts.kicker": "Regalos de Navidad",
  "gifts.h2": "Abre un regalo bajo el árbol.",
  "gifts.lede": "Toca un regalo brillante. Revela una sorpresa navideña gratis — retratos, tarjetas, créditos y más.",
  "gifts.cta": "Encontrar el regalo perfecto",
  "gifts.mom": "Mamá",
  "gifts.dad": "Papá",
  "gifts.partner": "Pareja",
  "gifts.friend": "Amigo",
  "gifts.kids": "Niños",
  "gifts.hint": "Elige a una persona. Los regalos responderán.",
  "gifts.react.mom": "Algo pensado, cálido y un poco lujoso — solo para ella.",
  "gifts.react.dad": "Útil, sorprendente y elegido con cuidado — se dará cuenta.",
  "gifts.react.partner": "Un regalo que se siente como un recuerdo, no como un ticket.",
  "gifts.react.friend": "El tipo de detalle que hace que un amigo se sienta visto.",
  "gifts.react.kids": "Primero el asombro. Luego la sonrisa que no pueden fingir.",
  "finder.kicker": "Buscador de regalos de Navidad",
  "finder.h2": "Encuentra el regalo de Navidad perfecto",
  "finder.lede": "¿No sabes qué comprar? Usa el Buscador de regalos de Navidad para combinar ideas con la persona, sus intereses y tu presupuesto — también para quien parece tenerlo todo. Guarda favoritos en una lista de deseos cuando quieras.",
  "finder.cta": "Encontrar un regalo de Navidad que les encante de verdad",
  "finder.hint": "Elige para quién compras y continúa en el buscador.",
  "portraits.kicker": "Retratos de Navidad",
  "portraits.h2": "Crea fotos mágicas de Navidad",
  "portraits.lede": "Sube una foto nítida y conviértela en un retrato festivo para familia, parejas o mascotas — incluidos perros y gatos. Descárgalo en privado o llévalo a una tarjeta de Navidad.",
  "portraits.cta": "Convierte tu foto en magia de Navidad",
  "portraits.family": "Familia",
  "portraits.couples": "Parejas",
  "portraits.pets": "Mascotas",
  "portraits.alt.family": "Familia transformada en un retrato navideño junto a la chimenea",
  "portraits.alt.couples": "Pareja transformada en un retrato romántico de Navidad",
  "portraits.alt.pets": "Mascota transformada en un retrato festivo de Navidad",
  "portraits.alt.before": "Una foto familiar cotidiana antes de convertirse en retrato de Navidad",
  "santa.kicker": "Papá Noel",
  "santa.h2": "Conoce a Papá Noel",
  "santa.h2Personalized": "Papá Noel espera a {name}...",
  "santa.lede": "Descubre la experiencia de Papá Noel. Empieza con el nombre y explora un momento navideño — sin afirmar un vídeo hablado en tu idioma.",
  "santa.bubble": "¡Jo jo jo, soy Papá Noel!",
  "santa.bubblePersonalized": "{name}? Conozco ese nombre...",
  "santa.label": "Nombre de tu hijo/a",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofía|Oliver",
  "santa.cta": "Conocer a Papá Noel",
  "santa.ctaPersonalized": "Continuar con {name}",
  "santa.reassurance": "Solo hace falta un momento para empezar la magia.",
  "santa.alt": "Papá Noel en la sala de Navidad, listo para saludarte",
  "santa.error": "Introduce un nombre con letras, espacios, guiones o apóstrofos.",
  "wishlist.kicker": "Lista de deseos",
  "wishlist.h2": "Crea y comparte una lista de deseos de Navidad",
  "wishlist.lede": "Añade deseos con enlaces de productos o texto libre, comparte un enlace sencillo con la familia y deja que reserven regalos para que las compras sigan coordinadas sin arruinar la sorpresa.",
  "wishlist.cta": "Crear una lista de deseos de Navidad",
  "wishlist.alt": "Una carta manuscrita a Papá Noel que sale de un sobre crema",
  "tree.kicker": "Árbol de Navidad",
  "tree.h2": "Construye un árbol lleno de regalos, recuerdos y sorpresas.",
  "tree.lede": "Compártelo con alguien a quien quieras. Luces, adornos y pequeños mensajes que aparecen al abrirlo.",
  "tree.cta": "Crear tu árbol de Navidad",
  "advent.kicker": "Adviento",
  "advent.h2": "Un poco de magia navideña cada día.",
  "advent.lede": "Abre la sorpresa de hoy. Vuelve mañana. La temporada se convierte en un ritual, no en una carrera.",
  "advent.cta": "Abrir la puerta de hoy",
  "advent.alt": "Un elegante calendario de Adviento de madera con una puerta iluminada para hoy",
  "advent.today": "Puerta de hoy",
  "cards.kicker": "Tarjetas de Navidad",
  "cards.h2": "Crea una tarjeta de Navidad personalizada",
  "cards.lede": "Combina una foto, un diseño festivo y un mensaje personal en una tarjeta de Navidad para descargar o compartir. Algunos mensajes merecen más que un texto.",
  "cards.cta": "Crear una tarjeta que querrán guardar",
  "cards.elegant": "Elegante",
  "cards.family": "Familia",
  "cards.romantic": "Romántica",
  "cards.funny": "Divertida",
  "cards.alt": "Una tarjeta de Navidad abierta sobre una mesa de madera junto a pino y velas",
  "messages.kicker": "Mensajes",
  "messages.h2": "A veces sabes lo que sientes.",
  "messages.lede": "Solo no sabes cómo decirlo. Te ayudamos a encontrar las palabras — y luego las haces tuyas.",
  "messages.cta": "Escribir mi mensaje de Navidad",
  "messages.for": "Para",
  "messages.tone": "Tono",
  "messages.heartfelt": "Sincero",
  "messages.funny": "Divertido",
  "messages.warm": "Cálido",
  "finale.kicker": "Esta Navidad",
  "finale.h2": "Haz esta Navidad inolvidable.",
  "finale.lede": "La sala está más completa. Las luces están encendidas. Empieza a crear — un regalo, un retrato, un mensaje, un momento.",
  "finale.cta": "Empezar a crear",
  "finale.alt": "El mismo salón de Navidad, más cálido y completo, con luces y regalos",
  "geo.h2": "¿Qué puedes crear con TheDigitalGifter para Navidad?",
  "geo.body": "TheDigitalGifter es un hub de creación navideña. Puedes encontrar ideas de regalos con el Buscador, convertir una foto en un retrato para familia, parejas o mascotas, descubrir la experiencia de Papá Noel, crear una lista de deseos compartible, diseñar una tarjeta con tu foto y mensaje, escribir deseos, decorar un árbol digital y abrir sorpresas diarias de Adviento.",
  "faq.h2": "Preguntas frecuentes",
  "faq.1.q": "¿Qué puedo crear para Navidad con TheDigitalGifter?",
  "faq.1.a": "Ideas de regalos, retratos navideños para familias, parejas y mascotas, la experiencia de Papá Noel, una lista de deseos compartible, tarjetas, mensajes, un árbol digital y un calendario de Adviento.",
  "faq.2.q": "¿Puede Papá Noel decir el nombre de mi hijo?",
  "faq.2.a": "Puedes empezar con el nombre en la página de Navidad o en la experiencia de Papá Noel. Los vídeos hablados están disponibles hoy en inglés y rumano — otros idiomas llegarán.",
  "faq.3.q": "¿Necesito habilidades de diseño?",
  "faq.3.a": "No. Cada experiencia de Navidad está guiada — sube una foto, responde unas preguntas o empieza con un nombre.",
  "faq.4.q": "¿Es para regalos digitales, físicos o ambos?",
  "faq.4.a": "Ambos. Usa el Buscador y la lista de deseos para comprar en cualquier sitio, y crea retratos y tarjetas digitales para enviar.",
  "faq.5.q": "¿Funciona en mi teléfono?",
  "faq.5.a": "Sí. El hub de Navidad y las experiencias de producto están pensados para móviles y ordenadores.",
  "nav.gifts": "Regalos bajo el árbol",
  "nav.finder": "Buscador de regalos",
  "nav.portraits": "Retratos",
  "nav.santa": "Papá Noel",
  "nav.wishlist": "Lista de deseos",
  "nav.tree": "Árbol",
  "nav.advent": "Adviento",
  "nav.cards": "Tarjetas",
  "nav.messages": "Mensajes",
};

const IT: CopyBag = {
  "seo.title": "Regali di Natale, ritratti e momenti con Babbo Natale | TheDigitalGifter",
  "seo.description": "Crea un Natale indimenticabile: trova il regalo giusto, trasforma una foto in un ritratto natalizio, scopri Babbo Natale, condividi una lista dei desideri, decora un albero, apri l’Avvento e scrivi un biglietto personale.",
  "hero.eyebrow": "Natale con The Digital Gifter",
  "hero.h1": "Crea qualcosa che ricorderanno.",
  "hero.lede": "Entra in un mondo di Natale vivo — regali sotto l’albero, ritratti vicino al fuoco e un momento speciale con Babbo Natale.",
  "hero.cta": "Inizia a creare",
  "hero.secondary": "Esplora questo Natale",
  "hero.alt": "Una lussuosa baita di montagna a Natale, con grandi finestre, camino in pietra e un albero luminoso",
  "hero.countdown.eyebrow": "Il Natale sta arrivando",
  "hero.countdown.days": "Giorni",
  "hero.countdown.hours": "Ore",
  "hero.countdown.minutes": "Minuti",
  "hero.countdown.seconds": "Secondi",
  "hero.countdown.until": "al Natale",
  "hero.countdown.arrived": "Buon Natale — la magia è qui.",
  "transition.kicker": "Il Natale è più di un regalo.",
  "transition.h2": "Trasforma questa stagione in qualcosa di magico.",
  "transition.lede": "Continua a scorrere. La stessa stanza si apre a ogni momento di Natale di cui potresti avere bisogno.",
  "gifts.kicker": "Regali di Natale",
  "gifts.h2": "Apri un regalo sotto l’albero.",
  "gifts.lede": "Tocca un pacco luminoso. Scopri una sorpresa natalizia gratuita — ritratti, biglietti, crediti e altro.",
  "gifts.cta": "Trova il regalo perfetto",
  "gifts.mom": "Mamma",
  "gifts.dad": "Papà",
  "gifts.partner": "Partner",
  "gifts.friend": "Amico",
  "gifts.kids": "Bambini",
  "gifts.hint": "Scegli una persona. I regali risponderanno.",
  "gifts.react.mom": "Qualcosa di premuroso, caldo e un po’ lussuoso — solo per lei.",
  "gifts.react.dad": "Utile, sorprendente e scelto con cura — se ne accorgerà.",
  "gifts.react.partner": "Un regalo che sembra un ricordo, non uno scontrino.",
  "gifts.react.friend": "Il tipo di regalo che fa sentire un amico visto.",
  "gifts.react.kids": "Prima lo stupore. Poi il sorriso che non possono fingere.",
  "finder.kicker": "Trova-regali di Natale",
  "finder.h2": "Trova il regalo di Natale perfetto",
  "finder.lede": "Non sai cosa comprare? Usa il Trova-regali di Natale per abbinare idee alla persona, ai suoi interessi e al tuo budget — anche per chi sembra avere già tutto. Salva i preferiti in una lista dei desideri quando sei pronto.",
  "finder.cta": "Trova un regalo di Natale che ameranno davvero",
  "finder.hint": "Scegli per chi stai acquistando, poi continua nel trova-regali.",
  "portraits.kicker": "Ritratti di Natale",
  "portraits.h2": "Crea foto di Natale magiche",
  "portraits.lede": "Carica una foto nitida e trasformala in un ritratto festivo per famiglia, coppie o animali — inclusi cani e gatti. Scaricalo in privato o portalo in un biglietto di Natale.",
  "portraits.cta": "Trasforma la tua foto in magia di Natale",
  "portraits.family": "Famiglia",
  "portraits.couples": "Coppie",
  "portraits.pets": "Animali",
  "portraits.alt.family": "Famiglia trasformata in un ritratto natalizio accanto al camino",
  "portraits.alt.couples": "Coppia trasformata in un ritratto romantico di Natale",
  "portraits.alt.pets": "Animale trasformato in un ritratto festivo di Natale",
  "portraits.alt.before": "Una foto di famiglia quotidiana prima di diventare un ritratto di Natale",
  "santa.kicker": "Babbo Natale",
  "santa.h2": "Incontra Babbo Natale",
  "santa.h2Personalized": "Babbo Natale aspetta {name}...",
  "santa.lede": "Scopri l’esperienza con Babbo Natale. Inizia con il nome ed esplora un momento natalizio — senza promettere un video parlato nella tua lingua.",
  "santa.bubble": "Ho ho ho, sono Babbo Natale!",
  "santa.bubblePersonalized": "{name}? Conosco quel nome...",
  "santa.label": "Nome di tuo figlio/a",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Incontra Babbo Natale",
  "santa.ctaPersonalized": "Continua con {name}",
  "santa.reassurance": "Basta un momento per far partire la magia.",
  "santa.alt": "Babbo Natale nella stanza di Natale, pronto ad accoglierti",
  "santa.error": "Inserisci un nome con lettere, spazi, trattini o apostrofi.",
  "wishlist.kicker": "Lista dei desideri",
  "wishlist.h2": "Crea e condividi una lista dei desideri di Natale",
  "wishlist.lede": "Aggiungi desideri da link di prodotti o testo libero, condividi un link semplice con la famiglia e lascia riservare i regali così lo shopping resta coordinato senza rovinare la sorpresa.",
  "wishlist.cta": "Crea una lista dei desideri di Natale",
  "wishlist.alt": "Una lettera scritta a mano a Babbo Natale che esce da una busta color crema",
  "tree.kicker": "Albero di Natale",
  "tree.h2": "Costruisci un albero pieno di regali, ricordi e sorprese.",
  "tree.lede": "Condividilo con qualcuno che ami. Luci, ornamenti e piccoli messaggi che appaiono quando lo aprono.",
  "tree.cta": "Crea il tuo albero di Natale",
  "advent.kicker": "Avvento",
  "advent.h2": "Un po’ di magia di Natale ogni giorno.",
  "advent.lede": "Apri la sorpresa di oggi. Torna domani. La stagione diventa un rituale, non una corsa.",
  "advent.cta": "Apri la porta di oggi",
  "advent.alt": "Un elegante calendario dell’Avvento in legno con una porta luminosa per oggi",
  "advent.today": "Porta di oggi",
  "cards.kicker": "Biglietti di Natale",
  "cards.h2": "Crea un biglietto di Natale personalizzato",
  "cards.lede": "Combina una foto, un design festivo e un messaggio personale in un biglietto di Natale da scaricare o condividere. Alcuni messaggi meritano più di un SMS.",
  "cards.cta": "Crea un biglietto che vorranno tenere",
  "cards.elegant": "Elegante",
  "cards.family": "Famiglia",
  "cards.romantic": "Romantico",
  "cards.funny": "Divertente",
  "cards.alt": "Un biglietto di Natale aperto su un tavolo di legno accanto a pino e candele",
  "messages.kicker": "Messaggi",
  "messages.h2": "A volte sai cosa senti.",
  "messages.lede": "Solo non sai come dirlo. Ti aiutiamo a trovare le parole — poi le fai tue.",
  "messages.cta": "Scrivi il mio messaggio di Natale",
  "messages.for": "Per",
  "messages.tone": "Tono",
  "messages.heartfelt": "Sincero",
  "messages.funny": "Divertente",
  "messages.warm": "Caldo",
  "finale.kicker": "Questo Natale",
  "finale.h2": "Rendi questo Natale indimenticabile.",
  "finale.lede": "La stanza è più piena. Le luci sono accese. Inizia a creare — un regalo, un ritratto, un messaggio, un momento.",
  "finale.cta": "Inizia a creare",
  "finale.alt": "Lo stesso soggiorno di Natale, più caldo e completo, con luci e regali",
  "geo.h2": "Cosa puoi creare con TheDigitalGifter per Natale?",
  "geo.body": "TheDigitalGifter è un hub di creazione natalizia. Puoi trovare idee regalo con il Trova-regali, trasformare una foto in un ritratto per famiglia, coppie o animali, scoprire l’esperienza Babbo Natale, creare una lista dei desideri condividibile, progettare un biglietto con foto e messaggio, scrivere auguri, decorare un albero digitale e aprire sorprese giornaliere dell’Avvento.",
  "faq.h2": "Domande frequenti",
  "faq.1.q": "Cosa posso creare per Natale con TheDigitalGifter?",
  "faq.1.a": "Idee regalo, ritratti natalizi per famiglie, coppie e animali, l’esperienza Babbo Natale, una lista dei desideri condividibile, biglietti, messaggi, un albero digitale e un calendario dell’Avvento.",
  "faq.2.q": "Babbo Natale può dire il nome di mio figlio?",
  "faq.2.a": "Puoi iniziare con il nome sulla pagina Natale o nell’esperienza Babbo Natale. I video parlati sono disponibili oggi in inglese e rumeno — altre lingue arriveranno.",
  "faq.3.q": "Servono competenze di design?",
  "faq.3.a": "No. Ogni esperienza natalizia è guidata — carica una foto, rispondi a poche domande o inizia con un nome.",
  "faq.4.q": "È per regali digitali, fisici o entrambi?",
  "faq.4.a": "Entrambi. Usa il Trova-regali e la lista dei desideri per fare shopping ovunque, e crea ritratti e biglietti digitali da inviare.",
  "faq.5.q": "Funziona sul mio telefono?",
  "faq.5.a": "Sì. L’hub di Natale e le esperienze prodotto sono pensati per telefoni e desktop.",
  "nav.gifts": "Regali sotto l’albero",
  "nav.finder": "Trova-regali",
  "nav.portraits": "Ritratti",
  "nav.santa": "Babbo Natale",
  "nav.wishlist": "Lista dei desideri",
  "nav.tree": "Albero",
  "nav.advent": "Avvento",
  "nav.cards": "Biglietti",
  "nav.messages": "Messaggi",
};

const PT: CopyBag = {
  "seo.title": "Presentes de Natal, retratos e momentos com o Pai Natal | TheDigitalGifter",
  "seo.description": "Crie um Natal inesquecível: encontre o presente certo, transforme uma foto num retrato de Natal, descubra o Pai Natal, partilhe uma lista de desejos, decore uma árvore, abra o Advento e escreva um cartão pessoal.",
  "hero.eyebrow": "Natal na The Digital Gifter",
  "hero.h1": "Crie algo de que se vão lembrar.",
  "hero.lede": "Entre num mundo de Natal vivo — presentes debaixo da árvore, retratos junto à lareira e um momento especial com o Pai Natal.",
  "hero.cta": "Começar a criar",
  "hero.secondary": "Explorar este Natal",
  "hero.alt": "Um chalé de montanha de luxo no Natal, com janelas do chão ao teto, lareira de pedra e uma árvore luminosa",
  "hero.countdown.eyebrow": "O Natal está a chegar",
  "hero.countdown.days": "Dias",
  "hero.countdown.hours": "Horas",
  "hero.countdown.minutes": "Minutos",
  "hero.countdown.seconds": "Segundos",
  "hero.countdown.until": "até ao Natal",
  "hero.countdown.arrived": "Feliz Natal — a magia está aqui.",
  "transition.kicker": "O Natal é mais do que um presente.",
  "transition.h2": "Transforme esta época em algo mágico.",
  "transition.lede": "Continue a deslizar. A mesma sala abre-se a cada momento de Natal de que possa precisar.",
  "gifts.kicker": "Presentes de Natal",
  "gifts.h2": "Abra um presente debaixo da árvore.",
  "gifts.lede": "Toque num presente luminoso. Revele uma surpresa de Natal gratuita — retratos, cartões, créditos e mais.",
  "gifts.cta": "Encontrar o presente perfeito",
  "gifts.mom": "Mãe",
  "gifts.dad": "Pai",
  "gifts.partner": "Parceiro",
  "gifts.friend": "Amigo",
  "gifts.kids": "Crianças",
  "gifts.hint": "Escolha uma pessoa. Os presentes respondem.",
  "gifts.react.mom": "Algo atencioso, acolhedor e um pouco luxuoso — só para ela.",
  "gifts.react.dad": "Útil, surpreendente e escolhido com cuidado — ele vai notar.",
  "gifts.react.partner": "Um presente que parece uma memória, não um recibo.",
  "gifts.react.friend": "O tipo de presente que faz um amigo sentir-se visto.",
  "gifts.react.kids": "Primeiro o espanto. Depois o sorriso que não conseguem fingir.",
  "finder.kicker": "Localizador de Presentes de Natal",
  "finder.h2": "Encontre o Presente de Natal Perfeito",
  "finder.lede": "Não sabe o que comprar? Use o Localizador de Presentes de Natal para combinar ideias com a pessoa, os interesses e o seu orçamento — inclusive para quem parece já ter tudo. Guarde favoritos numa lista de desejos quando estiver pronto.",
  "finder.cta": "Encontrar um presente de Natal que vão adorar de verdade",
  "finder.hint": "Escolha para quem está a comprar e continue no localizador.",
  "portraits.kicker": "Retratos de Natal",
  "portraits.h2": "Crie Fotos Mágicas de Natal",
  "portraits.lede": "Carregue uma foto nítida e transforme-a num retrato festivo para família, casais ou animais — incluindo cães e gatos. Descarregue em privado ou leve o retrato para um cartão de Natal.",
  "portraits.cta": "Transforme a sua foto em magia de Natal",
  "portraits.family": "Família",
  "portraits.couples": "Casais",
  "portraits.pets": "Animais",
  "portraits.alt.family": "Família transformada num retrato de Natal junto à lareira",
  "portraits.alt.couples": "Casal transformado num retrato romântico de Natal",
  "portraits.alt.pets": "Animal transformado num retrato festivo de Natal",
  "portraits.alt.before": "Uma foto de família do dia a dia antes de se tornar um retrato de Natal",
  "santa.kicker": "Pai Natal",
  "santa.h2": "Conheça o Pai Natal",
  "santa.h2Personalized": "O Pai Natal espera por {name}...",
  "santa.lede": "Descubra a experiência do Pai Natal. Comece pelo nome e explore um momento de Natal — sem afirmar um vídeo falado na sua língua.",
  "santa.bubble": "Ho ho ho, eu sou o Pai Natal!",
  "santa.bubblePersonalized": "{name}? Conheço esse nome...",
  "santa.label": "Nome da sua criança",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Conhecer o Pai Natal",
  "santa.ctaPersonalized": "Continuar com {name}",
  "santa.reassurance": "Basta um momento para começar a magia.",
  "santa.alt": "O Pai Natal na sala de Natal, pronto a recebê-lo",
  "santa.error": "Introduza um nome próprio com letras, espaços, hífenes ou apóstrofos.",
  "wishlist.kicker": "Lista de desejos",
  "wishlist.h2": "Crie e Partilhe uma Lista de Desejos de Natal",
  "wishlist.lede": "Adicione desejos a partir de links de produtos ou texto livre, partilhe um link simples com a família e deixe reservar presentes para as compras ficarem coordenadas sem estragar a surpresa.",
  "wishlist.cta": "Criar uma lista de desejos de Natal",
  "wishlist.alt": "Uma carta manuscrita ao Pai Natal a sair de um envelope cor de creme",
  "tree.kicker": "Árvore de Natal",
  "tree.h2": "Construa uma árvore cheia de presentes, memórias e surpresas.",
  "tree.lede": "Partilhe-a com alguém de quem gosta. Luzes, enfeites e pequenas mensagens que aparecem quando a abrem.",
  "tree.cta": "Criar a Sua Árvore de Natal",
  "advent.kicker": "Advento",
  "advent.h2": "Um pouco de magia de Natal todos os dias.",
  "advent.lede": "Abra a surpresa de hoje. Volte amanhã. A época torna-se um ritual, não uma corrida.",
  "advent.cta": "Abrir a Porta de Hoje",
  "advent.alt": "Um elegante calendário do Advento de madeira com uma porta luminosa para hoje",
  "advent.today": "Porta de hoje",
  "cards.kicker": "Cartões de Natal",
  "cards.h2": "Crie um Cartão de Natal Personalizado",
  "cards.lede": "Combine uma foto, um design festivo e uma mensagem pessoal num cartão de Natal que pode descarregar ou partilhar. Algumas mensagens merecem mais do que um texto.",
  "cards.cta": "Criar um cartão que vão querer guardar",
  "cards.elegant": "Elegante",
  "cards.family": "Família",
  "cards.romantic": "Romântico",
  "cards.funny": "Divertido",
  "cards.alt": "Um cartão de Natal aberto numa mesa de madeira junto a pinheiro e velas",
  "messages.kicker": "Mensagens",
  "messages.h2": "Às vezes sabe o que sente.",
  "messages.lede": "Só não sabe como dizer. Ajudamo-lo a encontrar as palavras — depois torna-as suas.",
  "messages.cta": "Escrever a Minha Mensagem de Natal",
  "messages.for": "Para",
  "messages.tone": "Tom",
  "messages.heartfelt": "Sincero",
  "messages.funny": "Divertido",
  "messages.warm": "Acolhedor",
  "finale.kicker": "Este Natal",
  "finale.h2": "Torne este Natal inesquecível.",
  "finale.lede": "A sala está mais completa. As luzes estão acesas. Comece a criar — um presente, um retrato, uma mensagem, um momento.",
  "finale.cta": "Começar a criar",
  "finale.alt": "A mesma sala de estar de Natal, mais quente e completa, com luzes e presentes",
  "geo.h2": "O que pode criar com TheDigitalGifter para o Natal?",
  "geo.body": "TheDigitalGifter é um hub de criação de Natal. Pode encontrar ideias de presentes com o Localizador, transformar uma foto num retrato para família, casais ou animais, descobrir a experiência do Pai Natal, criar uma lista de desejos partilhável, desenhar um cartão com a sua foto e mensagem, escrever desejos, decorar uma árvore digital e abrir surpresas diárias do Advento.",
  "faq.h2": "Perguntas frequentes",
  "faq.1.q": "O que posso criar para o Natal com TheDigitalGifter?",
  "faq.1.a": "Ideias de presentes, retratos de Natal para famílias, casais e animais, a experiência do Pai Natal, uma lista de desejos partilhável, cartões, mensagens, uma árvore digital e um calendário do Advento.",
  "faq.2.q": "O Pai Natal pode dizer o nome do meu filho?",
  "faq.2.a": "Pode começar pelo nome na página de Natal ou na experiência do Pai Natal. Os vídeos falados estão disponíveis hoje em inglês e romeno — outras línguas virão a seguir.",
  "faq.3.q": "Preciso de competências de design?",
  "faq.3.a": "Não. Cada experiência de Natal é guiada — carregue uma foto, responda a algumas perguntas ou comece com um nome.",
  "faq.4.q": "É para presentes digitais, físicos ou ambos?",
  "faq.4.a": "Ambos. Use o Localizador e a lista de desejos para comprar em qualquer lado, e crie retratos e cartões digitais para enviar.",
  "faq.5.q": "Funciona no meu telemóvel?",
  "faq.5.a": "Sim. O hub de Natal e as experiências de produto foram pensados para telemóveis e computadores.",
  "nav.gifts": "Presentes debaixo da árvore",
  "nav.finder": "Localizador de presentes",
  "nav.portraits": "Retratos",
  "nav.santa": "Pai Natal",
  "nav.wishlist": "Lista de desejos",
  "nav.tree": "Árvore",
  "nav.advent": "Advento",
  "nav.cards": "Cartões",
  "nav.messages": "Mensagens",
};

const NL: CopyBag = {
  "seo.title": "Kerstcadeaus, portretten & kerstman-momenten | TheDigitalGifter",
  "seo.description": "Maak een onvergetelijke kerst: vind het perfecte cadeau, verander een foto in een kerstportret, ontdek de kerstman, deel een verlanglijstje, versier een boom, open de Advent en schrijf een persoonlijke kaart.",
  "hero.eyebrow": "Kerst bij The Digital Gifter",
  "hero.h1": "Maak iets dat ze onthouden.",
  "hero.lede": "Stap in een levende kerstwereld — cadeaus onder de boom, portretten bij het vuur en een bijzonder moment met de kerstman.",
  "hero.cta": "Begin met maken",
  "hero.secondary": "Ontdek deze kerst",
  "hero.alt": "Een luxe berghut met Kerst, met vloer-tot-plafondramen, een stenen open haard en een gloeiende boom",
  "hero.countdown.eyebrow": "Kerst komt eraan",
  "hero.countdown.days": "Dagen",
  "hero.countdown.hours": "Uren",
  "hero.countdown.minutes": "Minuten",
  "hero.countdown.seconds": "Seconden",
  "hero.countdown.until": "tot Kerst",
  "hero.countdown.arrived": "Vrolijk Kerstfeest — de magie is er.",
  "transition.kicker": "Kerst is meer dan één cadeau.",
  "transition.h2": "Maak van dit seizoen iets magisch.",
  "transition.lede": "Blijf scrollen. Dezelfde kamer opent zich naar elk kerstmoment dat je nodig hebt.",
  "gifts.kicker": "Kerstcadeaus",
  "gifts.h2": "Open een cadeau onder de boom.",
  "gifts.lede": "Tik op een gloeiend cadeau. Onthul een gratis kerstverrassing — portretten, kaarten, credits en meer.",
  "gifts.cta": "Vind het perfecte cadeau",
  "gifts.mom": "Mama",
  "gifts.dad": "Papa",
  "gifts.partner": "Partner",
  "gifts.friend": "Vriend",
  "gifts.kids": "Kinderen",
  "gifts.hint": "Kies een persoon. De cadeaus antwoorden.",
  "gifts.react.mom": "Iets doordachts, warms en een beetje luxe — alleen voor haar.",
  "gifts.react.dad": "Nuttig, verrassend en met zorg gekozen — hij merkt het.",
  "gifts.react.partner": "Een cadeau dat voelt als een herinnering, niet als een bonnetje.",
  "gifts.react.friend": "Het soort cadeau waardoor een vriend zich gezien voelt.",
  "gifts.react.kids": "Eerst de verwondering. Dan de glimlach die ze niet kunnen veinzen.",
  "finder.kicker": "Kerst Cadeauzoeker",
  "finder.h2": "Vind het perfecte kerstcadeau",
  "finder.lede": "Weet je niet wat je moet kopen? Gebruik de Kerst Cadeauzoeker om ideeën te matchen met de persoon, hun interesses en je budget — ook voor iemand die al alles lijkt te hebben. Bewaar favorieten op een verlanglijstje wanneer je klaar bent.",
  "finder.cta": "Vind een kerstcadeau dat ze echt zullen liefhebben",
  "finder.hint": "Kies voor wie je winkelt en ga verder naar de zoeker.",
  "portraits.kicker": "Kerstportretten",
  "portraits.h2": "Maak magische kerstfoto’s",
  "portraits.lede": "Upload een scherpe foto en verander die in een feestelijk kerstportret voor familie, koppels of huisdieren — inclusief honden en katten. Download privé, of neem een portret mee naar een kerstkaart.",
  "portraits.cta": "Verander je foto in kerstmagie",
  "portraits.family": "Familie",
  "portraits.couples": "Koppels",
  "portraits.pets": "Huisdieren",
  "portraits.alt.family": "Familie omgetoverd tot een knus openhaard-kerstportret",
  "portraits.alt.couples": "Koppel omgetoverd tot een romantisch kerstportret",
  "portraits.alt.pets": "Huisdier omgetoverd tot een feestelijk kerstportret",
  "portraits.alt.before": "Een alledaagse familiefoto voordat het een kerstportret wordt",
  "santa.kicker": "Kerstman",
  "santa.h2": "Ontmoet de kerstman",
  "santa.h2Personalized": "De kerstman kijkt uit naar {name}...",
  "santa.lede": "Ontdek de kerstman-ervaring. Begin met de voornaam en verken een kerstmoment — zonder te beloven dat er in jouw taal gesproken wordt.",
  "santa.bubble": "Ho ho ho, ik ben de kerstman!",
  "santa.bubblePersonalized": "{name}? Die naam ken ik...",
  "santa.label": "Voornaam van je kind",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Sofia|Oliver",
  "santa.cta": "Ontmoet de kerstman",
  "santa.ctaPersonalized": "Ga verder met {name}",
  "santa.reassurance": "Het duurt maar even om de magie te starten.",
  "santa.alt": "De kerstman in de kerstkamer, klaar om je te begroeten",
  "santa.error": "Voer een voornaam in met letters, spaties, streepjes of apostroffen.",
  "wishlist.kicker": "Verlanglijstje",
  "wishlist.h2": "Maak en deel een kerstverlanglijstje",
  "wishlist.lede": "Voeg wensen toe via productlinks of vrije tekst, deel één eenvoudige link met familie en laat cadeaus reserveren zodat het winkelen gecoördineerd blijft zonder de verrassing te verpesten.",
  "wishlist.cta": "Maak een kerstverlanglijstje",
  "wishlist.alt": "Een handgeschreven brief aan de kerstman die uit een crème envelop glijdt",
  "tree.kicker": "Kerstboom",
  "tree.h2": "Bouw een kerstboom vol cadeaus, herinneringen en verrassingen.",
  "tree.lede": "Deel hem met iemand van wie je houdt. Lichtjes, ornamenten en kleine berichtjes die verschijnen wanneer ze hem openen.",
  "tree.cta": "Maak je kerstboom",
  "advent.kicker": "Advent",
  "advent.h2": "Elke dag een beetje kerstmagie.",
  "advent.lede": "Open de verrassing van vandaag. Kom morgen terug. Het seizoen wordt een ritueel, geen race.",
  "advent.cta": "Open de deur van vandaag",
  "advent.alt": "Een elegante houten adventskalender met één gloeiende deur voor vandaag",
  "advent.today": "Deur van vandaag",
  "cards.kicker": "Kerstkaarten",
  "cards.h2": "Maak een persoonlijke kerstkaart",
  "cards.lede": "Combineer een foto, een feestelijk ontwerp en een persoonlijk bericht tot een kerstkaart die je kunt downloaden of digitaal delen. Sommige berichten verdienen meer dan een sms.",
  "cards.cta": "Maak een kerstkaart die ze willen bewaren",
  "cards.elegant": "Elegant",
  "cards.family": "Familie",
  "cards.romantic": "Romantisch",
  "cards.funny": "Grappig",
  "cards.alt": "Een open kerstkaart op een houten tafel naast dennen en kaarslicht",
  "messages.kicker": "Berichten",
  "messages.h2": "Soms weet je wat je voelt.",
  "messages.lede": "Je weet alleen niet hoe je het moet zeggen. Wij helpen je de woorden te vinden — daarna maak je ze van jou.",
  "messages.cta": "Schrijf mijn kerstbericht",
  "messages.for": "Voor",
  "messages.tone": "Toon",
  "messages.heartfelt": "Hartelijk",
  "messages.funny": "Grappig",
  "messages.warm": "Warm",
  "finale.kicker": "Deze kerst",
  "finale.h2": "Maak deze kerst onvergetelijk.",
  "finale.lede": "De kamer is voller. De lichtjes branden. Begin met maken — een cadeau, een portret, een bericht, een moment.",
  "finale.cta": "Begin met maken",
  "finale.alt": "Dezelfde kerstwoonkamer, warmer en completer, met lichtjes en cadeaus",
  "geo.h2": "Wat kun je met TheDigitalGifter voor Kerst maken?",
  "geo.body": "TheDigitalGifter is een kerst-creatiehub. Je kunt cadeau-ideeën vinden met de Cadeauzoeker, een foto omzetten in een kerstportret voor familie, koppels of huisdieren, de kerstman-ervaring ontdekken, een deelbaar verlanglijstje maken, een kerstkaart ontwerpen met foto en bericht, kerstwensen schrijven, een digitale boom versieren en dagelijkse Advent-verrassingen openen.",
  "faq.h2": "Veelgestelde vragen",
  "faq.1.q": "Wat kan ik voor Kerst maken met TheDigitalGifter?",
  "faq.1.a": "Cadeau-ideeën, kerstportretten voor families, koppels en huisdieren, de kerstman-ervaring, een deelbaar verlanglijstje, kerstkaarten, kerstberichten, een digitale boom en een adventskalender.",
  "faq.2.q": "Kan de kerstman de naam van mijn kind zeggen?",
  "faq.2.a": "Je kunt starten met de voornaam op de kerstpagina of in de kerstman-ervaring. Gesproken video’s zijn vandaag beschikbaar in het Engels en Roemeens — andere talen volgen.",
  "faq.3.q": "Heb ik ontwerpvaardigheden nodig?",
  "faq.3.a": "Nee. Elke kerstervaring is begeleid — upload een foto, beantwoord een paar vragen of begin met een naam.",
  "faq.4.q": "Is dit voor digitale cadeaus, fysieke cadeaus, of beide?",
  "faq.4.a": "Beide. Gebruik de Cadeauzoeker en het verlanglijstje om overal te winkelen, en maak digitale portretten en kaarten om te versturen.",
  "faq.5.q": "Werkt dit op mijn telefoon?",
  "faq.5.a": "Ja. De kersthub en productervaringen zijn gemaakt voor telefoons én desktops.",
  "nav.gifts": "Cadeaus onder de boom",
  "nav.finder": "Cadeauzoeker",
  "nav.portraits": "Portretten",
  "nav.santa": "Kerstman",
  "nav.wishlist": "Verlanglijstje",
  "nav.tree": "Boom",
  "nav.advent": "Advent",
  "nav.cards": "Kaarten",
  "nav.messages": "Berichten",
};

const PL: CopyBag = {
  "seo.title": "Prezenty świąteczne, portrety i chwile ze Świętym Mikołajem | TheDigitalGifter",
  "seo.description": "Stwórz niezapomniane święta: znajdź idealny prezent, zamień zdjęcie w świąteczny portret, poznaj Świętego Mikołaja, udostępnij listę życzeń, udekoruj choinkę, otwórz Adwent i napisz osobistą kartkę.",
  "hero.eyebrow": "Boże Narodzenie w The Digital Gifter",
  "hero.h1": "Stwórz coś, co zapamiętają.",
  "hero.lede": "Wejdź do żyjącego świątecznego świata — prezenty pod choinką, portrety przy kominku i wyjątkowa chwila ze Świętym Mikołajem.",
  "hero.cta": "Zacznij tworzyć",
  "hero.secondary": "Odkryj te święta",
  "hero.alt": "Luksusowa górska chatka na Boże Narodzenie z oknami od podłogi do sufitu, kamiennym kominkiem i świecącą choinką",
  "hero.countdown.eyebrow": "Święta nadchodzą",
  "hero.countdown.days": "Dni",
  "hero.countdown.hours": "Godziny",
  "hero.countdown.minutes": "Minuty",
  "hero.countdown.seconds": "Sekundy",
  "hero.countdown.until": "do Świąt",
  "hero.countdown.arrived": "Wesołych Świąt — magia już jest.",
  "transition.kicker": "Święta to więcej niż jeden prezent.",
  "transition.h2": "Zamień ten sezon w coś magicznego.",
  "transition.lede": "Przewijaj dalej. Ten sam pokój otwiera się na każdą świąteczną chwilę, której możesz potrzebować.",
  "gifts.kicker": "Prezenty świąteczne",
  "gifts.h2": "Otwórz prezent pod choinką.",
  "gifts.lede": "Dotknij świecącego prezentu. Odkryj darmową świąteczną niespodziankę — portrety, kartki, kredyty i więcej.",
  "gifts.cta": "Znajdź idealny prezent",
  "gifts.mom": "Mama",
  "gifts.dad": "Tata",
  "gifts.partner": "Partner",
  "gifts.friend": "Przyjaciel",
  "gifts.kids": "Dzieci",
  "gifts.hint": "Wybierz osobę. Prezenty odpowiedzą.",
  "gifts.react.mom": "Coś przemyślanego, ciepłego i odrobinę luksusowego — tylko dla niej.",
  "gifts.react.dad": "Praktyczne, zaskakujące i wybrane z troską — zauważy.",
  "gifts.react.partner": "Prezent, który czuje się jak wspomnienie, nie jak paragon.",
  "gifts.react.friend": "Taki prezent, dzięki któremu przyjaciel czuje się zauważony.",
  "gifts.react.kids": "Najpierw zachwyt. Potem uśmiech, którego nie da się udawać.",
  "finder.kicker": "Wyszukiwarka prezentów świątecznych",
  "finder.h2": "Znajdź idealny prezent świąteczny",
  "finder.lede": "Nie wiesz, co kupić? Użyj Wyszukiwarki prezentów świątecznych, by dopasować pomysły do osoby, zainteresowań i budżetu — także dla kogoś, kto wydaje się mieć już wszystko. Zapisz ulubione na liście życzeń, gdy będziesz gotowy.",
  "finder.cta": "Znajdź prezent świąteczny, który naprawdę pokochają",
  "finder.hint": "Wybierz, dla kogo kupujesz, i przejdź do wyszukiwarki.",
  "portraits.kicker": "Portrety świąteczne",
  "portraits.h2": "Twórz magiczne zdjęcia świąteczne",
  "portraits.lede": "Prześlij wyraźne zdjęcie i zamień je w świąteczny portret dla rodziny, par lub zwierząt — w tym psy i koty. Pobierz prywatnie albo przenieś portret na kartkę świąteczną.",
  "portraits.cta": "Zamień zdjęcie w świąteczną magię",
  "portraits.family": "Rodzina",
  "portraits.couples": "Pary",
  "portraits.pets": "Zwierzęta",
  "portraits.alt.family": "Rodzina zamieniona w przytulny portret świąteczny przy kominku",
  "portraits.alt.couples": "Para zamieniona w romantyczny portret świąteczny",
  "portraits.alt.pets": "Zwierzę zamienione w świąteczny portret",
  "portraits.alt.before": "Codzienne zdjęcie rodzinne zanim stanie się portretem świątecznym",
  "santa.kicker": "Święty Mikołaj",
  "santa.h2": "Poznaj Świętego Mikołaja",
  "santa.h2Personalized": "Święty Mikołaj czeka na {name}...",
  "santa.lede": "Odkryj doświadczenie ze Świętym Mikołajem. Zacznij od imienia i poznaj świąteczną chwilę — bez twierdzenia o mówionym filmie w Twoim języku.",
  "santa.bubble": "Ho ho ho, jestem Święty Mikołaj!",
  "santa.bubblePersonalized": "{name}? Znam to imię...",
  "santa.label": "Imię Twojego dziecka",
  "santa.placeholder": "Emma",
  "santa.placeholders": "Emma|Noah|Zosia|Oliver",
  "santa.cta": "Poznaj Świętego Mikołaja",
  "santa.ctaPersonalized": "Kontynuuj z {name}",
  "santa.reassurance": "Wystarczy chwila, by zacząć magię.",
  "santa.alt": "Święty Mikołaj w świątecznym pokoju, gotowy Cię przywitać",
  "santa.error": "Wpisz imię używając liter, spacji, myślników lub apostrofów.",
  "wishlist.kicker": "Lista życzeń",
  "wishlist.h2": "Utwórz i udostępnij świąteczną listę życzeń",
  "wishlist.lede": "Dodawaj życzenia z linków do produktów lub wolnego tekstu, udostępnij jeden prosty link rodzinie i pozwól rezerwować prezenty, by zakupy były skoordynowane bez psucia niespodzianki.",
  "wishlist.cta": "Utwórz świąteczną listę życzeń",
  "wishlist.alt": "Ręcznie napisany list do Świętego Mikołaja wysuwający się z kremowej koperty",
  "tree.kicker": "Choinka",
  "tree.h2": "Zbuduj choinkę pełną prezentów, wspomnień i niespodzianek.",
  "tree.lede": "Udostępnij ją komuś, kogo kochasz. Światła, ozdoby i małe wiadomości, które pojawiają się przy otwieraniu.",
  "tree.cta": "Utwórz swoją choinkę",
  "advent.kicker": "Adwent",
  "advent.h2": "Odrobina świątecznej magii każdego dnia.",
  "advent.lede": "Otwórz dzisiejszą niespodziankę. Wróć jutro. Sezon staje się rytuałem, nie wyścigiem.",
  "advent.cta": "Otwórz dzisiejsze drzwiczki",
  "advent.alt": "Elegancki drewniany kalendarz adwentowy z jedną świecącą furtką na dziś",
  "advent.today": "Dzisiejsze drzwiczki",
  "cards.kicker": "Kartki świąteczne",
  "cards.h2": "Utwórz spersonalizowaną kartkę świąteczną",
  "cards.lede": "Połącz zdjęcie, świąteczny projekt i osobistą wiadomość w kartkę, którą możesz pobrać lub udostępnić cyfrowo. Niektóre wiadomości zasługują na więcej niż SMS.",
  "cards.cta": "Utwórz kartkę, którą będą chcieli zachować",
  "cards.elegant": "Elegancka",
  "cards.family": "Rodzinna",
  "cards.romantic": "Romantyczna",
  "cards.funny": "Zabawna",
  "cards.alt": "Otwarta kartka świąteczna na drewnianym stole obok świerku i świec",
  "messages.kicker": "Wiadomości",
  "messages.h2": "Czasem wiesz, co czujesz.",
  "messages.lede": "Tylko nie wiesz, jak to powiedzieć. Pomożemy znaleźć słowa — a Ty uczynisz je swoimi.",
  "messages.cta": "Napisz moją wiadomość świąteczną",
  "messages.for": "Dla",
  "messages.tone": "Ton",
  "messages.heartfelt": "Serdeczny",
  "messages.funny": "Zabawny",
  "messages.warm": "Ciepły",
  "finale.kicker": "Te święta",
  "finale.h2": "Uczyń te święta niezapomnianymi.",
  "finale.lede": "Pokój jest pełniejszy. Światła świecą. Zacznij tworzyć — prezent, portret, wiadomość, chwilę.",
  "finale.cta": "Zacznij tworzyć",
  "finale.alt": "Ten sam świąteczny salon, cieplejszy i pełniejszy, ze światłami i prezentami",
  "geo.h2": "Co możesz stworzyć z TheDigitalGifter na Boże Narodzenie?",
  "geo.body": "TheDigitalGifter to hub świątecznej twórczości. Możesz znaleźć pomysły na prezenty w Wyszukiwarce, zamienić zdjęcie w portret dla rodziny, par lub zwierząt, odkryć doświadczenie ze Świętym Mikołajem, stworzyć udostępnialną listę życzeń, zaprojektować kartkę ze zdjęciem i wiadomością, napisać życzenia, udekorować cyfrową choinkę i otwierać codzienne niespodzianki Adwentu.",
  "faq.h2": "Najczęściej zadawane pytania",
  "faq.1.q": "Co mogę stworzyć na święta z TheDigitalGifter?",
  "faq.1.a": "Pomysły na prezenty, portrety świąteczne dla rodzin, par i zwierząt, doświadczenie ze Świętym Mikołajem, udostępnialną listę życzeń, kartki, wiadomości, cyfrową choinkę i kalendarz adwentowy.",
  "faq.2.q": "Czy Święty Mikołaj może powiedzieć imię mojego dziecka?",
  "faq.2.a": "Możesz zacząć od imienia na stronie świątecznej lub w doświadczeniu ze Świętym Mikołajem. Mówione filmy są dziś dostępne po angielsku i rumuńsku — inne języki wkrótce.",
  "faq.3.q": "Czy potrzebuję umiejętności projektowych?",
  "faq.3.a": "Nie. Każde doświadczenie świąteczne jest prowadzone — prześlij zdjęcie, odpowiedz na kilka pytań lub zacznij od imienia.",
  "faq.4.q": "Czy to dla prezentów cyfrowych, fizycznych, czy obu?",
  "faq.4.a": "Obu. Użyj Wyszukiwarki i listy życzeń do zakupów gdziekolwiek, oraz twórz cyfrowe portrety i kartki do wysyłki.",
  "faq.5.q": "Czy to działa na telefonie?",
  "faq.5.a": "Tak. Hub świąteczny i doświadczenia produktowe są zaprojektowane na telefony i komputery.",
  "nav.gifts": "Prezenty pod choinką",
  "nav.finder": "Wyszukiwarka prezentów",
  "nav.portraits": "Portrety",
  "nav.santa": "Święty Mikołaj",
  "nav.wishlist": "Lista życzeń",
  "nav.tree": "Choinka",
  "nav.advent": "Adwent",
  "nav.cards": "Kartki",
  "nav.messages": "Wiadomości",
};

export const PACKS: Record<ChristmasLandingLocale, CopyBag> = {
  en: EN,
  ro: RO,
  de: DE,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  pl: PL,
};

/** Hub CTA / hero keys that must be localized for Wave 1 (P3D coverage). */
export const REQUIRED_UI_KEYS = [
  "hero.h1",
  "hero.cta",
  "hero.secondary",
  "finder.cta",
  "portraits.cta",
  "santa.cta",
  "wishlist.cta",
  "tree.cta",
  "advent.cta",
  "cards.cta",
  "messages.cta",
  "finale.cta",
] as const;

// Assert key parity across Wave 1 packs.
const _enKeySet = Object.keys(PACKS.en).sort().join("\0");
for (const loc of CHRISTMAS_LANDING_LOCALES) {
  const keys = Object.keys(PACKS[loc]);
  if (keys.length !== Object.keys(PACKS.en).length || keys.sort().join("\0") !== _enKeySet) {
    throw new Error(`Christmas landing UI pack key mismatch for locale: ${loc}`);
  }
}

export function landingT(
  key: string,
  locale: ChristmasLandingLocale = CHRISTMAS_LANDING_DEFAULT_LOCALE,
): string {
  return PACKS[locale]?.[key] ?? PACKS.en[key] ?? key;
}

export function landingDir(locale: string): "ltr" | "rtl" {
  return LANDING_LOCALE_DIR[locale] ?? "ltr";
}

export function resolveChristmasLandingLocale(value: unknown): ChristmasLandingLocale {
  const raw = String(value || "")
    .trim()
    .toLowerCase()
    .replace("_", "-");
  if (raw === "pt-pt" || raw === "pt_pt" || raw.startsWith("pt-")) return "pt";
  const code = raw.split("-")[0];
  if ((CHRISTMAS_LANDING_LOCALES as readonly string[]).includes(code)) {
    return code as ChristmasLandingLocale;
  }
  return CHRISTMAS_LANDING_DEFAULT_LOCALE;
}

export const LANDING_COPY_KEYS = Object.keys(PACKS.en);
