/**
 * Advent calendar UI copy — Wave 1 locale packs.
 * Unlock day math stays in treeLogic (Europe/Bucharest) — this file is display only.
 * Locale-aware dates use Intl — never concatenate English month sentences.
 */

export type AdventLocale = "en" | "ro" | "de" | "fr" | "es" | "it" | "pt" | "nl" | "pl";

export const ADVENT_UI_LOCALES: AdventLocale[] = [
  "en",
  "ro",
  "de",
  "fr",
  "es",
  "it",
  "pt",
  "nl",
  "pl",
];

/** BCP 47 tags for Intl (pt = European Portuguese). */
export const ADVENT_INTL_LOCALE: Record<AdventLocale, string> = {
  en: "en",
  ro: "ro",
  de: "de",
  fr: "fr",
  es: "es",
  it: "it",
  pt: "pt-PT",
  nl: "nl",
  pl: "pl",
};

type Dict = Record<string, string>;

const EN: Dict = {
  "brand": "The Digital Gifter",
  "title": "Advent Calendar",
  "lede.openToday": "Open today’s door for a Christmas reward.",
  "lede.ended": "This season’s Advent has ended. See you next year.",
  "lede.preseason": "Advent begins {date}.",

  "countdown.aria": "Countdown",
  "countdown.untilAdvent": "until Advent",
  "countdown.untilTomorrow": "until tomorrow’s door",
  "countdown.untilChristmas": "until Christmas",
  "countdown.days": "Days",
  "countdown.hours": "Hours",
  "countdown.minutes": "Minutes",
  "countdown.seconds": "Seconds",
  "countdown.arrived": "Merry Christmas — the magic is here.",

  "cta.openToday": "Open Today’s Door",
  "cta.comeBackTomorrow": "Come back tomorrow",
  "cta.availableToday": "Available today",
  "cta.signIn": "Sign in",
  "cta.signInClaim": "Sign in to claim today’s reward when Advent is live.",
  "cta.signInError": "Sign in to claim today’s reward.",
  "cta.close": "Close",
  "cta.openFree": "Open free gift",

  "door.opened": "Opened",
  "door.today": "Today",
  "door.soon": "Soon",
  "door.missed": "Missed",
  "door.locked": "Locked",
  "door.aria": "Day {day}, {state}",
  "doors.aria": "Advent doors",

  "status.engine": "Engine ready · claims {claims} · {tz}",
  "status.live": "live",
  "status.notLive": "not live yet",

  "free.heading": "Get Your Christmas Gift",
  "free.lede": "A free seasonal surprise — no cash credits for anonymous visitors.",
  "free.aria": "Free Christmas Gift",
  "free.already": "Same gift on refresh — no reroll.",
  "free.disabled": "Free Christmas Gift opens closer to the season.",
  "free.error": "Free gift unavailable",

  "reward.aria": "Reward claimed",
  "reward.unlocked": "Unlocked: {label}",

  "nav.tree": "Build your Christmas Tree",
  "nav.hub": "Christmas hub",

  "loading": "Loading…",
  "error.load": "Could not load Advent",
  "error.claim": "Claim failed",

  "day.title": "Day {day}",
};

const RO: Dict = {
  "brand": "The Digital Gifter",
  "title": "Calendar de Advent",
  "lede.openToday": "Deschide ușa de azi pentru o recompensă de Crăciun.",
  "lede.ended": "Adventul din acest sezon s-a încheiat. Ne vedem anul viitor.",
  "lede.preseason": "Adventul începe pe {date}.",
  "countdown.aria": "Numărătoare inversă",
  "countdown.untilAdvent": "până la Advent",
  "countdown.untilTomorrow": "până la ușa de mâine",
  "countdown.untilChristmas": "până la Crăciun",
  "countdown.days": "Zile",
  "countdown.hours": "Ore",
  "countdown.minutes": "Minute",
  "countdown.seconds": "Secunde",
  "countdown.arrived": "Crăciun fericit — magia e aici.",
  "cta.openToday": "Deschide ușa de azi",
  "cta.comeBackTomorrow": "Revino mâine",
  "cta.availableToday": "Disponibil azi",
  "cta.signIn": "Autentifică-te",
  "cta.signInClaim": "Autentifică-te ca să revendici recompensa de azi când Adventul e live.",
  "cta.signInError": "Autentifică-te ca să revendici recompensa de azi.",
  "cta.close": "Închide",
  "cta.openFree": "Deschide cadoul gratuit",
  "door.opened": "Deschisă",
  "door.today": "Azi",
  "door.soon": "Curând",
  "door.missed": "Ratată",
  "door.locked": "Blocat",
  "door.aria": "Ziua {day}, {state}",
  "doors.aria": "Uși de Advent",
  "status.engine": "Motor gata · revendicări {claims} · {tz}",
  "status.live": "live",
  "status.notLive": "încă nu e live",
  "free.heading": "Primește cadoul de Crăciun",
  "free.lede": "O surpriză de sezon gratuită — fără credite în numerar pentru vizitatori anonimi.",
  "free.aria": "Cadou gratuit de Crăciun",
  "free.already": "Același cadou la reîmprospătare — fără re-roll.",
  "free.disabled": "Cadoul gratuit de Crăciun se deschide mai aproape de sezon.",
  "free.error": "Cadoul gratuit nu este disponibil",
  "reward.aria": "Recompensă revendicat",
  "reward.unlocked": "Deblocat: {label}",
  "nav.tree": "Creează-ți bradul de Crăciun",
  "nav.hub": "Hub de Crăciun",
  "loading": "Se încarcă…",
  "error.load": "Nu am putut încărca Adventul",
  "error.claim": "Revendicarea a eșuat",
  "day.title": "Ziua {day}",
};

const DE: Dict = {
  "brand": "The Digital Gifter",
  "title": "Adventskalender",
  "lede.openToday": "Öffne die Tür von heute für eine Weihnachtsbelohnung.",
  "lede.ended": "Der Advent dieser Saison ist vorbei. Bis nächstes Jahr.",
  "lede.preseason": "Der Advent beginnt am {date}.",
  "countdown.aria": "Countdown",
  "countdown.untilAdvent": "bis zum Advent",
  "countdown.untilTomorrow": "bis zur Tür von morgen",
  "countdown.untilChristmas": "bis Weihnachten",
  "countdown.days": "Tage",
  "countdown.hours": "Stunden",
  "countdown.minutes": "Minuten",
  "countdown.seconds": "Sekunden",
  "countdown.arrived": "Frohe Weihnachten — die Magie ist da.",
  "cta.openToday": "Heutige Tür öffnen",
  "cta.comeBackTomorrow": "Komm morgen wieder",
  "cta.availableToday": "Heute verfügbar",
  "cta.signIn": "Anmelden",
  "cta.signInClaim": "Melde dich an, um die heutige Belohnung zu beanspruchen, wenn Advent live ist.",
  "cta.signInError": "Melde dich an, um die heutige Belohnung zu beanspruchen.",
  "cta.close": "Schließen",
  "cta.openFree": "Kostenloses Geschenk öffnen",
  "door.opened": "Geöffnet",
  "door.today": "Heute",
  "door.soon": "Bald",
  "door.missed": "Verpasst",
  "door.locked": "Gesperrt",
  "door.aria": "Tag {day}, {state}",
  "doors.aria": "Adventstüren",
  "status.engine": "Engine bereit · Claims {claims} · {tz}",
  "status.live": "live",
  "status.notLive": "noch nicht live",
  "free.heading": "Hol dir dein Weihnachtsgeschenk",
  "free.lede": "Eine kostenlose Saisonüberraschung — keine Bargeld-Credits für anonyme Besucher.",
  "free.aria": "Kostenloses Weihnachtsgeschenk",
  "free.already": "Gleiches Geschenk beim Aktualisieren — kein Reroll.",
  "free.disabled": "Das kostenlose Weihnachtsgeschenk öffnet näher an der Saison.",
  "free.error": "Kostenloses Geschenk nicht verfügbar",
  "reward.aria": "Belohnung beansprucht",
  "reward.unlocked": "Freigeschaltet: {label}",
  "nav.tree": "Weihnachtsbaum erstellen",
  "nav.hub": "Weihnachts-Hub",
  "loading": "Laden…",
  "error.load": "Advent konnte nicht geladen werden",
  "error.claim": "Beanspruchen fehlgeschlagen",
  "day.title": "Tag {day}",
};

const FR: Dict = {
  "brand": "The Digital Gifter",
  "title": "Calendrier de l’Avent",
  "lede.openToday": "Ouvrez la case d’aujourd’hui pour une récompense de Noël.",
  "lede.ended": "L’Avent de cette saison est terminé. À l’année prochaine.",
  "lede.preseason": "L’Avent commence le {date}.",
  "countdown.aria": "Compte à rebours",
  "countdown.untilAdvent": "avant l’Avent",
  "countdown.untilTomorrow": "avant la case de demain",
  "countdown.untilChristmas": "avant Noël",
  "countdown.days": "Jours",
  "countdown.hours": "Heures",
  "countdown.minutes": "Minutes",
  "countdown.seconds": "Secondes",
  "countdown.arrived": "Joyeux Noël — la magie est là.",
  "cta.openToday": "Ouvrir la case d’aujourd’hui",
  "cta.comeBackTomorrow": "Revenez demain",
  "cta.availableToday": "Disponible aujourd’hui",
  "cta.signIn": "Se connecter",
  "cta.signInClaim": "Connectez-vous pour réclamer la récompense du jour lorsque l’Avent est en ligne.",
  "cta.signInError": "Connectez-vous pour réclamer la récompense du jour.",
  "cta.close": "Fermer",
  "cta.openFree": "Ouvrir le cadeau gratuit",
  "door.opened": "Ouverte",
  "door.today": "Aujourd’hui",
  "door.soon": "Bientôt",
  "door.missed": "Manquée",
  "door.locked": "Verrouillée",
  "door.aria": "Jour {day}, {state}",
  "doors.aria": "Cases de l’Avent",
  "status.engine": "Moteur prêt · réclamations {claims} · {tz}",
  "status.live": "en ligne",
  "status.notLive": "pas encore en ligne",
  "free.heading": "Recevez votre cadeau de Noël",
  "free.lede": "Une surprise de saison gratuite — pas de crédits monétaires pour les visiteurs anonymes.",
  "free.aria": "Cadeau de Noël gratuit",
  "free.already": "Même cadeau au rafraîchissement — pas de nouveau tirage.",
  "free.disabled": "Le cadeau de Noël gratuit s’ouvre plus près de la saison.",
  "free.error": "Cadeau gratuit indisponible",
  "reward.aria": "Récompense réclamée",
  "reward.unlocked": "Débloqué : {label}",
  "nav.tree": "Créer votre sapin de Noël",
  "nav.hub": "Hub de Noël",
  "loading": "Chargement…",
  "error.load": "Impossible de charger l’Avent",
  "error.claim": "Réclamation échouée",
  "day.title": "Jour {day}",
};

const ES: Dict = {
  "brand": "The Digital Gifter",
  "title": "Calendario de Adviento",
  "lede.openToday": "Abre la puerta de hoy para una recompensa de Navidad.",
  "lede.ended": "El Adviento de esta temporada ha terminado. Hasta el año que viene.",
  "lede.preseason": "El Adviento empieza el {date}.",
  "countdown.aria": "Cuenta atrás",
  "countdown.untilAdvent": "hasta el Adviento",
  "countdown.untilTomorrow": "hasta la puerta de mañana",
  "countdown.untilChristmas": "hasta Navidad",
  "countdown.days": "Días",
  "countdown.hours": "Horas",
  "countdown.minutes": "Minutos",
  "countdown.seconds": "Segundos",
  "countdown.arrived": "Feliz Navidad — la magia está aquí.",
  "cta.openToday": "Abrir la puerta de hoy",
  "cta.comeBackTomorrow": "Vuelve mañana",
  "cta.availableToday": "Disponible hoy",
  "cta.signIn": "Iniciar sesión",
  "cta.signInClaim": "Inicia sesión para reclamar la recompensa de hoy cuando el Adviento esté activo.",
  "cta.signInError": "Inicia sesión para reclamar la recompensa de hoy.",
  "cta.close": "Cerrar",
  "cta.openFree": "Abrir regalo gratis",
  "door.opened": "Abierta",
  "door.today": "Hoy",
  "door.soon": "Pronto",
  "door.missed": "Perdida",
  "door.locked": "Bloqueada",
  "door.aria": "Día {day}, {state}",
  "doors.aria": "Puertas de Adviento",
  "status.engine": "Motor listo · reclamaciones {claims} · {tz}",
  "status.live": "en vivo",
  "status.notLive": "aún no en vivo",
  "free.heading": "Consigue tu regalo de Navidad",
  "free.lede": "Una sorpresa de temporada gratis — sin créditos en efectivo para visitantes anónimos.",
  "free.aria": "Regalo de Navidad gratis",
  "free.already": "El mismo regalo al actualizar — sin nuevo sorteo.",
  "free.disabled": "El regalo de Navidad gratis se abre más cerca de la temporada.",
  "free.error": "Regalo gratis no disponible",
  "reward.aria": "Recompensa reclamada",
  "reward.unlocked": "Desbloqueado: {label}",
  "nav.tree": "Crea tu árbol de Navidad",
  "nav.hub": "Hub de Navidad",
  "loading": "Cargando…",
  "error.load": "No se pudo cargar el Adviento",
  "error.claim": "Error al reclamar",
  "day.title": "Día {day}",
};

const IT: Dict = {
  "brand": "The Digital Gifter",
  "title": "Calendario dell’Avvento",
  "lede.openToday": "Apri la porta di oggi per una ricompensa di Natale.",
  "lede.ended": "L’Avvento di questa stagione è finito. Ci vediamo l’anno prossimo.",
  "lede.preseason": "L’Avvento inizia il {date}.",
  "countdown.aria": "Conto alla rovescia",
  "countdown.untilAdvent": "all’Avvento",
  "countdown.untilTomorrow": "alla porta di domani",
  "countdown.untilChristmas": "a Natale",
  "countdown.days": "Giorni",
  "countdown.hours": "Ore",
  "countdown.minutes": "Minuti",
  "countdown.seconds": "Secondi",
  "countdown.arrived": "Buon Natale — la magia è qui.",
  "cta.openToday": "Apri la porta di oggi",
  "cta.comeBackTomorrow": "Torna domani",
  "cta.availableToday": "Disponibile oggi",
  "cta.signIn": "Accedi",
  "cta.signInClaim": "Accedi per richiedere la ricompensa di oggi quando l’Avvento è attivo.",
  "cta.signInError": "Accedi per richiedere la ricompensa di oggi.",
  "cta.close": "Chiudi",
  "cta.openFree": "Apri il regalo gratis",
  "door.opened": "Aperta",
  "door.today": "Oggi",
  "door.soon": "Presto",
  "door.missed": "Persa",
  "door.locked": "Bloccata",
  "door.aria": "Giorno {day}, {state}",
  "doors.aria": "Porte dell’Avvento",
  "status.engine": "Motore pronto · richieste {claims} · {tz}",
  "status.live": "attivo",
  "status.notLive": "non ancora attivo",
  "free.heading": "Prendi il tuo regalo di Natale",
  "free.lede": "Una sorpresa stagionale gratuita — niente crediti in denaro per i visitatori anonimi.",
  "free.aria": "Regalo di Natale gratis",
  "free.already": "Stesso regalo al refresh — nessun nuovo estratto.",
  "free.disabled": "Il regalo di Natale gratis si apre più vicino alla stagione.",
  "free.error": "Regalo gratis non disponibile",
  "reward.aria": "Ricompensa richiesta",
  "reward.unlocked": "Sbloccato: {label}",
  "nav.tree": "Crea il tuo albero di Natale",
  "nav.hub": "Hub di Natale",
  "loading": "Caricamento…",
  "error.load": "Impossibile caricare l’Avvento",
  "error.claim": "Richiesta non riuscita",
  "day.title": "Giorno {day}",
};

const PT: Dict = {
  "brand": "The Digital Gifter",
  "title": "Calendário do Advento",
  "lede.openToday": "Abra a porta de hoje para uma recompensa de Natal.",
  "lede.ended": "O Advento desta época terminou. Até ao próximo ano.",
  "lede.preseason": "O Advento começa a {date}.",
  "countdown.aria": "Contagem decrescente",
  "countdown.untilAdvent": "até ao Advento",
  "countdown.untilTomorrow": "até à porta de amanhã",
  "countdown.untilChristmas": "até ao Natal",
  "countdown.days": "Dias",
  "countdown.hours": "Horas",
  "countdown.minutes": "Minutos",
  "countdown.seconds": "Segundos",
  "countdown.arrived": "Feliz Natal — a magia está aqui.",
  "cta.openToday": "Abrir a porta de hoje",
  "cta.comeBackTomorrow": "Volte amanhã",
  "cta.availableToday": "Disponível hoje",
  "cta.signIn": "Iniciar sessão",
  "cta.signInClaim": "Inicie sessão para reclamar a recompensa de hoje quando o Advento estiver ativo.",
  "cta.signInError": "Inicie sessão para reclamar a recompensa de hoje.",
  "cta.close": "Fechar",
  "cta.openFree": "Abrir presente grátis",
  "door.opened": "Aberta",
  "door.today": "Hoje",
  "door.soon": "Em breve",
  "door.missed": "Perdida",
  "door.locked": "Bloqueada",
  "door.aria": "Dia {day}, {state}",
  "doors.aria": "Portas do Advento",
  "status.engine": "Motor pronto · reivindicações {claims} · {tz}",
  "status.live": "ativo",
  "status.notLive": "ainda não ativo",
  "free.heading": "Receba o seu presente de Natal",
  "free.lede": "Uma surpresa sazonal gratuita — sem créditos em dinheiro para visitantes anónimos.",
  "free.aria": "Presente de Natal gratuito",
  "free.already": "O mesmo presente ao atualizar — sem novo sorteio.",
  "free.disabled": "O presente de Natal gratuito abre mais perto da época.",
  "free.error": "Presente gratuito indisponível",
  "reward.aria": "Recompensa reclamada",
  "reward.unlocked": "Desbloqueado: {label}",
  "nav.tree": "Crie a sua árvore de Natal",
  "nav.hub": "Hub de Natal",
  "loading": "A carregar…",
  "error.load": "Não foi possível carregar o Advento",
  "error.claim": "Falha ao reclamar",
  "day.title": "Dia {day}",
};

const NL: Dict = {
  "brand": "The Digital Gifter",
  "title": "Adventskalender",
  "lede.openToday": "Open de deur van vandaag voor een kerstreward.",
  "lede.ended": "De Advent van dit seizoen is voorbij. Tot volgend jaar.",
  "lede.preseason": "Advent begint op {date}.",
  "countdown.aria": "Aftellen",
  "countdown.untilAdvent": "tot Advent",
  "countdown.untilTomorrow": "tot de deur van morgen",
  "countdown.untilChristmas": "tot Kerstmis",
  "countdown.days": "Dagen",
  "countdown.hours": "Uren",
  "countdown.minutes": "Minuten",
  "countdown.seconds": "Seconden",
  "countdown.arrived": "Vrolijk kerstfeest — de magie is er.",
  "cta.openToday": "Open de deur van vandaag",
  "cta.comeBackTomorrow": "Kom morgen terug",
  "cta.availableToday": "Vandaag beschikbaar",
  "cta.signIn": "Inloggen",
  "cta.signInClaim": "Log in om de reward van vandaag te claimen wanneer Advent live is.",
  "cta.signInError": "Log in om de reward van vandaag te claimen.",
  "cta.close": "Sluiten",
  "cta.openFree": "Open gratis cadeau",
  "door.opened": "Geopend",
  "door.today": "Vandaag",
  "door.soon": "Binnenkort",
  "door.missed": "Gemist",
  "door.locked": "Vergrendeld",
  "door.aria": "Dag {day}, {state}",
  "doors.aria": "Adventsdeuren",
  "status.engine": "Engine klaar · claims {claims} · {tz}",
  "status.live": "live",
  "status.notLive": "nog niet live",
  "free.heading": "Haal je kerstcadeau",
  "free.lede": "Een gratis seizoensverrassing — geen contante credits voor anonieme bezoekers.",
  "free.aria": "Gratis kerstcadeau",
  "free.already": "Zelfde cadeau bij vernieuwen — geen herrol.",
  "free.disabled": "Het gratis kerstcadeau opent dichter bij het seizoen.",
  "free.error": "Gratis cadeau niet beschikbaar",
  "reward.aria": "Reward geclaimd",
  "reward.unlocked": "Ontgrendeld: {label}",
  "nav.tree": "Maak je kerstboom",
  "nav.hub": "Kersthub",
  "loading": "Laden…",
  "error.load": "Advent kon niet worden geladen",
  "error.claim": "Claimen mislukt",
  "day.title": "Dag {day}",
};

const PL: Dict = {
  "brand": "The Digital Gifter",
  "title": "Kalendarz adwentowy",
  "lede.openToday": "Otwórz dzisiejsze okienko po świąteczną nagrodę.",
  "lede.ended": "Tegoroczny Adwent dobiegł końca. Do zobaczenia w przyszłym roku.",
  "lede.preseason": "Adwent zaczyna się {date}.",
  "countdown.aria": "Odliczanie",
  "countdown.untilAdvent": "do Adwentu",
  "countdown.untilTomorrow": "do jutrzejszego okienka",
  "countdown.untilChristmas": "do Bożego Narodzenia",
  "countdown.days": "Dni",
  "countdown.hours": "Godziny",
  "countdown.minutes": "Minuty",
  "countdown.seconds": "Sekundy",
  "countdown.arrived": "Wesołych Świąt — magia jest tutaj.",
  "cta.openToday": "Otwórz dzisiejsze okienko",
  "cta.comeBackTomorrow": "Wróć jutro",
  "cta.availableToday": "Dostępne dziś",
  "cta.signIn": "Zaloguj się",
  "cta.signInClaim": "Zaloguj się, aby odebrać dzisiejszą nagrodę, gdy Adwent będzie aktywny.",
  "cta.signInError": "Zaloguj się, aby odebrać dzisiejszą nagrodę.",
  "cta.close": "Zamknij",
  "cta.openFree": "Otwórz darmowy prezent",
  "door.opened": "Otwarte",
  "door.today": "Dziś",
  "door.soon": "Wkrótce",
  "door.missed": "Pominięte",
  "door.locked": "Zablokowane",
  "door.aria": "Dzień {day}, {state}",
  "doors.aria": "Okienka adwentowe",
  "status.engine": "Silnik gotowy · odebrania {claims} · {tz}",
  "status.live": "aktywne",
  "status.notLive": "jeszcze nieaktywne",
  "free.heading": "Odbierz swój świąteczny prezent",
  "free.lede": "Darmowa sezonowa niespodzianka — bez kredytów pieniężnych dla anonimowych gości.",
  "free.aria": "Darmowy prezent świąteczny",
  "free.already": "Ten sam prezent po odświeżeniu — bez ponownego losowania.",
  "free.disabled": "Darmowy prezent świąteczny otwiera się bliżej sezonu.",
  "free.error": "Darmowy prezent niedostępny",
  "reward.aria": "Nagroda odebrana",
  "reward.unlocked": "Odblokowano: {label}",
  "nav.tree": "Stwórz swoją choinkę",
  "nav.hub": "Hub świąteczny",
  "loading": "Ładowanie…",
  "error.load": "Nie udało się wczytać Adwentu",
  "error.claim": "Odbiór nie powiódł się",
  "day.title": "Dzień {day}",
};

export const TABLES: Record<AdventLocale, Dict> = {
  en: EN,
  ro: RO,
  de: DE,
  fr: FR,
  es: ES,
  it: IT,
  pt: PT,
  nl: NL,
  pl: PL,
};

const _enKeySet = Object.keys(TABLES.en).sort().join("\0");
for (const loc of ADVENT_UI_LOCALES) {
  const pack = TABLES[loc];
  const keys = Object.keys(pack);
  if (keys.length !== Object.keys(TABLES.en).length || keys.sort().join("\0") !== _enKeySet) {
    throw new Error(`Advent UI pack key mismatch for locale: ${loc}`);
  }
}

export function adventT(
  key: string,
  locale: AdventLocale = "en",
  vars?: Record<string, string>,
): string {
  let text = TABLES[locale]?.[key] || TABLES.en[key] || key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      text = text.replaceAll(`{${k}}`, v);
    }
  }
  return text;
}

/** Format Advent season start (Dec 1) with Intl — no English concatenation. */
export function formatAdventStartDate(locale: AdventLocale, seasonYear: number): string {
  const d = new Date(Date.UTC(seasonYear, 11, 1, 12, 0, 0));
  return new Intl.DateTimeFormat(ADVENT_INTL_LOCALE[locale], {
    month: "long",
    day: "numeric",
    timeZone: "Europe/Bucharest",
  }).format(d);
}

export function doorStateLabel(
  door: "claimed" | "available" | "future" | "missed" | "preseason",
  locale: AdventLocale,
): string {
  switch (door) {
    case "claimed":
      return adventT("door.opened", locale);
    case "available":
      return adventT("door.today", locale);
    case "preseason":
      return adventT("door.soon", locale);
    case "missed":
      return adventT("door.missed", locale);
    default:
      return adventT("door.locked", locale);
  }
}
